<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Liana Pozza">
  <title>Regression: model development</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-945df11cfe02533d166420a10b935f00.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="../../site_libs/quarto-contrib/quarto-project/ochre/logo_charcoal.svg" data-background-position="bottom 4em center" data-background-size="10%" class="quarto-title-block center">
  <h1 class="title">Regression: model development</h1>
  <p class="subtitle">ENVX2001 Applied Statistical Methods</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Liana Pozza 
</div>
</div>
</div>

  <p class="date">Feb 2026</p>
</section>
<section>
<section id="variable-selection" class="title-slide slide level1 center">
<h1>Variable selection</h1>
<blockquote>
<p>“The hardest thing to learn in life is which bridge to cross and which to burn.”</p>
</blockquote>
<p>– <a href="https://en.wikipedia.org/wiki/David_Russell_(guitarist)">David Russell</a></p>
</section>
<section id="workflow" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Workflow</h2>
<ol type="1">
<li><span style="color: #D0D3D4;">Model development</span>
<ul>
<li><span style="color: #D0D3D4;">Explore: visualise, summarise</span></li>
<li><span style="color: #D0D3D4;">Transform predictors: linearise, reduce skewness/leverage</span></li>
<li><span style="color: #D0D3D4;">Model: fit, check assumptions, interpret, transform. Repeat.</span></li>
</ul></li>
<li>Variable selection
<ul>
<li>VIF: remove predictors with high variance inflation factor</li>
<li>Model selection: stepwise selection, AIC, principle of parsimony, assumption checks</li>
</ul></li>
<li><span style="color: #D0D3D4;">Predictive modelling</span>
<ul>
<li><span style="color: #D0D3D4;">Predict: Use the model to predict new data</span></li>
<li><span style="color: #D0D3D4;">Validate: Evaluate the model’s performance</span></li>
</ul></li>
</ol>
</section>
<section id="previously-on-envx2001" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Previously on ENVX2001…</h2>
<p>We fitted a multiple linear regression model to the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb1-1" class="hljs-ln-code"><a></a>full_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Ozone) <span class="sc">~</span> Temp <span class="sc">+</span> Solar.R <span class="sc">+</span> Wind, <span class="at">data =</span> airquality)</span>
<span id="cb1-2" class="hljs-ln-code"><a></a><span class="fu">summary</span>(full_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Ozone) ~ Temp + Solar.R + Wind, data = airquality)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.06193 -0.29970 -0.00231  0.30756  1.23578 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.2621323  0.5535669  -0.474 0.636798    
Temp         0.0491711  0.0060875   8.077 1.07e-12 ***
Solar.R      0.0025152  0.0005567   4.518 1.62e-05 ***
Wind        -0.0615625  0.0157130  -3.918 0.000158 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5086 on 107 degrees of freedom
  (42 observations deleted due to missingness)
Multiple R-squared:  0.6644,    Adjusted R-squared:  0.655 
F-statistic: 70.62 on 3 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math display">\[\widehat{log(Ozone)}=-0.262 + 0.0492 \cdot Temp + 0.00252 \cdot Solar.R - 0.0616 \cdot Wind\]</span></p>
</section>
<section id="question" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Question</h2>
<p><span class="math display">\[\widehat{log(Ozone)}=-0.262 + 0.0492 \cdot Temp + 0.00252 \cdot Solar.R - 0.0616 \cdot Wind\]</span></p>
<p><strong>Are all the variables/predictors needed?</strong></p>
<h3 id="principles">Principles</h3>
<p>A good model:</p>
<ul>
<li>Has only <em>useful</em> predictors: principle of parsimony</li>
<li>Has <em>no redundant</em> predictors: principle of orthogonality (no multicollinearity)</li>
<li>Is <em>interpretable</em> (principle of transparency; last week), or <em>predicts</em> well (principle of accuracy; next week)</li>
</ul>
</section>
<section id="on-the-principle-of-parsimony" class="slide level2">
<h2>On the principle of parsimony</h2>
<ul>
<li><a href="https://en.wikipedia.org/wiki/Occam%27s_razor">Ockham’s razor</a>: “Entities should not be multiplied unnecessarily.”</li>
<li>One should prefer the <em>simplest</em> explanation that fits the data if multiple explanations are equally good.</li>
</ul>
<blockquote>
<p>“It is vain to do with more what can be done with fewer.”</p>
</blockquote>
<p>– <a href="https://en.wikipedia.org/wiki/William_of_Ockham">William of Ockham</a> (1287–1347)</p>
</section>
<section id="what-happens-when-we-add-more-predictors-to-a-model" class="slide level2">
<h2>What happens when we add more predictors to a model?</h2>
<p>A simple example using polynomial regression.</p>
<ul>
<li>The more predictors we include, the more variance we can explain.</li>
<li>However, the more predictors and complexity we include, the more overfitted the model becomes.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">set.seed</span>(<span class="dv">1030</span>)</span>
<span id="cb3-2"><a></a>xsquared <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb3-3"><a></a>  x<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb3-4"><a></a>}</span>
<span id="cb3-5"><a></a><span class="co"># Generate xy data</span></span>
<span id="cb3-6"><a></a>sim_data <span class="ot">&lt;-</span> <span class="cf">function</span>(xsquared, <span class="at">sample_size =</span> <span class="dv">100</span>) {</span>
<span id="cb3-7"><a></a>  x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n =</span> sample_size, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">1</span>)</span>
<span id="cb3-8"><a></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> sample_size, <span class="at">mean =</span> <span class="fu">xsquared</span>(x), <span class="at">sd =</span> <span class="fl">0.05</span>)</span>
<span id="cb3-9"><a></a>  <span class="fu">data.frame</span>(x, y)</span>
<span id="cb3-10"><a></a>}</span>
<span id="cb3-11"><a></a><span class="co"># Generate predicted data (model)</span></span>
<span id="cb3-12"><a></a>df <span class="ot">&lt;-</span> <span class="fu">sim_data</span>(xsquared, <span class="at">sample_size =</span> <span class="dv">60</span>)</span>
<span id="cb3-13"><a></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df)</span>
<span id="cb3-14"><a></a>fit_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="at">degree =</span> <span class="dv">1</span>), <span class="at">data =</span> df)</span>
<span id="cb3-15"><a></a>fit_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="at">degree =</span> <span class="dv">2</span>), <span class="at">data =</span> df)</span>
<span id="cb3-16"><a></a>fit_many <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="at">degree =</span> <span class="dv">20</span>), <span class="at">data =</span> df)</span>
<span id="cb3-17"><a></a>truth <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb3-18"><a></a><span class="co"># Combine the data and model fits into a single data frame</span></span>
<span id="cb3-19"><a></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-20"><a></a>  <span class="at">x =</span> df<span class="sc">$</span>x,</span>
<span id="cb3-21"><a></a>  <span class="at">y =</span> df<span class="sc">$</span>y,</span>
<span id="cb3-22"><a></a>  <span class="at">fit =</span> <span class="fu">predict</span>(fit),</span>
<span id="cb3-23"><a></a>  <span class="at">fit_1 =</span> <span class="fu">predict</span>(fit_1),</span>
<span id="cb3-24"><a></a>  <span class="at">fit_2 =</span> <span class="fu">predict</span>(fit_2),</span>
<span id="cb3-25"><a></a>  <span class="at">fit_many =</span> <span class="fu">predict</span>(fit_many)</span>
<span id="cb3-26"><a></a>)</span>
<span id="cb3-27"><a></a></span>
<span id="cb3-28"><a></a><span class="co"># Reshape the data frame into long format</span></span>
<span id="cb3-29"><a></a>df_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(</span>
<span id="cb3-30"><a></a>  df,</span>
<span id="cb3-31"><a></a>  <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"fit_"</span>),</span>
<span id="cb3-32"><a></a>  <span class="at">names_to =</span> <span class="st">"model"</span>,</span>
<span id="cb3-33"><a></a>  <span class="at">values_to =</span> <span class="st">"value"</span></span>
<span id="cb3-34"><a></a>) <span class="sc">%&gt;%</span></span>
<span id="cb3-35"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-36"><a></a>    <span class="at">model =</span> <span class="fu">case_when</span>(</span>
<span id="cb3-37"><a></a>      model <span class="sc">==</span> <span class="st">"fit"</span> <span class="sc">~</span> <span class="st">"y = b"</span>,</span>
<span id="cb3-38"><a></a>      model <span class="sc">==</span> <span class="st">"fit_1"</span> <span class="sc">~</span> <span class="st">"y = b + mx"</span>,</span>
<span id="cb3-39"><a></a>      model <span class="sc">==</span> <span class="st">"fit_2"</span> <span class="sc">~</span> <span class="st">"y = b + mx + nx^2"</span>,</span>
<span id="cb3-40"><a></a>      model <span class="sc">==</span> <span class="st">"fit_many"</span> <span class="sc">~</span> <span class="st">"y = b + mx + nx^2 + ... + zx^20"</span>,</span>
<span id="cb3-41"><a></a>      <span class="cn">TRUE</span> <span class="sc">~</span> model</span>
<span id="cb3-42"><a></a>    )</span>
<span id="cb3-43"><a></a>  )</span>
<span id="cb3-44"><a></a><span class="co"># Plot</span></span>
<span id="cb3-45"><a></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_long, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> value, <span class="at">color =</span> model)) <span class="sc">+</span></span>
<span id="cb3-46"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>model, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb3-47"><a></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> y), <span class="at">alpha =</span> .<span class="dv">4</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb3-48"><a></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> .<span class="dv">9</span>, <span class="at">linetype =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-49"><a></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb3-50"><a></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb3-51"><a></a>  <span class="fu">geom_blank</span>()</span>
<span id="cb3-52"><a></a>p</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"></section>
<section id="variance-bias-trade-off" class="slide level2">
<h2>Variance-bias trade-off</h2>

<img data-src="images/bias_var.svg" class="r-stretch"><p>In concept…</p>
<ul>
<li>As complexity increases, bias (<span class="math inline">\(\sum{O-\bar{P}}\)</span>) <em>decreases</em> (the mean of a model’s predictions is closer to the true mean).</li>
<li>As complexity increases, prediction variance (<span class="math inline">\(\frac{\sum{(P-\bar{P})}^2}{n}\)</span>) increases.</li>
<li>The <strong>goal</strong> is to find a model that isn’t too simple or complex with a good balance between bias and variance.</li>
</ul>
<p><span class="math display">\[ \text{Mean Squared Error} = \text{Bias}^2 + \text{Variance} + \text{Immeasureable Error} \]</span> In practice, the math and relationships are a bit more irregular.</p>
</section>
<section id="how-do-we-determine-the-best-model" class="slide level2">
<h2>How do we determine the best model?</h2>
<p>Some model quality measures you should be familiar with:</p>
<ul>
<li><strong>R<sup>2</sup></strong>: variance explained by the model with a maximum value of 1 = 100%</li>
<li><strong>Residual standard error</strong>: the mean error of the observed values from the predicted/fitted values (i.e.&nbsp;line of best fit).</li>
<li><strong>Partial F-test</strong>: compare the full model to a reduced model, works well when the number of predictors is small and simple models.</li>
</ul>
<p>Some other commonly used measures:</p>
<ul>
<li><strong>Information criteria</strong>: AIC, BIC, etc. (more on this later).</li>
<li><strong>Error measures</strong>: useful when the aim for the model is to <strong>predict</strong>. The best model has the smallest residual error (or other similar metrics).</li>
</ul>
</section>
<section id="what-models-do-we-try" class="slide level2">
<h2>What models do we try?</h2>
<ul>
<li><strong>Everything</strong>: all possible combinations of predictors.
<ul>
<li>Each variable can either be included or excluded so the number of possible combinations is <span class="math inline">\(2^n\)</span></li>
<li>e.g.&nbsp;3 predictors (<span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, <span class="math inline">\(x_3\)</span>) could have 8 models
<ul>
<li>No variables i.e.&nbsp;mean <span class="math inline">\(y\)</span> the null hypothesis</li>
<li>1 variable: <span class="math inline">\(x_1\)</span>; <span class="math inline">\(x_2\)</span>; <span class="math inline">\(x_3\)</span></li>
<li>2 variables: <span class="math inline">\(x_1\)</span> + <span class="math inline">\(x_2\)</span>; <span class="math inline">\(x_1\)</span> + <span class="math inline">\(x_3\)</span>; <span class="math inline">\(x_2\)</span> + <span class="math inline">\(x_3\)</span></li>
<li>3 variables: <span class="math inline">\(x_1\)</span> + <span class="math inline">\(x_2\)</span> + <span class="math inline">\(x_3\)</span></li>
</ul></li>
<li>So…not recommended</li>
</ul></li>
<li><strong>Stepwise regression</strong>: add/remove predictors one at a time until removing a variable makes the model worse.</li>
<li><strong>Select meaningful predictors</strong> based on domain knowledge, correlation, or significance.</li>
<li>More complex approaches are available for big data and machine learning.</li>
</ul>
</section>
<section id="air-quality-can-we-reduce-the-number-of-predictors" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Air quality: can we reduce the number of predictors?</h2>
<p><strong>Full model:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb4-1" class="hljs-ln-code"><a></a><span class="fu">summary</span>(full_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Ozone) ~ Temp + Solar.R + Wind, data = airquality)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.06193 -0.29970 -0.00231  0.30756  1.23578 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.2621323  0.5535669  -0.474 0.636798    
Temp         0.0491711  0.0060875   8.077 1.07e-12 ***
Solar.R      0.0025152  0.0005567   4.518 1.62e-05 ***
Wind        -0.0615625  0.0157130  -3.918 0.000158 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5086 on 107 degrees of freedom
  (42 observations deleted due to missingness)
Multiple R-squared:  0.6644,    Adjusted R-squared:  0.655 
F-statistic: 70.62 on 3 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><code>Wind</code> has the highest p-value, can we remove it?</li>
<li>Full model: Multiple R-squared = 0.66, Adjusted R-squared = 0.66</li>
</ul>
</section>
<section id="section" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title"></h2>
<ul>
<li>Full model: multiple R-squared = 0.66, adjusted R-squared = 0.66</li>
</ul>
<p><strong>Reduced model: take out <code>Wind</code></strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb6-1" class="hljs-ln-code"><a></a>reduced_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Ozone) <span class="sc">~</span> Temp <span class="sc">+</span> Solar.R, <span class="at">data =</span> airquality)</span>
<span id="cb6-2" class="hljs-ln-code"><a></a><span class="fu">summary</span>(reduced_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Ozone) ~ Temp + Solar.R, data = airquality)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.83864 -0.33727  0.03444  0.29877  1.38210 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1.7646527  0.4249016  -4.153 6.58e-05 ***
Temp         0.0607386  0.0056663  10.719  &lt; 2e-16 ***
Solar.R      0.0024651  0.0005924   4.161 6.38e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5413 on 108 degrees of freedom
  (42 observations deleted due to missingness)
Multiple R-squared:  0.6163,    Adjusted R-squared:  0.6092 
F-statistic: 86.73 on 2 and 108 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>Reduced model: multiple R-squared = 0.62, adjusted R-squared = 0.61</li>
<li><strong>Adjusted R-squared is lower, but is a 4% difference “worth it”? Is it significant?</strong></li>
</ul>
</section>
<section id="the-r2-value" class="slide level2">
<h2>The R<sup>2</sup> value</h2>
<p>The R-squared value is the proportion of variance explained by the model.</p>
<p><span class="math display">\[ R^2 = \frac{SS_{reg}}{SS_{tot}} = 1 - \frac{SS_{res}}{SS_{tot}} \]</span></p>
<p>The adjusted R-squared value is the proportion of variance explained by the model, adjusted for the number of predictors.</p>
<p><span class="math display">\[R^2_{adj} = 1 - \frac{SS_{res}}{SS_{tot}} \frac{n-1}{n-p-1} \]</span></p>
<p>where <span class="math inline">\(n\)</span> is the number of observations and <span class="math inline">\(p\)</span> is the number of predictors.</p>
</section></section>
<section>
<section id="partial-f-test" class="title-slide slide level1 center">
<h1>Partial F-test</h1>

</section>
<section id="partial-f-test-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Partial F-test</h2>
<p>How much of an improvement in adjusted <span class="math inline">\(R^2\)</span> is worth having an extra variable / more complex model?</p>
<ul>
<li>We can perform a hypothesis test to determine whether the improvement is significant.</li>
<li>The F-test measures the full model against an intercept only model in terms of explained variance (residual sum of squares).</li>
<li>The <strong>partial F-test</strong> compares the full model to a reduced model in terms of the trade-off between model complexity and variance explained (i.e.&nbsp;<strong>adjusted</strong> <span class="math inline">\(R^2\)</span>).
<ul>
<li><span class="math inline">\(H_0\)</span>: no significant difference between the full and reduced models</li>
<li><span class="math inline">\(H_1\)</span>: the full model is significantly better than the reduced model</li>
<li>Calculating the F-stat:</li>
</ul></li>
</ul>
<p><span class="math display">\[F = \big| \frac{SS_{reg,full} - SS_{reg,reduced}}{(df_{res,full} - df_{res,reduced})} \big | \div MS_{res, full}\]</span></p>
</section>
<section id="partial-f-test-calculation" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Partial F-test: calculation</h2>
<p><span class="math display">\[F = \big| \frac{SS_{reg,full} - SS_{reg,reduced}}{(df_{res,full} - df_{res,reduced})} \big | \div MS_{res, full}\]</span> where:</p>
<ul>
<li><span class="math inline">\(SS_{reg,full}\)</span> is the sum of squares of the full model (total of predictors)</li>
<li><span class="math inline">\(SS_{reg,reduced}\)</span> is the sum of squares of the reduced model (total of predictors)</li>
<li><span class="math inline">\(df_{res,full}\)</span> is the degrees of freedom of the residuals of the full model</li>
<li><span class="math inline">\(df_{res,reduced}\)</span> is the degrees of freedom of the residuals of the reduced model</li>
<li><span class="math inline">\(MS_{res, full}\)</span> is the mean square of the residuals of the full model</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>full <span class="ot">&lt;-</span> <span class="fu">anova</span>(full_fit) <span class="sc">%&gt;%</span> broom<span class="sc">::</span><span class="fu">tidy</span>()</span>
<span id="cb8-2"><a></a>full</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  term         df sumsq meansq statistic   p.value
  &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 Temp          1 45.8  45.8       177.   2.07e-24
2 Solar.R       1  5.07  5.07       19.6  2.29e- 5
3 Wind          1  3.97  3.97       15.4  1.58e- 4
4 Residuals   107 27.7   0.259      NA   NA       </code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>reduced <span class="ot">&lt;-</span> <span class="fu">anova</span>(reduced_fit) <span class="sc">%&gt;%</span> broom<span class="sc">::</span><span class="fu">tidy</span>()</span>
<span id="cb10-2"><a></a>reduced</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  term         df sumsq meansq statistic   p.value
  &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 Temp          1 45.8  45.8       156.   1.05e-22
2 Solar.R       1  5.07  5.07       17.3  6.38e- 5
3 Residuals   108 31.6   0.293      NA   NA       </code></pre>
</div>
</div>
</div></div>
<p>Each row is the <em>individual effect</em> of each predictor on the response <span class="math inline">\(log(Ozone)\)</span> (whilst holding all other predictors constant).</p>
</section>
<section id="by-hand" class="slide level2">
<h2>By hand</h2>
<p><span class="math display">\[F = \big| \frac{SS_{reg,full} - SS_{reg,reduced}}{(df_{res,full} - df_{res,reduced})} \big | \div MS_{res, full}\]</span></p>
<ul>
<li><span class="math inline">\(SS_{reg,full} = 45.8 + 5.07 + 3.97 = 54.84\)</span></li>
<li><span class="math inline">\(SS_{reg,reduced} = 45.8 + 5.07 = 50.87\)</span></li>
<li><span class="math inline">\(df_{res,full} = 107\)</span></li>
<li><span class="math inline">\(df_{res,reduced} = 108\)</span></li>
<li><span class="math inline">\(MS_{res, full} = 0.259\)</span></li>
</ul>
<p><span class="math inline">\(F = |\frac{54.84 - 50.87}{(107-108)}| \div 0.259 = 15.33\)</span></p>
</section>
<section id="in-r-manually" class="slide level2">
<h2>In R (manually)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>ss_full <span class="ot">&lt;-</span> <span class="fu">sum</span>(full<span class="sc">$</span>sumsq[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb12-2"><a></a>ss_reduced <span class="ot">&lt;-</span> <span class="fu">sum</span>(reduced<span class="sc">$</span>sumsq[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb12-3"><a></a>df_full <span class="ot">&lt;-</span> full<span class="sc">$</span>df[<span class="dv">4</span>]</span>
<span id="cb12-4"><a></a>df_reduced <span class="ot">&lt;-</span> reduced<span class="sc">$</span>df[<span class="dv">3</span>]</span>
<span id="cb12-5"><a></a>ms_full <span class="ot">&lt;-</span> full<span class="sc">$</span>meansq[<span class="dv">4</span>]</span>
<span id="cb12-6"><a></a>F <span class="ot">&lt;-</span> <span class="fu">abs</span>((ss_full <span class="sc">-</span> ss_reduced) <span class="sc">/</span> ((df_full <span class="sc">-</span> df_reduced))) <span class="sc">/</span> ms_full</span>
<span id="cb12-7"><a></a>F     <span class="co"># F-statistic</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.35026</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">pf</span>(F, <span class="at">df1 =</span> <span class="dv">1</span>, <span class="at">df2 =</span> df_full, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="co"># corresponding p-value</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0001576806</code></pre>
</div>
</div>
<p>(There is a slight difference due to rounding)</p>
</section>
<section id="in-r-with-functions" class="slide level2">
<h2>In R with functions</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">anova</span>(reduced_fit, full_fit) <span class="co"># reduced goes first else will see negative df</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(Ozone) ~ Temp + Solar.R
Model 2: log(Ozone) ~ Temp + Solar.R + Wind
  Res.Df    RSS Df Sum of Sq     F    Pr(&gt;F)    
1    108 31.645                                 
2    107 27.675  1    3.9703 15.35 0.0001577 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>The partial F-test is significant (p-value &lt; 0.05), so we can reject the null hypothesis and conclude that the full model is significantly better, even if adjusted R<sup>2</sup> improves by 4%.</li>
</ul>
</section>
<section id="but-wait" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">But wait…</h2>
<p>Looking back at the original model, we can see that the partial regression coefficients are the <em>same</em> as the partial F-test results!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">anova</span>(reduced_fit, full_fit) <span class="co"># partial F-test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(Ozone) ~ Temp + Solar.R
Model 2: log(Ozone) ~ Temp + Solar.R + Wind
  Res.Df    RSS Df Sum of Sq     F    Pr(&gt;F)    
1    108 31.645                                 
2    107 27.675  1    3.9703 15.35 0.0001577 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">summary</span>(full_fit)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate   Std. Error    t value     Pr(&gt;|t|)
(Intercept) -0.262132313 0.5535668608 -0.4735332 6.367975e-01
Temp         0.049171124 0.0060875025  8.0773888 1.069103e-12
Solar.R      0.002515177 0.0005567301  4.5177673 1.616797e-05
Wind        -0.061562470 0.0157129654 -3.9179409 1.576806e-04</code></pre>
</div>
</div>
<p>This is because the reduced model is <em>nested</em> within the full model so the partial F-test is equivalent to a partial regression coefficient test.</p>
</section>
<section id="nested-models" class="slide level2">
<h2>Nested models</h2>
<ul>
<li>Previous example is a simple example of a <strong>nested model</strong>.</li>
<li>A model is nested within another model if the predictors in the first model are a subset of the predictors in the second model.</li>
<li>This makes comparing the two models easier, as we can compare the regression coefficients of the two models.</li>
</ul>
<h3 id="example">Example</h3>
<ul>
<li>If the original model is y ~ a + b + c:
<ul>
<li>Nested: y ~ a + b</li>
<li>Nested: y ~ a</li>
<li><em>Not</em> nested: y ~ a + b + <strong>d</strong> – because <strong>d</strong> is not in the full model</li>
</ul></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Partial F-tests will <em>only</em> make sense/work for nested models!</strong></p>
</div>
</div>
</div>
</section></section>
<section>
<section id="another-example-bird-abundance" class="title-slide slide level1 center">
<h1>Another example: Bird abundance</h1>

</section>
<section id="about" class="slide level2">
<h2>About</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a>loyn <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/loyn.csv"</span>)</span>
<span id="cb22-2"><a></a><span class="fu">str</span>(loyn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   56 obs. of  7 variables:
 $ ABUND  : num  5.3 2 1.5 17.1 13.8 14.1 3.8 2.2 3.3 3 ...
 $ AREA   : num  0.1 0.5 0.5 1 1 1 1 1 1 1 ...
 $ YR.ISOL: int  1968 1920 1900 1966 1918 1965 1955 1920 1965 1900 ...
 $ DIST   : int  39 234 104 66 246 234 467 284 156 311 ...
 $ LDIST  : int  39 234 311 66 246 285 467 1829 156 571 ...
 $ GRAZE  : int  2 5 5 3 5 3 5 5 4 5 ...
 $ ALT    : int  160 60 140 160 140 130 90 60 130 130 ...</code></pre>
</div>
</div>
<ul>
<li>Can we predict the abundance of birds in forest patches cleared for agriculture, based on patch size, area, grazing and other variables?</li>
<li>Loyn (<a href="https://www.researchgate.net/profile/Richard-Loyn/publication/279541149_Effects_of_patch_area_and_habitat_on_bird_abundances_species_numbers_and_tree_health_in_fragmented_Victoria_forests/links/563ae1bc08ae337ef2985592/Effects-of-patch-area-and-habitat-on-bird-abundances-species-numbers-and-tree-health-in-fragmented-Victoria-forests.pdf">1987</a>)
<ul>
<li>DIST: Distance to nearest patch (km)</li>
<li>LDIST: Distance to a larger patch (km)</li>
<li>AREA: Patch area (ha)</li>
<li>GRAZE: Grazing pressure 1 (light) – 5 (heavy) – ALT: Altitude (m)</li>
<li>YR.ISOL: Years since isolation (years)</li>
<li>ABUND: Density of forest birds in a forest patch (birds/patch)</li>
</ul></li>
</ul>
</section>
<section id="data-exploration" class="slide level2">
<h2>Data exploration</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a>loyn <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>ABUND) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> ABUND)) <span class="sc">+</span></span>
<span id="cb24-4"><a></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-5"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"ABUND"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-11-1.png" width="960" class="r-stretch"><ul>
<li>The predictors are on very different scales, which can cause problems for the model.</li>
<li>The relationships don’t look particularly linear…and outliers.</li>
<li>We will perform log<sub>10</sub> transforms of <code>AREA</code>, <code>LDIST</code>, and <code>DIST</code>.</li>
</ul>
</section>
<section id="log10-transformation" class="slide level2">
<h2>Log<sub>10</sub> transformation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="co"># perform transformations</span></span>
<span id="cb25-2"><a></a>loyn <span class="ot">&lt;-</span> loyn <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a></a>  <span class="fu">mutate</span>(<span class="at">AREA_L10 =</span> <span class="fu">log10</span>(AREA),</span>
<span id="cb25-4"><a></a>         <span class="at">LDIST_L10 =</span> <span class="fu">log10</span>(LDIST),</span>
<span id="cb25-5"><a></a>         <span class="at">DIST_L10 =</span> <span class="fu">log10</span>(DIST))</span>
<span id="cb25-6"><a></a></span>
<span id="cb25-7"><a></a><span class="co"># View distributions again</span></span>
<span id="cb25-8"><a></a>loyn <span class="sc">%&gt;%</span></span>
<span id="cb25-9"><a></a>  <span class="fu">select</span>(<span class="sc">-</span>ALT, <span class="sc">-</span>GRAZE, <span class="sc">-</span>YR.ISOL) <span class="sc">%&gt;%</span></span>
<span id="cb25-10"><a></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>ABUND) <span class="sc">%&gt;%</span></span>
<span id="cb25-11"><a></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="fu">factor</span>(name, <span class="at">levels =</span> <span class="fu">unique</span>(name))) <span class="sc">%&gt;%</span>  <span class="co"># Preserve original order</span></span>
<span id="cb25-12"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> ABUND)) <span class="sc">+</span></span>
<span id="cb25-13"><a></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-14"><a></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb25-15"><a></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"ABUND"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-12-1.png" width="960" class="r-stretch"></section>
<section id="checking-assumptions---no-transformation" class="slide level2">
<h2>Checking assumptions - no transformation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>loyn_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> YR.ISOL <span class="sc">+</span> GRAZE <span class="sc">+</span> ALT <span class="sc">+</span> AREA <span class="sc">+</span> LDIST <span class="sc">+</span> DIST, <span class="at">data =</span> loyn)</span>
<span id="cb26-2"><a></a><span class="fu">summary</span>(loyn_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ABUND ~ YR.ISOL + GRAZE + ALT + AREA + LDIST + DIST, 
    data = loyn)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.6638  -4.6409  -0.0883   4.2858  20.1042 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -1.097e+02  1.133e+02  -0.968  0.33791   
YR.ISOL      6.693e-02  5.684e-02   1.177  0.24472   
GRAZE       -3.447e+00  1.107e+00  -3.114  0.00308 **
ALT          4.772e-02  3.089e-02   1.545  0.12878   
AREA         8.866e-04  4.657e-03   0.190  0.84980   
LDIST        1.418e-03  1.310e-03   1.082  0.28451   
DIST         3.811e-03  5.418e-03   0.703  0.48514   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.947 on 49 degrees of freedom
Multiple R-squared:  0.5118,    Adjusted R-squared:  0.452 
F-statistic: 8.561 on 6 and 49 DF,  p-value: 2.24e-06</code></pre>
</div>
</div>
</section>
<section id="section-1" class="slide level2">
<h2></h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>performance<span class="sc">::</span><span class="fu">check_model</span>(loyn_fit, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"linearity"</span>, <span class="st">"qq"</span>, <span class="st">"homogeneity"</span>, <span class="st">"outliers"</span>)) <span class="co"># check specific assumptions</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-14-1.png" width="960" class="r-stretch"></section>
<section id="checking-assumptions---transformation" class="slide level2">
<h2>Checking assumptions - transformation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>loyn_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> YR.ISOL <span class="sc">+</span> GRAZE <span class="sc">+</span> ALT <span class="sc">+</span> AREA_L10 <span class="sc">+</span> LDIST_L10 <span class="sc">+</span> DIST_L10, <span class="at">data =</span> loyn)</span>
<span id="cb29-2"><a></a><span class="fu">summary</span>(loyn_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ABUND ~ YR.ISOL + GRAZE + ALT + AREA_L10 + LDIST_L10 + 
    DIST_L10, data = loyn)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.6506  -2.9390   0.5289   2.5353  15.2842 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -125.69725   91.69228  -1.371   0.1767    
YR.ISOL        0.07387    0.04520   1.634   0.1086    
GRAZE         -1.66774    0.92993  -1.793   0.0791 .  
ALT            0.01951    0.02396   0.814   0.4195    
AREA_L10       7.47023    1.46489   5.099 5.49e-06 ***
LDIST_L10     -0.64842    2.12270  -0.305   0.7613    
DIST_L10      -0.90696    2.67572  -0.339   0.7361    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.384 on 49 degrees of freedom
Multiple R-squared:  0.6849,    Adjusted R-squared:  0.6464 
F-statistic: 17.75 on 6 and 49 DF,  p-value: 8.443e-11</code></pre>
</div>
</div>
</section>
<section id="section-2" class="slide level2">
<h2></h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>performance<span class="sc">::</span><span class="fu">check_model</span>(loyn_fit, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"linearity"</span>, <span class="st">"qq"</span>, <span class="st">"homogeneity"</span>, <span class="st">"outliers"</span>)) <span class="co"># check specific assumptions</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-16-1.png" width="960" class="r-stretch"></section></section>
<section>
<section id="other-assumptions" class="title-slide slide level1 center">
<h1>Other Assumptions</h1>
<blockquote>
<p>LINE… + leverage + collinearity</p>
</blockquote>
</section>
<section id="leverage" class="slide level2">
<h2>Leverage</h2>
<ul>
<li>The leverage plot shows the influence of each observation (i.e.&nbsp;point) on the model.</li>
<li>Points with high leverage can have a large effect on the model when removed.</li>
<li>Identified by the Cook’s distance statistic – named after the American statistician R. Dennis Cook, who introduced the concept in 1977.</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The leverage plot is a useful tool for identifying outliers and influential points, but can also be used to check for other issues such as heteroskedasticity (equal variances) and non-linearity!</p>
</div>
</div>
</div>
</section>
<section id="reading-the-leverage-plot" class="slide level2">
<h2>Reading the leverage plot</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb32-2"><a></a><span class="fu">plot</span>(loyn_fit, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-17-1.png" width="960" class="r-stretch"><ul>
<li>Visually, points with Cook’s distance &gt; 0.5 are considered influential by default, but this is a somewhat arbitrary threshold.</li>
<li>In practice, you should use a threshold that is appropriate for your data and model.</li>
</ul>
</section>
<section id="outlier-detection-using-performance" class="slide level2">
<h2>Outlier detection using <code>performance</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a>performance<span class="sc">::</span><span class="fu">check_model</span>(loyn_fit, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"outliers"</span>, <span class="st">"pp_check"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-18-1.png" width="960" class="r-stretch"><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>performance<span class="sc">::</span><span class="fu">check_outliers</span>(loyn_fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: No outliers detected.
- Based on the following method and threshold: cook (0.919).
- For variable: (Whole model)</code></pre>
</div>
</div>
</section>
<section id="collinearity" class="slide level2">
<h2>Collinearity</h2>
<ul>
<li>Two predictors that have a <em>perfect</em> linear relationship (i.e.&nbsp;<span class="math inline">\(r\)</span> = 1 or -1) breaks the assumption of collinearity</li>
<li>Even strong correlations between predictors can lead to unstable estimates and large standard errors.</li>
<li>Variance inflation factors (VIFs) are a measure of collinearity in the model.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(<span class="fu">cor</span>(loyn), <span class="at">method =</span> <span class="st">"number"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-20-1.png" width="960" class="r-stretch"></section>
<section id="calculating-vif" class="slide level2">
<h2>Calculating VIF</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a>car<span class="sc">::</span><span class="fu">vif</span>(loyn_fit) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>) <span class="co"># numbers</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  YR.ISOL     GRAZE       ALT  AREA_L10 LDIST_L10  DIST_L10 
     1.80      2.52      1.47      1.91      2.01      1.65 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a><span class="fu">plot</span>(performance<span class="sc">::</span><span class="fu">check_collinearity</span>(loyn_fit)) <span class="co"># visual</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Lecture-08_files/figure-revealjs/unnamed-chunk-21-1.png" width="960" class="r-stretch"><ul>
<li><span class="math inline">\(1\)</span> = no correlation with other predictors.</li>
<li><span class="math inline">\(&gt;10\)</span> is a sign for high, not tolerable correlation of model predictors (which need to be removed and the model refitted).</li>
</ul>
</section>
<section id="the-best-model" class="slide level2">
<h2>The best model?</h2>
<p>If we remove the least significant variable…</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>full6 <span class="ot">&lt;-</span> loyn_fit</span>
<span id="cb40-2"><a></a>part5 <span class="ot">&lt;-</span> <span class="fu">update</span>(full6, . <span class="sc">~</span> . <span class="sc">-</span> LDIST_L10)</span>
<span id="cb40-3"><a></a>part4 <span class="ot">&lt;-</span> <span class="fu">update</span>(part5, . <span class="sc">~</span> . <span class="sc">-</span> DIST_L10)</span>
<span id="cb40-4"><a></a>part3 <span class="ot">&lt;-</span> <span class="fu">update</span>(part4, . <span class="sc">~</span> . <span class="sc">-</span> ALT)</span>
<span id="cb40-5"><a></a>part2 <span class="ot">&lt;-</span> <span class="fu">update</span>(part3, . <span class="sc">~</span> . <span class="sc">-</span> YR.ISOL)</span>
<span id="cb40-6"><a></a>part1 <span class="ot">&lt;-</span> <span class="fu">update</span>(part2, . <span class="sc">~</span> . <span class="sc">-</span> GRAZE)</span>
<span id="cb40-7"><a></a></span>
<span id="cb40-8"><a></a>formulas <span class="ot">&lt;-</span> <span class="fu">c</span>(part1<span class="sc">$</span>call<span class="sc">$</span>formula, </span>
<span id="cb40-9"><a></a>              part2<span class="sc">$</span>call<span class="sc">$</span>formula, </span>
<span id="cb40-10"><a></a>              part3<span class="sc">$</span>call<span class="sc">$</span>formula, </span>
<span id="cb40-11"><a></a>              part4<span class="sc">$</span>call<span class="sc">$</span>formula, </span>
<span id="cb40-12"><a></a>              part5<span class="sc">$</span>call<span class="sc">$</span>formula, </span>
<span id="cb40-13"><a></a>              loyn_fit<span class="sc">$</span>call<span class="sc">$</span>formula)</span>
<span id="cb40-14"><a></a>formulas <span class="ot">&lt;-</span></span>
<span id="cb40-15"><a></a>  <span class="fu">c</span>(<span class="st">"ABUND ~ AREA_L10"</span>,</span>
<span id="cb40-16"><a></a>    <span class="st">"ABUND ~ AREA_L10 + GRAZE"</span>,</span>
<span id="cb40-17"><a></a>    <span class="st">"ABUND ~ AREA_L10 + GRAZE + YR.ISOL"</span>,</span>
<span id="cb40-18"><a></a>    <span class="st">"ABUND ~ AREA_L10 + GRAZE + YR.ISOL + ALT"</span>,</span>
<span id="cb40-19"><a></a>    <span class="st">"ABUND ~ AREA_L10 + GRAZE + YR.ISOL + ALT + DIST_L10"</span>,</span>
<span id="cb40-20"><a></a>    <span class="st">"ABUND ~ AREA_L10 + GRAZE + YR.ISOL + ALT + DIST_L10 + LDIST_L10"</span>)</span>
<span id="cb40-21"><a></a></span>
<span id="cb40-22"><a></a>rs <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">glance</span>(part1), </span>
<span id="cb40-23"><a></a>          <span class="fu">glance</span>(part2), </span>
<span id="cb40-24"><a></a>          <span class="fu">glance</span>(part3), </span>
<span id="cb40-25"><a></a>          <span class="fu">glance</span>(part4),</span>
<span id="cb40-26"><a></a>          <span class="fu">glance</span>(part5), </span>
<span id="cb40-27"><a></a>          <span class="fu">glance</span>(full6)) <span class="sc">%&gt;%</span></span>
<span id="cb40-28"><a></a>        <span class="fu">mutate</span>(<span class="at">Model =</span> formulas) <span class="sc">%&gt;%</span></span>
<span id="cb40-29"><a></a>        <span class="fu">select</span>(Model, r.squared, adj.r.squared)</span>
<span id="cb40-30"><a></a></span>
<span id="cb40-31"><a></a>knitr<span class="sc">::</span><span class="fu">kable</span>(rs, <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 72%">
<col style="width: 11%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ABUND ~ AREA_L10</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.54</td>
</tr>
<tr class="even">
<td style="text-align: left;">ABUND ~ AREA_L10 + GRAZE</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">0.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ABUND ~ AREA_L10 + GRAZE + YR.ISOL</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="even">
<td style="text-align: left;">ABUND ~ AREA_L10 + GRAZE + YR.ISOL + ALT</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ABUND ~ AREA_L10 + GRAZE + YR.ISOL + ALT + DIST_L10</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.65</td>
</tr>
<tr class="even">
<td style="text-align: left;">ABUND ~ AREA_L10 + GRAZE + YR.ISOL + ALT + DIST_L10 + LDIST_L10</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.65</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>R-squared increases with addition of predictors.</li>
<li>Adj. R-squared <em>varies</em> with addition of predictors.</li>
</ul>
</section>
<section id="the-problem" class="slide level2">
<h2>The problem</h2>
<ul>
<li>Other combinations of predictors exist but are not shown.</li>
<li>Need <em>automated way</em> to select the best model – 6 predictors gives us 2^6 = <strong>64 models</strong> to choose from!</li>
<li>Options:
<ul>
<li>Backward elimination</li>
<li>Forward selection</li>
<li>Combination (R default)</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="backward-elimination" class="title-slide slide level1 center">
<h1>Backward elimination</h1>

</section>
<section id="steps-for-backward-elimination" class="slide level2">
<h2>Steps for backward elimination</h2>
<ol type="1">
<li>Start with full model.</li>
<li>For each predictor, test the effect of its removal on the model fit.</li>
<li>Remove the predictor that has the <em>least</em> effect on the model fit i.e.&nbsp;the <strong>least informative</strong> predictor, unless it is nonetheless supplying significant information about the response.</li>
<li>Repeat steps 2 and 3 until no predictors can be removed without significantly affecting the model fit.</li>
</ol>
<p>In backward selection, the model fit is assessed using the Akaike Information Criterion (AIC) or the Bayesian Information Criterion (BIC). <strong>Here we focus on the AIC.</strong></p>
</section>
<section id="about-aic" class="slide level2">
<h2>About AIC</h2>
<ul>
<li>Most <strong>popular</strong> model selection criterion (can be used for non-nested models)</li>
<li>Developed by <a href="https://en.wikipedia.org/wiki/Hirotugu_Akaike">Hirotsugu Akaike</a> under the name of “an information criterion” (AIC)</li>
<li>Founded on information theory which is concerned with the transmission, processing, utilization, and extraction of information.</li>
</ul>
<p><span class="math display">\[AIC = 2k - 2\ln(L)\]</span></p>
</section>
<section id="about-aic-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">About AIC</h2>
<p><span class="math display">\[AIC = 2k - 2\ln(L)\]</span></p>
<ul>
<li><span class="math inline">\(k\)</span> is the number of parameters in the model (predictors + intercept)</li>
<li><span class="math inline">\(L\)</span> is the maximum value of the likelihood function
<ul>
<li>If we predict using the (current) model, what is the probability density of the prediction compared to the original distribution?</li>
<li><span class="math inline">\(ln(L)\)</span> = goodness of fit (higher is better)</li>
</ul></li>
<li>For the number of parameters in the model (<span class="math inline">\(2k\)</span>) subtract the goodness of fit <span class="math inline">\(2ln(L)\)</span>
<ul>
<li><strong>The smaller the AIC, the better the model fits the data.</strong></li>
<li>A <em>relative</em> measure and <em>unitless</em>, so it is not worth trying to interpret alone.</li>
</ul></li>
<li>Can be calculated with the <code>AIC()</code> function in R</li>
</ul>
</section>
<section id="about-aic---fyi" class="slide level2">
<h2>About AIC - FYI</h2>
<p>In linear regression, AIC is sometimes calculated as:</p>
<p><span class="math display">\[AIC = n\log(\frac{RSS}{n}) + 2k\]</span></p>
<p>where <span class="math inline">\(RSS\)</span> is the residual sum of squares, <span class="math inline">\(2k\)</span> is the number of parameters in the model, and <span class="math inline">\(n\)</span> is the number of observations.</p>
<ul>
<li>The difference between this equation and the previous equation is a constant, or scaling</li>
<li>The <code>step()</code> function in R uses this equation (hence you may notice a difference in AIC values!)</li>
</ul>
</section>
<section id="back-to-our-example" class="slide level2">
<h2>Back to our example</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a>back_step <span class="ot">&lt;-</span> <span class="fu">step</span>(loyn_fit, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=214.14
ABUND ~ YR.ISOL + GRAZE + ALT + AREA_L10 + LDIST_L10 + DIST_L10

            Df Sum of Sq    RSS    AIC
- LDIST_L10  1      3.80 2000.7 212.25
- DIST_L10   1      4.68 2001.5 212.27
- ALT        1     27.02 2023.9 212.90
&lt;none&gt;                   1996.8 214.14
- YR.ISOL    1    108.83 2105.7 215.11
- GRAZE      1    131.07 2127.9 215.70
- AREA_L10   1   1059.75 3056.6 235.98

Step:  AIC=212.25
ABUND ~ YR.ISOL + GRAZE + ALT + AREA_L10 + DIST_L10

           Df Sum of Sq    RSS    AIC
- DIST_L10  1     12.64 2013.3 210.60
- ALT       1     35.12 2035.8 211.22
&lt;none&gt;                  2000.7 212.25
- YR.ISOL   1    121.64 2122.3 213.55
- GRAZE     1    132.44 2133.1 213.84
- AREA_L10  1   1193.04 3193.7 236.44

Step:  AIC=210.6
ABUND ~ YR.ISOL + GRAZE + ALT + AREA_L10

           Df Sum of Sq    RSS    AIC
- ALT       1     57.84 2071.1 210.19
&lt;none&gt;                  2013.3 210.60
- GRAZE     1    123.48 2136.8 211.94
- YR.ISOL   1    134.89 2148.2 212.23
- AREA_L10  1   1227.11 3240.4 235.25

Step:  AIC=210.19
ABUND ~ YR.ISOL + GRAZE + AREA_L10

           Df Sum of Sq    RSS    AIC
&lt;none&gt;                  2071.1 210.19
- YR.ISOL   1    129.81 2200.9 211.59
- GRAZE     1    188.45 2259.6 213.06
- AREA_L10  1   1262.97 3334.1 234.85</code></pre>
</div>
</div>
</section>
<section id="section-3" class="slide level2">
<h2></h2>
<p>Printing <code>back_step</code> reveals the final model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a>back_step</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ABUND ~ YR.ISOL + GRAZE + AREA_L10, data = loyn)

Coefficients:
(Intercept)      YR.ISOL        GRAZE     AREA_L10  
 -134.26065      0.07835     -1.90216      7.16617  </code></pre>
</div>
</div>
</section>
<section id="backward-elimination-coefficients" class="slide level2">
<h2>Backward elimination: coefficients</h2>
<p><strong>Full model</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(</span>
<span id="cb45-2"><a></a>  loyn_fit, back_step, </span>
<span id="cb45-3"><a></a>  <span class="at">show.ci =</span> <span class="cn">FALSE</span>, </span>
<span id="cb45-4"><a></a>  <span class="at">show.aic =</span> <span class="cn">TRUE</span>,</span>
<span id="cb45-5"><a></a>  <span class="at">dv.labels =</span> <span class="fu">c</span>(<span class="st">"Full model"</span>,</span>
<span id="cb45-6"><a></a>                <span class="st">"Reduced model"</span>)</span>
<span id="cb45-7"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top" style="border-collapse:collapse; border:none;">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Full model</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Reduced model</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-125.70</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.177</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-134.26</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.126</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">YR ISOL</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.07</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.109</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.08</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.077</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">GRAZE</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-1.67</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.079</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-1.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.034</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">ALT</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.02</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.419</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">AREA L10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.47</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.17</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">LDIST L10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.761</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">DIST L10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.91</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.736</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">56</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">56</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.685 / 0.646</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.673 / 0.654</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">AIC</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">375.064</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">371.109</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The reduced model retains more explanatory power than the full model!</p>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center">
<h1>Summary</h1>

</section>
<section id="model-selection" class="slide level2">
<h2>Model selection</h2>
<p><strong>Model development</strong></p>
<ol type="1">
<li>Start with full model and check assumptions (e.g.&nbsp;normality, homoscedasticity, linearity, etc.).</li>
<li>Look for additional issues (e.g.&nbsp;multicollinearity, outliers, etc.) – correlations, leverage, VIF plots.</li>
<li>Consider transformations (e.g.&nbsp;log, sqrt, etc.).</li>
<li>Test assumptions again.</li>
</ol>
<p><strong>Model selection</strong></p>
<ol start="5" type="1">
<li>Use VIF as an initial step to get rid of highly correlated predictors.</li>
<li>Perform variable selection using backward elimination (good and fast), because:
<ul>
<li>Using R<sup>2</sup> as a criterion is <em>not</em> recommended (it is not a good measure of model fit, only a good measure of variance explained).</li>
<li>Using partial F-test is good, but slow.</li>
</ul></li>
</ol>
</section></section>
<section>
<section id="next-lecture" class="title-slide slide level1 center">
<h1>Next lecture</h1>

</section>
<section id="next-lecture-model-training-and-prediction" class="slide level2">
<h2>Next lecture: model training and prediction</h2>
<ul>
<li>How to incorporate calibration and validation into your workflow</li>
<li>Determining prediction intervals and performance metrics</li>
</ul>
</section></section>
<section id="thanks" class="title-slide slide level1 center">
<h1>Thanks!</h1>
<p><strong>Questions? Comments?</strong></p>
<p>Slides made with <a href="https://quarto.org">Quarto</a></p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>