{
  "hash": "e2c055849903d985bf3eb7f2c651820b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tutorial 03\"\n# reviewed-by:\nformat:\n  sandstone-html:\n    code-tools: true\n---\n\n## Welcome {.unnumbered}\n\nIn this tutorial you will build a diagnostic toolkit for checking the assumptions behind t-tests and ANOVA, then take apart an ANOVA table step by step to understand what every number means.\n\nYou will learn how to:\n\n1. Check the assumptions of t-tests and ANOVA using visual and formal diagnostic tools.\n2. Recognise what \"good\" and \"bad\" diagnostics look like in practice.\n3. Construct an ANOVA table by hand from summary statistics.\n4. Interpret the F statistic and degrees of freedom in the context of an experiment.\n\n\n\n\n# Part 1: Checking assumptions\n\nBefore you trust the output of a t-test or ANOVA, you need to check whether the test was appropriate for the data. Both tests share the same assumptions because a two-sample t-test is a special case of one-way ANOVA with two groups. The underlying model is the same: comparing group means against a common error term.\n\nThe three assumptions are:\n\n1. **Normality** --- the residuals follow a normal distribution.\n2. **Equal variance** --- the spread of observations is roughly the same across groups.\n3. **Independence** --- the observations do not influence each other.\n\nThe first two are checked using diagnostic tools built around the **residuals** of a fitted model. Independence is different: it is a property of the study design, not something you can see in a plot. If samples were collected properly (random assignment, no repeated measures on the same subject), independence is satisfied.\n\n::: {.column-margin}\nThink of these checks as a toolkit, not a rigid checklist. ANOVA is robust to moderate departures from normality, especially with balanced designs and reasonable sample sizes. Judgement is involved.\n:::\n\n\n## 1a. What do good and bad diagnostics look like?\n\nThe tutor will walk through two datasets. The first meets the assumptions well. The second does not. For each dataset you will see the same five diagnostic checks. Focus on learning to read the patterns rather than on the R code behind them.\n\n### A well-behaved dataset {.unnumbered}\n\nThis dataset records the weight (in kg) of cattle from two breeds. Breed 1 has 12 observations and Breed 2 has 15. The data come from a lecture example.\n\n\n::: {.cell}\n\n:::\n\n\n**Boxplots** show the distribution of raw data within each group. Look for similar spread and no extreme skew.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Boxplots of cattle weight by breed](tutorial03_files/figure-html/fig-good-boxplot-1.png){#fig-good-boxplot width=672}\n:::\n:::\n\n\n**QQ plot of residuals** checks normality. Points should fall close to the red line.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Normal QQ plot of residuals (cattle data)](tutorial03_files/figure-html/fig-good-qq-1.png){#fig-good-qq width=672}\n:::\n:::\n\n\n**Shapiro-Wilk test** is a formal test of normality. A large p-value (above 0.05) means there is no strong evidence against normality. Keep in mind that this test rejects normality too readily with large samples and has low power with small samples. Treat it as one piece of evidence alongside the QQ plot, not a definitive gate.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(model_good)\nW = 0.95228, p-value = 0.2434\n```\n\n\n:::\n:::\n\n\n::: {.column-margin}\nThe plot below comes from a fitted model. You will learn to produce this yourself shortly. For now, focus on what the pattern tells you.\n:::\n\n**Residuals vs fitted plot** checks for equal variance and patterns. What to look for:\n\n- Random scatter around zero = good\n- Fan shape (wider spread on one side) = unequal variance\n- Curve = a non-linear relationship the model missed\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residuals vs fitted values (cattle data)](tutorial03_files/figure-html/fig-good-rvf-1.png){#fig-good-rvf width=672}\n:::\n:::\n\n\n**SD ratio** is a quick numeric check for equal variance. Compute the ratio of the largest group SD to the smallest. A ratio below 2 is generally acceptable.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nGroup SDs: 10.62 12.3 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSD ratio: 1.16\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n### Source code\n\n```r\n# Load and reshape cattle data\ncattle_wide <- read.csv(\"../lectures/L03/data/cattle.csv\")\ncattle_long <- data.frame(\n  Breed = c(\n    rep(\"Breed1\", sum(!is.na(cattle_wide$Breed1))),\n    rep(\"Breed2\", sum(!is.na(cattle_wide$Breed2)))\n  ),\n  Weight = c(\n    cattle_wide$Breed1[!is.na(cattle_wide$Breed1)],\n    cattle_wide$Breed2[!is.na(cattle_wide$Breed2)]\n  )\n)\nmodel_good <- aov(Weight ~ Breed, data = cattle_long)\n\n# Boxplot\nboxplot(Weight ~ Breed, data = cattle_long,\n        ylab = \"Weight (kg)\", xlab = \"Breed\",\n        col = c(\"lightblue\", \"lightgreen\"))\n\n# QQ plot\nqqnorm(residuals(model_good), main = \"\")\nqqline(residuals(model_good), col = \"red\")\n\n# Shapiro-Wilk test\nshapiro.test(residuals(model_good))\n\n# Residuals vs fitted\nplot(fitted(model_good), residuals(model_good),\n     xlab = \"Fitted values\", ylab = \"Residuals\",\n     pch = 16, col = \"steelblue\")\nabline(h = 0, lty = 2, col = \"grey\")\n\n# SD ratio\nsds_good <- tapply(cattle_long$Weight, cattle_long$Breed, sd)\nmax(sds_good) / min(sds_good)\n```\n:::\n\n\n### A problematic dataset {.unnumbered}\n\nThis simulated dataset has two groups of 15 observations each. Group A is drawn from a normal distribution. Group B is drawn from a right-skewed distribution with much larger variance. The violations are deliberately exaggerated to make them easy to spot.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Boxplots by group (simulated data)](tutorial03_files/figure-html/fig-bad-boxplot-1.png){#fig-bad-boxplot width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Normal QQ plot of residuals (simulated data)](tutorial03_files/figure-html/fig-bad-qq-1.png){#fig-bad-qq width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(model_bad)\nW = 0.83946, p-value = 0.000376\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residuals vs fitted values (simulated data)](tutorial03_files/figure-html/fig-bad-rvf-1.png){#fig-bad-rvf width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nGroup SDs: 1.42 11.28 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSD ratio: 7.94\n```\n\n\n:::\n:::\n\n\nCompare these to the cattle diagnostics. The boxplots show very different spread between the two groups. The QQ plot curves away from the reference line, indicating right skew in the residuals. The Shapiro-Wilk p-value is low, providing formal evidence against normality. The residuals-vs-fitted plot shows a fan shape --- variance is much larger for one group. The SD ratio is well above 2. These data clearly violate the assumptions of equal variance and normality.\n\n::: {.callout-tip collapse=\"true\"}\n### Source code\n\n```r\n# Simulated data with clear violations\nset.seed(2001)\nbad <- data.frame(\n  group = rep(c(\"A\", \"B\"), each = 15),\n  value = c(rnorm(15, 10, 2), rexp(15, rate = 0.1))\n)\nmodel_bad <- aov(value ~ group, data = bad)\n\n# Boxplot\nboxplot(value ~ group, data = bad,\n        ylab = \"Value\", xlab = \"Group\",\n        col = c(\"lightblue\", \"lightyellow\"))\n\n# QQ plot\nqqnorm(residuals(model_bad), main = \"\")\nqqline(residuals(model_bad), col = \"red\")\n\n# Shapiro-Wilk test\nshapiro.test(residuals(model_bad))\n\n# Residuals vs fitted\nplot(fitted(model_bad), residuals(model_bad),\n     xlab = \"Fitted values\", ylab = \"Residuals\",\n     pch = 16, col = \"tomato\")\nabline(h = 0, lty = 2, col = \"grey\")\n\n# SD ratio\nsds_bad <- tapply(bad$value, bad$group, sd)\nmax(sds_bad) / min(sds_bad)\n```\n:::\n\n\n### Discussion {.unnumbered}\n\n1. Would you be comfortable running a t-test on the cattle data? What gave you confidence?\n2. Which assumption is most clearly violated in the second dataset? How can you tell?\n3. ANOVA is robust to moderate departures from normality, especially with balanced designs. At what point would you decide the violations are too severe?\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Suggested answers\n\n1. Yes. The QQ plot shows points close to the line, the Shapiro-Wilk test has a large p-value (no evidence against normality), the boxplots show similar spread, and the SD ratio is about 1.16 (well below 2). The residuals-vs-fitted plot shows no obvious pattern.\n\n2. The equal variance assumption is the most dramatically violated. The SD ratio is close to 8, far above the rule-of-thumb threshold of 2. The boxplots show Group B is much more spread out than Group A, and the residuals-vs-fitted plot shows a clear fan shape. Normality is also violated (the QQ plot shows strong departure in the tails and the Shapiro-Wilk p-value is very small).\n\n3. There is no single threshold. In practice, consider the severity of the violation (moderate skew vs extreme skew), the balance and size of the design (balanced designs with reasonable n are more robust), and whether multiple diagnostics point in the same direction. If the QQ plot, Shapiro-Wilk, and residuals-vs-fitted all suggest problems, you should be concerned. If only one diagnostic is borderline, the test is likely still reliable.\n:::\n::::\n\n\n## 1b. Your turn: checking assumptions with PlantGrowth\n\nThe `PlantGrowth` dataset is built into R. It records the dried weight of plants under a control and two treatment conditions (30 observations, 10 per group, balanced design).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(PlantGrowth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t30 obs. of  2 variables:\n $ weight: num  4.17 5.58 5.18 6.11 4.5 4.61 5.17 4.53 5.33 5.14 ...\n $ group : Factor w/ 3 levels \"ctrl\",\"trt1\",..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\n::: {.question}\n### Worked Example 1\n\nFit a one-way ANOVA model to the PlantGrowth data and run all five diagnostic checks:\n\n1. Boxplot of the raw data\n2. QQ plot of the residuals\n3. Shapiro-Wilk test on the residuals\n4. Residuals vs fitted plot\n5. SD ratio\n\nThen interpret the results. Would you be comfortable running ANOVA on this dataset?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Solution\n\nFit the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_pg <- aov(weight ~ group, data = PlantGrowth)\n```\n:::\n\n\n**Boxplot:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(weight ~ group, data = PlantGrowth,\n        ylab = \"Dried weight\", xlab = \"Group\",\n        col = c(\"lightgreen\", \"lightyellow\", \"lightblue\"))\n```\n\n::: {.cell-output-display}\n![Plant weight by treatment group](tutorial03_files/figure-html/fig-pg-boxplot-1.png){#fig-pg-boxplot width=672}\n:::\n:::\n\n\n**QQ plot:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(residuals(model_pg), main = \"\")\nqqline(residuals(model_pg), col = \"red\")\n```\n\n::: {.cell-output-display}\n![Normal QQ plot of residuals (PlantGrowth)](tutorial03_files/figure-html/fig-pg-qq-1.png){#fig-pg-qq width=672}\n:::\n:::\n\n\n**Shapiro-Wilk:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(model_pg))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(model_pg)\nW = 0.96607, p-value = 0.4379\n```\n\n\n:::\n:::\n\n\n**Residuals vs fitted:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fitted(model_pg), residuals(model_pg),\n     xlab = \"Fitted values\", ylab = \"Residuals\",\n     pch = 16, col = \"darkgreen\")\nabline(h = 0, lty = 2, col = \"grey\")\n```\n\n::: {.cell-output-display}\n![Residuals vs fitted values (PlantGrowth)](tutorial03_files/figure-html/fig-pg-rvf-1.png){#fig-pg-rvf width=672}\n:::\n:::\n\n\n**SD ratio:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsds_pg <- tapply(PlantGrowth$weight, PlantGrowth$group, sd)\nsds_pg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ctrl      trt1      trt2 \n0.5830914 0.7936757 0.4425733 \n```\n\n\n:::\n\n```{.r .cell-code}\nmax(sds_pg) / min(sds_pg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.79332\n```\n\n\n:::\n:::\n\n\n**Interpretation:** The QQ plot shows points reasonably close to the line, the Shapiro-Wilk test does not reject normality (p = 0.44), and the residuals-vs-fitted plot shows no obvious fan shape or curvature. The SD ratio is about 1.8, which is below the rule-of-thumb threshold of 2. The design is balanced (10 per group), which adds robustness. Overall, the assumptions are reasonably well met and ANOVA is appropriate here.\n:::\n\n### Discussion {.unnumbered}\n\n1. How do the diagnostics for PlantGrowth compare to the cattle data? Are there any differences worth noting?\n2. If one of the three groups had noticeably more spread than the others, which diagnostic would show it most clearly?\n\n::: {.column-margin}\nIf assumptions are violated, there are remedies --- transformations, non-parametric alternatives, or robust methods --- which you will encounter in later weeks.\n:::\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Suggested answers\n\n1. Both datasets meet the assumptions reasonably well. The PlantGrowth SD ratio (about 1.8) is slightly higher than the cattle data (about 1.2), but still acceptable. The QQ plots and Shapiro-Wilk results are similar in both cases. The main difference is that PlantGrowth has three groups, so the residuals-vs-fitted plot shows three columns of points instead of two.\n\n2. The boxplot and the residuals-vs-fitted plot would both show it. The boxplot would show a wider box for that group. The residuals-vs-fitted plot would show a wider spread of points at the fitted value corresponding to that group (a fan shape). The SD ratio would confirm it numerically.\n:::\n::::\n\n\n# Part 2: The ANOVA table\n\n## Introduction\n\nThe ANOVA table is not just a container for a p-value. Every number in it tells you something about the data and the experiment. In this section you will build an ANOVA table from summary statistics, one step at a time.\n\n::: {.column-margin}\nANOVA table calculations and interpretation are both examinable.\n:::\n\nThe point of this exercise is to appreciate how the table is constructed, not to practise arithmetic. By the end you should be able to answer questions like:\n\n- What does the F statistic tell us?\n- What is the difference between the treatment and residual sum of squares?\n- What is total mean squares ($MS_{tot}$) and how does it relate to the variance of the data?\n- Can the degrees of freedom tell us whether an experiment is balanced or unbalanced?\n\nIn practice, R can produce an ANOVA table in a fraction of a second. Many people skip straight to the p-value and ignore everything else. That throws away useful information. By working through the table by hand, you will learn to read every row.\n\n\n## The experiment\n\nA researcher tested three planting densities of a maize fodder crop (20, 30, and 40 plants per unit area) across 15 similar plots, resulting in 5 plots per planting density. The sample means and standard deviations (kg of dry matter per plot) for each planting density are shown below:\n\n\n::: {#tbl-maize-summary .cell}\n::: {.cell-output-display}\n\n\n|Treatment               |  Mean| Std.Dev|Variance |\n|:-----------------------|-----:|-------:|:--------|\n|20 plants per unit area | 17.58|    2.70|7.29     |\n|30 plants per unit area | 27.18|    1.89|3.577    |\n|40 plants per unit area | 27.14|    2.02|4.093    |\n|Overall                 | 23.97|    5.11|-        |\n\n\n:::\n:::\n\n\nWe wish to perform an analysis of variance (ANOVA) to determine whether planting density influenced the total dry weight of maize per plot. The ANOVA table is mostly empty. The labels $a$ through $i$ mark the values we need to calculate.\n\n::: {.column-margin}\nMissing values in the ANOVA table have been labelled $a$ to $i$ for reference.\n:::\n\n\n::: {#tbl-anova-empty .cell}\n::: {.cell-output-display}\n\n\n|Source    |df  |Sum Sq |Mean Sq  |F value |\n|:---------|:---|:------|:--------|:-------|\n|Treatment |$a$ |$d$    |$152.96$ |$i$     |\n|Residual  |$b$ |$e$    |$g$      |-       |\n|Total     |$c$ |$f$    |$h$      |-       |\n\n\n:::\n:::\n\n\nWhat we know:\n\n- There are $t = 3$ treatments and $N = 15$ total observations.\n- The treatment mean square $MS_{trt} = 152.96$.\n- The overall standard deviation is $s = 5.11$ (pooling all 15 observations).\n- Hint: the total mean square $MS_{tot}$ is approximately the overall variance of the data.\n\nThe formulas for each row of the ANOVA table are:\n\n\n::: {#tbl-anova-formulas .cell}\n::: {.cell-output-display}\n\n\n|Source    |Df      |Sum Sq     |Mean Sq                          |F value             |\n|:---------|:-------|:----------|:--------------------------------|:-------------------|\n|Treatment |$t - 1$ |$SS_{trt}$ |$MS_{trt} = SS_{trt} / df_{trt}$ |$MS_{trt}/MS_{res}$ |\n|Residual  |$N - t$ |$SS_{res}$ |$MS_{res} = SS_{res} / df_{res}$ |                    |\n|Total     |$N - 1$ |$SS_{tot}$ |$MS_{tot} = SS_{tot} / df_{tot}$ |                    |\n\n\n:::\n:::\n\n\n\n## Step 1: Degrees of freedom\n\nThe degrees of freedom are straightforward to fill in. With $t = 3$ treatments and $N = 15$ total observations:\n\n- **Treatment df** $= t - 1 = 3 - 1 = 2$\n- **Residual df** $= N - t = 15 - 3 = 12$\n- **Total df** $= N - 1 = 15 - 1 = 14$\n\n\n::: {#tbl-anova-step1 .cell}\n::: {.cell-output-display}\n\n\n|Source    |df            |Sum Sq |Mean Sq  |F value |\n|:---------|:-------------|:------|:--------|:-------|\n|Treatment |$\\mathbf{2}$  |$d$    |$152.96$ |$i$     |\n|Residual  |$\\mathbf{12}$ |$e$    |$g$      |        |\n|Total     |$\\mathbf{14}$ |$f$    |$h$      |        |\n\n\n:::\n:::\n\n\n### Discussion {.unnumbered}\n\nCan you tell from the degrees of freedom whether this experiment is balanced?\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Suggested answer\n\nYes. If $df_{trt} + df_{res} = df_{tot}$ (i.e. $2 + 12 = 14$), the experiment is balanced. Each treatment has the same number of replicates: $n = N / t = 15 / 3 = 5$. If the experiment were unbalanced (different numbers of replicates per treatment), the total df would still be $N - 1$, but the split between treatment and residual df would reflect the unequal group sizes.\n:::\n::::\n\n\n## Step 2: Total variance ($MS_{tot}$)\n\nTo calculate the total mean square $MS_{tot}$, we use the overall standard deviation $s = 5.11$. The variance is the square of the standard deviation:\n\n$$MS_{tot} = s^2_{tot} = 5.11^2 = 26.1121$$\n\n\n::: {#tbl-anova-step2 .cell}\n::: {.cell-output-display}\n\n\n|Source    |df   |Sum Sq |Mean Sq          |F value |\n|:---------|:----|:------|:----------------|:-------|\n|Treatment |$2$  |$d$    |$152.96$         |$i$     |\n|Residual  |$12$ |$e$    |$g$              |        |\n|Total     |$14$ |$f$    |$\\mathbf{26.11}$ |        |\n\n\n:::\n:::\n\n\n### Discussion {.unnumbered}\n\nWhen you look at the total mean square value, what does it tell you about the spread of the data?\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Suggested answer\n\nThe total mean square is the variance of the data as a whole (not treatment-specific). It tells us how much the data varies from the overall mean. A value of 26.11 means the data are moderately spread out. However, a large $MS_{tot}$ on its own does not tell us whether that spread is due to the treatment effect or to random variation within groups. The F statistic will help answer that question.\n:::\n::::\n\n\n## Step 3: Sum of squares ($SS_{tot}$ and $SS_{trt}$)\n\nSince a mean square is calculated by dividing the sum of squares by the degrees of freedom:\n\n$$MS = \\frac{SS}{df}$$\n\nwe can rearrange to get:\n\n$$SS = MS \\times df$$\n\nThe total sum of squares:\n\n$$SS_{tot} = MS_{tot} \\times df_{tot} = 26.1121 \\times 14 = 365.5694$$\n\nThe treatment sum of squares:\n\n$$SS_{trt} = MS_{trt} \\times df_{trt} = 152.96 \\times 2 = 305.92$$\n\n\n::: {#tbl-anova-step3 .cell}\n::: {.cell-output-display}\n\n\n|Source    |df   |Sum Sq            |Mean Sq  |F value |\n|:---------|:----|:-----------------|:--------|:-------|\n|Treatment |$2$  |$\\mathbf{305.92}$ |$152.96$ |$i$     |\n|Residual  |$12$ |$e$               |$g$      |        |\n|Total     |$14$ |$\\mathbf{365.57}$ |$26.11$  |        |\n\n\n:::\n:::\n\n\n### Discussion {.unnumbered}\n\nWhat is the difference between the treatment and residual sum of squares?\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Suggested answer\n\nThe treatment sum of squares $SS_{trt}$ measures how much the treatment means differ from the overall mean. It captures the variation *between* groups. The residual sum of squares $SS_{res}$ measures how much the individual observations differ from their own treatment means. It captures the variation *within* groups. Together they partition the total variation in the data: $SS_{tot} = SS_{trt} + SS_{res}$.\n:::\n::::\n\n\n## Step 4: Residual SS and MS\n\nSince $SS_{tot} = SS_{trt} + SS_{res}$, we can find the residual sum of squares by subtraction:\n\n$$SS_{res} = SS_{tot} - SS_{trt} = 365.5694 - 305.92 = 59.6494$$\n\nThen the residual mean square:\n\n$$MS_{res} = \\frac{SS_{res}}{df_{res}} = \\frac{59.6494}{12} = 4.9708$$\n\n\n::: {#tbl-anova-step4 .cell}\n::: {.cell-output-display}\n\n\n|Source    |df   |Sum Sq           |Mean Sq         |F value |\n|:---------|:----|:----------------|:---------------|:-------|\n|Treatment |$2$  |$305.92$         |$152.96$        |$i$     |\n|Residual  |$12$ |$\\mathbf{59.65}$ |$\\mathbf{4.97}$ |        |\n|Total     |$14$ |$365.57$         |$26.11$         |        |\n\n\n:::\n:::\n\n\n### Discussion {.unnumbered}\n\nWhy do we need mean squares if we already have the sum of squares?\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Suggested answer\n\nSum of squares grow with the number of observations, so they are not directly comparable across rows with different degrees of freedom. The mean square divides by the degrees of freedom to standardise the variation, making it fair to compare treatment variation with residual variation. The F statistic is the ratio of these standardised quantities.\n:::\n::::\n\n\n## Step 5: The F statistic\n\nFinally, we calculate the F statistic by dividing the treatment mean square by the residual mean square:\n\n$$F = \\frac{MS_{trt}}{MS_{res}} = \\frac{152.96}{4.9708} = 30.77$$\n\n\n::: {#tbl-anova-step5 .cell}\n::: {.cell-output-display}\n\n\n|Source    |df   |Sum Sq   |Mean Sq  |F value          |\n|:---------|:----|:--------|:--------|:----------------|\n|Treatment |$2$  |$305.92$ |$152.96$ |$\\mathbf{30.77}$ |\n|Residual  |$12$ |$59.65$  |$4.97$   |                 |\n|Total     |$14$ |$365.57$ |$26.11$  |                 |\n\n\n:::\n:::\n\n\n### Discussion {.unnumbered}\n\n1. What does an F value of 1 mean? What about an F value of 30?\n2. What if we had 10 replicates per treatment instead of 5? Which numbers in the table would change, and in which direction?\n\n:::: {.content-visible when-profile=\"solution\"}\n::: {.ans}\n### Suggested answers\n\n1. An F value of 1 means the variation between treatment means is about the same as the variation within groups. There is no evidence that the treatments differ. An F value of 30 means the between-group variation is 30 times larger than the within-group variation. This is strong evidence that at least one treatment mean differs from the others.\n\n2. With 10 replicates per treatment, $N$ would increase from 15 to 30. The residual df would increase from 12 to 27, and the total df from 14 to 29. More replicates generally reduce $MS_{res}$ (better estimate of within-group variation), which would increase the F statistic if the treatment effect remains the same. The treatment df would stay at 2 (still 3 treatments).\n:::\n::::\n\n\n## Reading an ANOVA table in practice\n\nThe F statistic is a signal-to-noise ratio. The numerator ($MS_{trt}$) measures how much the group means differ from each other. The denominator ($MS_{res}$) measures how much variability exists within groups. A large F means the signal is much larger than the noise.\n\nCombined with the degrees of freedom, the F statistic tells you:\n\n- Whether there is evidence of a treatment effect (large F relative to what you would expect by chance)\n- How much replication underpins that conclusion (the residual df)\n\n::: {.column-margin}\nF and df are necessary but not sufficient. They do not tell you about effect size, whether assumptions are met, or which groups differ.\n:::\n\nBut the F statistic does **not** tell you:\n\n- **How big the effect is** in practical terms (effect size is a separate question)\n- **Whether the assumptions are met** (that is what Part 1 was about)\n- **Which groups differ** (that requires post-hoc tests, covered in the lab)\n\n\n## Bonus: doing it in R\n\nHere is the complete calculation in R code, matching the hand calculations above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define known values\nN <- 15           # total number of observations\nt <- 3            # number of treatments\nms_trt <- 152.96  # treatment mean square\nsd_overall <- 5.11\n\n# Degrees of freedom\ndf_trt <- t - 1         # treatment df\ndf_residual <- N - t    # residual df\ndf_total <- N - 1       # total df\n\n# Mean squares and sums of squares\nms_total <- sd_overall^2              # total mean square\nss_total <- ms_total * df_total       # total sum of squares\nss_trt <- ms_trt * df_trt            # treatment sum of squares\nss_residual <- ss_total - ss_trt     # residual sum of squares\nms_residual <- ss_residual / df_residual  # residual mean square\n\n# F statistic\nf_statistic <- ms_trt / ms_residual\n```\n:::\n\n\n\n::: {#tbl-anova-r .cell}\n::: {.cell-output-display}\n\n\n|Source    | Df| Sum.Sq| Mean.Sq|F.value |\n|:---------|--:|------:|-------:|:-------|\n|Treatment |  2|  305.9|   153.0|30.8    |\n|Residual  | 12|   59.6|     5.0|        |\n|Total     | 14|  365.6|    26.1|        |\n\n\n:::\n:::\n\n\n\n## Do you reject the null hypothesis?\n\nTo determine whether we reject the null hypothesis, we compare the F statistic to the F critical value. The F critical value is the value of F that marks the boundary of the rejection region under the null hypothesis. If the F statistic exceeds the F critical value, we reject the null.\n\n::: {.column-margin}\nWhen you run `summary(aov(...))` in R, the Total row is not shown. R only displays the treatment and residual rows.\n:::\n\nWe need the degrees of freedom for the treatment and residual, and the significance level (usually 0.05). The `qf()` function in R gives us the critical value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf(p = 0.05,\n   df1 = 2,   # treatment degrees of freedom\n   df2 = 12,  # residual degrees of freedom\n   lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.885294\n```\n\n\n:::\n:::\n\n\nSince the F statistic is 30.77, which is much larger than the F critical value of 3.89, we conclude that $P < 0.05$ and reject the null hypothesis that the treatment means are equal. There is strong evidence that planting density affects the dry weight of maize.\n\n\n## Which treatment means are different?\n\nRejecting the null hypothesis tells us that at least one treatment mean differs from the others. But which ones? To answer that, we would normally perform a post-hoc test such as Tukey's HSD. For now, the original summary table gives us a hint:\n\n\n::: {#tbl-maize-hint .cell}\n::: {.cell-output-display}\n\n\n|Treatment               |  Mean| Std.Dev|Variance |\n|:-----------------------|-----:|-------:|:--------|\n|20 plants per unit area | 17.58|    2.70|7.29     |\n|30 plants per unit area | 27.18|    1.89|3.577    |\n|40 plants per unit area | 27.14|    2.02|4.093    |\n|Overall                 | 23.97|    5.11|-        |\n\n\n:::\n:::\n\n\nThe mean dry weight for the 30 and 40 plants per unit area treatments are very similar (27.18 and 27.14). This suggests those two treatments are probably not significantly different from each other. The 20 plants per unit area treatment, with a mean of 17.58, is likely the one driving the significant F statistic.\n\nBut this is only a hint, not a definitive answer. The ANOVA table tells you whether group means differ overall. In the lab, you will learn how to identify which specific groups differ using post-hoc tests.\n\n\n# Summary {.unnumbered}\n\nIn this tutorial you:\n\n- Built a diagnostic toolkit for checking t-test and ANOVA assumptions\n- Learned that most diagnostics are different views on the **residuals**, and that independence is checked through study design\n- Took apart the ANOVA table step by step and understood what every number means\n- Saw why the F value and degrees of freedom are the first things to check when reading an ANOVA table\n\nNext week you will go deeper into residual-based diagnostics using standardised residuals.\n",
    "supporting": [
      "tutorial03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}