<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="The University of Sydney">

<title>Lab 08</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d2800b5aef52857891e752670e942548.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.js"></script>
<link href="../../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #000;
      }

      .quarto-title-block .quarto-title-banner {
        color: #000;
background: white;
      }
</style><noscript>
  <style>
    section.level2 { display: block !important; }
  </style>
</noscript>
<script>window.QUARTO_PROGRESSIVE_SECTIONS = true;</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../site_libs/quarto-contrib/quarto-project/sandstone/assets/styles.css">
</head>

<body class="floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Lab 08</h1>
            <p class="subtitle lead">ENVX2001 Applied Statistical Methods</p>
                  <div>
        <div class="description">
          The University of Sydney
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#welcome-to-week-8" id="toc-welcome-to-week-8" class="nav-link active" data-scroll-target="#welcome-to-week-8">Welcome to week 8!</a>
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning outcomes</a></li>
  <li><a href="#specific-goals" id="toc-specific-goals" class="nav-link" data-scroll-target="#specific-goals">Specific goals</a></li>
  <li><a href="#preparation" id="toc-preparation" class="nav-link" data-scroll-target="#preparation">Preparation</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#variable-selection-for-california-streamflow-45-mins" id="toc-variable-selection-for-california-streamflow-45-mins" class="nav-link" data-scroll-target="#variable-selection-for-california-streamflow-45-mins">1. Variable selection for California streamflow (~ 45 mins)</a>
  <ul class="collapse">
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a>
  <ul class="collapse">
  <li><a href="#exercise-1---exploring-full-and-reduced-models" id="toc-exercise-1---exploring-full-and-reduced-models" class="nav-link" data-scroll-target="#exercise-1---exploring-full-and-reduced-models">Exercise 1 - exploring full and reduced models</a></li>
  </ul></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a>
  <ul class="collapse">
  <li><a href="#exercise-2---which-model-is-a-significant-improvement" id="toc-exercise-2---which-model-is-a-significant-improvement" class="nav-link" data-scroll-target="#exercise-2---which-model-is-a-significant-improvement">Exercise 2 - which model is a significant improvement?</a></li>
  </ul></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"></a>
  <ul class="collapse">
  <li><a href="#exercise-3---stepwise-regression" id="toc-exercise-3---stepwise-regression" class="nav-link" data-scroll-target="#exercise-3---stepwise-regression">Exercise 3 - stepwise regression</a></li>
  </ul></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3"></a>
  <ul class="collapse">
  <li><a href="#exercise-2---which-model-is-a-significant-improvement-1" id="toc-exercise-2---which-model-is-a-significant-improvement-1" class="nav-link" data-scroll-target="#exercise-2---which-model-is-a-significant-improvement-1">Exercise 2 - which model is a significant improvement?</a></li>
  </ul></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4"></a>
  <ul class="collapse">
  <li><a href="#exercise-3---stepwise-regression-1" id="toc-exercise-3---stepwise-regression-1" class="nav-link" data-scroll-target="#exercise-3---stepwise-regression-1">Exercise 3 - stepwise regression</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#variable-selection-for-plant-aridity-20-mins" id="toc-variable-selection-for-plant-aridity-20-mins" class="nav-link" data-scroll-target="#variable-selection-for-plant-aridity-20-mins">2. Variable selection for plant aridity (~20 mins)</a>
  <ul class="collapse">
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5"></a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab08-model-selection.pdf"><i class="bi bi-file-pdf"></i>Typst (sandstone)</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<section id="welcome-to-week-8" class="level1">
<h1>Welcome to week 8!</h1>
<p>This week’s lab will give you some practice improving models by selecting the most useful predictors.</p>
<p>This will prepare you for next week’s content where we will use models for prediction.</p>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning outcomes</h2>
<p>This module links to the following unit learning outcomes:</p>
<ul>
<li><p>LO3. demonstrate proficiency in the use or the statistical programming language R to apply an ANOVA and fit regression models to experimental data</p></li>
<li><p>LO5. interpret the output and understand conceptually how its derived of a regression, ANOVA and multivariate analysis that have been calculated by R</p></li>
<li><p>LO6. write statistical and modelling results as part of a scientific report</p></li>
</ul>
<p>In this lab, we will learn how to:</p>
<p><strong>1. Fit and interpret simple linear regression (SLR) models</strong> <strong>2. Fit and interpret multiple linear regression (MLR) models</strong> <strong>3. Assess model assumptions and apply transformations when needed</strong> <strong>4. Evaluate and compare model fit statistics</strong></p>
</section>
<section id="specific-goals" class="level2">
<h2 class="anchored" data-anchor-id="specific-goals">Specific goals</h2>
<p><strong>By the end of this lab, you should be able to:</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Fit a simple linear regression model</label></li>
<li><label><input type="checkbox">Assess model assumptions and apply transformations when needed</label></li>
<li><label><input type="checkbox">Interpret model parameters and fit statistics</label></li>
<li><label><input type="checkbox">Fit a multiple linear regression model</label></li>
<li><label><input type="checkbox">Assess model assumptions, including collinearity between predictor variables</label></li>
<li><label><input type="checkbox">Determine the most suitable fit statistics for a multiple linear regression model</label></li>
<li><label><input type="checkbox">Write a conclusion on your findings</label></li>
</ul>
<p><strong>FIX EVERYTHING UP above</strong></p>
</section>
<section id="preparation" class="level2">
<h2 class="anchored" data-anchor-id="preparation">Preparation</h2>
<p>Please work on these exercises by creating your own Quarto file. You are welcome to write your responses up in the style of a report.</p>
<section id="packages" class="level3">
<h3 class="anchored" data-anchor-id="packages">Packages</h3>
<p>This lab uses <code>tidyverse</code>, <code>readxl</code>, <code>moments</code>, <code>psych</code>, and <code>performance</code>. Install any you are missing by running the following <strong>in the console</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"car"</span>, <span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If a package is already installed, R will simply reinstall it — no harm done.</p>
</section>
</section>
</section>
<section id="variable-selection-for-california-streamflow-45-mins" class="level1 page-columns page-full">
<h1>1. Variable selection for California streamflow (~ 45 mins)</h1>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/AdobeStock_668401555.jpeg" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Little Lakes Valley in the Eastern Sierra Nevada Mountains outside of Bishop, California. Source: Adobe Stock.</figcaption>
</figure>
</div>
<p>Last week you were investigating the relationship between precipitation at three sites (Lake Sabrina, Pine Creek, and Rock Creek) and stream runoff volume at a site near Bishop, California. You found that Lake Sabrina was not a significant predictor of runoff volume, but Pine Creek and Rock Creek were.</p>
<p>This week we will follow steps to see if we can produce a more parsimonious model. We will be focussing on the process rather than report writing, but we still encourage you to write up your conclusions as if it were for a report.</p>
<p>As a recap, the california_streamflow dataset you were analysing contains 43 years of annual precipitation measurements (in mm) taken at (originally) 6 sites in the Owens Valley in California. You will focus on only 3 variables.</p>
<p>The data is in the <strong>california_streamflow.xlsx</strong> file.</p>
<p>Variables are as follows:</p>
<ul>
<li><code>lake_sabrina</code>: Precipitation recorded at Lake Sabrina (mm)</li>
<li><code>pine_creek</code>: Precipitation recorded at Big Pine Creek (mm),</li>
<li><code>rock_creek</code>: Precipitation recorded at Rock Creek (mm)</li>
<li><code>runoff_volume</code>: Stream runoff volume measured at a site near Bishop, California (ML/year). This will be the response variable.</li>
</ul>
<p>Note the variables have already been log-transformed to increase normality of the residuals in the regressions.</p>
<p>Data source: Hollett, K.J., Danskin, F.M., McCaffrey, W.F., and Walti, S.L., 1991. Geology and water resources of Owens Valley, California. U.S. Geological Survey Water-Supply Paper 2370-H.</p>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
<section id="exercise-1---exploring-full-and-reduced-models" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-1---exploring-full-and-reduced-models">Exercise 1 - exploring full and reduced models</h3>
<p><em>(i)</em> Read in the data and investigate the relationship between each of your variables. Describe the relationships, supported by values (correlation coefficient) and plots.</p>
<p><em>(ii)</em> Fit a multiple linear regression model to the data using all variables. Set <code>runoff_volume</code> as the response variable and <code>lake_sabrina</code>, <code>pine_creek</code> and <code>rock_creek</code> as the predictor variables. This will be known as the ‘full model’.</p>
<p><em>(iii)</em> Check the assumptions of your model. Do you need to transform any variables? What does the Variance Inflation Factor (VIF) tell you about the collinearity between predictor variables?</p>
<p>HINT: The VIF will appear as one of the plots in the <code>check_model()</code> function, but it can also be helpful to get the values. You can use the <code>vif()</code> function from the <code>car</code> package to get the VIF values for each predictor variable.</p>
<p><em>(iv)</em> Make a note of the model parameters and fit statistics for the full model.</p>
<p><em>(v)</em> Remove <code>lake_sabrina</code> from the model and run the model again. This will be known as the ‘reduced model’.</p>
<p><em>(vi)</em> Is the reduced model an improvement on the full model? How can you tell? What statistics would you look at to determine this?</p>
</section>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
<section id="exercise-2---which-model-is-a-significant-improvement" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-2---which-model-is-a-significant-improvement">Exercise 2 - which model is a significant improvement?</h3>
<p>We can compare the models using the adjusted r<sup>2</sup>, but we will need to use hypothesis testing to decide whether the reduced model is a significant improvement or not. Let’s explore this by using the F-test to compare the full and reduced models.</p>
<p><em>(i)</em> State the null and alternative hypotheses for the F-test between the full and reduced models.</p>
<p><em>(ii)</em> Perform the F-test using the <code>anova()</code> function to compare the full and reduced models. What is the p-value? Based on this, what might we conclude to be the better model?</p>
</section>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2"></h2>
<section id="exercise-3---stepwise-regression" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-3---stepwise-regression">Exercise 3 - stepwise regression</h3>
<p>Instead of removing one predictor at a time, there is a much quicker way involving the <code>step()</code> function in R. This function performs stepwise regression, which is an automated process of adding or removing predictors based on their significance in the model and the Akaike Information Criterion (AIC).</p>
<p><em>(i)</em> When using the AIC, how do we select the better model?</p>
<p><em>(ii)</em> Have a go at running the <code>step()</code> function on the full model. Which model does it select as the best model?</p>
<p><em>(iii)</em> One final check: what are the AIC values for the full and reduced models? Which model has the lowest AIC value?</p>
<p>HINT: you can use the <code>AIC()</code> function to get the AIC values for each model. Insert the model name between the brackets.</p>
<p><em>(iv)</em> Based on our tests, which model do you think is the best model to use for predicting runoff volume at Bishop, California? Why have you chosen this model?</p>
</section>
<section id="solution" class="level4 ans">
<h4 class="anchored" data-anchor-id="solution">Solution</h4>
<section id="i-read-in-the-data-and-investigate-the-relationship-between-each-of-your-variables.-describe-the-relationships-supported-by-values-correlation-coefficient-and-plots." class="level5">
<h5 class="anchored" data-anchor-id="i-read-in-the-data-and-investigate-the-relationship-between-each-of-your-variables.-describe-the-relationships-supported-by-values-correlation-coefficient-and-plots."><em>(i)</em> Read in the data and investigate the relationship between each of your variables. Describe the relationships, supported by values (correlation coefficient) and plots.</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2"></a></span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="co"># read in the data</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>stream_data <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/california_streamflow.xlsx"</span>, <span class="st">"streamflow"</span>)</span>
<span id="cb2-5"><a href="#cb2-5"></a></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">glimpse</span>(stream_data) <span class="co"># check the data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 43
Columns: 4
$ lake_sabrina  &lt;dbl&gt; 1.958717, 2.087881, 1.981175, 2.054169, 2.102934, 2.1568…
$ pine_creek    &lt;dbl&gt; 2.017618, 2.282781, 2.383471, 2.451719, 2.618086, 2.3532…
$ rock_creek    &lt;dbl&gt; 2.275823, 2.450548, 2.491194, 2.585246, 2.706948, 2.3159…
$ runoff_volume &lt;dbl&gt; 4.825412, 4.920867, 4.911735, 4.924242, 5.120841, 4.9210…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># Correlations and scatterplots all in one (+ histograms for each variable)</span></span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="fu">library</span>(psych)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">pairs.panels</span>(stream_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab08-model-selection_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># can also get the same results separately</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="fu">cor</span>(stream_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              lake_sabrina pine_creek rock_creek runoff_volume
lake_sabrina    1.00000000 0.07848517 0.09054996     0.1649284
pine_creek      0.07848517 1.00000000 0.88381452     0.8929251
rock_creek      0.09054996 0.88381452 1.00000000     0.9194688
runoff_volume   0.16492838 0.89292511 0.91946880     1.0000000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">pairs</span>(stream_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab08-model-selection_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Similar to what we found last week, we see that runoff volume has a strong relationship with rock creek and pine creek, but not with lake sabrina. We also see that there is a strong relationship between rock creek and pine creek, which could be a sign of collinearity. We can confirm if this may be an issue with the model by observing the Variance inflation factor (VIF) later on when we check our model assumptions.</p>
</section>
<section id="ii-fit-a-multiple-linear-regression-model-to-the-data-using-all-variables.-set-runoff_volume-as-the-response-variable-and-lake_sabrina-pine_creek-and-rock_creek-as-the-predictor-variables.-this-will-be-known-as-the-full-model." class="level5">
<h5 class="anchored" data-anchor-id="ii-fit-a-multiple-linear-regression-model-to-the-data-using-all-variables.-set-runoff_volume-as-the-response-variable-and-lake_sabrina-pine_creek-and-rock_creek-as-the-predictor-variables.-this-will-be-known-as-the-full-model."><em>(ii)</em> Fit a multiple linear regression model to the data using all variables. Set <code>runoff_volume</code> as the response variable and <code>lake_sabrina</code>, <code>pine_creek</code> and <code>rock_creek</code> as the predictor variables. This will be known as the ‘full model’.</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># fit the full model</span></span>
<span id="cb11-2"><a href="#cb11-2"></a></span>
<span id="cb11-3"><a href="#cb11-3"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(runoff_volume <span class="sc">~</span> lake_sabrina <span class="sc">+</span> pine_creek <span class="sc">+</span> rock_creek, <span class="at">data =</span> stream_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="iii-check-the-assumptions-of-your-model.-do-you-need-to-transform-any-variables-what-does-the-variance-inflation-factor-vif-tell-you-about-the-collinearity-between-predictor-variables" class="level5">
<h5 class="anchored" data-anchor-id="iii-check-the-assumptions-of-your-model.-do-you-need-to-transform-any-variables-what-does-the-variance-inflation-factor-vif-tell-you-about-the-collinearity-between-predictor-variables"><em>(iii)</em> Check the assumptions of your model. Do you need to transform any variables? What does the Variance Inflation Factor (VIF) tell you about the collinearity between predictor variables?</h5>
<p>HINT: The VIF will appear as one of the plots in the <code>check_model()</code> function, but it can also be helpful to get the values. You can use the <code>vif()</code> function from the <code>car</code> package to get the VIF values for each predictor variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb12-2"><a href="#cb12-2"></a></span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="fu">check_model</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab08-model-selection_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co"># Lake Sabrina is doing something weird, so let's get VIF values too</span></span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a>car<span class="sc">::</span><span class="fu">vif</span>(full_model) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>) <span class="co"># numbers</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>lake_sabrina   pine_creek   rock_creek 
        1.01         4.57         4.58 </code></pre>
</div>
</div>
<p>Lake Sabrina = 1.01</p>
<p>Pine_creek = 4.57</p>
<p>Rock_creek = 4.58</p>
<p>Our threshold is 5, so given all of our VIFs are below this, we are not too concerned about collinearity. However, because they are close to the threshold it is something to keep in mind when interpreting the model parameters.</p>
</section>
<section id="iv-make-a-note-of-the-model-parameters-and-fit-statistics-for-the-full-model." class="level5">
<h5 class="anchored" data-anchor-id="iv-make-a-note-of-the-model-parameters-and-fit-statistics-for-the-full-model."><em>(iv)</em> Make a note of the model parameters and fit statistics for the full model.</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">summary</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = runoff_volume ~ lake_sabrina + pine_creek + rock_creek, 
    data = stream_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.09885 -0.03331  0.01025  0.03359  0.09495 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.25716    0.12360  26.352  &lt; 2e-16 ***
lake_sabrina  0.05631    0.03756   1.499  0.14185    
pine_creek    0.21085    0.06756   3.121  0.00339 ** 
rock_creek    0.43838    0.08798   4.983 1.32e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04861 on 39 degrees of freedom
Multiple R-squared:  0.8817,    Adjusted R-squared:  0.8726 
F-statistic: 96.88 on 3 and 39 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As we saw last week, Lake Sabrina is not a significant predictor of runoff volume, but Pine Creek and Rock Creek are. The model has an adjusted R<sup>2</sup> of 0.87, which means that 87% of the variation in runoff volume can be explained by the three predictor variables.</p>
</section>
<section id="v-remove-lake_sabrina-from-the-model-and-run-the-model-again.-this-will-be-known-as-the-reduced-model." class="level5">
<h5 class="anchored" data-anchor-id="v-remove-lake_sabrina-from-the-model-and-run-the-model-again.-this-will-be-known-as-the-reduced-model."><em>(v)</em> Remove <code>lake_sabrina</code> from the model and run the model again. This will be known as the ‘reduced model’.</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>reduced_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(runoff_volume <span class="sc">~</span> pine_creek <span class="sc">+</span> rock_creek, <span class="at">data =</span> stream_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="vi-is-the-reduced-model-an-improvement-on-the-full-model-how-can-you-tell-what-statistics-would-you-look-at-to-determine-this" class="level5">
<h5 class="anchored" data-anchor-id="vi-is-the-reduced-model-an-improvement-on-the-full-model-how-can-you-tell-what-statistics-would-you-look-at-to-determine-this"><em>(vi)</em> Is the reduced model an improvement on the full model? How can you tell? What statistics would you look at to determine this?</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">summary</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = runoff_volume ~ lake_sabrina + pine_creek + rock_creek, 
    data = stream_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.09885 -0.03331  0.01025  0.03359  0.09495 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.25716    0.12360  26.352  &lt; 2e-16 ***
lake_sabrina  0.05631    0.03756   1.499  0.14185    
pine_creek    0.21085    0.06756   3.121  0.00339 ** 
rock_creek    0.43838    0.08798   4.983 1.32e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04861 on 39 degrees of freedom
Multiple R-squared:  0.8817,    Adjusted R-squared:  0.8726 
F-statistic: 96.88 on 3 and 39 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">summary</span>(reduced_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = runoff_volume ~ pine_creek + rock_creek, data = stream_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.09832 -0.02350  0.01076  0.03291  0.08568 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.35762    0.10547  31.835  &lt; 2e-16 ***
pine_creek   0.21051    0.06861   3.068  0.00385 ** 
rock_creek   0.44437    0.08925   4.979 1.26e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04937 on 40 degrees of freedom
Multiple R-squared:  0.8749,    Adjusted R-squared:  0.8686 
F-statistic: 139.8 on 2 and 40 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Removing the <code>lake_sabrina</code> predictor from the model has slightly decreased the adjusted R<sup>2</sup> value, but it has also removed a non-significant predictor from the model. This is an improvement in terms of parsimony, but we will need to use hypothesis testing to determine whether the reduced model is a <em>significant</em> improvement on the full model. We can do this using an F-test, which we will explore in the next exercise.</p>
</section>
</section>
</section>
<section id="section-3" class="level2">
<h2 class="anchored" data-anchor-id="section-3"></h2>
<section id="exercise-2---which-model-is-a-significant-improvement-1" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-2---which-model-is-a-significant-improvement-1">Exercise 2 - which model is a significant improvement?</h3>
<p>We can compare the models using the adjusted r<sup>2</sup>, but we will need to use hypothesis testing to decide whether the reduced model is a significant improvement or not. Let’s explore this by using the F-test to compare the full and reduced models.</p>
<section id="i-state-the-null-and-alternative-hypotheses-for-the-f-test-between-the-full-and-reduced-models." class="level5">
<h5 class="anchored" data-anchor-id="i-state-the-null-and-alternative-hypotheses-for-the-f-test-between-the-full-and-reduced-models."><em>(i)</em> State the null and alternative hypotheses for the F-test between the full and reduced models.</h5>
<p>H0: No significant difference between full and reduced models H1: There is a significant difference between full and reduced models</p>
</section>
<section id="ii-perform-the-f-test-using-the-anova-function-to-compare-the-full-and-reduced-models.-what-is-the-p-value-based-on-this-what-might-we-conclude-to-be-the-better-model" class="level5">
<h5 class="anchored" data-anchor-id="ii-perform-the-f-test-using-the-anova-function-to-compare-the-full-and-reduced-models.-what-is-the-p-value-based-on-this-what-might-we-conclude-to-be-the-better-model"><em>(ii)</em> Perform the F-test using the <code>anova()</code> function to compare the full and reduced models. What is the p-value? Based on this, what might we conclude to be the better model?</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">anova</span>(full_model, reduced_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: runoff_volume ~ lake_sabrina + pine_creek + rock_creek
Model 2: runoff_volume ~ pine_creek + rock_creek
  Res.Df      RSS Df  Sum of Sq      F Pr(&gt;F)
1     39 0.092166                            
2     40 0.097478 -1 -0.0053121 2.2478 0.1419</code></pre>
</div>
</div>
<p>The P-value is 0.1419, which is larger than 0.05, so we fail to reject the null hypothesis. This means that the reduced model is not a significant improvement on the full model, and we would opt for the reduced model as it is more parsimonious.</p>
</section>
</section>
</section>
<section id="section-4" class="level2">
<h2 class="anchored" data-anchor-id="section-4"></h2>
<section id="exercise-3---stepwise-regression-1" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-3---stepwise-regression-1">Exercise 3 - stepwise regression</h3>
<p>Instead of removing one predictor at a time, there is a much quicker way involving the <code>step()</code> function in R. This function performs stepwise regression, which is an automated process of adding or removing predictors based on their significance in the model and the Akaike Information Criterion (AIC).</p>
<section id="i-when-using-the-aic-how-do-we-select-the-better-model" class="level5">
<h5 class="anchored" data-anchor-id="i-when-using-the-aic-how-do-we-select-the-better-model"><em>(i)</em> When using the AIC, how do we select the better model?</h5>
<p>Select the model with the lowest AIC value.</p>
<p>The AIC is a measure of the relative quality of a statistical model for a given set of data. It takes into account the goodness of fit and the complexity of the model (number of predictors). A lower AIC value indicates a better model.</p>
</section>
<section id="ii-have-a-go-at-running-the-step-function-on-the-full-model.-which-model-does-it-select-as-the-best-model" class="level5">
<h5 class="anchored" data-anchor-id="ii-have-a-go-at-running-the-step-function-on-the-full-model.-which-model-does-it-select-as-the-best-model"><em>(ii)</em> Have a go at running the <code>step()</code> function on the full model. Which model does it select as the best model?</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>step_model <span class="ot">&lt;-</span> <span class="fu">step</span>(full_model, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-256.25
runoff_volume ~ lake_sabrina + pine_creek + rock_creek

               Df Sum of Sq      RSS     AIC
&lt;none&gt;                      0.092166 -256.25
- lake_sabrina  1  0.005312 0.097478 -255.84
- pine_creek    1  0.023015 0.115181 -248.66
- rock_creek    1  0.058680 0.150845 -237.07</code></pre>
</div>
</div>
<p>The <code>step()</code> function selects the full model as the best model, which is inconsistent with our previous analysis using the F-test.</p>
<p>This is because the <code>step()</code> function uses the AIC to compare models, which is a different criterion than the F-test. The AIC takes into account both the goodness of fit and the complexity of the model, while the F-test only compares the goodness of fit between two models.</p>
<p>In this case, the AIC may be favoring the full model due to its better fit, even though it includes a non-significant predictor.</p>
</section>
<section id="iii-one-final-check-what-are-the-aic-values-for-the-full-and-reduced-models-which-model-has-the-lowest-aic-value" class="level5">
<h5 class="anchored" data-anchor-id="iii-one-final-check-what-are-the-aic-values-for-the-full-and-reduced-models-which-model-has-the-lowest-aic-value"><em>(iii)</em> One final check: what are the AIC values for the full and reduced models? Which model has the lowest AIC value?</h5>
<p>HINT: you can use the <code>AIC()</code> function to get the AIC values for each model. Insert the model name between the brackets.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">AIC</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -132.2222</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">AIC</span>(reduced_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -131.8126</code></pre>
</div>
</div>
</section>
<section id="iv-based-on-our-tests-which-model-do-you-think-is-the-best-model-to-use-for-predicting-runoff-volume-at-bishop-california-why-have-you-chosen-this-model" class="level5">
<h5 class="anchored" data-anchor-id="iv-based-on-our-tests-which-model-do-you-think-is-the-best-model-to-use-for-predicting-runoff-volume-at-bishop-california-why-have-you-chosen-this-model"><em>(iv)</em> Based on our tests, which model do you think is the best model to use for predicting runoff volume at Bishop, California? Why have you chosen this model?</h5>
<p>The reduced model is better. It is more parsimonious and does not include a non-significant predictor.</p>
<p>The F-test also indicates that the reduced model is not a significant improvement on the full model, so we would opt for the reduced model as it is simpler and just as good at explaining the variation in runoff volume.</p>
<p>We did see that the step function selected the full model as the best model based on AIC, but we would be cautious about this result given that it includes a non-significant predictor and the F-test did not support it as a significant improvement.</p>
<p>It was also helpful to calculate the AIC for our full and reduced models to confirm that the reduced model had a lower AIC value, which supports our choice of the reduced model.</p>
<p>Automated model selection methods are helpful when you have a large number of predictors, but our results demonstrate why we should not rely solely on these methods. We should also consider the significance of predictors and the overall fit of the model when making decisions about which model to use.</p>
</section>
</section>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before moving on to the next section, take a short break and stretch your legs.</p>
</div>
</div>
</section>
</section>
<section id="variable-selection-for-plant-aridity-20-mins" class="level1 page-columns page-full">
<h1>2. Variable selection for plant aridity (~20 mins)</h1>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/AdobeStock_659883118.jpeg" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Image of invasive capeweed. Source: Adobe Stock.</figcaption>
</figure>
</div>
<p>This dataset examines the adaptation of invasive capeweed (<em>Arctotheca calendula</em>) populations to aridity gradients across southern Australia. A common garden experiment was conducted from 2018-2019 with populations sourced from varying aridity levels, subjecting them to wet and dry treatments to measure traits related to drought escape, avoidance, and tolerance.</p>
<p>The dataset has been reduced to contain only the variables you will need to fit in the model. Furthermore, only the samples that received the wet treatment will be used for this analysis (n = 94 observations).</p>
<p>The dataset is in the <em>plant_aridity.csv</em> file.</p>
<p>Variables are as follows:</p>
<ul>
<li><code>growth_rate</code>: growth rate measured as differences in # of rosette leaves between zero and eight weeks after transplanting</li>
<li><code>days_to_flower</code>: days to first flowering since transplant (days)</li>
<li><code>specific_leaf_area</code>: specific leaf area as [leaf area (cm2) / dry mass (g)]</li>
<li><code>root_shoot_ratio</code>: root-to-shoot ratio [root mass/shoot mass]</li>
<li><code>chlorogenic_acid</code>: concentration of chlorogenic acid (mg/g frwt sample)</li>
<li><code>rel_fitness</code>: Relative fitness of each plant, seed count divided by the mean seed count</li>
</ul>
<p><code>rel_fitness</code> will be the response variable in your models, and the other variables will be the predictor variables.</p>
<p>Data source: Uesugi, Akane (2022). Data from: Multivariate selection mediated by aridity predicts divergence of drought resistant traits along natural aridity gradients of an invasive weed [Dataset]. Dryad. https://doi.org/10.5061/dryad.tht76hf17</p>
<p>Paper: Carvalho C, Davis R, Connallon T, Gleadow RM, Moore JL, Uesugi A. Multivariate selection mediated by aridity predicts divergence of drought-resistant traits along natural aridity gradients of an invasive weed. New Phytol. 2022 May;234(3):1088-1100. doi: 10.1111/nph.18018.</p>
<section id="section-5" class="level2">
<h2 class="anchored" data-anchor-id="section-5"></h2>
<div class="question">
<section id="exercise-1---initial-analyses" class="level3">
<h3 class="anchored" data-anchor-id="exercise-1---initial-analyses">Exercise 1 - initial analyses</h3>
<p><em>(i)</em> Write out the statistical model for a multiple linear regression and define it in terms of the data (i.e.&nbsp;relative fitness vs all other variables).</p>
<p>You can write it out in words and/or in mathematical notation.</p>
<p><span class="math display">
\textrm{relative_fitness} = \beta_0 + \beta_1\cdot \textrm{growth_rate} + \beta_2\cdot \textrm{days_to_flower} + \beta_3\cdot \textrm{specific_leaf_area} + \beta_4\cdot \textrm{root_shoot_ratio} +  \beta_5\cdot \textrm{chlorogenic_acid} + \epsilon_{i}
</span></p>
<p><em>(ii)</em> State the hypotheses you will be testing for the relationship between each site and runoff volume.</p>
<p>In multiple linear regression we are testing multiple hypotheses (one per predictor + one for the overall model).</p>
<p>Therefore:</p>
<ol type="1">
<li>Relationship between growth_rate and relative_fitness:</li>
</ol>
<p><span class="math display">H_0 : \beta_1 = 0</span></p>
<p><span class="math display">H_1 : \beta_1 \neq 0</span></p>
<ol start="2" type="1">
<li>days_to_flower and relative_fitness:</li>
</ol>
<p><span class="math display">H_0 : \beta_2 = 0</span> <span class="math display">H_1 : \beta_2 \neq 0</span></p>
<ol start="3" type="1">
<li>specific_leaf_area and relative_fitness:</li>
</ol>
<p><span class="math display">H_0 : \beta_3 = 0</span></p>
<p><span class="math display">H_1 : \beta_3 \neq 0</span></p>
<ol start="4" type="1">
<li>root_shoot_ratio and relative_fitness:</li>
</ol>
<p><span class="math display">H_0 : \beta_3 = 0</span></p>
<p><span class="math display">H_1 : \beta_3 \neq 0</span></p>
<ol start="5" type="1">
<li>chlorogenic_acid and relative_fitness:</li>
</ol>
<p><span class="math display">H_0 : \beta_4 = 0</span> <span class="math display">H_1 : \beta_4 \neq 0</span></p>
<ol start="4" type="1">
<li>Overall model:</li>
</ol>
<p><span class="math display">H_0 : \beta_1 = \beta_2 = \beta_3 = \beta_4 = \beta_5 = 0</span> <span class="math display">H_1 : \textrm{at least one } \beta_i \neq 0</span></p>
<p><em>(iii)</em> Read in the data and conduct some exploratory data analysis upon your variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>plant_aridity <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/plant_aridity.csv"</span>) </span>
<span id="cb30-2"><a href="#cb30-2"></a></span>
<span id="cb30-3"><a href="#cb30-3"></a><span class="fu">str</span>(plant_aridity)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   94 obs. of  6 variables:
 $ growth_rate       : num  -0.473 1.003 -0.301 0.742 1.436 ...
 $ days_to_flower    : num  1.496 0.647 -0.202 -0.415 -0.627 ...
 $ root_shoot_ratio  : num  -0.284 -0.504 -0.646 -0.463 1.204 ...
 $ specific_leaf_area: num  0.8466 -0.0843 0.1337 0.3673 0.4891 ...
 $ chlorogenic_acid  : num  0.594 -2.1821 -0.0745 1.4839 2.8136 ...
 $ rel_fitness       : num  1.63 1.248 2.172 2.834 0.682 ...</code></pre>
</div>
</div>
<p>Because we have more variables, it is ok to use the summary function here and report the values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">summary</span>(plant_aridity)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  growth_rate      days_to_flower     root_shoot_ratio  specific_leaf_area
 Min.   :-1.5164   Min.   :-1.90082   Min.   :-0.9722   Min.   :-2.3928   
 1st Qu.: 0.0694   1st Qu.:-0.78614   1st Qu.:-0.7792   1st Qu.:-0.2478   
 Median : 0.6536   Median : 0.11622   Median :-0.5730   Median : 0.0667   
 Mean   : 0.6526   Mean   : 0.08911   Mean   :-0.4217   Mean   : 0.0698   
 3rd Qu.: 1.2418   3rd Qu.: 0.64702   3rd Qu.:-0.2949   3rd Qu.: 0.4846   
 Max.   : 4.6546   Max.   : 2.98253   Max.   : 1.2066   Max.   : 2.4417   
 chlorogenic_acid     rel_fitness   
 Min.   :-2.195664   Min.   :0.599  
 1st Qu.:-0.605460   1st Qu.:1.364  
 Median :-0.007868   Median :1.821  
 Mean   :-0.024364   Mean   :1.867  
 3rd Qu.: 0.706484   3rd Qu.:2.268  
 Max.   : 2.813636   Max.   :4.350  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">apply</span>(plant_aridity, <span class="dv">2</span>, sd) <span class="co"># apply sd over columns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       growth_rate     days_to_flower   root_shoot_ratio specific_leaf_area 
         0.8872247          1.0503455          0.5012798          0.6328410 
  chlorogenic_acid        rel_fitness 
         0.9962748          0.6462569 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>moments<span class="sc">::</span><span class="fu">skewness</span>(plant_aridity, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       growth_rate     days_to_flower   root_shoot_ratio specific_leaf_area 
         0.8461223          0.3425118          1.4211986         -0.8075528 
  chlorogenic_acid        rel_fitness 
        -0.1087957          0.5975511 </code></pre>
</div>
</div>
<p>Growth rate: mean growth rate is 0.6526, which is similar to the median (0.6536), suggesting a relatively symmetric distribution. The standard deviation is 0.887. The skewness is 0.846, less than 1 but greater than 0.5, indicating a degree of skewness.</p>
<p>Days to flower: mean is 0.089, which is very close to the median (0.116), suggesting a symmetric distribution. The standard deviation is 1.05. The skewness is 0.343, which is close to zero, indicating a very symmetric distribution.</p>
<p>root_shoot_ratio: mean is -0.573, which is close to the median (-0.422), suggesting a symmetric distribution. The standard deviation is 0.501. The skewness is 1.42, which is greater than 1, indicating a positively skewed distribution.</p>
<p>specific_leaf_area: mean is 0.070, which is close to the median (0.067), suggesting a symmetric distribution. The standard deviation is 0.633. The skewness is -0.808, which is between -0.5 and -0.1, indicating a degree of skewness.</p>
<p>chlorogenic_acid: mean is -0.024, which is close to the median (-0.008), suggesting a symmetric distribution. The standard deviation is 0.996. The skewness is -0.109, which is close to zero, indicating a very symmetric distribution.</p>
<p>Specific leaf area: mean is 1.867, which is close to the median (1.821), suggesting a symmetric distribution. The standard deviation is 0.646. The skewness is 0.598, which is indicating a low amount of skewness.</p>
<p><em>(iv)</em> Investigate the relationship between each of your variables. Describe the relationship, supported by values (correlation coefficient) and plots.</p>
<p>Hint: we are not only looking at relationship between response and predictors here, but also the relationships between predictor variables (signs of collinearity).</p>
<p><em>(v)</em> Fit a multiple linear regression model to the data, with <code>runoff_volume</code> as the response variable and <code>lake_sabrina</code>, <code>pine_creek</code> and <code>rock_creek</code> as the predictor variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a>full_plant_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(rel_fitness <span class="sc">~</span> growth_rate <span class="sc">+</span> days_to_flower <span class="sc">+</span> </span>
<span id="cb38-2"><a href="#cb38-2"></a>    specific_leaf_area <span class="sc">+</span> root_shoot_ratio <span class="sc">+</span> chlorogenic_acid, </span>
<span id="cb38-3"><a href="#cb38-3"></a>    <span class="at">data =</span> plant_aridity)</span>
<span id="cb38-4"><a href="#cb38-4"></a></span>
<span id="cb38-5"><a href="#cb38-5"></a><span class="fu">summary</span>(full_plant_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rel_fitness ~ growth_rate + days_to_flower + specific_leaf_area + 
    root_shoot_ratio + chlorogenic_acid, data = plant_aridity)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.30267 -0.42467 -0.04943  0.42253  2.46902 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         1.67394    0.10120  16.541   &lt;2e-16 ***
growth_rate         0.13706    0.07513   1.824   0.0715 .  
days_to_flower      0.05923    0.06292   0.941   0.3492    
specific_leaf_area  0.12711    0.10493   1.211   0.2290    
root_shoot_ratio   -0.20716    0.13090  -1.583   0.1171    
chlorogenic_acid   -0.09623    0.06615  -1.455   0.1493    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6291 on 88 degrees of freedom
Multiple R-squared:  0.1033,    Adjusted R-squared:  0.05233 
F-statistic: 2.027 on 5 and 88 DF,  p-value: 0.08253</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="fu">check_model</span>(full_plant_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab08-model-selection_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(full_plant_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       growth_rate     days_to_flower specific_leaf_area   root_shoot_ratio 
          1.043994           1.026412           1.036008           1.011649 
  chlorogenic_acid 
          1.020416 </code></pre>
</div>
</div>
<p><em>(vi)</em> Check the assumptions of your model. Do you need to transform any variables?</p>
<p>Hint 1: you can use the the <code>check_model()</code> function from the <code>performance</code> package to check the assumptions of your model.</p>
<p>Hint 2: You may notice some collinearity occurring between predictors. This week you only need to acknowledge it and then you can move onto interpretation. Next week we will look at how to deal with collinearity in models.</p>
<p><em>(vii)</em> Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between precipitation at each site and runoff volume at Bishop, California?</p>
<p><em>(viii)</em> Write a concluding statement on your findings.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="co">#Load library if necessary</span></span>
<span id="cb43-2"><a href="#cb43-2"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb43-3"><a href="#cb43-3"></a></span>
<span id="cb43-4"><a href="#cb43-4"></a><span class="co">#Read in data</span></span>
<span id="cb43-5"><a href="#cb43-5"></a>fish_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/fish_communities.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 39 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): lake_id
dbl (6): chla, richness, evenness, abundance, biomass, productivity

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="co">#Have a look at the structure of the data</span></span>
<span id="cb45-2"><a href="#cb45-2"></a><span class="fu">str</span>(fish_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [39 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ lake_id     : chr [1:39] "FTH" "XLH" "HGH" "LH" ...
 $ chla        : num [1:39] 4.61 4.53 3.84 3.71 2.43 ...
 $ richness    : num [1:39] 2.64 2.89 1.99 2.94 2.37 ...
 $ evenness    : num [1:39] -0.356 -0.67 -0.423 -0.405 -0.589 ...
 $ abundance   : num [1:39] 2.24 3.34 1.24 2.67 1.12 ...
 $ biomass     : num [1:39] 4.96 6.03 4.67 6.52 5.32 ...
 $ productivity: num [1:39] 3.47 4.47 2.71 4.47 3.24 ...
 - attr(*, "spec")=
  .. cols(
  ..   lake_id = col_character(),
  ..   chla = col_double(),
  ..   richness = col_double(),
  ..   evenness = col_double(),
  ..   abundance = col_double(),
  ..   biomass = col_double(),
  ..   productivity = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>Explore the data on your own before making any models. (<em>Hint:</em> remember that we are only interested in the numeric variables for our linear models)</p>
</section>
<section id="section-6" class="level2">
<h2 class="anchored" data-anchor-id="section-6"></h2>
<section id="exercise-2" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-2">Exercise 2</h3>
<p><em>(i)</em> Write out the statistical model for a multiple linear regression and define it in terms of the data (precipitation at each site vs runoff volume at Bishop).</p>
<p>You can write it out in words and/or in mathematical notation.</p>
<p><em>(ii)</em> State the hypotheses you will be testing for the relationship between each site and runoff volume.</p>
<p><em>(iii)</em> Read in the data and conduct some exploratory data analysis upon your variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots.</p>
<p><em>(iv)</em> Investigate the relationship between each of your variables. Describe the relationship, supported by values (correlation coefficient) and plots.</p>
<p>Hint: we are not only looking at relationship between response and predictors here, but also the relationships between predictor variables (signs of collinearity).</p>
<p><em>(v)</em> Fit a multiple linear regression model to the data, with <code>runoff_volume</code> as the response variable and <code>lake_sabrina</code>, <code>pine_creek</code> and <code>rock_creek</code> as the predictor variables.</p>
<p><em>(vi)</em> Check the assumptions of your model. Do you need to transform any variables?</p>
<p>Hint 1: you can use the the <code>check_model()</code> function from the <code>performance</code> package to check the assumptions of your model.</p>
<p>Hint 2: You may notice some collinearity occurring between predictors. This week you only need to acknowledge it and then you can move onto interpretation. Next week we will look at how to deal with collinearity in models.</p>
<p><em>(vii)</em> Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between precipitation at each site and runoff volume at Bishop, California?</p>
<p><em>(viii)</em> Write a concluding statement on your findings.</p>
<p>Hint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.</p>
</section>


</section>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>The University of Sydney</p>
</div>
  </div>
</footer>




</body></html>