<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 09</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-d2800b5aef52857891e752670e942548.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.js"></script>
<link href="../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #000;
      }

      .quarto-title-block .quarto-title-banner {
        color: #000;
background: white;
      }
</style><noscript>
  <style>
    section.level2 { display: block !important; }
  </style>
</noscript>
<script>window.QUARTO_PROGRESSIVE_SECTIONS = true;</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../site_libs/quarto-contrib/quarto-project/sandstone/assets/styles.css">
</head>

<body class="floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Tutorial 09</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
            <p class="subtitle lead">ENVX2001 – Applied Statistical Methods</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">Semester 1</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#welcome-to-week-9" id="toc-welcome-to-week-9" class="nav-link active" data-scroll-target="#welcome-to-week-9">Welcome to week 9!</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages"><span class="header-section-number">0.1</span> Packages</a>
  <ul class="collapse">
  <li><a href="#downloads" id="toc-downloads" class="nav-link" data-scroll-target="#downloads">Downloads</a></li>
  </ul></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">0.2</span> The data</a></li>
  <li><a href="#data-splitting" id="toc-data-splitting" class="nav-link" data-scroll-target="#data-splitting"><span class="header-section-number">1</span> Data splitting</a></li>
  <li><a href="#fit-the-model-to-the-training-data" id="toc-fit-the-model-to-the-training-data" class="nav-link" data-scroll-target="#fit-the-model-to-the-training-data"><span class="header-section-number">2</span> Fit the model to the training data</a></li>
  <li><a href="#setting-up-for-our-analysis" id="toc-setting-up-for-our-analysis" class="nav-link" data-scroll-target="#setting-up-for-our-analysis"><span class="header-section-number">3</span> Setting up for our analysis</a>
  <ul class="collapse">
  <li><a href="#workflow-for-fitting-parsimonious-models" id="toc-workflow-for-fitting-parsimonious-models" class="nav-link" data-scroll-target="#workflow-for-fitting-parsimonious-models"><span class="header-section-number">3.1</span> Workflow for fitting parsimonious models</a></li>
  <li><a href="#packages-1" id="toc-packages-1" class="nav-link" data-scroll-target="#packages-1"><span class="header-section-number">3.2</span> Packages</a></li>
  <li><a href="#the-data-1" id="toc-the-data-1" class="nav-link" data-scroll-target="#the-data-1"><span class="header-section-number">3.3</span> The data</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">4</span> Analysis</a>
  <ul class="collapse">
  <li><a href="#model-development" id="toc-model-development" class="nav-link" data-scroll-target="#model-development"><span class="header-section-number">4.1</span> Model development</a></li>
  <li><a href="#model-selection-with-f-tests" id="toc-model-selection-with-f-tests" class="nav-link" data-scroll-target="#model-selection-with-f-tests"><span class="header-section-number">4.2</span> Model selection with F-tests</a></li>
  </ul></li>
  <li><a href="#model-selection-using-stepwise-regression" id="toc-model-selection-using-stepwise-regression" class="nav-link" data-scroll-target="#model-selection-using-stepwise-regression"><span class="header-section-number">5</span> Model selection using Stepwise regression</a>
  <ul class="collapse">
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up">Wrap-up</a>
  <ul class="collapse">
  <li><a href="#example-exam-questions" id="toc-example-exam-questions" class="nav-link" data-scroll-target="#example-exam-questions">Example exam questions</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="tutorial09.pdf"><i class="bi bi-file-pdf"></i>Typst (sandstone)</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<section id="welcome-to-week-9" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="welcome-to-week-9">Welcome to week 9!</h2>
<p>This week’s lecture introduced you to how we use models for prediction and how we assess the quality of the predictions.We will follow similar steps in today’s tutorial and lab class.</p>
<p>In this tutorial we will cover the key steps to fit a model, use it to make predictions, and then check assumptions, and select the most appropriate model.</p>
<p><strong>You will learn how to:</strong></p>
<ol type="1">
<li>Split data into training and test subsets</li>
<li>Fit your model to the training data and check assumptions are met</li>
<li>Use the trained model to make predictions using the training and the test subsets</li>
<li>Observe the quality of the predictions using appropriate statistics and plots</li>
</ol>
</section>
<section id="packages" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="packages"><span class="header-section-number">0.1</span> Packages</h2>
<p>This tutorial uses <code>tidyverse</code>, <code>readxl</code>, <code>moments</code>, <code>psych</code>, <code>performance</code> and <code>car</code>. Install any you are missing by running the following <strong>in the console</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>, <span class="st">"car"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If a package is already installed, R will simply reinstall it — no harm done.</p>
<section id="downloads" class="level3">
<h3 class="anchored" data-anchor-id="downloads">Downloads</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>File</th>
<th>Used in</th>
<th>Download</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Dippers.csv</code></td>
<td>all exercises</td>
<td><a href="data/Dippers.csv">Download</a></td>
</tr>
</tbody>
</table>
<p>Save the file into a folder called <code>data</code> inside your project folder.</p>
</section>
</section>
<section id="the-data" class="level2 page-columns page-full" data-number="0.2">
<h2 data-number="0.2" class="anchored" data-anchor-id="the-data"><span class="header-section-number">0.2</span> The data</h2>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/AdobeStock_93907188.jpeg" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Cute little Dipper (bird) standing on a rock by the water. Image source: markmedcalf via Adobe Stock.</figcaption>
</figure>
</div>
<p><a href="https://en.wikipedia.org/wiki/Dipper">Dippers</a> are thrush-sized birds living mainly in the upper reaches of rivers, which feed on benthic invertebrates by probing the river beds with their beaks. The dataset in this exercise contains data from a biological survey which examined the nature of the variables thought to influence the breeding of British dippers.</p>
<p>Twenty-two sites were included in the survey. Some of the variables have been transformed.</p>
<p>Data can be found in: <strong>Dippers.csv</strong></p>
<p>The variables measured were:</p>
<ul>
<li><code>Altitude</code> site altitude</li>
<li><code>Hardness</code> water hardness</li>
<li><code>RiverSlope</code> river-bed slope</li>
<li><code>LogCadd</code> the numbers of caddis fly larvae, transformed</li>
<li><code>LogStone</code> the numbers of stonefly larvae, transformed</li>
<li><code>LogMay</code> the numbers of mayfly larvae, transformed</li>
<li><code>LogOther</code> the numbers of all other invertebrates collected, transformed</li>
<li><code>Br_Dens</code> the number of breeding pairs of dippers per 10 km of river</li>
</ul>
<p>In the analyses, the four invertebrate variables were transformed using a <span class="math inline">log(x+1)</span> transformation.</p>
<p><code>Br_Dens</code> will be the response variable in our models.</p>
<p>Last week following use of the step() function, we found the most parsimonious model to be:</p>
<p><strong>Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogOther</strong></p>
<p>Model assumptions were met and the model explained 76% of variation in dipper breeding pair density, which was quite good.</p>
<p>We will use this model in our walkthrough today.</p>
</section>
<section id="data-splitting" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Data splitting</h1>
<p>Making predictions involves substituting in new values of x into our model equation to get new values of y.</p>
<p>We could use single values for each of our predictor variables and substitute them into the equation, but this is unrealistic and time consuming when we have a large number of observations. We therefore use a dataset containing our new observations of x to make the predictions and feed this into our model.</p>
<p>To understand the ability our model to predict new values of y from values of x previously unseen by the model, we need to test this on data that has not been used to fit the model.</p>
<p>It is common practice to split the data we have into two parts: a training (or calibration) subset and a test (or validation) subset. For each subset, we feed the predictor values into the model to get predictions of the y variable. We can then compare the predicted y with the observed y contained within each subset to get an indication of how well our model is performing.</p>
<p>Let’s read the data in and start splitting!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="co"># read in the data</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>dippers <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/Dippers.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3"></a></span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="fu">glimpse</span>(dippers) <span class="co"># check the data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 22
Columns: 8
$ Altitude   &lt;int&gt; 259, 198, 251, 184, 145, 145, 198, 160, 251, 159, 160, 145,…
$ Hardness   &lt;dbl&gt; 12.20, 22.00, 26.30, 22.50, 29.50, 39.90, 42.80, 59.60, 69.…
$ RiverSlope &lt;dbl&gt; 10.90, 14.70, 6.90, 4.60, 1.91, 5.00, 6.20, 14.30, 4.60, 3.…
$ LogCadd    &lt;dbl&gt; 2.303, 2.890, 3.784, 4.419, 3.219, 3.932, 3.664, 4.431, 3.7…
$ LogStone   &lt;dbl&gt; 5.242, 4.344, 5.231, 5.242, 3.829, 4.898, 4.357, 6.337, 5.4…
$ LogMay     &lt;dbl&gt; 0.000, 3.401, 5.826, 5.749, 5.509, 5.749, 5.371, 0.000, 4.8…
$ LogOther   &lt;dbl&gt; 1.386, 1.609, 1.386, 1.386, 1.099, 3.045, 1.386, 2.944, 2.5…
$ Br_Dens    &lt;dbl&gt; 3.60, 4.30, 3.80, 3.40, 3.80, 4.50, 4.30, 5.00, 4.50, 3.40,…</code></pre>
</div>
</div>
<p>There are different ways of splitting data, but what you choose generally depends on your dataset and the question you are trying to answer.</p>
<p>For example, we might split our dataset based on:</p>
<ul>
<li>a random selection of observations (random sampling)</li>
<li>certain factors or groups within the dataset (stratified sampling)</li>
<li>spatial location</li>
<li>time</li>
</ul>
<p>For today, we will be making a random split of the data, which is the most common method.</p>
<p>Because the sample size is very small, we will use 80% of the data for training and 20% for testing. The more observations we have to train the model, the better.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb4-2"><a href="#cb4-2"></a></span>
<span id="cb4-3"><a href="#cb4-3"></a>indexes <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(dippers), <span class="at">size =</span> <span class="fl">0.2</span> <span class="sc">*</span> <span class="fu">nrow</span>(dippers)) <span class="co"># randomly sample 20% of rows in the dataset</span></span>
<span id="cb4-4"><a href="#cb4-4"></a></span>
<span id="cb4-5"><a href="#cb4-5"></a>dippers_train <span class="ot">&lt;-</span> dippers[<span class="sc">-</span>indexes, ] <span class="co"># remove the 20% - training dataset</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>dippers_test <span class="ot">&lt;-</span> dippers[indexes, ] <span class="co"># select the 20% - test dataset</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In the code above, we first set a seed to ensure that we can reproduce the same random sample if we were to rerun the code chunk. Then we use the <code>sample()</code> function to randomly select 20% of the row indices from the dataset.</p>
<p>We create the training dataset by removing these selected indices from the original dataset ( [-index,] says “exclude everything but these indices”), and we create the test dataset by selecting only those indices.</p>
<p>Once we have split the data, we need to check the subsets. First ensure the structure and number of observations in each subset is correct, and then check the distribution of the variables (max, mean, median, min) in each subset to ensure they are similar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">str</span>(dippers_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   18 obs. of  8 variables:
 $ Altitude  : int  198 251 184 145 198 160 251 160 145 214 ...
 $ Hardness  : num  22 26.3 22.5 39.9 42.8 ...
 $ RiverSlope: num  14.7 6.9 4.6 5 6.2 14.3 4.6 15.8 5.9 5.7 ...
 $ LogCadd   : num  2.89 3.78 4.42 3.93 3.66 ...
 $ LogStone  : num  4.34 5.23 5.24 4.9 4.36 ...
 $ LogMay    : num  3.4 5.83 5.75 5.75 5.37 ...
 $ LogOther  : num  1.61 1.39 1.39 3.04 1.39 ...
 $ Br_Dens   : num  4.3 3.8 3.4 4.5 4.3 5 4.5 4.5 6.9 3.5 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">str</span>(dippers_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4 obs. of  8 variables:
 $ Altitude  : int  83 145 259 159
 $ Hardness  : num  153.9 29.5 12.2 68
 $ RiverSlope: num  2.88 1.91 10.9 3.3
 $ LogCadd   : num  2.83 3.22 2.3 4.45
 $ LogStone  : num  3.04 3.83 5.24 3.53
 $ LogMay    : num  5.9 5.51 0 6.03
 $ LogOther  : num  5.83 1.1 1.39 3.47
 $ Br_Dens   : num  2.9 3.8 3.6 3.4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">summary</span>(dippers_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Altitude        Hardness        RiverSlope       LogCadd     
 Min.   :107.0   Min.   : 15.50   Min.   : 4.60   Min.   :2.890  
 1st Qu.:160.0   1st Qu.: 40.62   1st Qu.: 5.75   1st Qu.:3.784  
 Median :187.5   Median : 84.73   Median : 7.25   Median :4.040  
 Mean   :195.8   Mean   : 74.07   Mean   :10.34   Mean   :4.326  
 3rd Qu.:236.5   3rd Qu.: 94.05   3rd Qu.:14.60   3rd Qu.:4.804  
 Max.   :305.0   Max.   :150.50   Max.   :26.20   Max.   :5.951  
    LogStone         LogMay         LogOther        Br_Dens     
 Min.   :3.434   Min.   :0.000   Min.   :1.099   Min.   :3.400  
 1st Qu.:4.599   1st Qu.:5.617   1st Qu.:1.848   1st Qu.:4.000  
 Median :5.175   Median :5.947   Median :3.132   Median :4.500  
 Mean   :5.215   Mean   :5.545   Mean   :3.419   Mean   :4.937  
 3rd Qu.:5.751   3rd Qu.:6.277   3rd Qu.:4.726   3rd Qu.:5.000  
 Max.   :6.791   Max.   :6.880   Max.   :6.773   Max.   :8.460  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">summary</span>(dippers_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Altitude        Hardness        RiverSlope        LogCadd     
 Min.   : 83.0   Min.   : 12.20   Min.   : 1.910   Min.   :2.303  
 1st Qu.:129.5   1st Qu.: 25.18   1st Qu.: 2.638   1st Qu.:2.700  
 Median :152.0   Median : 48.75   Median : 3.090   Median :3.026  
 Mean   :161.5   Mean   : 65.90   Mean   : 4.747   Mean   :3.202  
 3rd Qu.:184.0   3rd Qu.: 89.47   3rd Qu.: 5.200   3rd Qu.:3.528  
 Max.   :259.0   Max.   :153.90   Max.   :10.900   Max.   :4.454  
    LogStone         LogMay         LogOther        Br_Dens     
 Min.   :3.045   Min.   :0.000   Min.   :1.099   Min.   :2.900  
 1st Qu.:3.406   1st Qu.:4.132   1st Qu.:1.314   1st Qu.:3.275  
 Median :3.678   Median :5.705   Median :2.426   Median :3.500  
 Mean   :3.910   Mean   :4.360   Mean   :2.944   Mean   :3.425  
 3rd Qu.:4.182   3rd Qu.:5.933   3rd Qu.:4.056   3rd Qu.:3.650  
 Max.   :5.242   Max.   :6.031   Max.   :5.826   Max.   :3.800  </code></pre>
</div>
</div>
<p>We can see that the training dataset contains 18 observations and the test dataset contains 4 observations, which is very small, so we don’t expect to get very reliable information from the prediction quality statistics, but it still worth continuing to understand the process and see how we go.</p>
<p>Because of the limited sample size, we can see that the max and min values vary, but the distributions aren’t too different (e.g.&nbsp;we don’t have our response in one subset following a log distribution and the other following a normal distribution.)</p>
<p>From here we can proceed to model fitting.</p>
</section>
<section id="fit-the-model-to-the-training-data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Fit the model to the training data</h1>
<p>We only use the training data to fit the model. For this tutorial we will use the model we optimised last week:</p>
<p><strong>Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogOther</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co"># fit the model to the training data</span></span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a>train_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Br_Dens <span class="sc">~</span> Hardness <span class="sc">+</span> RiverSlope <span class="sc">+</span> LogCadd <span class="sc">+</span> LogStone <span class="sc">+</span> LogOther, <span class="at">data =</span> dippers_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can do a quick assumption check to ensure the model is appropriate for the training data, but we won’t go through this in detail as we have already done this for the full dataset last week.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="co"># Linearity</span></span>
<span id="cb14-3"><a href="#cb14-3"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"linearity"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># Normality</span></span>
<span id="cb15-2"><a href="#cb15-2"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"qq"</span>, <span class="st">"normality"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># Equal variance</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"homogeneity"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Outliers</span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"outliers"</span>, <span class="st">"pp_check"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-6-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># VIF - visual</span></span>
<span id="cb18-2"><a href="#cb18-2"></a><span class="fu">plot</span>(performance<span class="sc">::</span><span class="fu">check_collinearity</span>(train_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-6-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># VIF - numbers</span></span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="co"># comes from the car package</span></span>
<span id="cb19-3"><a href="#cb19-3"></a>car<span class="sc">::</span><span class="fu">vif</span>(train_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Hardness RiverSlope    LogCadd   LogStone   LogOther 
  1.613588   1.500583   2.218855   2.229204   2.362211 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="do">#### ALTERNATIVE: plot() function to check assumptions </span></span>
<span id="cb21-2"><a href="#cb21-2"></a></span>
<span id="cb21-3"><a href="#cb21-3"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb21-4"><a href="#cb21-4"></a></span>
<span id="cb21-5"><a href="#cb21-5"></a><span class="fu">plot</span>(train_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-6-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>Linearity: The relationship between the predictors and the response variable appears to be potentially nonlinear, because although the points are scattered, the line is indicating a possible trend.</p></li>
<li><p>Independence: The residuals appear to be independent.</p></li>
<li><p>Normality: The residuals appear to be approximately normally distributed, as the points in the Q-Q plot roughly follow a straight line. When we look at the <code>check_model()</code> version of the plot we a slight n-shape to the points, but this is only small compared to the overall distribution of the points, so we are not too concerned about this.</p></li>
<li><p>Equal variance: The residuals appear to have constant variance, as there is no clear pattern or fanning present in the standardised residuals vs fitted plot (scale-location in the base plot).</p></li>
<li><p>Leverage: No single observations lying outside the Cook’s distance line, indicating no influential observations.</p></li>
</ul>
<p>We use the training set to fit the model and check assumptions. We can also use this subset to make predictions and check the quality of the predictions. The predictions made with this subset will often look quite good, but this is because the observed y value has been used in model fitting; therefore we do not assess the true predictive performance of the model using the training set alone. Instead we can compare the prediction quality statistics and plots with those of the test set to get an indication of overfitting.</p>
<p>The test subset is a set of values which are not used to fit the model, and is therefore unseen by the model. This allows us to pretend we have a new set of values, but then we have the advantage of the actual observed y variable sitting within the dataset too, so we are able to test how similar the predictions are to our real observation.</p>
<p>We will run through this using last week’s data:</p>
<p>If the model is good, we expect the predictions to be close to the actual values.</p>
<p>If the model is bad, we expect the predictions to be far from the actual values.</p>
<p>The dataset can be obtained by:</p>
<p>Collecting new data.</p>
<p>Splitting the existing data into two parts before model building.</p>
<p>Data splitting</p>
<p>Cross-validation</p>
<p><em>use cars dataset?</em></p>
<p>This week’s lecture introduced you to variable selection and how to produce a more parsimonious model. We explored developing our models by fitting the full model, checking assumptions and deciding whether anything needed transformation. Once we were happy assumptions were met we could consider whether all of our predictors were useful in explaining the variation in our response variable.</p>
<p>In this tutorial, we will explore a new dataset and follow the steps of model selection to produce a model that explains a sufficient amount of variation, without being unnecessarily complex.</p>
<p><strong>You will learn how to:</strong></p>
<ol type="1">
<li>Check for collinearity and influential observations in a MLR model</li>
<li>Run partial F-tests to compare nested models</li>
<li>Implement stepwise regression using the <code>step()</code> function in R</li>
</ol>
</section>
<section id="setting-up-for-our-analysis" class="level1 page-columns page-full" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Setting up for our analysis</h1>
<section id="workflow-for-fitting-parsimonious-models" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="workflow-for-fitting-parsimonious-models"><span class="header-section-number">3.1</span> Workflow for fitting parsimonious models</h2>
<p><em>1. Model development</em></p>
<ul>
<li>Start with full model and check assumptions (e.g.&nbsp;normality, homoscedasticity, linearity, etc.)</li>
<li>Look for additional issues (e.g.&nbsp;multicollinearity, outliers, etc.) <br> -–&gt; correlations, leverage plot, VIF plots and statistics</li>
<li>Consider transformations (e.g.&nbsp;log, sqrt, etc.). <br> –&gt; Response: if assumptions aren’t met, transform the response variable <br> –&gt; Predictors: it may help to explore transformations of skewed predictors before fitting the model to explore if there is a relationship present. Transforming predictors generally does not affect assumptions, but it can help to linearise relationships and make them easier to interpret.</li>
<li>Following any transformations, test assumptions again.</li>
</ul>
<p><em>2. Model selection</em></p>
<ul>
<li>Use VIF as an initial step to get rid of highly correlated predictors.</li>
<li>Perform variable selection using backward elimination (good and fast), because:</li>
<li>Using r<sup>2</sup>2 as a criterion is not recommended (it is not a good measure of model fit, only a good measure of variance explained).</li>
<li>Using partial F-test is good, but slow.</li>
</ul>
</section>
<section id="packages-1" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="packages-1"><span class="header-section-number">3.2</span> Packages</h2>
<p>This tutorial uses <code>tidyverse</code>, <code>readxl</code>, <code>moments</code>, <code>psych</code>, <code>performance</code> and <code>car</code>. Install any you are missing by running the following <strong>in the console</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>, <span class="st">"car"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If a package is already installed, R will simply reinstall it — no harm done.</p>
</section>
<section id="the-data-1" class="level2 page-columns page-full" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="the-data-1"><span class="header-section-number">3.3</span> The data</h2>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/AdobeStock_93907188.jpeg" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Cute little Dipper (bird) standing on a rock by the water. Image source: markmedcalf via Adobe Stock.</figcaption>
</figure>
</div>
<p><a href="https://en.wikipedia.org/wiki/Dipper">Dippers</a> are thrush-sized birds living mainly in the upper reaches of rivers, which feed on benthic invertebrates by probing the river beds with their beaks. The dataset in this exercise contains data from a biological survey which examined the nature of the variables thought to influence the breeding of British dippers.</p>
<p>Twenty-two sites were included in the survey. Some of the variables have been transformed.</p>
<p>Data can be found in: <strong>Dippers.csv</strong></p>
<p>The variables measured were:</p>
<ul>
<li><code>Altitude</code> site altitude</li>
<li><code>Hardness</code> water hardness</li>
<li><code>RiverSlope</code> river-bed slope</li>
<li><code>LogCadd</code> the numbers of caddis fly larvae, transformed</li>
<li><code>LogStone</code> the numbers of stonefly larvae, transformed</li>
<li><code>LogMay</code> the numbers of mayfly larvae, transformed</li>
<li><code>LogOther</code> the numbers of all other invertebrates collected, transformed</li>
<li><code>Br_Dens</code> the number of breeding pairs of dippers per 10 km of river</li>
</ul>
<p>In the analyses, the four invertebrate variables were transformed using a <span class="math inline">log(x+1)</span> transformation.</p>
<p><code>Br_Dens</code> will be the response variable in our models.</p>
</section>
</section>
<section id="analysis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Analysis</h1>
<section id="model-development" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="model-development"><span class="header-section-number">4.1</span> Model development</h2>
<p><em>(i)</em> Read in the data and investigate the relationship between each of your variables. Describe the relationships, supported by values (correlation coefficient) and plots.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># read in the data</span></span>
<span id="cb24-2"><a href="#cb24-2"></a>dippers <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/Dippers.csv"</span>)</span>
<span id="cb24-3"><a href="#cb24-3"></a></span>
<span id="cb24-4"><a href="#cb24-4"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="fu">glimpse</span>(dippers) <span class="co"># check the data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 22
Columns: 8
$ Altitude   &lt;int&gt; 259, 198, 251, 184, 145, 145, 198, 160, 251, 159, 160, 145,…
$ Hardness   &lt;dbl&gt; 12.20, 22.00, 26.30, 22.50, 29.50, 39.90, 42.80, 59.60, 69.…
$ RiverSlope &lt;dbl&gt; 10.90, 14.70, 6.90, 4.60, 1.91, 5.00, 6.20, 14.30, 4.60, 3.…
$ LogCadd    &lt;dbl&gt; 2.303, 2.890, 3.784, 4.419, 3.219, 3.932, 3.664, 4.431, 3.7…
$ LogStone   &lt;dbl&gt; 5.242, 4.344, 5.231, 5.242, 3.829, 4.898, 4.357, 6.337, 5.4…
$ LogMay     &lt;dbl&gt; 0.000, 3.401, 5.826, 5.749, 5.509, 5.749, 5.371, 0.000, 4.8…
$ LogOther   &lt;dbl&gt; 1.386, 1.609, 1.386, 1.386, 1.099, 3.045, 1.386, 2.944, 2.5…
$ Br_Dens    &lt;dbl&gt; 3.60, 4.30, 3.80, 3.40, 3.80, 4.50, 4.30, 5.00, 4.50, 3.40,…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># Correlations and scatterplots all in one (+ histograms for each variable)</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="fu">library</span>(psych)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'psych'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">pairs.panels</span>(dippers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="co"># can also get the same results separately</span></span>
<span id="cb30-2"><a href="#cb30-2"></a><span class="fu">cor</span>(dippers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Altitude    Hardness  RiverSlope   LogCadd    LogStone
Altitude    1.00000000 -0.08170082  0.49003652 0.1807820  0.47736562
Hardness   -0.08170082  1.00000000  0.24208735 0.3337586  0.02951218
RiverSlope  0.49003652  0.24208735  1.00000000 0.4313081  0.57479242
LogCadd     0.18078205  0.33375857  0.43130806 1.0000000  0.44347440
LogStone    0.47736562  0.02951218  0.57479242 0.4434744  1.00000000
LogMay     -0.12782013  0.41356844 -0.09616686 0.4378978 -0.16744101
LogOther   -0.33859788  0.55399249 -0.02007183 0.3521440 -0.30025225
Br_Dens     0.40635349  0.35034817  0.71022164 0.6126891  0.76294367
                LogMay    LogOther    Br_Dens
Altitude   -0.12782013 -0.33859788  0.4063535
Hardness    0.41356844  0.55399249  0.3503482
RiverSlope -0.09616686 -0.02007183  0.7102216
LogCadd     0.43789780  0.35214400  0.6126891
LogStone   -0.16744101 -0.30025225  0.7629437
LogMay      1.00000000  0.38820063  0.1562659
LogOther    0.38820063  1.00000000 -0.1277591
Br_Dens     0.15626585 -0.12775913  1.0000000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">pairs</span>(dippers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Between Br_Dens and other variables, there are a number of relatively stong correlations, particularly with LogStone (r = 763), RiverSlope (r = 0.710) and LogCadd (r = 0.613).</p>
<p>There are also some strong correlations between the predictor variables themselves, particularly between RiverSlope and LogStone (r = 0.575) and LogOther and Hardness (r = 0.554). This could be an issue for our model, as collinearity can make it difficult to interpret the model parameters and can inflate the standard errors of the estimates.</p>
<p>We can confirm if correlations between predictors may be an issue with the model by observing the Variance inflation factor (VIF) later on when we check our model assumptions.</p>
<p><em>(ii)</em> Fit a multiple linear regression model to the data using all variables. Set <code>Br_Dens</code> as the response variable and the remaining variables as the predictors. This will be known as the ‘full model’.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="co"># fit the full model</span></span>
<span id="cb33-2"><a href="#cb33-2"></a></span>
<span id="cb33-3"><a href="#cb33-3"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Br_Dens <span class="sc">~</span> Altitude <span class="sc">+</span> Hardness <span class="sc">+</span> RiverSlope <span class="sc">+</span> LogCadd <span class="sc">+</span> LogStone <span class="sc">+</span> LogMay <span class="sc">+</span> LogOther, <span class="at">data =</span> dippers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><em>(iii)</em> Check the assumptions of your model. Do you need to transform any variables? What does the Variance Inflation Factor (VIF) tell you about the collinearity between predictor variables?</p>
<p>The VIF will appear as one of the plots in the <code>check_model()</code> function, but it can also be helpful to get the values. You can use the <code>vif()</code> function from the <code>car</code> package to get the VIF values for each predictor variable.</p>
<p>The check_model function has been squishing plots, so it may be better at times to plot them individually. You may use the following code, adapted to your model object names:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb34-2"><a href="#cb34-2"></a></span>
<span id="cb34-3"><a href="#cb34-3"></a><span class="co"># Linearity</span></span>
<span id="cb34-4"><a href="#cb34-4"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"linearity"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a><span class="co"># Normality</span></span>
<span id="cb35-2"><a href="#cb35-2"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"qq"</span>, <span class="st">"normality"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="co"># Equal variance</span></span>
<span id="cb36-2"><a href="#cb36-2"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"homogeneity"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="co"># Outliers</span></span>
<span id="cb37-2"><a href="#cb37-2"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"outliers"</span>, <span class="st">"pp_check"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-10-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># VIF - visual</span></span>
<span id="cb38-2"><a href="#cb38-2"></a><span class="fu">plot</span>(performance<span class="sc">::</span><span class="fu">check_collinearity</span>(full_model))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-10-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># VIF - numbers</span></span>
<span id="cb39-2"><a href="#cb39-2"></a><span class="co"># comes from the car package</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>car<span class="sc">::</span><span class="fu">vif</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Altitude   Hardness RiverSlope    LogCadd   LogStone     LogMay   LogOther 
  1.589862   1.835610   2.030493   2.639160   2.489586   1.838431   2.341119 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a><span class="do">#### ALTERNATIVE: plot() function to check assumptions </span></span>
<span id="cb41-2"><a href="#cb41-2"></a></span>
<span id="cb41-3"><a href="#cb41-3"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb41-4"><a href="#cb41-4"></a></span>
<span id="cb41-5"><a href="#cb41-5"></a><span class="fu">plot</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial09_files/figure-html/unnamed-chunk-10-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>Linearity: The relationship between the predictors and the response variable appears to be linear, as the residuals are mostly scattered around the horizontal line at zero in the residuals vs fitted plot.</p></li>
<li><p>Independence: The residuals appear to be independent, as there is no clear pattern in the residuals vs fitted plot.</p></li>
<li><p>Normality: The residuals appear to be approximately normally distributed, as the points in the Q-Q plot roughly follow a straight line. When we look at the <code>check_model()</code> version of the plot we a slight n-shape to the points, but this is only small compared to the overall distribution of the points, so we are not too concerned about this.</p></li>
<li><p>Equal variance: The residuals appear to have constant variance, as there is no clear pattern or fanning present in the standardised residuals vs fitted plot (scale-location in the base plot).</p></li>
<li><p>Leverage: No single observations lying outside the Cook’s distance line, indicating no influential observations.</p></li>
</ul>
<p><strong>VIF and collinearity</strong></p>
<p>VIF Thresholds vary, depending on who you ask. General rule is that if it is greater than 10, then you need to remove the associated predictor. Some conservative people prefer a value of 5, so we will go with this.</p>
<p>Our threshold is 5, so given all of our VIFs are below this, we are not too concerned about collinearity. However, because they are close to the threshold it is something to keep in mind when interpreting the model parameters.</p>
<p><em>(iv)</em> Make a note of the model parameters and fit statistics for the full model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="fu">summary</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Br_Dens ~ Altitude + Hardness + RiverSlope + LogCadd + 
    LogStone + LogMay + LogOther, data = dippers)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.24313 -0.38686  0.06925  0.42252  1.19902 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) -0.881054   1.215055  -0.725   0.4803  
Altitude    -0.001801   0.003537  -0.509   0.6186  
Hardness     0.009956   0.004961   2.007   0.0645 .
RiverSlope   0.080254   0.035781   2.243   0.0416 *
LogCadd      0.408917   0.274412   1.490   0.1584  
LogStone     0.604083   0.249207   2.424   0.0295 *
LogMay       0.114607   0.114116   1.004   0.3323  
LogOther    -0.267073   0.131828  -2.026   0.0623 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7208 on 14 degrees of freedom
Multiple R-squared:  0.8433,    Adjusted R-squared:  0.765 
F-statistic: 10.77 on 7 and 14 DF,  p-value: 0.0001085</code></pre>
</div>
</div>
<p>We can see that there are two significant predictors (RiverSlope and LogStone) in the full model, but there are also a number of non-significant predictors. The adjusted R<sup>2</sup> value is 0.77, which indicates that the model explains 77% of the variation in the response variable.</p>
<p>Because there are so many non-significant predictors in the model, we may want to consider removing some of them to produce a more parsimonious model.</p>
<p><em>(v)</em> Select the least significant predictor and remove it from the model.</p>
<p>In this case, the least significant predictor is <code>Altitude</code> (P = 0.619). Remove it from the model and run the model again. This will be known as the ‘reduced model’.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a>reduced_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Br_Dens <span class="sc">~</span> Hardness <span class="sc">+</span> RiverSlope <span class="sc">+</span> LogCadd <span class="sc">+</span> LogStone <span class="sc">+</span> LogMay <span class="sc">+</span> LogOther, <span class="at">data =</span> dippers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><em>(vi)</em> Is the reduced model an improvement on the full model? How can you tell? What statistics would you look at to determine this?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="fu">summary</span>(full_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Br_Dens ~ Altitude + Hardness + RiverSlope + LogCadd + 
    LogStone + LogMay + LogOther, data = dippers)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.24313 -0.38686  0.06925  0.42252  1.19902 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) -0.881054   1.215055  -0.725   0.4803  
Altitude    -0.001801   0.003537  -0.509   0.6186  
Hardness     0.009956   0.004961   2.007   0.0645 .
RiverSlope   0.080254   0.035781   2.243   0.0416 *
LogCadd      0.408917   0.274412   1.490   0.1584  
LogStone     0.604083   0.249207   2.424   0.0295 *
LogMay       0.114607   0.114116   1.004   0.3323  
LogOther    -0.267073   0.131828  -2.026   0.0623 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7208 on 14 degrees of freedom
Multiple R-squared:  0.8433,    Adjusted R-squared:  0.765 
F-statistic: 10.77 on 7 and 14 DF,  p-value: 0.0001085</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="fu">summary</span>(reduced_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + 
    LogMay + LogOther, data = dippers)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.21925 -0.36896  0.03995  0.40149  1.27830 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) -1.112573   1.098551  -1.013   0.3272  
Hardness     0.010101   0.004829   2.092   0.0539 .
RiverSlope   0.073829   0.032643   2.262   0.0390 *
LogCadd      0.405503   0.267470   1.516   0.1503  
LogStone     0.587737   0.240949   2.439   0.0276 *
LogMay       0.111440   0.111096   1.003   0.3317  
LogOther    -0.251481   0.125014  -2.012   0.0626 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7028 on 15 degrees of freedom
Multiple R-squared:  0.8404,    Adjusted R-squared:  0.7766 
F-statistic: 13.17 on 6 and 15 DF,  p-value: 3.139e-05</code></pre>
</div>
</div>
<p>Removing the <code>Altitude</code> predictor from the model has slightly increased the adjusted R<sup>2</sup> value. This is an improvement in terms of parsimony, but we will need to use hypothesis testing to determine whether the reduced model is a <em>significant</em> improvement on the full model. We can do this using an F-test.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should now be able to prepare an appropriate model by refining it, checking your assumptions, and ensuring collinearity is not an issue.</p>
</div>
</div>
</section>
<section id="model-selection-with-f-tests" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="model-selection-with-f-tests"><span class="header-section-number">4.2</span> Model selection with F-tests</h2>
<p>We wil use the partial F-test to determine whether there is a significant difference between the models.</p>
<p><em>(i)</em> State hypotheses</p>
<p>H0: no significant difference between the full and reduced models H1: There is a significant difference between the full and reduced models</p>
<p>If we fail to reject H0, then we would opt for the reduced model as it is more parsimonious (i.e.&nbsp;it is explaining a similar amount of variation with fewer predictors).</p>
<p>If we reject H0, then we would opt for the full model as it is a significant improvement on the reduced model.</p>
<p><em>(ii)</em> Run the test</p>
<p>Once we have established our hypotheses, we can perform the F-test using the <code>anova()</code> function to compare the full and reduced models.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="fu">anova</span>(full_model, reduced_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Br_Dens ~ Altitude + Hardness + RiverSlope + LogCadd + LogStone + 
    LogMay + LogOther
Model 2: Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogMay + 
    LogOther
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     14 7.2739                           
2     15 7.4085 -1  -0.13464 0.2591 0.6186</code></pre>
</div>
</div>
<p><em>(iii)</em> Are the models significantly different?</p>
<p>The P-value is 0.6186, which is larger than 0.05, so we fail to reject the null hypothesis.</p>
<p>This means that the full model is not a significant improvement on the reduced model, and we would opt for the reduced model as it is more parsimonious.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should now be able to use an F-test to determine whether the reduced model is a significant improvement on the full model.</p>
<p><strong>Remember:</strong> the F-test is only useful if comparing nested models.</p>
</div>
</div>
</section>
</section>
<section id="model-selection-using-stepwise-regression" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Model selection using Stepwise regression</h1>
<p>When we have many predictors, this manual testing can become time consuming, so we can choose to use the <code>step()</code> function in R, which performs stepwise regression. This function will automatically remove the least significant predictor and test the model again, until it finds the best model based on the AIC criterion.</p>
<p><em>(i)</em> Run the <code>step()</code> function on the full model to perform stepwise regression.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>step_model <span class="ot">&lt;-</span> <span class="fu">step</span>(full_model, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-8.35
Br_Dens ~ Altitude + Hardness + RiverSlope + LogCadd + LogStone + 
    LogMay + LogOther

             Df Sum of Sq     RSS     AIC
- Altitude    1   0.13464  7.4085 -9.9451
- LogMay      1   0.52404  7.7979 -8.8181
&lt;none&gt;                     7.2739 -8.3486
- LogCadd     1   1.15372  8.4276 -7.1097
- Hardness    1   2.09230  9.3662 -4.7866
- LogOther    1   2.13246  9.4063 -4.6925
- RiverSlope  1   2.61383  9.8877 -3.5945
- LogStone    1   3.05288 10.3268 -2.6387

Step:  AIC=-9.95
Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogMay + 
    LogOther

             Df Sum of Sq     RSS      AIC
- LogMay      1   0.49696  7.9055 -10.5167
&lt;none&gt;                     7.4085  -9.9451
- LogCadd     1   1.13522  8.5437  -8.8086
- LogOther    1   1.99863  9.4071  -6.6906
- Hardness    1   2.16061  9.5691  -6.3150
- RiverSlope  1   2.52643  9.9349  -5.4897
- LogStone    1   2.93869 10.3472  -4.5952

Step:  AIC=-10.52
Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogOther

             Df Sum of Sq     RSS      AIC
&lt;none&gt;                     7.9055 -10.5167
- RiverSlope  1    2.1227 10.0282  -7.2842
- LogOther    1    2.3128 10.2182  -6.8712
- LogStone    1    2.4742 10.3797  -6.5262
- LogCadd     1    2.9091 10.8146  -5.6232
- Hardness    1    3.3747 11.2801  -4.6960</code></pre>
</div>
</div>
<p><em>(ii)</em> What is the final model that the <code>step()</code> function has produced? How does it compare to the full and reduced models?</p>
<p>Since we have stored the step() output as an object, we can just call the object, which will show us the final model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a>step_model</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + 
    LogOther, data = dippers)

Coefficients:
(Intercept)     Hardness   RiverSlope      LogCadd     LogStone     LogOther  
   -0.72462      0.01181      0.06538      0.54880      0.51249     -0.26813  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="do">## OR</span></span>
<span id="cb56-2"><a href="#cb56-2"></a></span>
<span id="cb56-3"><a href="#cb56-3"></a><span class="fu">summary</span>(step_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + 
    LogOther, data = dippers)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.18190 -0.49120 -0.08373  0.41721  1.31073 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) -0.724619   1.028416  -0.705   0.4912  
Hardness     0.011811   0.004519   2.613   0.0188 *
RiverSlope   0.065384   0.031545   2.073   0.0547 .
LogCadd      0.548799   0.226169   2.426   0.0274 *
LogStone     0.512494   0.229020   2.238   0.0398 *
LogOther    -0.268128   0.123932  -2.164   0.0460 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7029 on 16 degrees of freedom
Multiple R-squared:  0.8297,    Adjusted R-squared:  0.7765 
F-statistic: 15.59 on 5 and 16 DF,  p-value: 1.169e-05</code></pre>
</div>
</div>
<p>We can see that the selected model is:</p>
<p>Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogOther</p>
<p>Or with the addition of the partial regression coefficients, our equation is:</p>
<p>Br_Dens = -0.725 + 0.012 * Hardness + 0.065 * RiverSlope + 0.549 * LogCadd + 0.512 * LogStone - 0.268 * LogOther</p>
<p>We can see there has also been a marginal change in the adjusted R<sup>2</sup> value, which is now 0.7765, compared to 0.765 for the full model and 0.7766 for the reduced model. This supports the idea that the full model explained a similar amount of variation in the response compared to the simplest model obtained from the <code>step()</code> function. Therefore it makes sense to select the simpler model.</p>
<p><em>(iii)</em> How does the AIC of the stepwise regression model compare to the full and reduced models?</p>
<p>We can test this using the AIC() function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="fu">AIC</span>(full_model, reduced_model, step_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              df      AIC
full_model     9 56.08470
reduced_model  8 54.48820
step_model     7 53.91655</code></pre>
</div>
</div>
<p>Full_model AIC = 56.1</p>
<p>Reduced_model AIC = 54.5</p>
<p>step_model AIC = 53.9</p>
<p>As we select the model with the smallest AIC, we can confirm that the model selected by the <code>step()</code> function is better.</p>
<p>You may notice that the AIC values are different between the <code>step()</code> function and the <code>AIC()</code> function. This is because the <code>step()</code> function uses a different method to calculate the AIC values, which is based on the likelihood of the model, while the <code>AIC()</code> function uses a different method based on the residual sum of squares.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should now be able to run the <code>step()</code> function to select the most appropriate model.</p>
</div>
</div>
<section id="wrap-up" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="wrap-up">Wrap-up</h2>
<p>In this tutorial, we used the dippers dataset to get some practice testing model assumptions and checking for collinearity. We then used partial F-tests and stepwise regression to select a more parsimonious model.</p>
<section id="example-exam-questions" class="level3">
<h3 class="anchored" data-anchor-id="example-exam-questions">Example exam questions</h3>
<ol type="1">
<li><p>What assumptions do we need to check for when fitting a multiple linear regression?</p></li>
<li><p>Why don’t we just rely on the adjusted r<sup>2</sup> to compare models?</p></li>
<li><p>Can F-tests be run on non-nested models? Why or why not?</p></li>
</ol>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb60" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb60-1"><a href="#cb60-1"></a><span class="co">---</span></span>
<span id="cb60-2"><a href="#cb60-2"></a><span class="an">title:</span><span class="co"> "Tutorial 09"</span></span>
<span id="cb60-3"><a href="#cb60-3"></a><span class="co"># reviewed-by: LP 2026</span></span>
<span id="cb60-4"><a href="#cb60-4"></a><span class="an">format:</span></span>
<span id="cb60-5"><a href="#cb60-5"></a><span class="co">  sandstone-html:</span></span>
<span id="cb60-6"><a href="#cb60-6"></a><span class="co">    code-tools: true</span></span>
<span id="cb60-7"><a href="#cb60-7"></a><span class="an">resources:</span></span>
<span id="cb60-8"><a href="#cb60-8"></a><span class="co">  - data/Dippers.csv</span></span>
<span id="cb60-9"><a href="#cb60-9"></a><span class="co">---</span></span>
<span id="cb60-10"><a href="#cb60-10"></a></span>
<span id="cb60-11"><a href="#cb60-11"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb60-12"><a href="#cb60-12"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb60-13"><a href="#cb60-13"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb60-14"><a href="#cb60-14"></a><span class="in">```</span></span>
<span id="cb60-15"><a href="#cb60-15"></a></span>
<span id="cb60-16"><a href="#cb60-16"></a><span class="fu">## Welcome to week 9! {.unnumbered}</span></span>
<span id="cb60-17"><a href="#cb60-17"></a></span>
<span id="cb60-18"><a href="#cb60-18"></a>This week's lecture introduced you to how we use models for prediction and how we assess the quality of the predictions.We will follow similar steps in today's tutorial and lab class. </span>
<span id="cb60-19"><a href="#cb60-19"></a></span>
<span id="cb60-20"><a href="#cb60-20"></a></span>
<span id="cb60-21"><a href="#cb60-21"></a>In this tutorial we will cover the key steps to fit a model, use it to make predictions, and then check assumptions, and select the most appropriate model.</span>
<span id="cb60-22"><a href="#cb60-22"></a></span>
<span id="cb60-23"><a href="#cb60-23"></a>**You will learn how to:**</span>
<span id="cb60-24"><a href="#cb60-24"></a></span>
<span id="cb60-25"><a href="#cb60-25"></a><span class="ss">1.  </span>Split data into training and test subsets</span>
<span id="cb60-26"><a href="#cb60-26"></a><span class="ss">2.  </span>Fit your model to the training data and check assumptions are met</span>
<span id="cb60-27"><a href="#cb60-27"></a><span class="ss">3.  </span>Use the trained model to make predictions using the training and the test subsets</span>
<span id="cb60-28"><a href="#cb60-28"></a><span class="ss">4.  </span>Observe the quality of the predictions using appropriate statistics and plots</span>
<span id="cb60-29"><a href="#cb60-29"></a></span>
<span id="cb60-30"><a href="#cb60-30"></a></span>
<span id="cb60-31"><a href="#cb60-31"></a></span>
<span id="cb60-32"><a href="#cb60-32"></a><span class="fu">## Packages</span></span>
<span id="cb60-33"><a href="#cb60-33"></a></span>
<span id="cb60-34"><a href="#cb60-34"></a>This tutorial uses <span class="in">`tidyverse`</span>, <span class="in">`readxl`</span>, <span class="in">`moments`</span>, <span class="in">`psych`</span>, <span class="in">`performance`</span> and <span class="in">`car`</span>. Install any you are missing by running the following **in the console**:</span>
<span id="cb60-35"><a href="#cb60-35"></a></span>
<span id="cb60-38"><a href="#cb60-38"></a><span class="in">```{r}</span></span>
<span id="cb60-39"><a href="#cb60-39"></a><span class="co">#| eval: false</span></span>
<span id="cb60-40"><a href="#cb60-40"></a></span>
<span id="cb60-41"><a href="#cb60-41"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>, <span class="st">"car"</span>))</span>
<span id="cb60-42"><a href="#cb60-42"></a><span class="in">```</span></span>
<span id="cb60-43"><a href="#cb60-43"></a></span>
<span id="cb60-44"><a href="#cb60-44"></a>If a package is already installed, R will simply reinstall it — no harm done.</span>
<span id="cb60-45"><a href="#cb60-45"></a></span>
<span id="cb60-46"><a href="#cb60-46"></a><span class="fu">### Downloads</span></span>
<span id="cb60-47"><a href="#cb60-47"></a></span>
<span id="cb60-48"><a href="#cb60-48"></a><span class="pp">|</span> File <span class="pp">|</span> Used in <span class="pp">|</span> Download <span class="pp">|</span></span>
<span id="cb60-49"><a href="#cb60-49"></a><span class="pp">|---|---|---|</span></span>
<span id="cb60-50"><a href="#cb60-50"></a><span class="pp">|</span> <span class="in">`Dippers.csv`</span> <span class="pp">|</span> all exercises <span class="pp">|</span> <span class="co">[</span><span class="ot">Download</span><span class="co">](data/Dippers.csv)</span> <span class="pp">|</span></span>
<span id="cb60-51"><a href="#cb60-51"></a></span>
<span id="cb60-52"><a href="#cb60-52"></a>Save the file into a folder called <span class="in">`data`</span> inside your project folder.</span>
<span id="cb60-53"><a href="#cb60-53"></a></span>
<span id="cb60-54"><a href="#cb60-54"></a></span>
<span id="cb60-55"><a href="#cb60-55"></a><span class="fu">## The data</span></span>
<span id="cb60-56"><a href="#cb60-56"></a></span>
<span id="cb60-57"><a href="#cb60-57"></a><span class="al">![Cute little Dipper (bird) standing on a rock by the water. Image source: markmedcalf via Adobe Stock.](images/AdobeStock_93907188.jpeg)</span></span>
<span id="cb60-58"><a href="#cb60-58"></a></span>
<span id="cb60-59"><a href="#cb60-59"></a><span class="co">[</span><span class="ot">Dippers</span><span class="co">](https://en.wikipedia.org/wiki/Dipper)</span> are thrush-sized birds living mainly in the upper reaches of rivers, which feed on benthic invertebrates by probing the river beds with their beaks. The dataset in this exercise contains data from a biological survey which examined the nature of the variables thought to influence the breeding of British dippers. </span>
<span id="cb60-60"><a href="#cb60-60"></a></span>
<span id="cb60-61"><a href="#cb60-61"></a>Twenty-two sites were included in the survey. Some of the variables have been transformed. </span>
<span id="cb60-62"><a href="#cb60-62"></a></span>
<span id="cb60-63"><a href="#cb60-63"></a>Data can be found in: **Dippers.csv**</span>
<span id="cb60-64"><a href="#cb60-64"></a></span>
<span id="cb60-65"><a href="#cb60-65"></a>The variables measured were:  </span>
<span id="cb60-66"><a href="#cb60-66"></a></span>
<span id="cb60-67"><a href="#cb60-67"></a><span class="ss">- </span><span class="in">`Altitude`</span> site altitude</span>
<span id="cb60-68"><a href="#cb60-68"></a><span class="ss">- </span><span class="in">`Hardness`</span> water hardness</span>
<span id="cb60-69"><a href="#cb60-69"></a><span class="ss">- </span><span class="in">`RiverSlope`</span> river-bed slope</span>
<span id="cb60-70"><a href="#cb60-70"></a><span class="ss">- </span><span class="in">`LogCadd`</span> the numbers of caddis fly larvae, transformed</span>
<span id="cb60-71"><a href="#cb60-71"></a><span class="ss">- </span><span class="in">`LogStone`</span> the numbers of stonefly larvae, transformed</span>
<span id="cb60-72"><a href="#cb60-72"></a><span class="ss">- </span><span class="in">`LogMay`</span> the numbers of mayfly larvae, transformed</span>
<span id="cb60-73"><a href="#cb60-73"></a><span class="ss">- </span><span class="in">`LogOther`</span> the numbers of all other invertebrates collected, transformed</span>
<span id="cb60-74"><a href="#cb60-74"></a><span class="ss">- </span><span class="in">`Br_Dens`</span> the number of breeding pairs of dippers per 10 km of river  </span>
<span id="cb60-75"><a href="#cb60-75"></a></span>
<span id="cb60-76"><a href="#cb60-76"></a>In the analyses, the four invertebrate variables were transformed using a $log(x+1)$ transformation.</span>
<span id="cb60-77"><a href="#cb60-77"></a></span>
<span id="cb60-78"><a href="#cb60-78"></a><span class="in">`Br_Dens`</span> will be the response variable in our models. </span>
<span id="cb60-79"><a href="#cb60-79"></a></span>
<span id="cb60-80"><a href="#cb60-80"></a>Last week following use of the step() function, we found the most parsimonious model to be:</span>
<span id="cb60-81"><a href="#cb60-81"></a></span>
<span id="cb60-82"><a href="#cb60-82"></a>**Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogOther**</span>
<span id="cb60-83"><a href="#cb60-83"></a></span>
<span id="cb60-84"><a href="#cb60-84"></a>Model assumptions were met and the model explained 76% of variation in dipper breeding pair density, which was quite good. </span>
<span id="cb60-85"><a href="#cb60-85"></a></span>
<span id="cb60-86"><a href="#cb60-86"></a>We will use this model in our walkthrough today. </span>
<span id="cb60-87"><a href="#cb60-87"></a></span>
<span id="cb60-88"><a href="#cb60-88"></a></span>
<span id="cb60-89"><a href="#cb60-89"></a><span class="fu"># Data splitting</span></span>
<span id="cb60-90"><a href="#cb60-90"></a></span>
<span id="cb60-91"><a href="#cb60-91"></a>Making predictions involves substituting in new values of x into our model equation to get new values of y.</span>
<span id="cb60-92"><a href="#cb60-92"></a></span>
<span id="cb60-93"><a href="#cb60-93"></a>We could use single values for each of our predictor variables and substitute them into the equation, but this is unrealistic and time consuming when we have a large number of observations. We therefore use a dataset containing our new observations of x to make the predictions and feed this into our model. </span>
<span id="cb60-94"><a href="#cb60-94"></a></span>
<span id="cb60-95"><a href="#cb60-95"></a>To understand the ability our model to predict new values of y from values of x previously unseen by the model, we need to test this on data that has not been used to fit the model. </span>
<span id="cb60-96"><a href="#cb60-96"></a></span>
<span id="cb60-97"><a href="#cb60-97"></a>It is common practice to split the data we have into two parts: a training (or calibration) subset and a test (or validation) subset.  For each subset, we feed the predictor values into the model to get predictions of the y variable. We can then compare the predicted y with the observed y contained within each subset to get an indication of how well our model is performing.</span>
<span id="cb60-98"><a href="#cb60-98"></a></span>
<span id="cb60-99"><a href="#cb60-99"></a>Let's read the data in and start splitting!</span>
<span id="cb60-100"><a href="#cb60-100"></a></span>
<span id="cb60-103"><a href="#cb60-103"></a><span class="in">```{r}</span></span>
<span id="cb60-104"><a href="#cb60-104"></a><span class="co"># read in the data</span></span>
<span id="cb60-105"><a href="#cb60-105"></a>dippers <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/Dippers.csv"</span>)</span>
<span id="cb60-106"><a href="#cb60-106"></a></span>
<span id="cb60-107"><a href="#cb60-107"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb60-108"><a href="#cb60-108"></a><span class="fu">glimpse</span>(dippers) <span class="co"># check the data</span></span>
<span id="cb60-109"><a href="#cb60-109"></a><span class="in">```</span></span>
<span id="cb60-110"><a href="#cb60-110"></a></span>
<span id="cb60-111"><a href="#cb60-111"></a></span>
<span id="cb60-112"><a href="#cb60-112"></a>There are different ways of splitting data, but what you choose generally depends on your dataset and the question you are trying to answer.</span>
<span id="cb60-113"><a href="#cb60-113"></a></span>
<span id="cb60-114"><a href="#cb60-114"></a>For example, we might split our dataset based on: </span>
<span id="cb60-115"><a href="#cb60-115"></a></span>
<span id="cb60-116"><a href="#cb60-116"></a><span class="ss">- </span>a random selection of observations (random sampling)</span>
<span id="cb60-117"><a href="#cb60-117"></a><span class="ss">- </span>certain factors or groups within the dataset (stratified sampling)</span>
<span id="cb60-118"><a href="#cb60-118"></a><span class="ss">- </span>spatial location</span>
<span id="cb60-119"><a href="#cb60-119"></a><span class="ss">- </span>time </span>
<span id="cb60-120"><a href="#cb60-120"></a></span>
<span id="cb60-121"><a href="#cb60-121"></a>For today, we will be making a random split of the data, which is the most common method. </span>
<span id="cb60-122"><a href="#cb60-122"></a></span>
<span id="cb60-123"><a href="#cb60-123"></a>Because the sample size is very small, we will use 80% of the data for training and 20% for testing. The more observations we have to train the model, the better. </span>
<span id="cb60-124"><a href="#cb60-124"></a></span>
<span id="cb60-127"><a href="#cb60-127"></a><span class="in">```{r}</span></span>
<span id="cb60-128"><a href="#cb60-128"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb60-129"><a href="#cb60-129"></a></span>
<span id="cb60-130"><a href="#cb60-130"></a>indexes <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(dippers), <span class="at">size =</span> <span class="fl">0.2</span> <span class="sc">*</span> <span class="fu">nrow</span>(dippers)) <span class="co"># randomly sample 20% of rows in the dataset</span></span>
<span id="cb60-131"><a href="#cb60-131"></a></span>
<span id="cb60-132"><a href="#cb60-132"></a>dippers_train <span class="ot">&lt;-</span> dippers[<span class="sc">-</span>indexes, ] <span class="co"># remove the 20% - training dataset</span></span>
<span id="cb60-133"><a href="#cb60-133"></a>dippers_test <span class="ot">&lt;-</span> dippers[indexes, ] <span class="co"># select the 20% - test dataset</span></span>
<span id="cb60-134"><a href="#cb60-134"></a><span class="in">```</span></span>
<span id="cb60-135"><a href="#cb60-135"></a></span>
<span id="cb60-136"><a href="#cb60-136"></a>In the code above, we first set a seed to ensure that we can reproduce the same random sample if we were to rerun the code chunk. </span>
<span id="cb60-137"><a href="#cb60-137"></a>Then we use the <span class="in">`sample()`</span> function to randomly select 20% of the row indices from the dataset. </span>
<span id="cb60-138"><a href="#cb60-138"></a></span>
<span id="cb60-139"><a href="#cb60-139"></a>We create the training dataset by removing these selected indices from the original dataset ( <span class="co">[</span><span class="ot">-index,</span><span class="co">]</span> says "exclude everything but these indices"), and we create the test dataset by selecting only those indices.</span>
<span id="cb60-140"><a href="#cb60-140"></a></span>
<span id="cb60-141"><a href="#cb60-141"></a>Once we have split the data, we need to check the subsets. First ensure the structure and number of observations in each subset is correct, and then check the distribution of the variables (max, mean, median, min) in each subset to ensure they are similar.</span>
<span id="cb60-142"><a href="#cb60-142"></a></span>
<span id="cb60-145"><a href="#cb60-145"></a><span class="in">```{r}</span></span>
<span id="cb60-146"><a href="#cb60-146"></a><span class="fu">str</span>(dippers_train)</span>
<span id="cb60-147"><a href="#cb60-147"></a><span class="fu">str</span>(dippers_test)</span>
<span id="cb60-148"><a href="#cb60-148"></a></span>
<span id="cb60-149"><a href="#cb60-149"></a><span class="fu">summary</span>(dippers_train)</span>
<span id="cb60-150"><a href="#cb60-150"></a><span class="fu">summary</span>(dippers_test)</span>
<span id="cb60-151"><a href="#cb60-151"></a><span class="in">```</span></span>
<span id="cb60-152"><a href="#cb60-152"></a></span>
<span id="cb60-153"><a href="#cb60-153"></a>We can see that the training dataset contains 18 observations and the test dataset contains 4 observations, which is very small, so we don't expect to get very reliable information from the prediction quality statistics, but it still worth continuing to understand the process and see how we go. </span>
<span id="cb60-154"><a href="#cb60-154"></a></span>
<span id="cb60-155"><a href="#cb60-155"></a>Because of the limited sample size, we can see that the max and min values vary, but the distributions aren't too different (e.g. we don't have our response in one subset following a log distribution and the other following a normal distribution.) </span>
<span id="cb60-156"><a href="#cb60-156"></a></span>
<span id="cb60-157"><a href="#cb60-157"></a>From here we can proceed to model fitting. </span>
<span id="cb60-158"><a href="#cb60-158"></a></span>
<span id="cb60-159"><a href="#cb60-159"></a><span class="fu"># Fit the model to the training data</span></span>
<span id="cb60-160"><a href="#cb60-160"></a></span>
<span id="cb60-161"><a href="#cb60-161"></a>We only use the training data to fit the model. For this tutorial we will use the model we optimised last week: </span>
<span id="cb60-162"><a href="#cb60-162"></a></span>
<span id="cb60-163"><a href="#cb60-163"></a>**Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + LogOther**</span>
<span id="cb60-164"><a href="#cb60-164"></a></span>
<span id="cb60-167"><a href="#cb60-167"></a><span class="in">```{r}</span></span>
<span id="cb60-168"><a href="#cb60-168"></a><span class="co"># fit the model to the training data</span></span>
<span id="cb60-169"><a href="#cb60-169"></a></span>
<span id="cb60-170"><a href="#cb60-170"></a>train_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Br_Dens <span class="sc">~</span> Hardness <span class="sc">+</span> RiverSlope <span class="sc">+</span> LogCadd <span class="sc">+</span> LogStone <span class="sc">+</span> LogOther, <span class="at">data =</span> dippers_train)</span>
<span id="cb60-171"><a href="#cb60-171"></a></span>
<span id="cb60-172"><a href="#cb60-172"></a><span class="in">```</span></span>
<span id="cb60-173"><a href="#cb60-173"></a></span>
<span id="cb60-174"><a href="#cb60-174"></a>We can do a quick assumption check to ensure the model is appropriate for the training data, but we won't go through this in detail as we have already done this for the full dataset last week. </span>
<span id="cb60-175"><a href="#cb60-175"></a></span>
<span id="cb60-178"><a href="#cb60-178"></a><span class="in">```{r}</span></span>
<span id="cb60-179"><a href="#cb60-179"></a><span class="fu">library</span>(performance)</span>
<span id="cb60-180"><a href="#cb60-180"></a><span class="co"># Linearity</span></span>
<span id="cb60-181"><a href="#cb60-181"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"linearity"</span>))</span>
<span id="cb60-182"><a href="#cb60-182"></a></span>
<span id="cb60-183"><a href="#cb60-183"></a><span class="co"># Normality</span></span>
<span id="cb60-184"><a href="#cb60-184"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"qq"</span>, <span class="st">"normality"</span>))</span>
<span id="cb60-185"><a href="#cb60-185"></a></span>
<span id="cb60-186"><a href="#cb60-186"></a><span class="co"># Equal variance</span></span>
<span id="cb60-187"><a href="#cb60-187"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"homogeneity"</span>))</span>
<span id="cb60-188"><a href="#cb60-188"></a></span>
<span id="cb60-189"><a href="#cb60-189"></a><span class="co"># Outliers</span></span>
<span id="cb60-190"><a href="#cb60-190"></a><span class="fu">check_model</span>(train_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"outliers"</span>, <span class="st">"pp_check"</span>))</span>
<span id="cb60-191"><a href="#cb60-191"></a></span>
<span id="cb60-192"><a href="#cb60-192"></a><span class="co"># VIF - visual</span></span>
<span id="cb60-193"><a href="#cb60-193"></a><span class="fu">plot</span>(performance<span class="sc">::</span><span class="fu">check_collinearity</span>(train_model))</span>
<span id="cb60-194"><a href="#cb60-194"></a></span>
<span id="cb60-195"><a href="#cb60-195"></a><span class="co"># VIF - numbers</span></span>
<span id="cb60-196"><a href="#cb60-196"></a><span class="co"># comes from the car package</span></span>
<span id="cb60-197"><a href="#cb60-197"></a>car<span class="sc">::</span><span class="fu">vif</span>(train_model)</span>
<span id="cb60-198"><a href="#cb60-198"></a></span>
<span id="cb60-199"><a href="#cb60-199"></a></span>
<span id="cb60-200"><a href="#cb60-200"></a><span class="do">#### ALTERNATIVE: plot() function to check assumptions </span></span>
<span id="cb60-201"><a href="#cb60-201"></a></span>
<span id="cb60-202"><a href="#cb60-202"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb60-203"><a href="#cb60-203"></a></span>
<span id="cb60-204"><a href="#cb60-204"></a><span class="fu">plot</span>(train_model)</span>
<span id="cb60-205"><a href="#cb60-205"></a></span>
<span id="cb60-206"><a href="#cb60-206"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb60-207"><a href="#cb60-207"></a></span>
<span id="cb60-208"><a href="#cb60-208"></a><span class="in">```</span></span>
<span id="cb60-209"><a href="#cb60-209"></a></span>
<span id="cb60-210"><a href="#cb60-210"></a></span>
<span id="cb60-211"><a href="#cb60-211"></a><span class="ss">* </span>Linearity: The relationship between the predictors and the response variable appears to be potentially nonlinear, because although the points are scattered, the line is indicating a possible trend. </span>
<span id="cb60-212"><a href="#cb60-212"></a></span>
<span id="cb60-213"><a href="#cb60-213"></a><span class="ss">* </span>Independence: The residuals appear to be independent.</span>
<span id="cb60-214"><a href="#cb60-214"></a></span>
<span id="cb60-215"><a href="#cb60-215"></a><span class="ss">* </span>Normality: The residuals appear to be approximately normally distributed, as the points in the Q-Q plot roughly follow a straight line. When we look at the <span class="in">`check_model()`</span> version of the plot we a slight n-shape to the points, but this is only small compared to the overall distribution of the points, so we are not too concerned about this.</span>
<span id="cb60-216"><a href="#cb60-216"></a></span>
<span id="cb60-217"><a href="#cb60-217"></a><span class="ss">* </span>Equal variance: The residuals appear to have constant variance, as there is no clear pattern or fanning present in the standardised residuals vs fitted plot (scale-location in the base plot).</span>
<span id="cb60-218"><a href="#cb60-218"></a></span>
<span id="cb60-219"><a href="#cb60-219"></a><span class="ss">* </span>Leverage: No single observations lying outside the Cook's distance line, indicating no influential observations.</span>
<span id="cb60-220"><a href="#cb60-220"></a></span>
<span id="cb60-221"><a href="#cb60-221"></a>We use the training set to fit the model and check assumptions. We can also use this subset to make predictions and check the quality of the predictions.  The predictions made with this subset will often look quite good, but this is because the observed y value has been used in model fitting; therefore we do not assess the true predictive performance of the model using the training set alone. Instead we can compare the prediction quality statistics and plots with those of the test set to get an indication of overfitting.  </span>
<span id="cb60-222"><a href="#cb60-222"></a></span>
<span id="cb60-223"><a href="#cb60-223"></a>The test subset is a set of values which are not used to fit the model, and is therefore unseen by the model. This allows us to  pretend we have a new set of values, but then we have the advantage of the actual observed y variable sitting within the dataset too, so we are able to test how similar the predictions are to our real observation. </span>
<span id="cb60-224"><a href="#cb60-224"></a></span>
<span id="cb60-225"><a href="#cb60-225"></a>We will run through this using last week's data: </span>
<span id="cb60-226"><a href="#cb60-226"></a></span>
<span id="cb60-227"><a href="#cb60-227"></a></span>
<span id="cb60-228"><a href="#cb60-228"></a></span>
<span id="cb60-229"><a href="#cb60-229"></a></span>
<span id="cb60-230"><a href="#cb60-230"></a></span>
<span id="cb60-231"><a href="#cb60-231"></a></span>
<span id="cb60-232"><a href="#cb60-232"></a></span>
<span id="cb60-233"><a href="#cb60-233"></a></span>
<span id="cb60-234"><a href="#cb60-234"></a></span>
<span id="cb60-235"><a href="#cb60-235"></a></span>
<span id="cb60-236"><a href="#cb60-236"></a></span>
<span id="cb60-237"><a href="#cb60-237"></a></span>
<span id="cb60-238"><a href="#cb60-238"></a></span>
<span id="cb60-239"><a href="#cb60-239"></a>If the model is good, we expect the predictions to be close to the actual values.</span>
<span id="cb60-240"><a href="#cb60-240"></a></span>
<span id="cb60-241"><a href="#cb60-241"></a>If the model is bad, we expect the predictions to be far from the actual values.</span>
<span id="cb60-242"><a href="#cb60-242"></a></span>
<span id="cb60-243"><a href="#cb60-243"></a>The dataset can be obtained by:</span>
<span id="cb60-244"><a href="#cb60-244"></a></span>
<span id="cb60-245"><a href="#cb60-245"></a>Collecting new data.</span>
<span id="cb60-246"><a href="#cb60-246"></a></span>
<span id="cb60-247"><a href="#cb60-247"></a>Splitting the existing data into two parts before model building.</span>
<span id="cb60-248"><a href="#cb60-248"></a></span>
<span id="cb60-249"><a href="#cb60-249"></a>Data splitting</span>
<span id="cb60-250"><a href="#cb60-250"></a></span>
<span id="cb60-251"><a href="#cb60-251"></a>Cross-validation</span>
<span id="cb60-252"><a href="#cb60-252"></a></span>
<span id="cb60-253"><a href="#cb60-253"></a>*use cars dataset?*</span>
<span id="cb60-254"><a href="#cb60-254"></a></span>
<span id="cb60-255"><a href="#cb60-255"></a>This week's lecture introduced you to variable selection and how to produce a more parsimonious model. We explored developing our models by fitting the full model, checking assumptions and deciding whether anything needed transformation. Once we were happy assumptions were met we could consider whether all of our predictors were useful in explaining the variation in our response variable.</span>
<span id="cb60-256"><a href="#cb60-256"></a></span>
<span id="cb60-257"><a href="#cb60-257"></a>In this tutorial, we will explore a new dataset and follow the steps of model selection to produce a model that explains a sufficient amount of variation, without being unnecessarily complex. </span>
<span id="cb60-258"><a href="#cb60-258"></a></span>
<span id="cb60-259"><a href="#cb60-259"></a>**You will learn how to:**</span>
<span id="cb60-260"><a href="#cb60-260"></a></span>
<span id="cb60-261"><a href="#cb60-261"></a><span class="ss">1.  </span>Check for collinearity and influential observations in a MLR model</span>
<span id="cb60-262"><a href="#cb60-262"></a><span class="ss">2.  </span>Run partial F-tests to compare nested models</span>
<span id="cb60-263"><a href="#cb60-263"></a><span class="ss">3.  </span>Implement stepwise regression using the <span class="in">`step()`</span> function in R</span>
<span id="cb60-264"><a href="#cb60-264"></a></span>
<span id="cb60-265"><a href="#cb60-265"></a></span>
<span id="cb60-266"><a href="#cb60-266"></a><span class="fu"># Setting up for our analysis</span></span>
<span id="cb60-267"><a href="#cb60-267"></a></span>
<span id="cb60-268"><a href="#cb60-268"></a><span class="fu">## Workflow for fitting parsimonious models</span></span>
<span id="cb60-269"><a href="#cb60-269"></a></span>
<span id="cb60-270"><a href="#cb60-270"></a>*1. Model development*</span>
<span id="cb60-271"><a href="#cb60-271"></a></span>
<span id="cb60-272"><a href="#cb60-272"></a><span class="ss">* </span>Start with full model and check assumptions (e.g. normality, homoscedasticity, linearity, etc.)</span>
<span id="cb60-273"><a href="#cb60-273"></a><span class="ss">* </span>Look for additional issues (e.g. multicollinearity, outliers, etc.) </span>
<span id="cb60-274"><a href="#cb60-274"></a>  <span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span> -–&gt; correlations, leverage plot, VIF plots and statistics</span>
<span id="cb60-275"><a href="#cb60-275"></a><span class="ss">* </span>Consider transformations (e.g. log, sqrt, etc.).</span>
<span id="cb60-276"><a href="#cb60-276"></a>  <span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span> --&gt; Response: if assumptions aren't met, transform the response variable</span>
<span id="cb60-277"><a href="#cb60-277"></a>  <span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span> --&gt; Predictors: it may help to explore transformations of skewed predictors before fitting the model to explore if there is a relationship present. Transforming predictors generally does not affect assumptions, but it can help to linearise relationships and make them easier to interpret.</span>
<span id="cb60-278"><a href="#cb60-278"></a><span class="ss">* </span>Following any transformations, test assumptions again.</span>
<span id="cb60-279"><a href="#cb60-279"></a></span>
<span id="cb60-280"><a href="#cb60-280"></a>*2. Model selection*</span>
<span id="cb60-281"><a href="#cb60-281"></a></span>
<span id="cb60-282"><a href="#cb60-282"></a><span class="ss">- </span>Use VIF as an initial step to get rid of highly correlated predictors.</span>
<span id="cb60-283"><a href="#cb60-283"></a><span class="ss">- </span>Perform variable selection using backward elimination (good and fast), because:</span>
<span id="cb60-284"><a href="#cb60-284"></a><span class="ss">- </span>Using r^2^2 as a criterion is not recommended (it is not a good measure of model fit, only a good measure of variance explained).</span>
<span id="cb60-285"><a href="#cb60-285"></a><span class="ss">- </span>Using partial F-test is good, but slow.</span>
<span id="cb60-286"><a href="#cb60-286"></a></span>
<span id="cb60-287"><a href="#cb60-287"></a><span class="fu">## Packages</span></span>
<span id="cb60-288"><a href="#cb60-288"></a></span>
<span id="cb60-289"><a href="#cb60-289"></a>This tutorial uses <span class="in">`tidyverse`</span>, <span class="in">`readxl`</span>, <span class="in">`moments`</span>, <span class="in">`psych`</span>, <span class="in">`performance`</span> and <span class="in">`car`</span>. Install any you are missing by running the following **in the console**:</span>
<span id="cb60-290"><a href="#cb60-290"></a></span>
<span id="cb60-293"><a href="#cb60-293"></a><span class="in">```{r}</span></span>
<span id="cb60-294"><a href="#cb60-294"></a><span class="co">#| eval: false</span></span>
<span id="cb60-295"><a href="#cb60-295"></a></span>
<span id="cb60-296"><a href="#cb60-296"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>, <span class="st">"car"</span>))</span>
<span id="cb60-297"><a href="#cb60-297"></a><span class="in">```</span></span>
<span id="cb60-298"><a href="#cb60-298"></a></span>
<span id="cb60-299"><a href="#cb60-299"></a>If a package is already installed, R will simply reinstall it — no harm done.</span>
<span id="cb60-300"><a href="#cb60-300"></a></span>
<span id="cb60-301"><a href="#cb60-301"></a><span class="fu">## The data</span></span>
<span id="cb60-302"><a href="#cb60-302"></a></span>
<span id="cb60-303"><a href="#cb60-303"></a><span class="al">![Cute little Dipper (bird) standing on a rock by the water. Image source: markmedcalf via Adobe Stock.](images/AdobeStock_93907188.jpeg)</span></span>
<span id="cb60-304"><a href="#cb60-304"></a></span>
<span id="cb60-305"><a href="#cb60-305"></a><span class="co">[</span><span class="ot">Dippers</span><span class="co">](https://en.wikipedia.org/wiki/Dipper)</span> are thrush-sized birds living mainly in the upper reaches of rivers, which feed on benthic invertebrates by probing the river beds with their beaks. The dataset in this exercise contains data from a biological survey which examined the nature of the variables thought to influence the breeding of British dippers. </span>
<span id="cb60-306"><a href="#cb60-306"></a></span>
<span id="cb60-307"><a href="#cb60-307"></a>Twenty-two sites were included in the survey. Some of the variables have been transformed. </span>
<span id="cb60-308"><a href="#cb60-308"></a></span>
<span id="cb60-309"><a href="#cb60-309"></a>Data can be found in: **Dippers.csv**</span>
<span id="cb60-310"><a href="#cb60-310"></a></span>
<span id="cb60-311"><a href="#cb60-311"></a>The variables measured were:  </span>
<span id="cb60-312"><a href="#cb60-312"></a></span>
<span id="cb60-313"><a href="#cb60-313"></a><span class="ss">- </span><span class="in">`Altitude`</span> site altitude</span>
<span id="cb60-314"><a href="#cb60-314"></a><span class="ss">- </span><span class="in">`Hardness`</span> water hardness</span>
<span id="cb60-315"><a href="#cb60-315"></a><span class="ss">- </span><span class="in">`RiverSlope`</span> river-bed slope</span>
<span id="cb60-316"><a href="#cb60-316"></a><span class="ss">- </span><span class="in">`LogCadd`</span> the numbers of caddis fly larvae, transformed</span>
<span id="cb60-317"><a href="#cb60-317"></a><span class="ss">- </span><span class="in">`LogStone`</span> the numbers of stonefly larvae, transformed</span>
<span id="cb60-318"><a href="#cb60-318"></a><span class="ss">- </span><span class="in">`LogMay`</span> the numbers of mayfly larvae, transformed</span>
<span id="cb60-319"><a href="#cb60-319"></a><span class="ss">- </span><span class="in">`LogOther`</span> the numbers of all other invertebrates collected, transformed</span>
<span id="cb60-320"><a href="#cb60-320"></a><span class="ss">- </span><span class="in">`Br_Dens`</span> the number of breeding pairs of dippers per 10 km of river  </span>
<span id="cb60-321"><a href="#cb60-321"></a></span>
<span id="cb60-322"><a href="#cb60-322"></a>In the analyses, the four invertebrate variables were transformed using a $log(x+1)$ transformation.</span>
<span id="cb60-323"><a href="#cb60-323"></a></span>
<span id="cb60-324"><a href="#cb60-324"></a><span class="in">`Br_Dens`</span> will be the response variable in our models. </span>
<span id="cb60-325"><a href="#cb60-325"></a></span>
<span id="cb60-326"><a href="#cb60-326"></a><span class="fu"># Analysis</span></span>
<span id="cb60-327"><a href="#cb60-327"></a></span>
<span id="cb60-328"><a href="#cb60-328"></a><span class="fu">## Model development</span></span>
<span id="cb60-329"><a href="#cb60-329"></a></span>
<span id="cb60-330"><a href="#cb60-330"></a>*(i)* Read in the data and investigate the relationship between each of your variables. Describe the relationships, supported by values (correlation coefficient) and plots.</span>
<span id="cb60-331"><a href="#cb60-331"></a></span>
<span id="cb60-334"><a href="#cb60-334"></a><span class="in">```{r}</span></span>
<span id="cb60-335"><a href="#cb60-335"></a><span class="co"># read in the data</span></span>
<span id="cb60-336"><a href="#cb60-336"></a>dippers <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/Dippers.csv"</span>)</span>
<span id="cb60-337"><a href="#cb60-337"></a></span>
<span id="cb60-338"><a href="#cb60-338"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb60-339"><a href="#cb60-339"></a><span class="fu">glimpse</span>(dippers) <span class="co"># check the data</span></span>
<span id="cb60-340"><a href="#cb60-340"></a></span>
<span id="cb60-341"><a href="#cb60-341"></a><span class="co"># Correlations and scatterplots all in one (+ histograms for each variable)</span></span>
<span id="cb60-342"><a href="#cb60-342"></a><span class="fu">library</span>(psych)</span>
<span id="cb60-343"><a href="#cb60-343"></a><span class="fu">pairs.panels</span>(dippers)</span>
<span id="cb60-344"><a href="#cb60-344"></a></span>
<span id="cb60-345"><a href="#cb60-345"></a><span class="co"># can also get the same results separately</span></span>
<span id="cb60-346"><a href="#cb60-346"></a><span class="fu">cor</span>(dippers)</span>
<span id="cb60-347"><a href="#cb60-347"></a><span class="fu">pairs</span>(dippers)</span>
<span id="cb60-348"><a href="#cb60-348"></a></span>
<span id="cb60-349"><a href="#cb60-349"></a><span class="in">```</span></span>
<span id="cb60-350"><a href="#cb60-350"></a></span>
<span id="cb60-351"><a href="#cb60-351"></a>Between Br_Dens and other variables, there are a number of relatively stong correlations, particularly with LogStone (r = 763), RiverSlope (r = 0.710) and LogCadd (r = 0.613). </span>
<span id="cb60-352"><a href="#cb60-352"></a></span>
<span id="cb60-353"><a href="#cb60-353"></a>There are also some strong correlations between the predictor variables themselves, particularly between RiverSlope and LogStone (r = 0.575) and LogOther and Hardness (r = 0.554). This could be an issue for our model, as collinearity can make it difficult to interpret the model parameters and can inflate the standard errors of the estimates.</span>
<span id="cb60-354"><a href="#cb60-354"></a></span>
<span id="cb60-355"><a href="#cb60-355"></a>We can confirm if correlations between predictors may be an issue with the model by observing the Variance inflation factor (VIF) later on when we check our model assumptions.</span>
<span id="cb60-356"><a href="#cb60-356"></a></span>
<span id="cb60-357"><a href="#cb60-357"></a>*(ii)* Fit a multiple linear regression model to the data using all variables. Set  <span class="in">`Br_Dens`</span> as the response variable and the remaining variables as the predictors.  This will be known as the 'full model'. </span>
<span id="cb60-358"><a href="#cb60-358"></a></span>
<span id="cb60-361"><a href="#cb60-361"></a><span class="in">```{r}</span></span>
<span id="cb60-362"><a href="#cb60-362"></a><span class="co"># fit the full model</span></span>
<span id="cb60-363"><a href="#cb60-363"></a></span>
<span id="cb60-364"><a href="#cb60-364"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Br_Dens <span class="sc">~</span> Altitude <span class="sc">+</span> Hardness <span class="sc">+</span> RiverSlope <span class="sc">+</span> LogCadd <span class="sc">+</span> LogStone <span class="sc">+</span> LogMay <span class="sc">+</span> LogOther, <span class="at">data =</span> dippers)</span>
<span id="cb60-365"><a href="#cb60-365"></a></span>
<span id="cb60-366"><a href="#cb60-366"></a><span class="in">```</span></span>
<span id="cb60-367"><a href="#cb60-367"></a></span>
<span id="cb60-368"><a href="#cb60-368"></a></span>
<span id="cb60-369"><a href="#cb60-369"></a>*(iii)* Check the assumptions of your model. Do you need to transform any variables? What does the Variance Inflation Factor (VIF) tell you about the collinearity between predictor variables?</span>
<span id="cb60-370"><a href="#cb60-370"></a></span>
<span id="cb60-371"><a href="#cb60-371"></a>The VIF will appear as one of the plots in the <span class="in">`check_model()`</span> function, but it can also be helpful to get the values. You can use the <span class="in">`vif()`</span> function from the <span class="in">`car`</span> package to get the VIF values for each predictor variable. </span>
<span id="cb60-372"><a href="#cb60-372"></a></span>
<span id="cb60-373"><a href="#cb60-373"></a>The check_model function has been squishing plots, so it may be better at times to plot them individually. You may use the following code, adapted to your model object names:</span>
<span id="cb60-374"><a href="#cb60-374"></a></span>
<span id="cb60-377"><a href="#cb60-377"></a><span class="in">```{r}</span></span>
<span id="cb60-378"><a href="#cb60-378"></a><span class="fu">library</span>(performance)</span>
<span id="cb60-379"><a href="#cb60-379"></a></span>
<span id="cb60-380"><a href="#cb60-380"></a><span class="co"># Linearity</span></span>
<span id="cb60-381"><a href="#cb60-381"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"linearity"</span>))</span>
<span id="cb60-382"><a href="#cb60-382"></a></span>
<span id="cb60-383"><a href="#cb60-383"></a><span class="co"># Normality</span></span>
<span id="cb60-384"><a href="#cb60-384"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"qq"</span>, <span class="st">"normality"</span>))</span>
<span id="cb60-385"><a href="#cb60-385"></a></span>
<span id="cb60-386"><a href="#cb60-386"></a><span class="co"># Equal variance</span></span>
<span id="cb60-387"><a href="#cb60-387"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"homogeneity"</span>))</span>
<span id="cb60-388"><a href="#cb60-388"></a></span>
<span id="cb60-389"><a href="#cb60-389"></a><span class="co"># Outliers</span></span>
<span id="cb60-390"><a href="#cb60-390"></a><span class="fu">check_model</span>(full_model, <span class="at">check =</span> <span class="fu">c</span>(<span class="st">"outliers"</span>, <span class="st">"pp_check"</span>))</span>
<span id="cb60-391"><a href="#cb60-391"></a></span>
<span id="cb60-392"><a href="#cb60-392"></a><span class="co"># VIF - visual</span></span>
<span id="cb60-393"><a href="#cb60-393"></a><span class="fu">plot</span>(performance<span class="sc">::</span><span class="fu">check_collinearity</span>(full_model))</span>
<span id="cb60-394"><a href="#cb60-394"></a></span>
<span id="cb60-395"><a href="#cb60-395"></a><span class="co"># VIF - numbers</span></span>
<span id="cb60-396"><a href="#cb60-396"></a><span class="co"># comes from the car package</span></span>
<span id="cb60-397"><a href="#cb60-397"></a>car<span class="sc">::</span><span class="fu">vif</span>(full_model)</span>
<span id="cb60-398"><a href="#cb60-398"></a></span>
<span id="cb60-399"><a href="#cb60-399"></a></span>
<span id="cb60-400"><a href="#cb60-400"></a><span class="do">#### ALTERNATIVE: plot() function to check assumptions </span></span>
<span id="cb60-401"><a href="#cb60-401"></a></span>
<span id="cb60-402"><a href="#cb60-402"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb60-403"><a href="#cb60-403"></a></span>
<span id="cb60-404"><a href="#cb60-404"></a><span class="fu">plot</span>(full_model)</span>
<span id="cb60-405"><a href="#cb60-405"></a></span>
<span id="cb60-406"><a href="#cb60-406"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb60-407"><a href="#cb60-407"></a></span>
<span id="cb60-408"><a href="#cb60-408"></a><span class="in">```</span></span>
<span id="cb60-409"><a href="#cb60-409"></a></span>
<span id="cb60-410"><a href="#cb60-410"></a><span class="ss">* </span>Linearity: The relationship between the predictors and the response variable appears to be linear, as the residuals are mostly scattered around the horizontal line at zero in the residuals vs fitted plot.</span>
<span id="cb60-411"><a href="#cb60-411"></a></span>
<span id="cb60-412"><a href="#cb60-412"></a><span class="ss">* </span>Independence: The residuals appear to be independent, as there is no clear pattern in the residuals vs fitted plot.</span>
<span id="cb60-413"><a href="#cb60-413"></a></span>
<span id="cb60-414"><a href="#cb60-414"></a><span class="ss">* </span>Normality: The residuals appear to be approximately normally distributed, as the points in the Q-Q plot roughly follow a straight line. When we look at the <span class="in">`check_model()`</span> version of the plot we a slight n-shape to the points, but this is only small compared to the overall distribution of the points, so we are not too concerned about this.</span>
<span id="cb60-415"><a href="#cb60-415"></a></span>
<span id="cb60-416"><a href="#cb60-416"></a><span class="ss">* </span>Equal variance: The residuals appear to have constant variance, as there is no clear pattern or fanning present in the standardised residuals vs fitted plot (scale-location in the base plot).</span>
<span id="cb60-417"><a href="#cb60-417"></a></span>
<span id="cb60-418"><a href="#cb60-418"></a><span class="ss">* </span>Leverage: No single observations lying outside the Cook's distance line, indicating no influential observations.</span>
<span id="cb60-419"><a href="#cb60-419"></a></span>
<span id="cb60-420"><a href="#cb60-420"></a>**VIF and collinearity**</span>
<span id="cb60-421"><a href="#cb60-421"></a></span>
<span id="cb60-422"><a href="#cb60-422"></a>VIF Thresholds vary, depending on who you ask. General rule is that if it is greater than 10, then you need to remove the associated predictor. Some conservative people prefer a value of 5, so we will go with this. </span>
<span id="cb60-423"><a href="#cb60-423"></a></span>
<span id="cb60-424"><a href="#cb60-424"></a>Our threshold is 5, so given all of our VIFs are below this, we are not too concerned about collinearity. However, because they are close to the threshold it is something to keep in mind when interpreting the model parameters.</span>
<span id="cb60-425"><a href="#cb60-425"></a></span>
<span id="cb60-426"><a href="#cb60-426"></a>*(iv)* Make a note of the model parameters and fit statistics for the full model. </span>
<span id="cb60-427"><a href="#cb60-427"></a></span>
<span id="cb60-430"><a href="#cb60-430"></a><span class="in">```{r}</span></span>
<span id="cb60-431"><a href="#cb60-431"></a><span class="fu">summary</span>(full_model)</span>
<span id="cb60-432"><a href="#cb60-432"></a><span class="in">```</span></span>
<span id="cb60-433"><a href="#cb60-433"></a></span>
<span id="cb60-434"><a href="#cb60-434"></a>We can see that there are two significant predictors (RiverSlope and LogStone) in the full model, but there are also a number of non-significant predictors. The adjusted R^2^ value is 0.77, which indicates that the model explains 77% of the variation in the response variable.</span>
<span id="cb60-435"><a href="#cb60-435"></a></span>
<span id="cb60-436"><a href="#cb60-436"></a>Because there are so many non-significant predictors in the model, we may want to consider removing some of them to produce a more parsimonious model. </span>
<span id="cb60-437"><a href="#cb60-437"></a></span>
<span id="cb60-438"><a href="#cb60-438"></a>*(v)*  Select the least significant predictor and remove it from the model. </span>
<span id="cb60-439"><a href="#cb60-439"></a></span>
<span id="cb60-440"><a href="#cb60-440"></a>In this case, the least significant predictor is <span class="in">`Altitude`</span> (P = 0.619). Remove it from the model and run the model again. This will be known as the 'reduced model'.</span>
<span id="cb60-441"><a href="#cb60-441"></a></span>
<span id="cb60-444"><a href="#cb60-444"></a><span class="in">```{r}</span></span>
<span id="cb60-445"><a href="#cb60-445"></a>reduced_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Br_Dens <span class="sc">~</span> Hardness <span class="sc">+</span> RiverSlope <span class="sc">+</span> LogCadd <span class="sc">+</span> LogStone <span class="sc">+</span> LogMay <span class="sc">+</span> LogOther, <span class="at">data =</span> dippers)</span>
<span id="cb60-446"><a href="#cb60-446"></a></span>
<span id="cb60-447"><a href="#cb60-447"></a><span class="in">```</span></span>
<span id="cb60-448"><a href="#cb60-448"></a></span>
<span id="cb60-449"><a href="#cb60-449"></a>*(vi)* Is the reduced model an improvement on the full model? How can you tell? What statistics would you look at to determine this?</span>
<span id="cb60-450"><a href="#cb60-450"></a></span>
<span id="cb60-453"><a href="#cb60-453"></a><span class="in">```{r}</span></span>
<span id="cb60-454"><a href="#cb60-454"></a><span class="fu">summary</span>(full_model)</span>
<span id="cb60-455"><a href="#cb60-455"></a><span class="fu">summary</span>(reduced_model)</span>
<span id="cb60-456"><a href="#cb60-456"></a><span class="in">```</span></span>
<span id="cb60-457"><a href="#cb60-457"></a></span>
<span id="cb60-458"><a href="#cb60-458"></a>Removing the <span class="in">`Altitude`</span> predictor from the model has slightly increased the adjusted R^2^ value. This is an improvement in terms of parsimony, but we will need to use hypothesis testing to determine whether the reduced model is a *significant* improvement on the full model. We can do this using an F-test. </span>
<span id="cb60-459"><a href="#cb60-459"></a></span>
<span id="cb60-460"><a href="#cb60-460"></a>::: callout-note</span>
<span id="cb60-461"><a href="#cb60-461"></a><span class="fu">## Checkpoint</span></span>
<span id="cb60-462"><a href="#cb60-462"></a></span>
<span id="cb60-463"><a href="#cb60-463"></a>You should now be able to prepare an appropriate model by refining it, checking your assumptions, and ensuring collinearity is not an issue.</span>
<span id="cb60-464"><a href="#cb60-464"></a></span>
<span id="cb60-465"><a href="#cb60-465"></a>:::</span>
<span id="cb60-466"><a href="#cb60-466"></a></span>
<span id="cb60-467"><a href="#cb60-467"></a><span class="fu">## Model selection with F-tests</span></span>
<span id="cb60-468"><a href="#cb60-468"></a></span>
<span id="cb60-469"><a href="#cb60-469"></a>We wil use the partial F-test to determine whether there is a significant difference between the models. </span>
<span id="cb60-470"><a href="#cb60-470"></a></span>
<span id="cb60-471"><a href="#cb60-471"></a>*(i)* State hypotheses</span>
<span id="cb60-472"><a href="#cb60-472"></a></span>
<span id="cb60-473"><a href="#cb60-473"></a>H0: no significant difference between the full and reduced models</span>
<span id="cb60-474"><a href="#cb60-474"></a>H1: There is a significant difference between the full and reduced models</span>
<span id="cb60-475"><a href="#cb60-475"></a></span>
<span id="cb60-476"><a href="#cb60-476"></a>If we fail to reject H0, then we would opt for the reduced model as it is more parsimonious (i.e. it is explaining a similar amount of variation with fewer predictors). </span>
<span id="cb60-477"><a href="#cb60-477"></a></span>
<span id="cb60-478"><a href="#cb60-478"></a>If we reject H0, then we would opt for the full model as it is a significant improvement on the reduced model.</span>
<span id="cb60-479"><a href="#cb60-479"></a></span>
<span id="cb60-480"><a href="#cb60-480"></a>*(ii)* Run the test</span>
<span id="cb60-481"><a href="#cb60-481"></a></span>
<span id="cb60-482"><a href="#cb60-482"></a>Once we have established our hypotheses, we can perform the F-test using the <span class="in">`anova()`</span> function to compare the full and reduced models. </span>
<span id="cb60-483"><a href="#cb60-483"></a></span>
<span id="cb60-486"><a href="#cb60-486"></a><span class="in">```{r}</span></span>
<span id="cb60-487"><a href="#cb60-487"></a><span class="fu">anova</span>(full_model, reduced_model)</span>
<span id="cb60-488"><a href="#cb60-488"></a></span>
<span id="cb60-489"><a href="#cb60-489"></a><span class="in">```</span></span>
<span id="cb60-490"><a href="#cb60-490"></a></span>
<span id="cb60-491"><a href="#cb60-491"></a>*(iii)* Are the models significantly different?</span>
<span id="cb60-492"><a href="#cb60-492"></a></span>
<span id="cb60-493"><a href="#cb60-493"></a>The P-value is 0.6186, which is larger than 0.05, so we fail to reject the null hypothesis.</span>
<span id="cb60-494"><a href="#cb60-494"></a></span>
<span id="cb60-495"><a href="#cb60-495"></a>This means that the full model is not a significant improvement on the reduced model, and we would opt for the reduced model as it is more parsimonious.</span>
<span id="cb60-496"><a href="#cb60-496"></a></span>
<span id="cb60-497"><a href="#cb60-497"></a></span>
<span id="cb60-498"><a href="#cb60-498"></a>::: callout-note</span>
<span id="cb60-499"><a href="#cb60-499"></a><span class="fu">## Checkpoint</span></span>
<span id="cb60-500"><a href="#cb60-500"></a></span>
<span id="cb60-501"><a href="#cb60-501"></a>You should now be able to use an F-test to determine whether the reduced model is a significant improvement on the full model. </span>
<span id="cb60-502"><a href="#cb60-502"></a></span>
<span id="cb60-503"><a href="#cb60-503"></a>**Remember:** the F-test is only useful if comparing nested models. </span>
<span id="cb60-504"><a href="#cb60-504"></a>:::</span>
<span id="cb60-505"><a href="#cb60-505"></a></span>
<span id="cb60-506"><a href="#cb60-506"></a><span class="fu"># Model selection using Stepwise regression</span></span>
<span id="cb60-507"><a href="#cb60-507"></a></span>
<span id="cb60-508"><a href="#cb60-508"></a>When we have many predictors, this manual testing can become time consuming, so we can choose to use the <span class="in">`step()`</span> function in R, which performs stepwise regression. This function will automatically remove the least significant predictor and test the model again, until it finds the best model based on the AIC criterion.</span>
<span id="cb60-509"><a href="#cb60-509"></a></span>
<span id="cb60-510"><a href="#cb60-510"></a>*(i)* Run the <span class="in">`step()`</span> function on the full model to perform stepwise regression.</span>
<span id="cb60-511"><a href="#cb60-511"></a></span>
<span id="cb60-514"><a href="#cb60-514"></a><span class="in">```{r}</span></span>
<span id="cb60-515"><a href="#cb60-515"></a>step_model <span class="ot">&lt;-</span> <span class="fu">step</span>(full_model, <span class="at">direction =</span> <span class="st">"backward"</span>)</span>
<span id="cb60-516"><a href="#cb60-516"></a></span>
<span id="cb60-517"><a href="#cb60-517"></a><span class="in">```</span></span>
<span id="cb60-518"><a href="#cb60-518"></a></span>
<span id="cb60-519"><a href="#cb60-519"></a>*(ii)* What is the final model that the <span class="in">`step()`</span> function has produced? How does it compare to the full and reduced models?</span>
<span id="cb60-520"><a href="#cb60-520"></a></span>
<span id="cb60-521"><a href="#cb60-521"></a>Since we have stored the step() output as an object, we can just call the object, which will show us the final model: </span>
<span id="cb60-522"><a href="#cb60-522"></a></span>
<span id="cb60-525"><a href="#cb60-525"></a><span class="in">```{r}</span></span>
<span id="cb60-526"><a href="#cb60-526"></a>step_model</span>
<span id="cb60-527"><a href="#cb60-527"></a></span>
<span id="cb60-528"><a href="#cb60-528"></a><span class="do">## OR</span></span>
<span id="cb60-529"><a href="#cb60-529"></a></span>
<span id="cb60-530"><a href="#cb60-530"></a><span class="fu">summary</span>(step_model)</span>
<span id="cb60-531"><a href="#cb60-531"></a><span class="in">```</span></span>
<span id="cb60-532"><a href="#cb60-532"></a></span>
<span id="cb60-533"><a href="#cb60-533"></a>We can see that the selected model is: </span>
<span id="cb60-534"><a href="#cb60-534"></a></span>
<span id="cb60-535"><a href="#cb60-535"></a>Br_Dens ~ Hardness + RiverSlope + LogCadd + LogStone + </span>
<span id="cb60-536"><a href="#cb60-536"></a>    LogOther</span>
<span id="cb60-537"><a href="#cb60-537"></a>    </span>
<span id="cb60-538"><a href="#cb60-538"></a>Or with the addition of the partial regression coefficients, our equation is: </span>
<span id="cb60-539"><a href="#cb60-539"></a></span>
<span id="cb60-540"><a href="#cb60-540"></a>Br_Dens = -0.725 + 0.012 * Hardness + 0.065 * RiverSlope + 0.549 * LogCadd + 0.512 * LogStone - 0.268 * LogOther</span>
<span id="cb60-541"><a href="#cb60-541"></a></span>
<span id="cb60-542"><a href="#cb60-542"></a>We can see there has also been a marginal change in the adjusted R^2^ value, which is now 0.7765, compared to 0.765 for the full model and 0.7766 for the reduced model. This supports the idea that the full model explained a similar amount of variation in the response compared to the simplest model obtained from the <span class="in">`step()`</span> function. Therefore it makes sense to select the simpler model. </span>
<span id="cb60-543"><a href="#cb60-543"></a></span>
<span id="cb60-544"><a href="#cb60-544"></a>*(iii)* How does the AIC of the stepwise regression model compare to the full and reduced models?</span>
<span id="cb60-545"><a href="#cb60-545"></a></span>
<span id="cb60-546"><a href="#cb60-546"></a>We can test this using the AIC() function: </span>
<span id="cb60-547"><a href="#cb60-547"></a></span>
<span id="cb60-550"><a href="#cb60-550"></a><span class="in">```{r}</span></span>
<span id="cb60-551"><a href="#cb60-551"></a><span class="fu">AIC</span>(full_model, reduced_model, step_model)</span>
<span id="cb60-552"><a href="#cb60-552"></a></span>
<span id="cb60-553"><a href="#cb60-553"></a><span class="in">```</span></span>
<span id="cb60-554"><a href="#cb60-554"></a></span>
<span id="cb60-555"><a href="#cb60-555"></a>Full_model AIC = 56.1</span>
<span id="cb60-556"><a href="#cb60-556"></a></span>
<span id="cb60-557"><a href="#cb60-557"></a>Reduced_model AIC = 54.5</span>
<span id="cb60-558"><a href="#cb60-558"></a></span>
<span id="cb60-559"><a href="#cb60-559"></a>step_model AIC = 53.9</span>
<span id="cb60-560"><a href="#cb60-560"></a></span>
<span id="cb60-561"><a href="#cb60-561"></a>As we select the model with the smallest AIC, we can confirm that the model selected by the <span class="in">`step()`</span> function is better. </span>
<span id="cb60-562"><a href="#cb60-562"></a></span>
<span id="cb60-563"><a href="#cb60-563"></a>You may notice that the AIC values are different between the <span class="in">`step()`</span> function and the <span class="in">`AIC()`</span> function. This is because the <span class="in">`step()`</span> function uses a different method to calculate the AIC values, which is based on the likelihood of the model, while the <span class="in">`AIC()`</span> function uses a different method based on the residual sum of squares.</span>
<span id="cb60-564"><a href="#cb60-564"></a></span>
<span id="cb60-565"><a href="#cb60-565"></a>::: callout-note</span>
<span id="cb60-566"><a href="#cb60-566"></a><span class="fu">## Checkpoint</span></span>
<span id="cb60-567"><a href="#cb60-567"></a></span>
<span id="cb60-568"><a href="#cb60-568"></a>You should now be able to run the <span class="in">`step()`</span> function to select the most appropriate model. </span>
<span id="cb60-569"><a href="#cb60-569"></a></span>
<span id="cb60-570"><a href="#cb60-570"></a>:::</span>
<span id="cb60-571"><a href="#cb60-571"></a></span>
<span id="cb60-572"><a href="#cb60-572"></a><span class="fu">## Wrap-up {.unnumbered}</span></span>
<span id="cb60-573"><a href="#cb60-573"></a></span>
<span id="cb60-574"><a href="#cb60-574"></a>In this tutorial, we used the dippers dataset to get some practice testing model assumptions and checking for collinearity. We then used partial F-tests and stepwise regression to select a more parsimonious model. </span>
<span id="cb60-575"><a href="#cb60-575"></a></span>
<span id="cb60-576"><a href="#cb60-576"></a></span>
<span id="cb60-577"><a href="#cb60-577"></a><span class="fu">### Example exam questions</span></span>
<span id="cb60-578"><a href="#cb60-578"></a></span>
<span id="cb60-579"><a href="#cb60-579"></a><span class="ss">1. </span>What assumptions do we need to check for when fitting a multiple linear regression?</span>
<span id="cb60-580"><a href="#cb60-580"></a></span>
<span id="cb60-581"><a href="#cb60-581"></a><span class="ss">2. </span>Why don't we just rely on the adjusted r^2^ to compare models?</span>
<span id="cb60-582"><a href="#cb60-582"></a></span>
<span id="cb60-583"><a href="#cb60-583"></a><span class="ss">3. </span>Can F-tests be run on non-nested models? Why or why not?</span>
<span id="cb60-584"><a href="#cb60-584"></a></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>The University of Sydney</p>
</div>
  </div>
</footer>




</body></html>