<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tutorial 07</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5acddea9ec7addd5e9532e878e20728d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-e3345c6ef29c45a7958e8df45469d16f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5acddea9ec7addd5e9532e878e20728d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-85a6e9acf135b508f40e500a51f36ff8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-85a6e9acf135b508f40e500a51f36ff8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-85a6e9acf135b508f40e500a51f36ff8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.js"></script>
<link href="../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #000;
      }

      .quarto-title-block .quarto-title-banner {
        color: #000;
background: white;
      }
</style><noscript>
  <style>
    section.level2 { display: block !important; }
  </style>
</noscript>
<script>window.QUARTO_PROGRESSIVE_SECTIONS = true;</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../site_libs/quarto-contrib/quarto-project/sandstone/assets/styles.css">
</head>

<body class="floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Tutorial 07</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
            <p class="subtitle lead">ENVX2001 – Applied Statistical Methods</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">Semester 1</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#welcome-to-week-7" id="toc-welcome-to-week-7" class="nav-link active" data-scroll-target="#welcome-to-week-7">Welcome to week 7!</a></li>
  <li><a href="#simple-linear-regression-vs-multiple-linear-regression" id="toc-simple-linear-regression-vs-multiple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression-vs-multiple-linear-regression">Simple linear regression vs Multiple Linear Regression</a></li>
  <li><a href="#setting-up-for-our-analysis" id="toc-setting-up-for-our-analysis" class="nav-link" data-scroll-target="#setting-up-for-our-analysis"><span class="header-section-number">1</span> Setting up for our analysis</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages"><span class="header-section-number">1.1</span> Packages</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"><span class="header-section-number">1.2</span> The data</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">2</span> Analysis</a>
  <ul class="collapse">
  <li><a href="#exercise-1-state-the-models-and-hypotheses" id="toc-exercise-1-state-the-models-and-hypotheses" class="nav-link" data-scroll-target="#exercise-1-state-the-models-and-hypotheses">Exercise 1: State the models and hypotheses</a>
  <ul class="collapse">
  <li><a href="#part-a-simple-linear-regression" id="toc-part-a-simple-linear-regression" class="nav-link" data-scroll-target="#part-a-simple-linear-regression">Part A — Simple linear regression</a></li>
  <li><a href="#part-b-multiple-linear-regression" id="toc-part-b-multiple-linear-regression" class="nav-link" data-scroll-target="#part-b-multiple-linear-regression">Part B — Multiple linear regression</a></li>
  </ul></li>
  <li><a href="#exercise-2-explore-the-data" id="toc-exercise-2-explore-the-data" class="nav-link" data-scroll-target="#exercise-2-explore-the-data">Exercise 2: Explore the data</a>
  <ul class="collapse">
  <li><a href="#part-a-distributions" id="toc-part-a-distributions" class="nav-link" data-scroll-target="#part-a-distributions">Part A — Distributions</a></li>
  <li><a href="#part-b-correlations" id="toc-part-b-correlations" class="nav-link" data-scroll-target="#part-b-correlations">Part B — Correlations</a></li>
  </ul></li>
  <li><a href="#exercise-3-fit-models-and-check-assumptions" id="toc-exercise-3-fit-models-and-check-assumptions" class="nav-link" data-scroll-target="#exercise-3-fit-models-and-check-assumptions">Exercise 3: Fit models and check assumptions</a>
  <ul class="collapse">
  <li><a href="#part-a-simple-linear-regression-1" id="toc-part-a-simple-linear-regression-1" class="nav-link" data-scroll-target="#part-a-simple-linear-regression-1">Part A — Simple linear regression</a></li>
  <li><a href="#part-b-multiple-linear-regression-1" id="toc-part-b-multiple-linear-regression-1" class="nav-link" data-scroll-target="#part-b-multiple-linear-regression-1">Part B — Multiple linear regression</a></li>
  </ul></li>
  <li><a href="#exercise-4-evaluate-model-fit" id="toc-exercise-4-evaluate-model-fit" class="nav-link" data-scroll-target="#exercise-4-evaluate-model-fit">Exercise 4: Evaluate model fit</a>
  <ul class="collapse">
  <li><a href="#part-a-simple-linear-regression-conclusion" id="toc-part-a-simple-linear-regression-conclusion" class="nav-link" data-scroll-target="#part-a-simple-linear-regression-conclusion">Part A — Simple linear regression conclusion</a></li>
  <li><a href="#part-b-multiple-linear-regression-conclusion" id="toc-part-b-multiple-linear-regression-conclusion" class="nav-link" data-scroll-target="#part-b-multiple-linear-regression-conclusion">Part B — Multiple linear regression conclusion</a></li>
  </ul></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up">Wrap-up</a>
  <ul class="collapse">
  <li><a href="#example-exam-questions" id="toc-example-exam-questions" class="nav-link" data-scroll-target="#example-exam-questions">Example exam questions</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="tutorial07.pdf"><i class="bi bi-file-pdf"></i>Typst (sandstone)</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<section id="welcome-to-week-7" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="welcome-to-week-7">Welcome to week 7!</h2>
<p>This week’s lecture introduced you to Simple- and Multiple- Linear Regression. For both of these regression techniques we defined the key steps in model fitting and how to interpret model output.</p>
<p>In this tutorial, we will explore key differences between simple linear regression (SLR) and multiple linear regression (MLR), and we will learn how to fit these models in R. We will also discuss how to test assumptions and evaluate model fit for both types of regression.</p>
<p>You will learn how to:</p>
<ol type="1">
<li>Distinguish key similarities and differences between simple linear regression (SLR) and multiple linear regression (MLR) models</li>
<li>Implement the fitting process for each type of model</li>
<li>Test assumptions and evaluate model fit of SLR and MLR models.</li>
</ol>
</section>
<section id="simple-linear-regression-vs-multiple-linear-regression" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="simple-linear-regression-vs-multiple-linear-regression">Simple linear regression vs Multiple Linear Regression</h2>
<div id="tbl-perf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-perf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Similarities and differences between MLR and SLR models
</figcaption>
<div aria-describedby="tbl-perf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Element</th>
<th style="text-align: left;">Simple Linear Regression (SLR)</th>
<th style="text-align: left;">Multiple Linear Regression (MLR)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Number of predictors</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2 or more</td>
</tr>
<tr class="even">
<td style="text-align: left;">Model form</td>
<td style="text-align: left;"><span class="math inline">Y = \beta_0 + \beta_1x + \epsilon</span></td>
<td style="text-align: left;"><span class="math inline">Y = \beta_0 + \beta_1x_1 + \beta_2x_2 + ... + \beta_nx_n + \epsilon</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">How to fit in R</td>
<td style="text-align: left;"><code>lm(y ~ x, data = dataset)</code></td>
<td style="text-align: left;"><code>lm(y ~ x1 + x2 + ... + xn, data = dataset)</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Assumptions</td>
<td style="text-align: left;">L.I.N.E.</td>
<td style="text-align: left;">L.I.N.E., collinearity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Model evaluation</td>
<td style="text-align: left;"><span class="math inline">r^2</span>, residual plots</td>
<td style="text-align: left;">Adjusted <span class="math inline">r^2</span>, residual plots, VIF</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusion</td>
<td style="text-align: left;">“as <span class="math inline">x</span> increases, <span class="math inline">y</span> also increases/decreases by <span class="math inline">\beta_1</span> units”</td>
<td style="text-align: left;">“as <span class="math inline">x_1</span> increases, <span class="math inline">y</span> also increases/decreases by <span class="math inline">\beta_1</span> units, holding all other predictors constant”</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="setting-up-for-our-analysis" class="level1 page-columns page-full" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Setting up for our analysis</h1>
<section id="packages" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="packages"><span class="header-section-number">1.1</span> Packages</h2>
<p>This tutorial uses <code>tidyverse</code>, <code>readxl</code>, <code>moments</code>, <code>psych</code>, and <code>performance</code>. Install any you are missing by running the following <strong>in the console</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If a package is already installed, R will simply reinstall it — no harm done.</p>
</section>
<section id="the-data" class="level2 page-columns page-full" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="the-data"><span class="header-section-number">1.2</span> The data</h2>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/Prunus-serotina.jpeg" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Black Cherry tree foliage and flowers, from Wikimedia Commons, by Sten Porse.</figcaption>
</figure>
</div>
<p>For both examples we will use the <em>trees</em> dataset, which is an in-built dataset provided by R. It contains measurements of diameter (inches), height (feet) and volume of timber (cubic feet) of 31 felled Black Cherry trees.</p>
<p><code>Volume</code> will be our response variable for both models.</p>
<p>Note: the ‘girth’ variable within the dataset is actually the diameter of the tree. We can rename it now, which also adds it into our R Environment:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>trees <span class="ot">&lt;-</span> trees <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>    <span class="fu">rename</span>(<span class="at">Diameter =</span> Girth)</span>
<span id="cb2-3"><a href="#cb2-3"></a></span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">head</span>(trees)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Diameter Height Volume
1      8.3     70   10.3
2      8.6     65   10.3
3      8.8     63   10.2
4     10.5     72   16.4
5     10.7     81   18.8
6     10.8     83   19.7</code></pre>
</div>
</div>
<p>Original data source:</p>
<p>⁠Meyer H. A. (1953). Forest Mensuration. Penns Valley Publishers.</p>
<p>⁠Ryan T. A., Joiner B. L., Ryan B. F. (1976). The Minitab Student Handbook. Duxbury Press, North Scituate, MA. ISBN 087150359X</p>
</section>
</section>
<section id="analysis" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Analysis</h1>
<section id="exercise-1-state-the-models-and-hypotheses" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-1-state-the-models-and-hypotheses">Exercise 1: State the models and hypotheses</h2>
<section id="part-a-simple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="part-a-simple-linear-regression">Part A — Simple linear regression</h3>
<p>The statistical model for a simple linear regression is:</p>
<p><span class="math display">
y_{i} = \beta_0 + \beta_1x_i + \epsilon_{i}
</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">y_{i}</span> is the response variable (Volume) for the <span class="math inline">i</span>th observation when the predictor X = <span class="math inline">x_i</span> (Diameter)</li>
<li><span class="math inline">\beta_0</span> is the intercept where the regression line crosses the y-axis (the expected timber Volume when Diameter is 0)</li>
<li><span class="math inline">\beta_1</span> is the slope of the regression line, which represents the change in timber Volume for a one-unit increase in Diameter</li>
<li><span class="math inline">\epsilon_{i}</span> is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance</li>
</ul>
<p>OR if written in terms of the variables in our dataset, the model would be:</p>
<p><span class="math display">
Volume = \beta_0 + \beta_1\cdot \ Diameter + \epsilon_{i}
</span></p>
<p><span class="math inline">H_0: \beta_1 = 0</span> , The slope is equal to zero, i.e.&nbsp;there is no relationship between Diameter and Volume</p>
<p><span class="math inline">H_1: \beta_1 \neq 0</span> , The slope is not equal to zero, i.e.&nbsp;There is a relationship between diameter and volume</p>
</section>
<section id="part-b-multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="part-b-multiple-linear-regression">Part B — Multiple linear regression</h3>
<p>The statistical model for a multiple linear regression with 2 predictors is:</p>
<p><span class="math display">
y_{i} = \beta_0 + \beta_1x_1 + \beta_2x_2 + \epsilon_{i}
</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">y_{i}</span> is the response variable (timber volume) for the <span class="math inline">i</span>th observation</li>
<li><span class="math inline">\beta_0</span> is the intercept where the regression line crosses the y-axis</li>
<li><span class="math inline">\beta_1</span> is the slope of the regression line for the first predictor, which represents the change in Volume for a one-unit increase in tree Diameter</li>
<li><span class="math inline">\beta_2</span> is the slope of the regression line for the second predictor, which represents the change in Volume for a one-unit increase in tree Height</li>
<li><span class="math inline">\epsilon_{i}</span> is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance</li>
</ul>
<p>OR if written in terms of the variables in our dataset, the model would be:</p>
<p><span class="math display">
Volume = \beta_0 + \beta_1\cdot \ Diameter + \beta_2\cdot \ Height + \epsilon_{i}
</span></p>
<p>For Multiple linear regression we are testing two (or more) predictors, so we have multiple null and alternative hypotheses to test.</p>
<p>First we test the partial regression coefficients for each predictor:</p>
<p><span class="math inline">H_0: \beta_1 = 0</span> , The partial regression slope is equal to zero, i.e.&nbsp;there is no relationship between Diameter and Volume</p>
<p><span class="math inline">H_1: \beta_1 \neq 0</span> , The partial regression slope is not equal to zero, i.e.&nbsp;There is a relationship between diameter and Volume</p>
<p><span class="math inline">H_0: \beta_2 = 0</span> , The partial regression slope is equal to zero, i.e.&nbsp;there is no relationship between Height and Volume</p>
<p><span class="math inline">H_1: \beta_2 \neq 0</span> , The partial regression slope is not equal to zero, i.e.&nbsp;There is a relationship between Height and Volume</p>
<p>Then we also test the overall model:</p>
<p><span class="math inline">H_0: \beta_1 = \beta_2 = 0</span> (all partial regression slopes are equal to zero, i.e.&nbsp;there is no relationship between diameter, height and volume)</p>
<p><span class="math inline">H_1: \beta_1 \neq 0</span> and/or <span class="math inline">\beta_2 \neq 0</span> (at least one partial regression slope is not equal to zero, i.e. there is a relationship between either diameter and volume, or height and volume).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should now be able to write down the model equation for both simple and multiple linear regression, and state the associated null and alternative hypotheses. You should also be able to explain why multiple linear regression requires a separate null hypothesis for each partial regression coefficient, as well as a null hypothesis for the overall model.</p>
</div>
</div>
</section>
</section>
<section id="exercise-2-explore-the-data" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-2-explore-the-data">Exercise 2: Explore the data</h2>
<section id="part-a-distributions" class="level3">
<h3 class="anchored" data-anchor-id="part-a-distributions">Part A — Distributions</h3>
<p>For each variable we need to check the distribution, identify outliers and check for correlations between predictors (for MLR).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb4-2"><a href="#cb4-2"></a></span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="fu">summary</span>(trees)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Diameter         Height       Volume     
 Min.   : 8.30   Min.   :63   Min.   :10.20  
 1st Qu.:11.05   1st Qu.:72   1st Qu.:19.40  
 Median :12.90   Median :76   Median :24.20  
 Mean   :13.25   Mean   :76   Mean   :30.17  
 3rd Qu.:15.25   3rd Qu.:80   3rd Qu.:37.30  
 Max.   :20.60   Max.   :87   Max.   :77.00  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># Apply the sd function for each column</span></span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">apply</span>(trees, <span class="dv">2</span>, sd) <span class="co"># (margin = 2 means apply the function to columns)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Diameter    Height    Volume 
 3.138139  6.371813 16.437846 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">skewness</span>(trees)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Diameter     Height     Volume 
 0.5263163 -0.3748690  1.0643575 </code></pre>
</div>
</div>
<p>The mean diameter is 13.25 inches and the median is 12.90 inches. The values range from 8.30 to 20.60 inches and the standard deviation is 3.14 inches. There is a slight skew, indicated by the skewness coefficient of 0.526. The slight skew is also visible in the following boxplot where the median lies closer to the first quartile.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Diameter)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3"></a>    <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The mean and median height is 76 feet and the values range from 63 to 87 feet. The standard deviation is 6.37 feet and the skewness coefficient is -0.37, indicating a relatively symmetrical distribution. The boxplot also shows a relatively symmetrical distribution, with the median lying close to the centre of the box.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Height)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>    <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The mean volume of timber is 30.17 cubic feet and the median is 24.20 cubic feet. The values range from 10.20 to 77.00 cubic feet and the standard deviation is 16.44 cubic feet. The skewness coefficient is 1.06, indicating that the variable is positively skewed. This is also visible in the boxplot, where the median lies closer to the first quartile and there are some high values that are potential outliers.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Volume)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>    <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Why do the high values matter?</strong></p>
<p>The high values would have high leverage in our model, causing the residuals to be skewed, violating our assumptions. The boxplot is therefore telling us that we might need to transform Volume to stabilise the variance of the regression, but it is worth confirming this with the diagnostic plots after fitting the model.</p>
</section>
<section id="part-b-correlations" class="level3">
<h3 class="anchored" data-anchor-id="part-b-correlations">Part B — Correlations</h3>
<p>For both simple and multiple linear regression we need to check the correlation between our response variable and our predictor variable.</p>
<p>For multiple linear regression it is also important to check the relationships between the predictor variables, as a strong correlation may indicate collinearity, which can influence the model.</p>
<p>We will start by looking at all correlations, and then for our simple linear regression we will select the variable that has the strongest correlation with the response (Volume) to use as our single predictor variable.</p>
<p>First we will use the correlation coefficient to understand the strength and direction of the relationships between the variables. Then we can look at the scatterplots between variables to verify the correlation coefficients and identify if there are any other types of relationships (e.g.&nbsp;non-linear) that may be occurring between variables.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Remember
</div>
</div>
<div class="callout-body-container callout-body">
<p>Correlation coefficients only measure the strength and direction of LINEAR relationships.</p>
<p>It is therefore important to visualise the relationships between variables to check for non-linear relationships, which may not be captured by the correlation coefficient.</p>
</div>
</div>
<p>Let’s have a look at the correlation coefficients between variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">cor</span>(trees)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Diameter    Height    Volume
Diameter 1.0000000 0.5192801 0.9671194
Height   0.5192801 1.0000000 0.5982497
Volume   0.9671194 0.5982497 1.0000000</code></pre>
</div>
</div>
<p>The correlation coefficient between Volume and Diameter is 0.967, which indicates a very strong positive linear relationship.</p>
<p>The correlation coefficient between Volume and Height is 0.598, which indicates a weak positive linear relationship.</p>
<p>The correlation coefficient between Diameter and Height is 0.519, which indicates a weak positive linear relationship, suggesting that there may be collinearity between these two predictor variables.</p>
<p>Now let’s look at the scatterplots between variables to verify these relationships:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">pairs</span>(trees)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatterplots confirm the strong positive linear relationship between Volume and Diameter as we can see the points following a clear trend on the plot. The points in the plot between height and volume also seem to follow a weaker positive trend as they appear more scattered across the plot area.</p>
<p>This is similar in the scatterplot between diameter and height where the points are also quite scattered but still follow a weak positive trend.</p>
<p>You are welcome to use the above code to create scatterplots between each pair of variables, and calculate the correlation coefficients separately, but if you prefer something cleaner, you can also use the <code>pairs.panels()</code> function from the <code>psych</code> package which produces a neat array of plots and coefficients.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># not using library(psych) as I am only using the function once</span></span>
<span id="cb16-2"><a href="#cb16-2"></a></span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="co"># instead do the following: </span></span>
<span id="cb16-4"><a href="#cb16-4"></a>psych<span class="sc">::</span><span class="fu">pairs.panels</span>(trees)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see the function produces scatterplots and correlation coefficients between each variable, as well as histograms for each individual variable. The histograms can supplement our EDA where we are looking at the distribution for each variable.</p>
<p>We have identified some potential collinearity occurring between height and diameter, but we will run the models today. Next week we will cover how to manage collinearity in MLR.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should now be able to describe the distribution of each variable using summary statistics, histograms and boxplots, and identify any potential outliers. You should also be able to use correlation coefficients and scatterplots to identify the strength and direction of relationships between variables, and to spot potential collinearity between predictor variables.</p>
</div>
</div>
</section>
</section>
<section id="exercise-3-fit-models-and-check-assumptions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-3-fit-models-and-check-assumptions">Exercise 3: Fit models and check assumptions</h2>
<p>Our correlation analyses identified that Diameter is more strongly correlated with Volume, so we will use Diameter as our predictor variable in the simple linear regression.</p>
<p>Fitting multiple and simple linear regression uses the same function in R, you just need to add on the additional predictors for multiple linear regression.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>mod_slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter, <span class="at">data =</span> trees)</span>
<span id="cb17-2"><a href="#cb17-2"></a></span>
<span id="cb17-3"><a href="#cb17-3"></a>mod_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter <span class="sc">+</span> Height, <span class="at">data =</span> trees)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Once you have fitted the models, you then need to check the assumptions have been met.</p>
<p>You can check model assumptions using the <code>plot()</code> function, but the <code>check_model()</code> function from the <code>performance</code> package produces a more comprehensive set of diagnostic plots to check assumptions.</p>
<section id="part-a-simple-linear-regression-1" class="level3">
<h3 class="anchored" data-anchor-id="part-a-simple-linear-regression-1">Part A — Simple linear regression</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb18-2"><a href="#cb18-2"></a></span>
<span id="cb18-3"><a href="#cb18-3"></a><span class="fu">check_model</span>(mod_slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Our assumptions for a simple linear regression are L.I.N.E. - Linearity, Independence, Normality, Equal variance. We also need to check if there are any observations that are having a larger influence on the model (higher leverage).</p>
<ul>
<li><p>L: The Linearity (residuals vs fitted) plot shows the residuals are not randomly scattered around the horizontal line at 0. This tells us that there is a non-linear relationship between diameter and volume.</p></li>
<li><p>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other.</p></li>
<li><p>N: The Normality (QQ) plot shows that the residuals mostly follow the straight line, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met.</p></li>
<li><p>E: The residuals vs fitted plot also shows the reference line is not flat and the points are not evenly scattered. This tells us that the variance of the residuals is not constant across all levels of diameter, which violates the assumption of equal variance (homoscedasticity).</p></li>
<li><p>Influential observations: The residuals vs leverage plot shows that there is an outlier in the data which may have an influence on the model. This is likely due to the high values of volume that we identified in our EDA.</p></li>
</ul>
<p>Decision: Our assumptions are not met, and we know that the volume variable is positively skewed, so we will log transform the response variable to stabilise the variance of the regression and manage the leverage of the outliers in the variable. This should reduce the skew and help meet our assumptions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># Create column containing log10Volume</span></span>
<span id="cb19-2"><a href="#cb19-2"></a></span>
<span id="cb19-3"><a href="#cb19-3"></a>trees <span class="ot">&lt;-</span> trees <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4"></a>    <span class="fu">mutate</span>(<span class="at">log10Volume =</span> <span class="fu">log10</span>(Volume))</span>
<span id="cb19-5"><a href="#cb19-5"></a></span>
<span id="cb19-6"><a href="#cb19-6"></a><span class="co"># Refit model with transformed Volume</span></span>
<span id="cb19-7"><a href="#cb19-7"></a></span>
<span id="cb19-8"><a href="#cb19-8"></a>log_mod_slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(log10Volume <span class="sc">~</span> Diameter, <span class="at">data =</span> trees)</span>
<span id="cb19-9"><a href="#cb19-9"></a></span>
<span id="cb19-10"><a href="#cb19-10"></a><span class="co"># Recheck assumptions</span></span>
<span id="cb19-11"><a href="#cb19-11"></a></span>
<span id="cb19-12"><a href="#cb19-12"></a><span class="fu">check_model</span>(log_mod_slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>L: The Linearity (residuals vs fitted) plot looks better, with more points following the line. The line still does not perfectly follow the horizontal line at 0, but it is much improved from the previous plot, so we can say that the linearity assumption is now mostly met. If we wanted to, it would also be worth exploring non-linear modelling but we will not cover that today.</p></li>
<li><p>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other. (same as before; not something we can always test for and it links back to the original experimental design).</p></li>
<li><p>N: The Normality (QQ) plot shows that the residuals follow the straight line much better now, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met.</p></li>
<li><p>E: The standardised residuals vs fitted plot shows the reference line is flatter, does not deviate as much as before, and the points are a bit more scattered. This tells us that the variance of the residuals has improved to a point where we can continue to our analyses. If you have something like this in a report, it is worth acknowledging that other models may be more appropriate and worth exploring.</p></li>
<li><p>Influential observations: The residuals vs leverage plot is no longer showing a point outside the dashed (Cook’s distance) line. This means there are no longer observations that are having a higher influence on the model and we can proceed with our model interpretation.</p></li>
</ul>
<p>Decision: Transforming Volume has helped us meet the model assumptions.</p>
<p>Some of the diagnostics have told us the relationship may be non-linear, so in the real world we would also consider fitting alternative models to see if there is something better out there to represent the relationship between tree volume and diameter. This is especially important if we wanted to use the model for prediction.</p>
</section>
<section id="part-b-multiple-linear-regression-1" class="level3">
<h3 class="anchored" data-anchor-id="part-b-multiple-linear-regression-1">Part B — Multiple linear regression</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">check_model</span>(mod_mlr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Our assumptions for a multiple linear regression are L.I.N.E. - Linearity, Independence, Normality, Equal variance AND collinearity. We also need to check if there are any observations that are having a larger influence on the model (higher leverage).</p>
<ul>
<li><p>L: The Linearity (residuals vs fitted) plot shows the residuals are not randomly scattered around the horizontal line at 0. This tells us that there is a non-linear relationship between our predictors and volume.</p></li>
<li><p>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other. (this is same as before; not something we can always test for and it links back to the original experimental design).</p></li>
<li><p>N: The Normality (QQ) plot shows that the residuals mostly follow the straight line, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met.</p></li>
<li><p>E: The residuals vs fitted plot also shows the reference line is not very flat and the points are not evenly scattered. This tells us that the variance of the residuals is not constant across our predictors, which violates the assumption of equal variance (homoscedasticity).</p></li>
<li><p>Influential observations: The residuals vs leverage plot shows no points lying outside the Cook’s distance (dashed) line, telling us that there are no single values influencing the model.</p></li>
<li><p>Collinearity: We can check for collinearity using the VIF (Variance Inflation Factor) which is provided in our <code>check_model()</code> function from the <code>performance</code> package. A VIF value above 5 (or 10, depending on who you ask) indicates a potential issue with collinearity. In our model, the VIFs for Diameter and Height are both low (&lt; 5), which indicates that there is no issue with collinearity between these two predictor variables.</p></li>
</ul>
<p>Decision: Our assumptions are not met, and we know that the volume variable is positively skewed, so like in our simple linear regression, we will use log-transformed Volume to stabilise the variance of the regression. This should reduce the skew and help meet our assumptions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># Refit model with transformed Volume</span></span>
<span id="cb21-2"><a href="#cb21-2"></a></span>
<span id="cb21-3"><a href="#cb21-3"></a>log_mod_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(log10Volume <span class="sc">~</span> Diameter <span class="sc">+</span> Height, <span class="at">data =</span> trees)</span>
<span id="cb21-4"><a href="#cb21-4"></a></span>
<span id="cb21-5"><a href="#cb21-5"></a><span class="co"># Recheck assumptions</span></span>
<span id="cb21-6"><a href="#cb21-6"></a></span>
<span id="cb21-7"><a href="#cb21-7"></a><span class="fu">check_model</span>(log_mod_mlr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tutorial07_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>L: The Linearity (residuals vs fitted) plot looks slightly better, with more points following the line. The line still does not perfectly follow the horizontal line at 0, but it is improved from the previous plot, so we can say that the linearity assumption is now mostly met. If we wanted to, it would also be worth exploring non-linear modelling but we will not cover that today.</p></li>
<li><p>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other. (same as before; not something we can always test for and it links back to the original experimental design).</p></li>
<li><p>N: The Normality (QQ) plot shows that the residuals follow the straight line much better now, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met.</p></li>
<li><p>E: The standardised residuals vs fitted plot shows the reference line is flatter and the points are a bit more scattered. This tells us that the variance of the residuals has improved to a point where we can continue to our analyses.</p></li>
<li><p>Influential observations: The residuals vs leverage plot shows the points are closer to the dashed line centred at 0 and no points are outside the dashed (Cook’s distance) line, indicating that there are no individual observations impacting on the model.</p></li>
</ul>
<p>Decision: Similar to the simple linear regression, transforming Volume has helped us meet the model assumptions.</p>
<p>Also similar to the simple linear regression, some of the diagnostics have told us the relationship may be non-linear, so in the real world we would also consider fitting alternative models to see if there is something better out there to represent the relationship between tree volume and diameter. This is especially important if we want to use the model for prediction.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should now be able to test assumptions for simple linear regression and multiple linear regression.</p>
<p>We can now move onto interpretation!</p>
</div>
</div>
</section>
</section>
<section id="exercise-4-evaluate-model-fit" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-4-evaluate-model-fit">Exercise 4: Evaluate model fit</h2>
<section id="part-a-simple-linear-regression-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="part-a-simple-linear-regression-conclusion">Part A — Simple linear regression conclusion</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">summary</span>(log_mod_slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log10Volume ~ Diameter, data = trees)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.09867 -0.04981  0.01255  0.03444  0.13218 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.485974   0.045176   10.76 1.23e-11 ***
Diameter    0.070601   0.003321   21.26  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.05708 on 29 degrees of freedom
Multiple R-squared:  0.9397,    Adjusted R-squared:  0.9376 
F-statistic:   452 on 1 and 29 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="1">
<li>State the model equation</li>
</ol>
<p>Model equation is <span class="math inline">log10(Volume) = 0.486 + 0.0706 \cdot Diameter</span></p>
<ol start="2" type="1">
<li>Interpretation of regression coefficients</li>
</ol>
<p>For every 1 unit change in Diameter, we expect a 0.0706 increase in log10(Volume).</p>
<ol start="3" type="1">
<li>P-value</li>
</ol>
<p>The P-value for the slope coefficient is &lt; 0.001, meaning we reject our null hypothesis that the slope is equal to zero (<span class="math inline">H_0: \beta_1 = 0</span>) and conclude that Diameter is a significant predictor of log10(Volume).</p>
<ol start="4" type="1">
<li>R-squared</li>
</ol>
<p>As we only have one predictor in the model, we can use the r<sup>2</sup> value rather than the adjusted r<sup>2</sup>.</p>
<p>The r<sup>2</sup> value is 0.94, which means that 94% of the variation in log10(Volume) can be explained by Diameter. This is a very strong r<sup>2</sup> value, suggesting that Diameter alone is able to explain most of the variation in log10(Volume).</p>
</section>
<section id="part-b-multiple-linear-regression-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="part-b-multiple-linear-regression-conclusion">Part B — Multiple linear regression conclusion</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">summary</span>(log_mod_mlr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log10Volume ~ Diameter + Height, data = trees)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.076991 -0.037357 -0.004312  0.025586  0.073835 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.044552   0.093510   0.476    0.637    
Diameter    0.063098   0.002861  22.057  &lt; 2e-16 ***
Height      0.007116   0.001409   5.051 2.41e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04202 on 28 degrees of freedom
Multiple R-squared:  0.9684,    Adjusted R-squared:  0.9662 
F-statistic: 429.7 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="1">
<li>State the model equation</li>
</ol>
<p>Model equation is:</p>
<p><span class="math inline">log10(Volume) = 0.0446 + 0.0631 \cdot Diameter + 0.0071 \cdot Height</span></p>
<ol start="2" type="1">
<li>Interpretation of regression coefficients</li>
</ol>
<p><em>Holding all other variables constant:</em> (very important to include this)</p>
<ul>
<li><p>For every 1 unit change in Diameter, we expect a 0.0631 increase in log10(Volume);</p></li>
<li><p>For every 1 unit change in Height, we expect a 0.0071 increase in log10(Volume).</p></li>
</ul>
<ol start="3" type="1">
<li>P-value</li>
</ol>
<p>When assessing the p-values, we must consider the p-value associated with each partial regression coefficient, as well as the overall model.</p>
<ol type="a">
<li>Relationship between Diameter and log10(Volume):</li>
</ol>
<p>The P-value for the partial regression coefficient is &lt; 0.001, meaning we reject our null hypothesis that the slope is equal to zero (<span class="math inline">H_0: \beta_1 = 0</span>) and conclude that Diameter is a significant predictor of log10(Volume).</p>
<ol start="2" type="a">
<li>Relationship between Height and log10(Volume):</li>
</ol>
<p>The P-value for the partial regression coefficient is &lt; 0.001, meaning we reject our null hypothesis that the slope is equal to zero (<span class="math inline">H_0: \beta_2 = 0</span>) and conclude that Height is also a significant predictor of log10(Volume).</p>
<ol start="3" type="a">
<li>Overall model:</li>
</ol>
<p>The P-value for the model is &lt; 0.001, indicating that at least one slope is not equal to zero. This means we reject our null hypothesis that all partial slopes are equal to zero (<span class="math display">H_0 : \beta_1 = \beta_2 = 0</span>) and conclude that our model is significant.</p>
<ol start="4" type="1">
<li>R-squared</li>
</ol>
<p>As we have more than one predictor in the model, we will need to use the adjusted r<sup>2</sup>. We will cover the reason for this in next week’s lecture.</p>
<p>The adjusted r<sup>2</sup> value is 0.97, which means that 97% of the variation in log10(Volume) can be explained by our model. This is a very strong r<sup>2</sup> value. Although there was some correlation between Diameter and Height in our EDA, the VIFs from our diagnostics were low, so collinearity is unlikely to be influencing our model.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checkpoint
</div>
</div>
<div class="callout-body-container callout-body">
<p>You should now be able to interpret the summary output of a fitted simple and multiple linear regression, including the model equation, the regression coefficients, the p-values and the (adjusted) r-squared. You should also be able to explain why multiple linear regression uses the adjusted r-squared rather than the r-squared, and why the interpretation of a partial regression coefficient always requires the phrase “holding all other variables constant”.</p>
</div>
</div>
</section>
</section>
<section id="wrap-up" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="wrap-up">Wrap-up</h2>
<p>In this tutorial, we have walked through the processes for simple and multiple linear regression, including how to fit models, check assumptions and how to interpret the output. You will hopefully now be able to recall key differences between the two types of models, which will help direct your analysis.</p>
<p>You will now apply these skills in the lab. If you have any questions please reach out to your tutors.</p>
<section id="example-exam-questions" class="level3">
<h3 class="anchored" data-anchor-id="example-exam-questions">Example exam questions</h3>
<ol type="1">
<li><p>Describe 3 key differences between simple linear regression and multiple linear regression.</p></li>
<li><p>Describe how we would check the assumptions of a multiple linear regression. What would we do if we found that one of the assumptions was violated?</p></li>
<li><p>If you fitted a multiple linear regression and only one predictor was significant, would you still expect the model to be significant? Justify your answer (it may help to recall the hypotheses for MLR).</p></li>
</ol>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ENVX-resources\.github\.io\/ENVX2001-resources\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb26-1"><a href="#cb26-1"></a><span class="co">---</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="an">title:</span><span class="co"> "Tutorial 07"</span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="co"># reviewed-by: ACA, 2026, updated by LP 2026</span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="an">format:</span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="co">  sandstone-html:</span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="co">    code-tools: true</span></span>
<span id="cb26-7"><a href="#cb26-7"></a><span class="co">---</span></span>
<span id="cb26-8"><a href="#cb26-8"></a></span>
<span id="cb26-9"><a href="#cb26-9"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb26-10"><a href="#cb26-10"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-11"><a href="#cb26-11"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb26-12"><a href="#cb26-12"></a></span>
<span id="cb26-13"><a href="#cb26-13"></a><span class="in">```</span></span>
<span id="cb26-14"><a href="#cb26-14"></a></span>
<span id="cb26-15"><a href="#cb26-15"></a><span class="fu">## Welcome to week 7! {.unnumbered}</span></span>
<span id="cb26-16"><a href="#cb26-16"></a></span>
<span id="cb26-17"><a href="#cb26-17"></a>This week's lecture introduced you to Simple- and Multiple- Linear Regression. For both of these regression techniques we defined the key steps in model fitting and how to interpret model output. </span>
<span id="cb26-18"><a href="#cb26-18"></a></span>
<span id="cb26-19"><a href="#cb26-19"></a>In this tutorial, we will explore key differences between simple linear regression (SLR) and multiple linear regression (MLR), and we will learn how to fit these models in R. We will also discuss how to test assumptions and evaluate model fit for both types of regression.</span>
<span id="cb26-20"><a href="#cb26-20"></a></span>
<span id="cb26-21"><a href="#cb26-21"></a>You will learn how to:</span>
<span id="cb26-22"><a href="#cb26-22"></a></span>
<span id="cb26-23"><a href="#cb26-23"></a><span class="ss">1.  </span>Distinguish key similarities and differences between simple linear regression (SLR) and multiple linear regression (MLR) models</span>
<span id="cb26-24"><a href="#cb26-24"></a><span class="ss">2.  </span>Implement the fitting process for each type of model</span>
<span id="cb26-25"><a href="#cb26-25"></a><span class="ss">3.  </span>Test assumptions and evaluate model fit of SLR and MLR models.</span>
<span id="cb26-26"><a href="#cb26-26"></a></span>
<span id="cb26-27"><a href="#cb26-27"></a><span class="fu">## Simple linear regression vs Multiple Linear Regression {.unnumbered}</span></span>
<span id="cb26-28"><a href="#cb26-28"></a></span>
<span id="cb26-29"><a href="#cb26-29"></a><span class="pp">|</span> Element <span class="pp">|</span> Simple Linear Regression (SLR) <span class="pp">|</span> Multiple Linear Regression (MLR) <span class="pp">|</span></span>
<span id="cb26-30"><a href="#cb26-30"></a><span class="pp">|:------------------------|:------------------------|:------------------------|</span></span>
<span id="cb26-31"><a href="#cb26-31"></a><span class="pp">|</span> Number of predictors <span class="pp">|</span> 1 <span class="pp">|</span> 2 or more <span class="pp">|</span></span>
<span id="cb26-32"><a href="#cb26-32"></a><span class="pp">|</span> Model form <span class="pp">|</span> $Y = \beta_0 + \beta_1x + \epsilon$ <span class="pp">|</span> $Y = \beta_0 + \beta_1x_1 + \beta_2x_2 + ... + \beta_nx_n + \epsilon$ <span class="pp">|</span></span>
<span id="cb26-33"><a href="#cb26-33"></a><span class="pp">|</span> How to fit in R <span class="pp">|</span> <span class="in">`lm(y ~ x, data = dataset)`</span> <span class="pp">|</span> <span class="in">`lm(y ~ x1 + x2 + ... + xn, data = dataset)`</span> <span class="pp">|</span></span>
<span id="cb26-34"><a href="#cb26-34"></a><span class="pp">|</span> Assumptions <span class="pp">|</span> L.I.N.E. <span class="pp">|</span> L.I.N.E., collinearity <span class="pp">|</span></span>
<span id="cb26-35"><a href="#cb26-35"></a><span class="pp">|</span> Model evaluation <span class="pp">|</span> $r^2$, residual plots <span class="pp">|</span> Adjusted $r^2$, residual plots, VIF<span class="pp">|</span></span>
<span id="cb26-36"><a href="#cb26-36"></a><span class="pp">|</span> Conclusion <span class="pp">|</span> "as $x$ increases, $y$ also increases/decreases by $\beta_1$ units" <span class="pp">|</span> "as $x_1$ increases, $y$ also increases/decreases by $\beta_1$ units, holding all other predictors constant" <span class="pp">|</span></span>
<span id="cb26-37"><a href="#cb26-37"></a></span>
<span id="cb26-38"><a href="#cb26-38"></a>: Similarities and differences between MLR and SLR models {#tbl-perf}</span>
<span id="cb26-39"><a href="#cb26-39"></a></span>
<span id="cb26-40"><a href="#cb26-40"></a><span class="fu"># Setting up for our analysis</span></span>
<span id="cb26-41"><a href="#cb26-41"></a></span>
<span id="cb26-42"><a href="#cb26-42"></a><span class="fu">## Packages</span></span>
<span id="cb26-43"><a href="#cb26-43"></a></span>
<span id="cb26-44"><a href="#cb26-44"></a>This tutorial uses <span class="in">`tidyverse`</span>, <span class="in">`readxl`</span>, <span class="in">`moments`</span>, <span class="in">`psych`</span>, and <span class="in">`performance`</span>. Install any you are missing by running the following **in the console**:</span>
<span id="cb26-45"><a href="#cb26-45"></a></span>
<span id="cb26-48"><a href="#cb26-48"></a><span class="in">```{r}</span></span>
<span id="cb26-49"><a href="#cb26-49"></a><span class="co">#| eval: false</span></span>
<span id="cb26-50"><a href="#cb26-50"></a></span>
<span id="cb26-51"><a href="#cb26-51"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>))</span>
<span id="cb26-52"><a href="#cb26-52"></a><span class="in">```</span></span>
<span id="cb26-53"><a href="#cb26-53"></a></span>
<span id="cb26-54"><a href="#cb26-54"></a>If a package is already installed, R will simply reinstall it — no harm done.</span>
<span id="cb26-55"><a href="#cb26-55"></a></span>
<span id="cb26-56"><a href="#cb26-56"></a><span class="fu">## The data</span></span>
<span id="cb26-57"><a href="#cb26-57"></a></span>
<span id="cb26-58"><a href="#cb26-58"></a><span class="al">![Black Cherry tree foliage and flowers, from Wikimedia Commons, by Sten Porse.](images/Prunus-serotina.jpeg)</span></span>
<span id="cb26-59"><a href="#cb26-59"></a></span>
<span id="cb26-60"><a href="#cb26-60"></a>For both examples we will use the *trees* dataset, which is an in-built dataset provided by R. It contains measurements of diameter (inches), height (feet) and volume of timber (cubic feet) of 31 felled Black Cherry trees. </span>
<span id="cb26-61"><a href="#cb26-61"></a></span>
<span id="cb26-62"><a href="#cb26-62"></a><span class="in">`Volume`</span> will be our response variable for both models. </span>
<span id="cb26-63"><a href="#cb26-63"></a></span>
<span id="cb26-64"><a href="#cb26-64"></a>Note: the 'girth' variable within the dataset is actually the diameter of the tree. We can rename it now, which also adds it into our R Environment: </span>
<span id="cb26-65"><a href="#cb26-65"></a></span>
<span id="cb26-68"><a href="#cb26-68"></a><span class="in">```{r}</span></span>
<span id="cb26-69"><a href="#cb26-69"></a>trees <span class="ot">&lt;-</span> trees <span class="sc">%&gt;%</span></span>
<span id="cb26-70"><a href="#cb26-70"></a>    <span class="fu">rename</span>(<span class="at">Diameter =</span> Girth)</span>
<span id="cb26-71"><a href="#cb26-71"></a></span>
<span id="cb26-72"><a href="#cb26-72"></a><span class="fu">head</span>(trees)</span>
<span id="cb26-73"><a href="#cb26-73"></a><span class="in">```</span></span>
<span id="cb26-74"><a href="#cb26-74"></a></span>
<span id="cb26-75"><a href="#cb26-75"></a>Original data source: </span>
<span id="cb26-76"><a href="#cb26-76"></a></span>
<span id="cb26-77"><a href="#cb26-77"></a>⁠Meyer H. A. (1953). Forest Mensuration. Penns Valley Publishers.</span>
<span id="cb26-78"><a href="#cb26-78"></a></span>
<span id="cb26-79"><a href="#cb26-79"></a>⁠Ryan T. A., Joiner B. L., Ryan B. F. (1976). The Minitab Student Handbook. Duxbury Press, North Scituate, MA. ISBN 087150359X</span>
<span id="cb26-80"><a href="#cb26-80"></a></span>
<span id="cb26-81"><a href="#cb26-81"></a></span>
<span id="cb26-82"><a href="#cb26-82"></a></span>
<span id="cb26-83"><a href="#cb26-83"></a><span class="fu"># Analysis</span></span>
<span id="cb26-84"><a href="#cb26-84"></a></span>
<span id="cb26-85"><a href="#cb26-85"></a><span class="fu">## Exercise 1: State the models and hypotheses {.unnumbered}</span></span>
<span id="cb26-86"><a href="#cb26-86"></a></span>
<span id="cb26-87"><a href="#cb26-87"></a><span class="fu">### Part A --- Simple linear regression</span></span>
<span id="cb26-88"><a href="#cb26-88"></a></span>
<span id="cb26-89"><a href="#cb26-89"></a>The statistical model for a simple linear regression is:</span>
<span id="cb26-90"><a href="#cb26-90"></a></span>
<span id="cb26-91"><a href="#cb26-91"></a>$$</span>
<span id="cb26-92"><a href="#cb26-92"></a>y_{i} = \beta_0 + \beta_1x_i + \epsilon_{i}</span>
<span id="cb26-93"><a href="#cb26-93"></a>$$</span>
<span id="cb26-94"><a href="#cb26-94"></a></span>
<span id="cb26-95"><a href="#cb26-95"></a>Where:</span>
<span id="cb26-96"><a href="#cb26-96"></a></span>
<span id="cb26-97"><a href="#cb26-97"></a><span class="ss">- </span>$y_{i}$ is the response variable (Volume) for the $i$th observation when the predictor X = $x_i$ (Diameter)</span>
<span id="cb26-98"><a href="#cb26-98"></a><span class="ss">- </span>$\beta_0$ is the intercept where the regression line crosses the y-axis (the expected timber Volume when Diameter is 0)</span>
<span id="cb26-99"><a href="#cb26-99"></a><span class="ss">- </span>$\beta_1$ is the slope of the regression line, which represents the change in timber Volume for a one-unit increase in Diameter</span>
<span id="cb26-100"><a href="#cb26-100"></a><span class="ss">- </span>$\epsilon_{i}$ is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance</span>
<span id="cb26-101"><a href="#cb26-101"></a></span>
<span id="cb26-102"><a href="#cb26-102"></a>OR if written in terms of the variables in our dataset, the model would be:</span>
<span id="cb26-103"><a href="#cb26-103"></a></span>
<span id="cb26-104"><a href="#cb26-104"></a>$$</span>
<span id="cb26-105"><a href="#cb26-105"></a>Volume = \beta_0 + \beta_1\cdot \ Diameter + \epsilon_{i}</span>
<span id="cb26-106"><a href="#cb26-106"></a>$$</span>
<span id="cb26-107"><a href="#cb26-107"></a></span>
<span id="cb26-108"><a href="#cb26-108"></a>$H_0: \beta_1 = 0$ , The slope is equal to zero, i.e. there is no relationship between Diameter and Volume</span>
<span id="cb26-109"><a href="#cb26-109"></a></span>
<span id="cb26-110"><a href="#cb26-110"></a>$H_1: \beta_1 \neq 0$ , The slope is not equal to zero, i.e. There is a relationship between diameter and volume</span>
<span id="cb26-111"><a href="#cb26-111"></a></span>
<span id="cb26-112"><a href="#cb26-112"></a><span class="fu">### Part B --- Multiple linear regression</span></span>
<span id="cb26-113"><a href="#cb26-113"></a></span>
<span id="cb26-114"><a href="#cb26-114"></a>The statistical model for a multiple linear regression with 2 predictors is:</span>
<span id="cb26-115"><a href="#cb26-115"></a></span>
<span id="cb26-116"><a href="#cb26-116"></a>$$</span>
<span id="cb26-117"><a href="#cb26-117"></a>y_{i} = \beta_0 + \beta_1x_1 + \beta_2x_2 + \epsilon_{i}</span>
<span id="cb26-118"><a href="#cb26-118"></a>$$</span>
<span id="cb26-119"><a href="#cb26-119"></a></span>
<span id="cb26-120"><a href="#cb26-120"></a>Where:</span>
<span id="cb26-121"><a href="#cb26-121"></a></span>
<span id="cb26-122"><a href="#cb26-122"></a><span class="ss">- </span>$y_{i}$ is the response variable (timber volume) for the $i$th observation</span>
<span id="cb26-123"><a href="#cb26-123"></a><span class="ss">- </span>$\beta_0$ is the intercept where the regression line crosses the y-axis</span>
<span id="cb26-124"><a href="#cb26-124"></a><span class="ss">- </span>$\beta_1$ is the slope of the regression line for the first predictor, which represents the change in Volume for a one-unit increase in tree Diameter</span>
<span id="cb26-125"><a href="#cb26-125"></a><span class="ss">- </span>$\beta_2$ is the slope of the regression line for the second predictor, which represents the change in Volume for a one-unit increase in tree Height</span>
<span id="cb26-126"><a href="#cb26-126"></a><span class="ss">- </span>$\epsilon_{i}$ is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance</span>
<span id="cb26-127"><a href="#cb26-127"></a></span>
<span id="cb26-128"><a href="#cb26-128"></a>OR if written in terms of the variables in our dataset, the model would be:</span>
<span id="cb26-129"><a href="#cb26-129"></a></span>
<span id="cb26-130"><a href="#cb26-130"></a>$$</span>
<span id="cb26-131"><a href="#cb26-131"></a>Volume = \beta_0 + \beta_1\cdot \ Diameter + \beta_2\cdot \ Height + \epsilon_{i}</span>
<span id="cb26-132"><a href="#cb26-132"></a>$$</span>
<span id="cb26-133"><a href="#cb26-133"></a></span>
<span id="cb26-134"><a href="#cb26-134"></a>For Multiple linear regression we are testing two (or more) predictors, so we have multiple null and alternative hypotheses to test.</span>
<span id="cb26-135"><a href="#cb26-135"></a></span>
<span id="cb26-136"><a href="#cb26-136"></a>First we test the partial regression coefficients for each predictor:</span>
<span id="cb26-137"><a href="#cb26-137"></a></span>
<span id="cb26-138"><a href="#cb26-138"></a>$H_0: \beta_1 = 0$ , The partial regression slope is equal to zero, i.e. there is no relationship between Diameter and Volume</span>
<span id="cb26-139"><a href="#cb26-139"></a></span>
<span id="cb26-140"><a href="#cb26-140"></a>$H_1: \beta_1 \neq 0$ , The partial regression slope is not equal to zero, i.e. There is a relationship between diameter and Volume</span>
<span id="cb26-141"><a href="#cb26-141"></a></span>
<span id="cb26-142"><a href="#cb26-142"></a></span>
<span id="cb26-143"><a href="#cb26-143"></a>$H_0: \beta_2 = 0$ , The partial regression slope is equal to zero, i.e. there is no relationship between Height and Volume</span>
<span id="cb26-144"><a href="#cb26-144"></a></span>
<span id="cb26-145"><a href="#cb26-145"></a>$H_1: \beta_2 \neq 0$ , The partial regression slope is not equal to zero, i.e. There is a relationship between Height and Volume</span>
<span id="cb26-146"><a href="#cb26-146"></a></span>
<span id="cb26-147"><a href="#cb26-147"></a>Then we also test the overall model:</span>
<span id="cb26-148"><a href="#cb26-148"></a></span>
<span id="cb26-149"><a href="#cb26-149"></a>$H_0: \beta_1 = \beta_2 = 0$ (all partial regression slopes are equal to zero, i.e. there is no relationship between diameter, height and volume)</span>
<span id="cb26-150"><a href="#cb26-150"></a></span>
<span id="cb26-151"><a href="#cb26-151"></a>$H_1: \beta_1 \neq 0$ and/or $\beta_2 \neq 0$ (at least one partial regression slope is not equal to zero, i.e.</span>
<span id="cb26-152"><a href="#cb26-152"></a>there is a relationship between either diameter and volume, or height and volume).</span>
<span id="cb26-153"><a href="#cb26-153"></a></span>
<span id="cb26-154"><a href="#cb26-154"></a>::: callout-note</span>
<span id="cb26-155"><a href="#cb26-155"></a><span class="fu">## Checkpoint</span></span>
<span id="cb26-156"><a href="#cb26-156"></a></span>
<span id="cb26-157"><a href="#cb26-157"></a>You should now be able to write down the model equation for both simple and multiple linear regression, and state the associated null and alternative hypotheses. You should also be able to explain why multiple linear regression requires a separate null hypothesis for each partial regression coefficient, as well as a null hypothesis for the overall model.</span>
<span id="cb26-158"><a href="#cb26-158"></a></span>
<span id="cb26-159"><a href="#cb26-159"></a>:::</span>
<span id="cb26-160"><a href="#cb26-160"></a></span>
<span id="cb26-161"><a href="#cb26-161"></a><span class="fu">## Exercise 2: Explore the data {.unnumbered}</span></span>
<span id="cb26-162"><a href="#cb26-162"></a></span>
<span id="cb26-163"><a href="#cb26-163"></a><span class="fu">### Part A --- Distributions</span></span>
<span id="cb26-164"><a href="#cb26-164"></a></span>
<span id="cb26-165"><a href="#cb26-165"></a>For each variable we need to check the distribution, identify outliers and check for correlations between predictors (for MLR).</span>
<span id="cb26-166"><a href="#cb26-166"></a></span>
<span id="cb26-169"><a href="#cb26-169"></a><span class="in">```{r}</span></span>
<span id="cb26-170"><a href="#cb26-170"></a><span class="fu">library</span>(moments)</span>
<span id="cb26-171"><a href="#cb26-171"></a></span>
<span id="cb26-172"><a href="#cb26-172"></a><span class="fu">summary</span>(trees)</span>
<span id="cb26-173"><a href="#cb26-173"></a></span>
<span id="cb26-174"><a href="#cb26-174"></a><span class="co"># Apply the sd function for each column</span></span>
<span id="cb26-175"><a href="#cb26-175"></a><span class="fu">apply</span>(trees, <span class="dv">2</span>, sd) <span class="co"># (margin = 2 means apply the function to columns)</span></span>
<span id="cb26-176"><a href="#cb26-176"></a></span>
<span id="cb26-177"><a href="#cb26-177"></a><span class="fu">skewness</span>(trees)</span>
<span id="cb26-178"><a href="#cb26-178"></a></span>
<span id="cb26-179"><a href="#cb26-179"></a><span class="in">```</span></span>
<span id="cb26-180"><a href="#cb26-180"></a></span>
<span id="cb26-181"><a href="#cb26-181"></a>The mean diameter is 13.25 inches and the median is 12.90 inches. The values range from 8.30 to 20.60 inches and the standard deviation is 3.14 inches. There is a slight skew, indicated by the skewness coefficient of 0.526. The slight skew is also visible in the following boxplot where the median lies closer to the first quartile. </span>
<span id="cb26-182"><a href="#cb26-182"></a></span>
<span id="cb26-185"><a href="#cb26-185"></a><span class="in">```{r}</span></span>
<span id="cb26-186"><a href="#cb26-186"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Diameter)) <span class="sc">+</span></span>
<span id="cb26-187"><a href="#cb26-187"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb26-188"><a href="#cb26-188"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb26-189"><a href="#cb26-189"></a><span class="in">```</span></span>
<span id="cb26-190"><a href="#cb26-190"></a></span>
<span id="cb26-191"><a href="#cb26-191"></a></span>
<span id="cb26-192"><a href="#cb26-192"></a>The mean and median height is 76 feet and the values range from 63 to 87 feet. The standard deviation is 6.37 feet and the skewness coefficient is -0.37, indicating a relatively symmetrical distribution. The boxplot also shows a relatively symmetrical distribution, with the median lying close to the centre of the box.</span>
<span id="cb26-193"><a href="#cb26-193"></a></span>
<span id="cb26-196"><a href="#cb26-196"></a><span class="in">```{r}</span></span>
<span id="cb26-197"><a href="#cb26-197"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Height)) <span class="sc">+</span></span>
<span id="cb26-198"><a href="#cb26-198"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb26-199"><a href="#cb26-199"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb26-200"><a href="#cb26-200"></a></span>
<span id="cb26-201"><a href="#cb26-201"></a><span class="in">```</span></span>
<span id="cb26-202"><a href="#cb26-202"></a></span>
<span id="cb26-203"><a href="#cb26-203"></a></span>
<span id="cb26-204"><a href="#cb26-204"></a>The mean volume of timber is 30.17 cubic feet and the median is 24.20 cubic feet. The values range from 10.20 to 77.00 cubic feet and the standard deviation is 16.44 cubic feet. The skewness coefficient is 1.06, indicating that the variable is positively skewed. This is also visible in the boxplot, where the median lies closer to the first quartile and there are some high values that are potential outliers.</span>
<span id="cb26-205"><a href="#cb26-205"></a></span>
<span id="cb26-208"><a href="#cb26-208"></a><span class="in">```{r}</span></span>
<span id="cb26-209"><a href="#cb26-209"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> Volume)) <span class="sc">+</span></span>
<span id="cb26-210"><a href="#cb26-210"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb26-211"><a href="#cb26-211"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb26-212"><a href="#cb26-212"></a></span>
<span id="cb26-213"><a href="#cb26-213"></a><span class="in">```</span></span>
<span id="cb26-214"><a href="#cb26-214"></a></span>
<span id="cb26-215"><a href="#cb26-215"></a></span>
<span id="cb26-216"><a href="#cb26-216"></a>**Why do the high values matter?**</span>
<span id="cb26-217"><a href="#cb26-217"></a></span>
<span id="cb26-218"><a href="#cb26-218"></a>The high values would have high leverage in our model, causing the residuals to be skewed, violating our assumptions. The boxplot is therefore telling us that we might need to transform Volume to stabilise the variance of the regression, but it is worth confirming this with the diagnostic plots after fitting the model.</span>
<span id="cb26-219"><a href="#cb26-219"></a></span>
<span id="cb26-220"><a href="#cb26-220"></a><span class="fu">### Part B --- Correlations</span></span>
<span id="cb26-221"><a href="#cb26-221"></a></span>
<span id="cb26-222"><a href="#cb26-222"></a>For both simple and multiple linear regression we need to check the correlation between our response variable and our predictor variable. </span>
<span id="cb26-223"><a href="#cb26-223"></a></span>
<span id="cb26-224"><a href="#cb26-224"></a>For multiple linear regression it is also important to check the relationships between the predictor variables, as a strong correlation may indicate collinearity, which can influence the model.</span>
<span id="cb26-225"><a href="#cb26-225"></a></span>
<span id="cb26-226"><a href="#cb26-226"></a>We will start by looking at all correlations, and then for our simple linear regression we will select the variable that has the strongest correlation with the response (Volume) to use as our single predictor variable.</span>
<span id="cb26-227"><a href="#cb26-227"></a></span>
<span id="cb26-228"><a href="#cb26-228"></a>First we will use the correlation coefficient to understand the strength and direction of the relationships between the variables. Then we can look at the scatterplots between variables to verify the correlation coefficients and identify if there are any other types of relationships (e.g. non-linear) that may be occurring between variables. </span>
<span id="cb26-229"><a href="#cb26-229"></a></span>
<span id="cb26-230"><a href="#cb26-230"></a>::: {.callout-tip}</span>
<span id="cb26-231"><a href="#cb26-231"></a><span class="fu">## Remember</span></span>
<span id="cb26-232"><a href="#cb26-232"></a></span>
<span id="cb26-233"><a href="#cb26-233"></a>Correlation coefficients only measure the strength and direction of LINEAR relationships. </span>
<span id="cb26-234"><a href="#cb26-234"></a></span>
<span id="cb26-235"><a href="#cb26-235"></a>It is therefore important to visualise the relationships between variables to check for non-linear relationships, which may not be captured by the correlation coefficient.</span>
<span id="cb26-236"><a href="#cb26-236"></a></span>
<span id="cb26-237"><a href="#cb26-237"></a>:::</span>
<span id="cb26-238"><a href="#cb26-238"></a></span>
<span id="cb26-239"><a href="#cb26-239"></a>Let's have a look at the correlation coefficients between variables: </span>
<span id="cb26-240"><a href="#cb26-240"></a></span>
<span id="cb26-243"><a href="#cb26-243"></a><span class="in">```{r}</span></span>
<span id="cb26-244"><a href="#cb26-244"></a><span class="fu">cor</span>(trees)</span>
<span id="cb26-245"><a href="#cb26-245"></a><span class="in">```</span></span>
<span id="cb26-246"><a href="#cb26-246"></a></span>
<span id="cb26-247"><a href="#cb26-247"></a>The correlation coefficient between Volume and Diameter is 0.967, which indicates a very strong positive linear relationship. </span>
<span id="cb26-248"><a href="#cb26-248"></a></span>
<span id="cb26-249"><a href="#cb26-249"></a>The correlation coefficient between Volume and Height is 0.598, which indicates a weak positive linear relationship. </span>
<span id="cb26-250"><a href="#cb26-250"></a></span>
<span id="cb26-251"><a href="#cb26-251"></a>The correlation coefficient between Diameter and Height is 0.519, which indicates a weak positive linear relationship, suggesting that there may be collinearity between these two predictor variables. </span>
<span id="cb26-252"><a href="#cb26-252"></a></span>
<span id="cb26-253"><a href="#cb26-253"></a>Now let's look at the scatterplots between variables to verify these relationships:</span>
<span id="cb26-254"><a href="#cb26-254"></a></span>
<span id="cb26-257"><a href="#cb26-257"></a><span class="in">```{r}</span></span>
<span id="cb26-258"><a href="#cb26-258"></a><span class="fu">pairs</span>(trees)</span>
<span id="cb26-259"><a href="#cb26-259"></a><span class="in">```</span></span>
<span id="cb26-260"><a href="#cb26-260"></a></span>
<span id="cb26-261"><a href="#cb26-261"></a>The scatterplots confirm the strong positive linear relationship between Volume and Diameter as we can see the points following a clear trend on the plot. The points in the plot between height and volume also seem to follow a weaker positive trend as they appear more scattered across the plot area. </span>
<span id="cb26-262"><a href="#cb26-262"></a></span>
<span id="cb26-263"><a href="#cb26-263"></a>This is similar in the scatterplot between diameter and height where the points are also quite scattered but still follow a weak positive trend. </span>
<span id="cb26-264"><a href="#cb26-264"></a></span>
<span id="cb26-265"><a href="#cb26-265"></a>You are welcome to use the above code to create scatterplots between each pair of variables, and calculate the correlation coefficients separately, but if you prefer something cleaner, you can also use the <span class="in">`pairs.panels()`</span> function from the <span class="in">`psych`</span> package which produces a neat array of plots and coefficients. </span>
<span id="cb26-266"><a href="#cb26-266"></a></span>
<span id="cb26-269"><a href="#cb26-269"></a><span class="in">```{r}</span></span>
<span id="cb26-270"><a href="#cb26-270"></a><span class="co"># not using library(psych) as I am only using the function once</span></span>
<span id="cb26-271"><a href="#cb26-271"></a></span>
<span id="cb26-272"><a href="#cb26-272"></a><span class="co"># instead do the following: </span></span>
<span id="cb26-273"><a href="#cb26-273"></a>psych<span class="sc">::</span><span class="fu">pairs.panels</span>(trees)</span>
<span id="cb26-274"><a href="#cb26-274"></a></span>
<span id="cb26-275"><a href="#cb26-275"></a><span class="in">```</span></span>
<span id="cb26-276"><a href="#cb26-276"></a></span>
<span id="cb26-277"><a href="#cb26-277"></a>We can see the function produces scatterplots and correlation coefficients between each variable, as well as histograms for each individual variable. The histograms can supplement our EDA where we are looking at the distribution for each variable. </span>
<span id="cb26-278"><a href="#cb26-278"></a></span>
<span id="cb26-279"><a href="#cb26-279"></a>We have identified some potential collinearity occurring between height and diameter, but we will run the models today. Next week we will cover how to manage collinearity in MLR.</span>
<span id="cb26-280"><a href="#cb26-280"></a></span>
<span id="cb26-281"><a href="#cb26-281"></a>::: callout-note</span>
<span id="cb26-282"><a href="#cb26-282"></a><span class="fu">## Checkpoint</span></span>
<span id="cb26-283"><a href="#cb26-283"></a></span>
<span id="cb26-284"><a href="#cb26-284"></a>You should now be able to describe the distribution of each variable using summary statistics, histograms and boxplots, and identify any potential outliers. You should also be able to use correlation coefficients and scatterplots to identify the strength and direction of relationships between variables, and to spot potential collinearity between predictor variables.</span>
<span id="cb26-285"><a href="#cb26-285"></a></span>
<span id="cb26-286"><a href="#cb26-286"></a>:::</span>
<span id="cb26-287"><a href="#cb26-287"></a></span>
<span id="cb26-288"><a href="#cb26-288"></a><span class="fu">## Exercise 3: Fit models and check assumptions {.unnumbered}</span></span>
<span id="cb26-289"><a href="#cb26-289"></a></span>
<span id="cb26-290"><a href="#cb26-290"></a>Our correlation analyses identified that Diameter is more strongly correlated with Volume, so we will use Diameter as our predictor variable in the simple linear regression.</span>
<span id="cb26-291"><a href="#cb26-291"></a></span>
<span id="cb26-292"><a href="#cb26-292"></a>Fitting multiple and simple linear regression uses the same function in R, you just need to add on the additional predictors for multiple linear regression. </span>
<span id="cb26-293"><a href="#cb26-293"></a></span>
<span id="cb26-296"><a href="#cb26-296"></a><span class="in">```{r}</span></span>
<span id="cb26-297"><a href="#cb26-297"></a>mod_slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter, <span class="at">data =</span> trees)</span>
<span id="cb26-298"><a href="#cb26-298"></a></span>
<span id="cb26-299"><a href="#cb26-299"></a>mod_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter <span class="sc">+</span> Height, <span class="at">data =</span> trees)</span>
<span id="cb26-300"><a href="#cb26-300"></a></span>
<span id="cb26-301"><a href="#cb26-301"></a><span class="in">```</span></span>
<span id="cb26-302"><a href="#cb26-302"></a></span>
<span id="cb26-303"><a href="#cb26-303"></a>Once you have fitted the models, you then need to check the assumptions have been met.</span>
<span id="cb26-304"><a href="#cb26-304"></a></span>
<span id="cb26-305"><a href="#cb26-305"></a>You can check model assumptions using the <span class="in">`plot()`</span> function, but the <span class="in">`check_model()`</span> function from the <span class="in">`performance`</span> package produces a more comprehensive set of diagnostic plots to check assumptions.</span>
<span id="cb26-306"><a href="#cb26-306"></a></span>
<span id="cb26-307"><a href="#cb26-307"></a><span class="fu">### Part A --- Simple linear regression</span></span>
<span id="cb26-308"><a href="#cb26-308"></a></span>
<span id="cb26-311"><a href="#cb26-311"></a><span class="in">```{r}</span></span>
<span id="cb26-312"><a href="#cb26-312"></a><span class="co">#| fig-height: 10</span></span>
<span id="cb26-313"><a href="#cb26-313"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb26-314"><a href="#cb26-314"></a><span class="fu">library</span>(performance)</span>
<span id="cb26-315"><a href="#cb26-315"></a></span>
<span id="cb26-316"><a href="#cb26-316"></a><span class="fu">check_model</span>(mod_slr)</span>
<span id="cb26-317"><a href="#cb26-317"></a></span>
<span id="cb26-318"><a href="#cb26-318"></a><span class="in">```</span></span>
<span id="cb26-319"><a href="#cb26-319"></a></span>
<span id="cb26-320"><a href="#cb26-320"></a>Our assumptions for a simple linear regression are L.I.N.E. - Linearity, Independence, Normality, Equal variance. We also need to check if there are any observations that are having a larger influence on the model (higher leverage).</span>
<span id="cb26-321"><a href="#cb26-321"></a></span>
<span id="cb26-322"><a href="#cb26-322"></a><span class="ss">* </span>L: The Linearity (residuals vs fitted) plot shows the residuals are not randomly scattered around the horizontal line at 0. This tells us that there is a non-linear relationship between diameter and volume. </span>
<span id="cb26-323"><a href="#cb26-323"></a></span>
<span id="cb26-324"><a href="#cb26-324"></a><span class="ss">* </span>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other. </span>
<span id="cb26-325"><a href="#cb26-325"></a></span>
<span id="cb26-326"><a href="#cb26-326"></a><span class="ss">* </span>N: The Normality (QQ) plot shows that the residuals mostly follow the straight line, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met. </span>
<span id="cb26-327"><a href="#cb26-327"></a></span>
<span id="cb26-328"><a href="#cb26-328"></a><span class="ss">* </span>E: The residuals vs fitted plot also shows the reference line is not flat and the points are not evenly scattered. This tells us that the variance of the residuals is not constant across all levels of diameter, which violates the assumption of equal variance (homoscedasticity).</span>
<span id="cb26-329"><a href="#cb26-329"></a></span>
<span id="cb26-330"><a href="#cb26-330"></a><span class="ss">* </span>Influential observations: The residuals vs leverage plot shows that there is an outlier in the data which may have an influence on the model. This is likely due to the high values of volume that we identified in our EDA.</span>
<span id="cb26-331"><a href="#cb26-331"></a></span>
<span id="cb26-332"><a href="#cb26-332"></a>Decision: Our assumptions are not met, and we know that the volume variable is positively skewed, so we will log transform the response variable to stabilise the variance of the regression and manage the leverage of the outliers in the variable. This should reduce the skew and help meet our assumptions.</span>
<span id="cb26-333"><a href="#cb26-333"></a></span>
<span id="cb26-334"><a href="#cb26-334"></a></span>
<span id="cb26-335"><a href="#cb26-335"></a></span>
<span id="cb26-338"><a href="#cb26-338"></a><span class="in">```{r}</span></span>
<span id="cb26-339"><a href="#cb26-339"></a><span class="co">#| fig-height: 10</span></span>
<span id="cb26-340"><a href="#cb26-340"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb26-341"><a href="#cb26-341"></a></span>
<span id="cb26-342"><a href="#cb26-342"></a><span class="co"># Create column containing log10Volume</span></span>
<span id="cb26-343"><a href="#cb26-343"></a></span>
<span id="cb26-344"><a href="#cb26-344"></a>trees <span class="ot">&lt;-</span> trees <span class="sc">%&gt;%</span></span>
<span id="cb26-345"><a href="#cb26-345"></a>    <span class="fu">mutate</span>(<span class="at">log10Volume =</span> <span class="fu">log10</span>(Volume))</span>
<span id="cb26-346"><a href="#cb26-346"></a></span>
<span id="cb26-347"><a href="#cb26-347"></a><span class="co"># Refit model with transformed Volume</span></span>
<span id="cb26-348"><a href="#cb26-348"></a></span>
<span id="cb26-349"><a href="#cb26-349"></a>log_mod_slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(log10Volume <span class="sc">~</span> Diameter, <span class="at">data =</span> trees)</span>
<span id="cb26-350"><a href="#cb26-350"></a></span>
<span id="cb26-351"><a href="#cb26-351"></a><span class="co"># Recheck assumptions</span></span>
<span id="cb26-352"><a href="#cb26-352"></a></span>
<span id="cb26-353"><a href="#cb26-353"></a><span class="fu">check_model</span>(log_mod_slr)</span>
<span id="cb26-354"><a href="#cb26-354"></a></span>
<span id="cb26-355"><a href="#cb26-355"></a><span class="in">```</span></span>
<span id="cb26-356"><a href="#cb26-356"></a></span>
<span id="cb26-357"><a href="#cb26-357"></a><span class="ss">* </span>L: The Linearity (residuals vs fitted) plot looks better, with more points following the line. The line still does not perfectly follow the horizontal line at 0, but it is much improved from the previous plot, so we can say that the linearity assumption is now mostly met. If we wanted to, it would also be worth exploring non-linear modelling but we will not cover that today. </span>
<span id="cb26-358"><a href="#cb26-358"></a></span>
<span id="cb26-359"><a href="#cb26-359"></a><span class="ss">* </span>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other. (same as before; not something we can always test for and it links back to the original experimental design).</span>
<span id="cb26-360"><a href="#cb26-360"></a></span>
<span id="cb26-361"><a href="#cb26-361"></a><span class="ss">* </span>N: The Normality (QQ) plot shows that the residuals follow the straight line much better now, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met. </span>
<span id="cb26-362"><a href="#cb26-362"></a></span>
<span id="cb26-363"><a href="#cb26-363"></a><span class="ss">* </span>E: The standardised residuals vs fitted plot shows the reference line is flatter, does not deviate as much as before, and the points are a bit more scattered. This tells us that the variance of the residuals has improved to a point where we can continue to our analyses. If you have something like this in a report, it is worth acknowledging that other models may be more appropriate and worth exploring.</span>
<span id="cb26-364"><a href="#cb26-364"></a></span>
<span id="cb26-365"><a href="#cb26-365"></a><span class="ss">* </span>Influential observations: The residuals vs leverage plot is no longer showing a point outside the dashed (Cook's distance) line. This means there are no longer observations that are having a higher influence on the model and we can proceed with our model interpretation. </span>
<span id="cb26-366"><a href="#cb26-366"></a></span>
<span id="cb26-367"><a href="#cb26-367"></a>Decision: Transforming Volume has helped us meet the model assumptions. </span>
<span id="cb26-368"><a href="#cb26-368"></a></span>
<span id="cb26-369"><a href="#cb26-369"></a>Some of the diagnostics have told us the relationship may be non-linear, so in the real world we would also consider fitting alternative models to see if there is something better out there to represent the relationship between tree volume and diameter. This is especially important if we wanted to use the model for prediction. </span>
<span id="cb26-370"><a href="#cb26-370"></a></span>
<span id="cb26-371"><a href="#cb26-371"></a></span>
<span id="cb26-372"><a href="#cb26-372"></a><span class="fu">### Part B --- Multiple linear regression</span></span>
<span id="cb26-373"><a href="#cb26-373"></a></span>
<span id="cb26-376"><a href="#cb26-376"></a><span class="in">```{r}</span></span>
<span id="cb26-377"><a href="#cb26-377"></a><span class="co">#| fig-height: 10</span></span>
<span id="cb26-378"><a href="#cb26-378"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb26-379"><a href="#cb26-379"></a></span>
<span id="cb26-380"><a href="#cb26-380"></a><span class="fu">check_model</span>(mod_mlr)</span>
<span id="cb26-381"><a href="#cb26-381"></a></span>
<span id="cb26-382"><a href="#cb26-382"></a><span class="in">```</span></span>
<span id="cb26-383"><a href="#cb26-383"></a></span>
<span id="cb26-384"><a href="#cb26-384"></a>Our assumptions for a multiple linear regression are L.I.N.E. - Linearity, Independence, Normality, Equal variance AND collinearity. We also need to check if there are any observations that are having a larger influence on the model (higher leverage).</span>
<span id="cb26-385"><a href="#cb26-385"></a></span>
<span id="cb26-386"><a href="#cb26-386"></a><span class="ss">* </span>L: The Linearity (residuals vs fitted) plot shows the residuals are not randomly scattered around the horizontal line at 0. This tells us that there is a non-linear relationship between our predictors and volume. </span>
<span id="cb26-387"><a href="#cb26-387"></a></span>
<span id="cb26-388"><a href="#cb26-388"></a><span class="ss">* </span>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other. (this is same as before; not something we can always test for and it links back to the original experimental design).</span>
<span id="cb26-389"><a href="#cb26-389"></a></span>
<span id="cb26-390"><a href="#cb26-390"></a><span class="ss">* </span>N: The Normality (QQ) plot shows that the residuals mostly follow the straight line, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met. </span>
<span id="cb26-391"><a href="#cb26-391"></a></span>
<span id="cb26-392"><a href="#cb26-392"></a><span class="ss">* </span>E: The residuals vs fitted plot also shows the reference line is not very flat and the points are not evenly scattered. This tells us that the variance of the residuals is not constant across our predictors, which violates the assumption of equal variance (homoscedasticity).</span>
<span id="cb26-393"><a href="#cb26-393"></a></span>
<span id="cb26-394"><a href="#cb26-394"></a><span class="ss">* </span>Influential observations: The residuals vs leverage plot shows no points lying outside the Cook's distance (dashed) line, telling us that there are no single values influencing the model. </span>
<span id="cb26-395"><a href="#cb26-395"></a></span>
<span id="cb26-396"><a href="#cb26-396"></a><span class="ss">* </span>Collinearity: We can check for collinearity using the VIF (Variance Inflation Factor) which is provided in our <span class="in">`check_model()`</span> function from the <span class="in">`performance`</span> package. A VIF value above 5 (or 10, depending on who you ask) indicates a potential issue with collinearity. In our model, the VIFs for Diameter and Height are both low (&lt; 5), which indicates that there is no issue with collinearity between these two predictor variables. </span>
<span id="cb26-397"><a href="#cb26-397"></a></span>
<span id="cb26-398"><a href="#cb26-398"></a>Decision: Our assumptions are not met, and we know that the volume variable is positively skewed, so like in our simple linear regression, we will use log-transformed Volume to stabilise the variance of the regression. This should reduce the skew and help meet our assumptions.</span>
<span id="cb26-399"><a href="#cb26-399"></a></span>
<span id="cb26-400"><a href="#cb26-400"></a></span>
<span id="cb26-403"><a href="#cb26-403"></a><span class="in">```{r}</span></span>
<span id="cb26-404"><a href="#cb26-404"></a><span class="co">#| fig-height: 10</span></span>
<span id="cb26-405"><a href="#cb26-405"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb26-406"><a href="#cb26-406"></a></span>
<span id="cb26-407"><a href="#cb26-407"></a><span class="co"># Refit model with transformed Volume</span></span>
<span id="cb26-408"><a href="#cb26-408"></a></span>
<span id="cb26-409"><a href="#cb26-409"></a>log_mod_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(log10Volume <span class="sc">~</span> Diameter <span class="sc">+</span> Height, <span class="at">data =</span> trees)</span>
<span id="cb26-410"><a href="#cb26-410"></a></span>
<span id="cb26-411"><a href="#cb26-411"></a><span class="co"># Recheck assumptions</span></span>
<span id="cb26-412"><a href="#cb26-412"></a></span>
<span id="cb26-413"><a href="#cb26-413"></a><span class="fu">check_model</span>(log_mod_mlr)</span>
<span id="cb26-414"><a href="#cb26-414"></a></span>
<span id="cb26-415"><a href="#cb26-415"></a><span class="in">```</span></span>
<span id="cb26-416"><a href="#cb26-416"></a></span>
<span id="cb26-417"><a href="#cb26-417"></a><span class="ss">* </span>L: The Linearity (residuals vs fitted) plot looks slightly better, with more points following the line. The line still does not perfectly follow the horizontal line at 0, but it is improved from the previous plot, so we can say that the linearity assumption is now mostly met. If we wanted to, it would also be worth exploring non-linear modelling but we will not cover that today. </span>
<span id="cb26-418"><a href="#cb26-418"></a></span>
<span id="cb26-419"><a href="#cb26-419"></a><span class="ss">* </span>I: The Independence assumption is met as the data is collected from different trees, so the observations are independent of each other. (same as before; not something we can always test for and it links back to the original experimental design).</span>
<span id="cb26-420"><a href="#cb26-420"></a></span>
<span id="cb26-421"><a href="#cb26-421"></a><span class="ss">* </span>N: The Normality (QQ) plot shows that the residuals follow the straight line much better now, which indicates that the residuals are normally distributed. It looks like the assumption of normality has been met. </span>
<span id="cb26-422"><a href="#cb26-422"></a></span>
<span id="cb26-423"><a href="#cb26-423"></a><span class="ss">* </span>E: The standardised residuals vs fitted plot shows the reference line is flatter and the points are a bit more scattered. This tells us that the variance of the residuals has improved to a point where we can continue to our analyses. </span>
<span id="cb26-424"><a href="#cb26-424"></a></span>
<span id="cb26-425"><a href="#cb26-425"></a><span class="ss">* </span>Influential observations: The residuals vs leverage plot shows the points are closer to the dashed line centred at 0 and no points are outside the dashed (Cook's distance) line, indicating that there are no individual observations impacting on the model.</span>
<span id="cb26-426"><a href="#cb26-426"></a></span>
<span id="cb26-427"><a href="#cb26-427"></a>Decision: Similar to the simple linear regression, transforming Volume has helped us meet the model assumptions. </span>
<span id="cb26-428"><a href="#cb26-428"></a></span>
<span id="cb26-429"><a href="#cb26-429"></a>Also similar to the simple linear regression, some of the diagnostics have told us the relationship may be non-linear, so in the real world we would also consider fitting alternative models to see if there is something better out there to represent the relationship between tree volume and diameter. This is especially important if we want to use the model for prediction. </span>
<span id="cb26-430"><a href="#cb26-430"></a></span>
<span id="cb26-431"><a href="#cb26-431"></a></span>
<span id="cb26-432"><a href="#cb26-432"></a>::: callout-note</span>
<span id="cb26-433"><a href="#cb26-433"></a><span class="fu">## Checkpoint</span></span>
<span id="cb26-434"><a href="#cb26-434"></a></span>
<span id="cb26-435"><a href="#cb26-435"></a>You should now be able to test assumptions for simple linear regression and multiple linear regression. </span>
<span id="cb26-436"><a href="#cb26-436"></a></span>
<span id="cb26-437"><a href="#cb26-437"></a>We can now move onto interpretation!</span>
<span id="cb26-438"><a href="#cb26-438"></a></span>
<span id="cb26-439"><a href="#cb26-439"></a>:::</span>
<span id="cb26-440"><a href="#cb26-440"></a></span>
<span id="cb26-441"><a href="#cb26-441"></a><span class="fu">## Exercise 4: Evaluate model fit {.unnumbered}</span></span>
<span id="cb26-442"><a href="#cb26-442"></a></span>
<span id="cb26-443"><a href="#cb26-443"></a><span class="fu">### Part A --- Simple linear regression conclusion</span></span>
<span id="cb26-444"><a href="#cb26-444"></a></span>
<span id="cb26-447"><a href="#cb26-447"></a><span class="in">```{r}</span></span>
<span id="cb26-448"><a href="#cb26-448"></a><span class="fu">summary</span>(log_mod_slr)</span>
<span id="cb26-449"><a href="#cb26-449"></a></span>
<span id="cb26-450"><a href="#cb26-450"></a><span class="in">```</span></span>
<span id="cb26-451"><a href="#cb26-451"></a></span>
<span id="cb26-452"><a href="#cb26-452"></a><span class="ss">1. </span>State the model equation</span>
<span id="cb26-453"><a href="#cb26-453"></a></span>
<span id="cb26-454"><a href="#cb26-454"></a>Model equation is $log10(Volume) = 0.486 + 0.0706 \cdot Diameter$</span>
<span id="cb26-455"><a href="#cb26-455"></a></span>
<span id="cb26-456"><a href="#cb26-456"></a><span class="ss">2. </span>Interpretation of regression coefficients</span>
<span id="cb26-457"><a href="#cb26-457"></a></span>
<span id="cb26-458"><a href="#cb26-458"></a>For every 1 unit change in Diameter, we expect a 0.0706 increase in log10(Volume).</span>
<span id="cb26-459"><a href="#cb26-459"></a></span>
<span id="cb26-460"><a href="#cb26-460"></a><span class="ss">3. </span>P-value</span>
<span id="cb26-461"><a href="#cb26-461"></a></span>
<span id="cb26-462"><a href="#cb26-462"></a>The P-value for the slope coefficient is &lt; 0.001, meaning we reject our null hypothesis that the slope is equal to zero ($H_0: \beta_1 = 0$) and conclude that Diameter is a significant predictor of log10(Volume).</span>
<span id="cb26-463"><a href="#cb26-463"></a></span>
<span id="cb26-464"><a href="#cb26-464"></a><span class="ss">4. </span>R-squared</span>
<span id="cb26-465"><a href="#cb26-465"></a></span>
<span id="cb26-466"><a href="#cb26-466"></a>As we only have one predictor in the model, we can use the r^2^ value rather than the adjusted r^2^.</span>
<span id="cb26-467"><a href="#cb26-467"></a></span>
<span id="cb26-468"><a href="#cb26-468"></a>The r^2^ value is 0.94, which means that 94% of the variation in log10(Volume) can be explained by Diameter. This is a very strong r^2^ value, suggesting that Diameter alone is able to explain most of the variation in log10(Volume).</span>
<span id="cb26-469"><a href="#cb26-469"></a></span>
<span id="cb26-470"><a href="#cb26-470"></a></span>
<span id="cb26-471"><a href="#cb26-471"></a><span class="fu">### Part B --- Multiple linear regression conclusion</span></span>
<span id="cb26-472"><a href="#cb26-472"></a></span>
<span id="cb26-475"><a href="#cb26-475"></a><span class="in">```{r}</span></span>
<span id="cb26-476"><a href="#cb26-476"></a><span class="fu">summary</span>(log_mod_mlr)</span>
<span id="cb26-477"><a href="#cb26-477"></a></span>
<span id="cb26-478"><a href="#cb26-478"></a><span class="in">```</span></span>
<span id="cb26-479"><a href="#cb26-479"></a></span>
<span id="cb26-480"><a href="#cb26-480"></a></span>
<span id="cb26-481"><a href="#cb26-481"></a><span class="ss">1. </span>State the model equation</span>
<span id="cb26-482"><a href="#cb26-482"></a></span>
<span id="cb26-483"><a href="#cb26-483"></a>Model equation is:</span>
<span id="cb26-484"><a href="#cb26-484"></a></span>
<span id="cb26-485"><a href="#cb26-485"></a>$log10(Volume) = 0.0446 + 0.0631 \cdot Diameter + 0.0071 \cdot Height$</span>
<span id="cb26-486"><a href="#cb26-486"></a></span>
<span id="cb26-487"><a href="#cb26-487"></a><span class="ss">2. </span>Interpretation of regression coefficients</span>
<span id="cb26-488"><a href="#cb26-488"></a></span>
<span id="cb26-489"><a href="#cb26-489"></a>*Holding all other variables constant:* (very important to include this)</span>
<span id="cb26-490"><a href="#cb26-490"></a></span>
<span id="cb26-491"><a href="#cb26-491"></a><span class="ss">* </span>For every 1 unit change in Diameter, we expect a 0.0631 increase in log10(Volume);</span>
<span id="cb26-492"><a href="#cb26-492"></a></span>
<span id="cb26-493"><a href="#cb26-493"></a><span class="ss">* </span>For every 1 unit change in Height, we expect a 0.0071 increase in log10(Volume).</span>
<span id="cb26-494"><a href="#cb26-494"></a></span>
<span id="cb26-495"><a href="#cb26-495"></a></span>
<span id="cb26-496"><a href="#cb26-496"></a><span class="ss">3. </span>P-value</span>
<span id="cb26-497"><a href="#cb26-497"></a></span>
<span id="cb26-498"><a href="#cb26-498"></a>When assessing the p-values, we must consider the p-value associated with each partial regression coefficient, as well as the overall model.</span>
<span id="cb26-499"><a href="#cb26-499"></a></span>
<span id="cb26-500"><a href="#cb26-500"></a></span>
<span id="cb26-501"><a href="#cb26-501"></a>a. Relationship between Diameter and log10(Volume):</span>
<span id="cb26-502"><a href="#cb26-502"></a></span>
<span id="cb26-503"><a href="#cb26-503"></a>The P-value for the partial regression coefficient is &lt; 0.001, meaning we reject our null hypothesis that the slope is equal to zero ($H_0: \beta_1 = 0$) and conclude that Diameter is a significant predictor of log10(Volume).</span>
<span id="cb26-504"><a href="#cb26-504"></a></span>
<span id="cb26-505"><a href="#cb26-505"></a>b. Relationship between Height and log10(Volume):</span>
<span id="cb26-506"><a href="#cb26-506"></a></span>
<span id="cb26-507"><a href="#cb26-507"></a>The P-value for the partial regression coefficient is &lt; 0.001, meaning we reject our null hypothesis that the slope is equal to zero ($H_0: \beta_2 = 0$) and conclude that Height is also a significant predictor of log10(Volume).</span>
<span id="cb26-508"><a href="#cb26-508"></a></span>
<span id="cb26-509"><a href="#cb26-509"></a>c. Overall model:</span>
<span id="cb26-510"><a href="#cb26-510"></a></span>
<span id="cb26-511"><a href="#cb26-511"></a>The P-value for the model is &lt; 0.001, indicating that at least one slope is not equal to zero. This means we reject our null hypothesis that all partial slopes are equal to zero ($$H_0 : \beta_1 = \beta_2 = 0$$) and conclude that our model is significant.</span>
<span id="cb26-512"><a href="#cb26-512"></a></span>
<span id="cb26-513"><a href="#cb26-513"></a></span>
<span id="cb26-514"><a href="#cb26-514"></a><span class="ss">4. </span>R-squared</span>
<span id="cb26-515"><a href="#cb26-515"></a></span>
<span id="cb26-516"><a href="#cb26-516"></a>As we have more than one predictor in the model, we will need to use the adjusted r^2^. We will cover the reason for this in next week's lecture.</span>
<span id="cb26-517"><a href="#cb26-517"></a></span>
<span id="cb26-518"><a href="#cb26-518"></a>The adjusted r^2^ value is 0.97, which means that 97% of the variation in log10(Volume) can be explained by our model. This is a very strong r^2^ value. Although there was some correlation between Diameter and Height in our EDA, the VIFs from our diagnostics were low, so collinearity is unlikely to be influencing our model.</span>
<span id="cb26-519"><a href="#cb26-519"></a></span>
<span id="cb26-520"><a href="#cb26-520"></a></span>
<span id="cb26-521"><a href="#cb26-521"></a>::: callout-note</span>
<span id="cb26-522"><a href="#cb26-522"></a><span class="fu">## Checkpoint</span></span>
<span id="cb26-523"><a href="#cb26-523"></a></span>
<span id="cb26-524"><a href="#cb26-524"></a>You should now be able to interpret the summary output of a fitted simple and multiple linear regression, including the model equation, the regression coefficients, the p-values and the (adjusted) r-squared. You should also be able to explain why multiple linear regression uses the adjusted r-squared rather than the r-squared, and why the interpretation of a partial regression coefficient always requires the phrase "holding all other variables constant".</span>
<span id="cb26-525"><a href="#cb26-525"></a></span>
<span id="cb26-526"><a href="#cb26-526"></a>:::</span>
<span id="cb26-527"><a href="#cb26-527"></a></span>
<span id="cb26-528"><a href="#cb26-528"></a></span>
<span id="cb26-529"><a href="#cb26-529"></a></span>
<span id="cb26-530"><a href="#cb26-530"></a></span>
<span id="cb26-531"><a href="#cb26-531"></a></span>
<span id="cb26-532"><a href="#cb26-532"></a><span class="fu">## Wrap-up {.unnumbered}</span></span>
<span id="cb26-533"><a href="#cb26-533"></a></span>
<span id="cb26-534"><a href="#cb26-534"></a>In this tutorial, we have walked through the processes for simple and multiple linear regression, including how to fit models, check assumptions and how to interpret the output. You will hopefully now be able to recall key differences between the two types of models, which will help direct your analysis. </span>
<span id="cb26-535"><a href="#cb26-535"></a></span>
<span id="cb26-536"><a href="#cb26-536"></a>You will now apply these skills in the lab. If you have any questions please reach out to your tutors. </span>
<span id="cb26-537"><a href="#cb26-537"></a></span>
<span id="cb26-538"><a href="#cb26-538"></a><span class="fu">### Example exam questions</span></span>
<span id="cb26-539"><a href="#cb26-539"></a></span>
<span id="cb26-540"><a href="#cb26-540"></a><span class="ss">1. </span>Describe 3 key differences between simple linear regression and multiple linear regression. </span>
<span id="cb26-541"><a href="#cb26-541"></a></span>
<span id="cb26-542"><a href="#cb26-542"></a><span class="ss">2. </span>Describe how we would check the assumptions of a multiple linear regression. What would we do if we found that one of the assumptions was violated?</span>
<span id="cb26-543"><a href="#cb26-543"></a></span>
<span id="cb26-544"><a href="#cb26-544"></a><span class="ss">3.  </span>If you fitted a multiple linear regression and only one predictor was significant, would you still expect the model to be significant? Justify your answer (it may help to recall the hypotheses for MLR).</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>The University of Sydney</p>
</div>
  </div>
</footer>




</body></html>