<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="The University of Sydney">

<title>Lab 5 - Experimental Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d2800b5aef52857891e752670e942548.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-d61f110efc67b49214fed019bbcb8369.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d61f110efc67b49214fed019bbcb8369.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-d61f110efc67b49214fed019bbcb8369.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.js"></script>
<link href="../../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #000;
      }

      .quarto-title-block .quarto-title-banner {
        color: #000;
background: white;
      }
</style><noscript>
  <style>
    section.level2 { display: block !important; }
  </style>
</noscript>
<script>window.QUARTO_PROGRESSIVE_SECTIONS = true;</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../site_libs/quarto-contrib/quarto-project/sandstone/assets/styles.css">
</head>

<body class="floating quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Lab 5 - Experimental Design</h1>
            <p class="subtitle lead">ENVX2001 Applied Statistical Methods</p>
                  <div>
        <div class="description">
          The University of Sydney
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">Semester 1, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercise-1---randomisation-for-a-crd-using-r-walk-through" id="toc-exercise-1---randomisation-for-a-crd-using-r-walk-through" class="nav-link active" data-scroll-target="#exercise-1---randomisation-for-a-crd-using-r-walk-through">Exercise 1 - Randomisation for a CRD using R (Walk-through)</a>
  <ul class="collapse">
  <li><a href="#question-1.1" id="toc-question-1.1" class="nav-link" data-scroll-target="#question-1.1">Question 1.1</a></li>
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution">Solution</a></li>
  <li><a href="#question-1.2" id="toc-question-1.2" class="nav-link" data-scroll-target="#question-1.2">Question 1.2</a></li>
  <li><a href="#solution-1" id="toc-solution-1" class="nav-link" data-scroll-target="#solution-1">Solution</a></li>
  <li><a href="#question-1.3" id="toc-question-1.3" class="nav-link" data-scroll-target="#question-1.3">Question 1.3</a></li>
  <li><a href="#solution-2" id="toc-solution-2" class="nav-link" data-scroll-target="#solution-2">Solution</a></li>
  </ul></li>
  <li><a href="#exercise-2---the-balance-between-the-number-of-sampling-units-and-experimental-units-walk-through" id="toc-exercise-2---the-balance-between-the-number-of-sampling-units-and-experimental-units-walk-through" class="nav-link" data-scroll-target="#exercise-2---the-balance-between-the-number-of-sampling-units-and-experimental-units-walk-through">Exercise 2 - The balance between the number of sampling units and experimental units (Walk-through)</a>
  <ul class="collapse">
  <li><a href="#question-2.1" id="toc-question-2.1" class="nav-link" data-scroll-target="#question-2.1">Question 2.1</a></li>
  <li><a href="#solution-3" id="toc-solution-3" class="nav-link" data-scroll-target="#solution-3">Solution</a></li>
  <li><a href="#question-2.2" id="toc-question-2.2" class="nav-link" data-scroll-target="#question-2.2">Question 2.2</a></li>
  <li><a href="#solution-4" id="toc-solution-4" class="nav-link" data-scroll-target="#solution-4">Solution</a></li>
  <li><a href="#question-2.3" id="toc-question-2.3" class="nav-link" data-scroll-target="#question-2.3">Question 2.3</a></li>
  <li><a href="#solution-5" id="toc-solution-5" class="nav-link" data-scroll-target="#solution-5">Solution</a></li>
  <li><a href="#question-2.4" id="toc-question-2.4" class="nav-link" data-scroll-target="#question-2.4">Question 2.4</a></li>
  <li><a href="#solution-6" id="toc-solution-6" class="nav-link" data-scroll-target="#solution-6">Solution</a></li>
  <li><a href="#solution-7" id="toc-solution-7" class="nav-link" data-scroll-target="#solution-7">Solution</a></li>
  <li><a href="#solution-8" id="toc-solution-8" class="nav-link" data-scroll-target="#solution-8">Solution</a></li>
  <li><a href="#solution-9" id="toc-solution-9" class="nav-link" data-scroll-target="#solution-9">Solution</a></li>
  <li><a href="#question-2.5" id="toc-question-2.5" class="nav-link" data-scroll-target="#question-2.5">Question 2.5</a></li>
  <li><a href="#solution-10" id="toc-solution-10" class="nav-link" data-scroll-target="#solution-10">Solution</a></li>
  <li><a href="#question-2.6" id="toc-question-2.6" class="nav-link" data-scroll-target="#question-2.6">Question 2.6</a></li>
  <li><a href="#solution-11" id="toc-solution-11" class="nav-link" data-scroll-target="#solution-11">Solution</a></li>
  </ul></li>
  <li><a href="#exercise-3---a-paired-t-test-generalises-to-a-one-way-anova-rcbd" id="toc-exercise-3---a-paired-t-test-generalises-to-a-one-way-anova-rcbd" class="nav-link" data-scroll-target="#exercise-3---a-paired-t-test-generalises-to-a-one-way-anova-rcbd">Exercise 3 - A paired t-test generalises to a one-way ANOVA – RCBD</a>
  <ul class="collapse">
  <li><a href="#question-3.1" id="toc-question-3.1" class="nav-link" data-scroll-target="#question-3.1">Question 3.1</a></li>
  <li><a href="#solution-12" id="toc-solution-12" class="nav-link" data-scroll-target="#solution-12">Solution</a></li>
  <li><a href="#question-3.2" id="toc-question-3.2" class="nav-link" data-scroll-target="#question-3.2">Question 3.2</a></li>
  <li><a href="#question-3.3" id="toc-question-3.3" class="nav-link" data-scroll-target="#question-3.3">Question 3.3</a></li>
  <li><a href="#solution-13" id="toc-solution-13" class="nav-link" data-scroll-target="#solution-13">Solution</a></li>
  </ul></li>
  <li><a href="#exercise-4---one-way-anova---rcbd" id="toc-exercise-4---one-way-anova---rcbd" class="nav-link" data-scroll-target="#exercise-4---one-way-anova---rcbd">Exercise 4 - One-way ANOVA - RCBD</a>
  <ul class="collapse">
  <li><a href="#question-4.1" id="toc-question-4.1" class="nav-link" data-scroll-target="#question-4.1">Question 4.1</a></li>
  <li><a href="#solution-14" id="toc-solution-14" class="nav-link" data-scroll-target="#solution-14">Solution</a></li>
  <li><a href="#question-4.2" id="toc-question-4.2" class="nav-link" data-scroll-target="#question-4.2">Question 4.2</a></li>
  <li><a href="#solution-15" id="toc-solution-15" class="nav-link" data-scroll-target="#solution-15">Solution</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab05-exp-designs.pdf"><i class="bi bi-file-pdf"></i>Typst (sandstone)</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Learning outcomes
</div>
</div>
<div class="callout-body-container callout-body">
<p>At the end of this lab students should be able to:</p>
<ul>
<li><p>distinguish between sampling units and experimental units;</p></li>
<li><p>use R to generate randomisations for CRDs and RCBDs;</p></li>
<li><p>use R to analyse experiments with blocking, and assess the usefulness of blocking.</p></li>
</ul>
<p>All of the data for this lab is in the <strong>Data5.xlsx</strong> file.</p>
</div>
</div>
<section id="exercise-1---randomisation-for-a-crd-using-r-walk-through" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1---randomisation-for-a-crd-using-r-walk-through">Exercise 1 - Randomisation for a CRD using R (Walk-through)</h2>
<p>Consider a glass house experiment conducted on a bench on which it was judged that the growing conditions would be consistent across the bench. The experimenter had five different smoked water treatments for assisting the germination of <em>Banksia</em> seeds. She had 50 dishes on which she could place seeds randomly selected from a uniform batch of <em>Banksia</em> seeds. The dishes were to be placed on the bench and each of the five water solutions allocated randomly to 10 of the dishes.</p>
<section id="question-1.1" class="level3 question">
<h3 class="anchored" data-anchor-id="question-1.1">Question 1.1</h3>
<p><em>(i)</em> What would the degrees of freedom be in a corresponding ANOVA table?</p>
</section>
<section id="solution" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution">Solution</h3>
<ul>
<li><p>Treatment df = t – 1 = 5 – 1 = 4</p></li>
<li><p>Residual df = N – t = 50 – 5 = 45</p></li>
<li><p>Total df = N – 1 = 50 – 1 = 49</p></li>
</ul>
</section>
<section id="question-1.2" class="level3 question">
<h3 class="anchored" data-anchor-id="question-1.2">Question 1.2</h3>
<p><em>(ii)</em> Suppose that Treatment 1 was a control. In situations where the comparisons of interest are of the other treatments (2 to 5) with the control, and not amongst the other treatments, it can be advantageous to increase the number of control replicates to 20. What are the degrees of freedom in the corresponding ANOVA table?</p>
</section>
<section id="solution-1" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-1">Solution</h3>
<ul>
<li><p>Treatment df = t – 1 = 5 – 1 = 4</p></li>
<li><p>Residual df = N – t = 60 – 5 = 55</p></li>
<li><p>Total df = N – 1 = 60 – 1 = 59</p></li>
</ul>
</section>
<section id="question-1.3" class="level3 question">
<h3 class="anchored" data-anchor-id="question-1.3">Question 1.3</h3>
<p><em>(iii)</em> The formula for standard error of the difference (SED) is:</p>
<p><span class="math inline">SED=\sqrt{Resid\ MS\left(\frac{1}{n_1}+\frac{1}{n_2}\right)}</span>.</p>
<p>Given the SED formula, what percentage improvement (i.e.&nbsp;reduction) has been achieved for the SED between Treatment 1 and 2 when there are equal replicates <em>(i)</em> versus unequal replicates <em>(ii)</em>? Assume the Residual MS is a constant.</p>
</section>
<section id="solution-2" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-2">Solution</h3>
<p>For the equal replicate design:</p>
<p><span class="math inline">SED=\sqrt{Resid\ MS\left(\frac{1}{10}+\frac{1}{10}\right)}\approx0.447\times\sqrt{Resid\ MS}</span>.</p>
<p>For the second design:</p>
<p><span class="math inline">SED=\sqrt{Resid\ MS\left(\frac{1}{20}+\frac{1}{10}\right)}\approx0.387\times\sqrt{Resid\ MS}</span>.</p>
<p>So SED(extra control rep) / SED(equal rep) = 0.387 / 0.447 = 0.866, i.e.&nbsp;a 13.4% reduction in the SED.</p>
</section>
</section>
<section id="exercise-2---the-balance-between-the-number-of-sampling-units-and-experimental-units-walk-through" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2---the-balance-between-the-number-of-sampling-units-and-experimental-units-walk-through">Exercise 2 - The balance between the number of sampling units and experimental units (Walk-through)</h2>
<p>Horticulturalists have been studying the nutrient requirements of lettuce growing in a sand medium; in particular they are looking at the nitrate concentration in leaf petioles in response to varying applied nitrogen nutrient levels (5, 11, 18 and 32 mmol/L). Lettuce plants are grown in separate pots, so different nitrogen levels may be applied to individual pots, and one or more leaves sampled per plant. They are also interested in optimising their experimental protocol for future studies; consequently they conducted five separate experiments where they sampled different number of leaves per plant, and differing number of plants, but kept the total number of leaves sampled at 128 in each experiment. The experiments were conducted as follows:</p>
<ul>
<li><p>Experiment 1: 16 leaves per plant; 2 plants per treatment;</p></li>
<li><p>Experiment 2: 8 leaves per plant; 4 plants per treatment;</p></li>
<li><p>Experiment 3: 4 leaves per plant; 8 plants per treatment;</p></li>
<li><p>Experiment 4: 2 leaves per plant; 16 plants per treatment;</p></li>
<li><p>Experiment 5: 1 leaf per plant; 32 plants per treatment.</p></li>
</ul>
<p>Similar lettuce plants were used across all five experiments, and in all cases, a CRD was used to allocate the plants amongst the treatments. The datasets are located in the <em>Data5.xlsx</em> file. There are separate sheets for each Experiment called <em>Experiment1</em>, <em>Experiment2</em>, etc.</p>
<section id="question-2.1" class="level3 question">
<h3 class="anchored" data-anchor-id="question-2.1">Question 2.1</h3>
<p><em>(i)</em> What are the experimental units and what are the sampling units in the above experiments. For each experiment, how many experimental units and how many sampling units are used?</p>
</section>
<section id="solution-3" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-3">Solution</h3>
<p>The experimental unit is the plant, and the sampling unit is the leaf on the plant. All experiments have 128 sampling units (leaves). However, the number of experimental units varies, and is: Experiment 1: 8; Experiment 2: 16; Experiment 3: 32; Experiment 4: 64; and Experiment 5: 128.</p>
</section>
<section id="question-2.2" class="level3 question">
<h3 class="anchored" data-anchor-id="question-2.2">Question 2.2</h3>
<p><em>(ii)</em> When there are multiple sampling units per experimental unit, in simple situations (as is here), an appropriate method is simply to average the responses over all the sampling units belonging to an experimental unit, and analyse these. So in this case, we need to average the observed nitrate values over all the leaves in the plant. The code below shows how to do this using a function called <code>rowMeans</code> which finds the average in a row across multiple columns. Here we do this for <em>Experiment1</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="solution-4" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-4">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>exp1<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data/Data5.xlsx"</span>,<span class="at">sheet=</span><span class="st">"Experiment1"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>exp1<span class="sc">$</span>treatment<span class="ot">&lt;-</span><span class="fu">as.factor</span>(exp1<span class="sc">$</span>treatment)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>exp1<span class="sc">$</span>response<span class="ot">&lt;-</span><span class="fu">rowMeans</span>(exp1[,<span class="dv">3</span><span class="sc">:</span><span class="dv">18</span>])</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(exp1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [8 × 19] (S3: tbl_df/tbl/data.frame)
 $ treatment: Factor w/ 4 levels "N1","N2","N3",..: 1 1 2 2 3 3 4 4
 $ plant    : num [1:8] 1 2 3 4 5 6 7 8
 $ leaf1    : num [1:8] 2.46 1.73 3.31 2.49 2.4 2.6 3.06 2.23
 $ leaf2    : num [1:8] 2.45 1.3 2.5 2.73 2.56 2.42 1.95 2.39
 $ leaf3    : num [1:8] 3.24 2.37 2.02 2.32 1.67 2.48 2.38 2.69
 $ leaf4    : num [1:8] 2.36 1.46 1.97 1.54 1.78 2.3 1.93 2.4
 $ leaf5    : num [1:8] 3.17 1.52 2.46 2.5 2 2.09 1.32 1.74
 $ leaf6    : num [1:8] 2.87 1.99 1.52 2.62 3.32 1.66 1.87 2.84
 $ leaf7    : num [1:8] 2.39 2.79 2.07 2.71 1.75 2.46 2.42 2.36
 $ leaf8    : num [1:8] 2.94 2.03 1.68 1.92 2.49 2.68 2.22 3.3
 $ leaf9    : num [1:8] 2.76 2.23 2.68 3.07 2.21 2.07 2.38 1.62
 $ leaf10   : num [1:8] 3 2.17 1.45 2.48 2.33 1.75 2.76 1.82
 $ leaf11   : num [1:8] 2.54 2.74 1.96 2.15 1.46 2.61 2.04 3.03
 $ leaf12   : num [1:8] 3.19 1.36 2.26 2.73 2.2 2.63 2.07 3.66
 $ leaf13   : num [1:8] 3.03 1.45 1.94 2.22 1.61 2.08 2.09 4.03
 $ leaf14   : num [1:8] 2.42 1.19 2.38 2.37 2.6 3.44 2.18 1.59
 $ leaf15   : num [1:8] 2.68 1.12 2.66 1.75 1.3 2.46 2.18 2.81
 $ leaf16   : num [1:8] 2.56 0.77 1.85 1.49 1.61 2.5 1.95 2.27
 $ response : num [1:8] 2.75 1.76 2.17 2.32 2.08 ...</code></pre>
</div>
</div>
</section>
<section id="question-2.3" class="level3 question">
<h3 class="anchored" data-anchor-id="question-2.3">Question 2.3</h3>
<p><em>(iii)</em> Perform a one-way ANOVA on these average data. (It will also be helpful to obtain the treatment means using the <code>emmeans</code> function, as done in previous topics. What are your conclusions about the effect of varying applied nitrogen levels? You don’t have to look at post-hoc tests, just examine the F-test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="solution-5" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-5">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">aov</span>(response<span class="sc">~</span>treatment,<span class="at">data=</span>exp1)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
treatment    3 0.0208 0.00693   0.045  0.986
Residuals    4 0.6186 0.15466               </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod1,<span class="st">"treatment"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean    SE df lower.CL upper.CL
 N1          2.26 0.278  4     1.49     3.03
 N2          2.24 0.278  4     1.47     3.02
 N3          2.23 0.278  4     1.46     3.01
 N4          2.36 0.278  4     1.59     3.13

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Conclusion: There are no significant differences in mean nitrate level across the four nitrogen treatment groups (F = 0.045; df = 3,4; P = 0.99).</p>
</section>
<section id="question-2.4" class="level3 question">
<h3 class="anchored" data-anchor-id="question-2.4">Question 2.4</h3>
<p><em>(iV)</em> Repeat this for Experiments 2 to 5. What are your conclusions in each experiment?</p>
</section>
<p>Experiment 2: 8 leaves per plant, 4 plants per treatment</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="solution-6" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-6">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>exp2<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data/Data5.xlsx"</span>,<span class="at">sheet=</span><span class="st">"Experiment2"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>exp2<span class="sc">$</span>treatment<span class="ot">&lt;-</span><span class="fu">as.factor</span>(exp2<span class="sc">$</span>treatment)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>exp2<span class="sc">$</span>response<span class="ot">&lt;-</span><span class="fu">rowMeans</span>(exp2[,<span class="dv">3</span><span class="sc">:</span><span class="dv">10</span>])</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>mod2<span class="ot">&lt;-</span><span class="fu">aov</span>(response<span class="sc">~</span>treatment,<span class="at">data=</span>exp2)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
treatment    3 0.3042  0.1014   0.911  0.465
Residuals   12 1.3360  0.1113               </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod2,<span class="st">"treatment"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean    SE df lower.CL upper.CL
 N1          1.96 0.167 12     1.60     2.33
 N2          2.13 0.167 12     1.76     2.49
 N3          2.35 0.167 12     1.99     2.71
 N4          2.11 0.167 12     1.75     2.47

Confidence level used: 0.95 </code></pre>
</div>
</div>
</section>
<p>Experiment 3: 4 leaves per plant, 8 plants per treatment</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="solution-7" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-7">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>exp3<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data/Data5.xlsx"</span>,<span class="at">sheet=</span><span class="st">"Experiment3"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>exp3<span class="sc">$</span>treatment<span class="ot">&lt;-</span><span class="fu">as.factor</span>(exp3<span class="sc">$</span>treatment)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>exp3<span class="sc">$</span>response<span class="ot">&lt;-</span><span class="fu">rowMeans</span>(exp3[,<span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>])</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>mod3<span class="ot">&lt;-</span><span class="fu">aov</span>(response<span class="sc">~</span>treatment,<span class="at">data=</span>exp3)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)   
treatment    3  1.889  0.6296   5.825 0.00318 **
Residuals   28  3.026  0.1081                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod3,<span class="st">"treatment"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean    SE df lower.CL upper.CL
 N1          1.92 0.116 28     1.68     2.16
 N2          2.23 0.116 28     1.99     2.47
 N3          2.44 0.116 28     2.21     2.68
 N4          2.56 0.116 28     2.32     2.80

Confidence level used: 0.95 </code></pre>
</div>
</div>
</section>
<p>Experiment 4: 2 leaves per plant, 16 plants per treatment</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="solution-8" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-8">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>exp4<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data/Data5.xlsx"</span>,<span class="at">sheet=</span><span class="st">"Experiment4"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>exp4<span class="sc">$</span>treatment<span class="ot">&lt;-</span><span class="fu">as.factor</span>(exp4<span class="sc">$</span>treatment)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>exp4<span class="sc">$</span>response<span class="ot">&lt;-</span><span class="fu">rowMeans</span>(exp4[,<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>])</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>mod4<span class="ot">&lt;-</span><span class="fu">aov</span>(response<span class="sc">~</span>treatment,<span class="at">data=</span>exp4)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)   
treatment    3  4.136  1.3787   5.761 0.00157 **
Residuals   60 14.357  0.2393                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod4,<span class="st">"treatment"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean    SE df lower.CL upper.CL
 N1          2.03 0.122 60     1.79     2.27
 N2          2.11 0.122 60     1.87     2.36
 N3          2.15 0.122 60     1.91     2.40
 N4          2.68 0.122 60     2.43     2.92

Confidence level used: 0.95 </code></pre>
</div>
</div>
</section>
<p>Experiment 5: 1 leaf per plant, 32 plants per treatment. Note, no averaging required as sampling unit = experimental unit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="solution-9" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-9">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>exp5<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data/Data5.xlsx"</span>,<span class="at">sheet=</span><span class="st">"Experiment5"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>exp5<span class="sc">$</span>treatment<span class="ot">&lt;-</span><span class="fu">as.factor</span>(exp5<span class="sc">$</span>treatment)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>exp5<span class="sc">$</span>response<span class="ot">&lt;-</span>exp5<span class="sc">$</span>leaf1</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>mod5<span class="ot">&lt;-</span><span class="fu">aov</span>(response<span class="sc">~</span>treatment,<span class="at">data=</span>exp5)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)  
treatment     3   2.97  0.9915   3.219 0.0251 *
Residuals   124  38.19  0.3080                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(mod5,<span class="st">"treatment"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> treatment emmean     SE  df lower.CL upper.CL
 N1          2.00 0.0981 124     1.81     2.20
 N2          2.14 0.0981 124     1.94     2.33
 N3          2.31 0.0981 124     2.12     2.51
 N4          2.40 0.0981 124     2.20     2.59

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>While Experiment 2 also did not indicate significant differences in mean nitrate level across the four nitrogen treatments, significant differences were detected in the subsequent experiments, particularly in Experiments 3 and 4. There is a trend of increasing mean nitrate concentrations with increasing nitrogen treatment, indicating a dose-response relationship.</p>
</section>
<section id="question-2.5" class="level3 question">
<h3 class="anchored" data-anchor-id="question-2.5">Question 2.5</h3>
<p><em>(v)</em> Summarise the results in terms of the balance between sampling plants versus leaves, and what recommendations would you make for future studies?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="solution-10" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-10">Solution</h3>
<p>With a fixed number of leaves (sampling units), increasing the number of plants and reducing the number of leaves sampled per plant results in an increased significance for the treatment effect being detected. However, there is evidence that only sampling one leaf per plant results in a moderate decline in the significance levels. These findings are seen when either the Residual MS, F or P-values are used to make this assessment. So for this scheme, it would be recommended to use Experiment 3 or Experiment 4 protocols. Note that the standard errors of means (SE) also decline with increasing plants per treatments, though this changes little with eight or more.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 26%">
<col style="width: 21%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Experiment</th>
<th style="text-align: right;">Plants_Per_Treatment</th>
<th style="text-align: right;">Leaves_Per_Plant</th>
<th style="text-align: right;">Resid_MS</th>
<th style="text-align: right;">F_Stat</th>
<th style="text-align: right;">P_Value</th>
<th style="text-align: right;">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.155</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.986</td>
<td style="text-align: right;">0.278</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.111</td>
<td style="text-align: right;">0.91</td>
<td style="text-align: right;">0.465</td>
<td style="text-align: right;">0.167</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.108</td>
<td style="text-align: right;">5.82</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.116</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">5.76</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.122</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.308</td>
<td style="text-align: right;">3.22</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.098</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="question-2.6" class="level3 question">
<h3 class="anchored" data-anchor-id="question-2.6">Question 2.6</h3>
<p><em>(vi)</em> There are two sources of random variation encountered in these experiments:</p>
<p>-variation between leaves within a plant; and</p>
<p>-variation between plants within the same treatment group.</p>
<p>How do you think your recommendations might change in <em>(iv)</em> if:</p>
<p>-there was (virtually) no variation between leaves within a plant; only between plants; or</p>
<p>-there was (virtually) no variation between plants, only variation between leaves within a plant.</p>
</section>
<section id="solution-11" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-11">Solution</h3>
<p>If there is virtually no variation between leaves within a plant, then just using one leaf per plant would be sufficient, so Experiment 5 would be the optimal protocol here.</p>
<p>If there is much leaf to leaf variation, but little between-plant variation, then it is best to increase the number of leaves sampled per plant, and use fewer plants. So Experiment 1 might be optimal here (but this would give the very minimal level of replication, so for a cautionary approach, Experiment 2 might be used).</p>
</section>
</section>
<section id="exercise-3---a-paired-t-test-generalises-to-a-one-way-anova-rcbd" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3---a-paired-t-test-generalises-to-a-one-way-anova-rcbd">Exercise 3 - A paired t-test generalises to a one-way ANOVA – RCBD</h2>
<p>Fifteen farms cooperated in a field trial in which a normal fattening ration for pigs (ration A) was compared with the same rations supplemented with a small trace of copper (ration B). Each farmer set up two pens of pigs, as similar as possible in all respects, and allocated the two rations at random, ration A to one pen and ration B to the other. The mean weight gains per pen (g/day) are stored in the two columns of the <strong>copper</strong> sheet in the <strong>Data5.xlsx</strong> file.</p>
<p>This description clearly suggests the design is an RCBD, with 15 farms but only 2 treatments. As we have seen, a paired design is the simplest form of RCBD. In this example we will not worry about model assumptions.</p>
<section id="question-3.1" class="level3 question">
<h3 class="anchored" data-anchor-id="question-3.1">Question 3.1</h3>
<p><em>(i)</em> Firstly analyse the data using a paired t-test. Assuming you read the data is as a data frame called <code>copper</code> the code is <code>t.test(x=copper$RationA,y=copper$RationB,paired=T)</code>. Interpret the results.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="solution-12" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-12">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>copper<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data/Data5.xlsx"</span>,<span class="at">sheet =</span> <span class="st">"copper"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(copper)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
   Farm RationA RationB
  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     1     422     531
2     2     526     467
3     3     476     558
4     4     499     585
5     5     422     472
6     6     503     522</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x=</span>copper<span class="sc">$</span>RationA,<span class="at">y=</span>copper<span class="sc">$</span>RationB,<span class="at">paired=</span>T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  copper$RationA and copper$RationB
t = -3.2545, df = 14, p-value = 0.005761
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -67.90951 -13.95716
sample estimates:
mean difference 
      -40.93333 </code></pre>
</div>
</div>
<p>Pigs fed Ration B (copper supplement) have a significantly higher weight gain than those on Ration A (P = 0.006). On average, the cupper supplemented pigs (B) have a weight gain of 41 g/day more than the control, but a 95% confidence interval for this difference is between 14.0 and 67.9 g/day more.</p>
</section>
<section id="question-3.2" class="level3 question">
<h3 class="anchored" data-anchor-id="question-3.2">Question 3.2</h3>
<p><em>(ii)</em> Next we will obtain an analysis of the data using ANOVA. To do this analysis however, you will first need to re-arrange the data set into a form suitable for ANOVA. That is, you will need a single column of weight gains, a column of treatment identifiers, and a column indicating the Farm number. The code below will do this for you:</p>
<ul>
<li><p><code>dat&lt;-stack(copper[,2:3])</code></p></li>
<li><p><code>farms&lt;-rep(c(1:15),times=2)</code></p></li>
<li><p><code>coppern&lt;-cbind(farms,dat)</code></p></li>
</ul>
<p>The first line stacks (using the <code>stack</code> function) the 2 columns of weight gain on top of each other (column name is <code>values</code>) and adds a column indicating which ration is associated with each weight gain value (column name is <code>ind</code>).</p>
<p>The second line repeats (using the <code>rep</code> function) the values of farm numbers twice so for each of the weight gains we have an associated farm.</p>
<p>The third line joins the two data frames together (using the <code>cbind</code> function) to create the new stacked dataset which can be used by the <code>aov</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(copper)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
   Farm RationA RationB
  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     1     422     531
2     2     526     467
3     3     476     558
4     4     499     585
5     5     422     472
6     6     503     522</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">stack</span>(copper[,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>])</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>farms<span class="ot">&lt;-</span><span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>),<span class="at">times=</span><span class="dv">2</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>coppern<span class="ot">&lt;-</span><span class="fu">cbind</span>(farms,dat)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(coppern)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   30 obs. of  3 variables:
 $ farms : int  1 2 3 4 5 6 7 8 9 10 ...
 $ values: num  422 526 476 499 422 503 445 449 299 517 ...
 $ ind   : Factor w/ 2 levels "RationA","RationB": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
</section>
<section id="question-3.3" class="level3 question">
<h3 class="anchored" data-anchor-id="question-3.3">Question 3.3</h3>
<p><em>(iii)</em> The general code for performing an 1-way anova with a randomised complete block design is:</p>
<p><code>aov(response~block+treatment,data=data)</code></p>
<p>In this example the <code>response</code> is the weight gain, <code>blocks</code> are farms and the <code>treatment</code> is ration. Your names will be different. Having obtained the analysis, check that the results from the ANOVA is identical to the paired t-test:</p>
<ul>
<li><p>the same <em>P</em>-value;</p></li>
<li><p>the same test statistic (though expressed as an <em>F</em>-statistic instead of a <em>t</em>-statistic, with <em>F</em> = <span class="math inline">t^2</span> to that from the paired <em>t</em>-test.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="solution-13" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-13">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>block.anova<span class="ot">&lt;-</span><span class="fu">aov</span>(values<span class="sc">~</span><span class="fu">as.factor</span>(farms)<span class="sc">+</span>ind,<span class="at">data=</span>coppern)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(block.anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: values
                 Df Sum Sq Mean Sq F value   Pr(&gt;F)   
as.factor(farms) 14  71524  5108.9   4.306 0.004963 **
ind               1  12567 12566.5  10.592 0.005761 **
Residuals        14  16610  1186.5                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Comparisons with paired t-test.</p>
<ul>
<li><p>P = 0.006 in both analyses</p></li>
<li><p><span class="math inline">t^2</span> = <span class="math inline">(–3.25)^2</span> = 10.59 = F</p></li>
<li><p>Residual df = 14 = df for t-test</p></li>
</ul>
</section>
</section>
<section id="exercise-4---one-way-anova---rcbd" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4---one-way-anova---rcbd">Exercise 4 - One-way ANOVA - RCBD</h2>
<p>Three diets for hamsters were tested for differences in weight gain after a specified period of time. Six inbred lines were used with three hamsters selected from each line. The three diets were assigned at random to the hamsters in each line. The data is in the <strong>hamsters</strong> sheet in the <strong>Data5.xlsx</strong> file.</p>
<section id="question-4.1" class="level3 question">
<h3 class="anchored" data-anchor-id="question-4.1">Question 4.1</h3>
<p><em>(i)</em> Are the mean weight gains the same across diets? Are any diets more or less effective than other diets? You will need to use the <code>emmeans</code> package and its <code>emmeans()</code> function. Read in the data and perform post-hoc tests.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="solution-14" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-14">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>hamster<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"data/Data5.xlsx"</span>,<span class="at">sheet=</span><span class="st">"hamster"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hamster)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Inbred_Line Wt_Gain  Diet
  &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;
1 A                18     1
2 B                16     1
3 C                17     1
4 D                19     1
5 E                12     1
6 F                13     1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>hamster<span class="sc">$</span>Diet<span class="ot">&lt;-</span><span class="fu">as.factor</span>(hamster<span class="sc">$</span>Diet)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>hamster<span class="sc">$</span>Inbred_Line<span class="ot">&lt;-</span><span class="fu">as.factor</span>(hamster<span class="sc">$</span>Inbred_Line)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>block.anova<span class="ot">&lt;-</span><span class="fu">aov</span>(Wt_Gain<span class="sc">~</span>Inbred_Line<span class="sc">+</span>Diet,<span class="at">data=</span>hamster)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(block.anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Wt_Gain
            Df Sum Sq Mean Sq F value   Pr(&gt;F)   
Inbred_Line  5 71.167  14.233  7.4912 0.003650 **
Diet         2 36.333  18.167  9.5614 0.004773 **
Residuals   10 19.000   1.900                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Perform post-hoc tests.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(block.anova, pairwise <span class="sc">~</span> Diet)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Diet emmean    SE df lower.CL upper.CL
 1      15.8 0.563 10     14.6     17.1
 2      13.0 0.563 10     11.7     14.3
 3      12.7 0.563 10     11.4     13.9

Results are averaged over the levels of: Inbred_Line 
Confidence level used: 0.95 

$contrasts
 contrast      estimate    SE df t.ratio p.value
 Diet1 - Diet2    2.833 0.796 10   3.560  0.0131
 Diet1 - Diet3    3.167 0.796 10   3.979  0.0067
 Diet2 - Diet3    0.333 0.796 10   0.419  0.9087

Results are averaged over the levels of: Inbred_Line 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>There are significant differences in mean weigh gain of hamsters amongst the three diets (F = 9.56; df = 2, 10; P = 0.005). Based on the post-hoc tests, hamsters fed diet 1 had a significantly higher weight gain than those fed diets 2 or 3, whereas there was no significant difference between weights for hamsters on Diets 2 and 3.</p>
</section>
<section id="question-4.2" class="level3 question">
<h3 class="anchored" data-anchor-id="question-4.2">Question 4.2</h3>
<p><em>(ii)</em> Re-run the analysis without blocking, i.e.&nbsp;as a CRD. Are the conclusions different? Would you use blocking in the future? What proportion of the variation was explained by blocking?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="solution-15" class="level3 ans">
<h3 class="anchored" data-anchor-id="solution-15">Solution</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>crd.anova<span class="ot">&lt;-</span><span class="fu">aov</span>(Wt_Gain<span class="sc">~</span>Diet,<span class="at">data=</span>hamster)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(crd.anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Wt_Gain
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
Diet       2 36.333 18.1667  3.0222 0.07892 .
Residuals 15 90.167  6.0111                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We now have a non-significant F-test. Based on Block SS in the original analysis value of 71.167, we can see that the majority of the Residual SS (90.167) in the CRD is from the between-block differences. By including the block effect through the RCBD we have dramatically reduced the Residual SS.</p>
<p>The proportion of variation explained by the Blocking is:</p>
<p><span class="math inline">\frac{Block\ SS}{Total\ SS}=\frac{71.167}{126.5}=0.56</span>.</p>
<p>Therefore 56% of the variation in the response is explained by the blocking. This is compelling evidence for using blocking in future versions of the experiment.</p>
</section>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Built using the SOLES Quarto handbook template</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>The University of Sydney</p>
</div>
  </div>
</footer>




</body></html>