<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="The University of Sydney">

<title>Lab 07</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d2800b5aef52857891e752670e942548.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9fa6dbbe6219e357c3a17d5a2c09c803.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-7278299327f02d2322d90678f67156e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.js"></script>
<link href="../../site_libs/quarto-contrib/progressive-sections-1.0.0/progressive-sections.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #000;
      }

      .quarto-title-block .quarto-title-banner {
        color: #000;
background: white;
      }
</style><noscript>
  <style>
    section.level2 { display: block !important; }
  </style>
</noscript>
<script>window.QUARTO_PROGRESSIVE_SECTIONS = true;</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../site_libs/quarto-contrib/quarto-project/sandstone/assets/styles.css">
</head>

<body class="floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Lab 07</h1>
            <p class="subtitle lead">ENVX2001 Applied Statistical Methods</p>
                  <div>
        <div class="description">
          The University of Sydney
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#welcome-to-week-7" id="toc-welcome-to-week-7" class="nav-link active" data-scroll-target="#welcome-to-week-7">Welcome to week 7!</a>
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning outcomes</a></li>
  <li><a href="#specific-goals" id="toc-specific-goals" class="nav-link" data-scroll-target="#specific-goals">Specific goals</a></li>
  <li><a href="#preparation" id="toc-preparation" class="nav-link" data-scroll-target="#preparation">Preparation</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#comparing-diagnostic-plots" id="toc-comparing-diagnostic-plots" class="nav-link" data-scroll-target="#comparing-diagnostic-plots">Comparing diagnostic plots</a></li>
  <li><a href="#downloads" id="toc-downloads" class="nav-link" data-scroll-target="#downloads">Downloads</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#simple-linear-regression-30-min" id="toc-simple-linear-regression-30-min" class="nav-link" data-scroll-target="#simple-linear-regression-30-min">1. Simple linear regression (~30 min)</a>
  <ul class="collapse">
  <li><a href="#analysis-for-bird-abundance-and-area-of-forest-patch" id="toc-analysis-for-bird-abundance-and-area-of-forest-patch" class="nav-link" data-scroll-target="#analysis-for-bird-abundance-and-area-of-forest-patch">Analysis for bird abundance and area of forest patch</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a>
  <ul class="collapse">
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link" data-scroll-target="#exercise-1">Exercise 1</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#multiple-linear-regression-30-min" id="toc-multiple-linear-regression-30-min" class="nav-link" data-scroll-target="#multiple-linear-regression-30-min">2. Multiple linear regression (~30 min)</a>
  <ul class="collapse">
  <li><a href="#analysis-for-runoff-and-precipitation-in-bishop-california" id="toc-analysis-for-runoff-and-precipitation-in-bishop-california" class="nav-link" data-scroll-target="#analysis-for-runoff-and-precipitation-in-bishop-california">Analysis for runoff and precipitation in Bishop, California</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a>
  <ul class="collapse">
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#closing-thoughts" id="toc-closing-thoughts" class="nav-link" data-scroll-target="#closing-thoughts">Closing thoughts</a>
  <ul class="collapse">
  <li><a href="#attribution" id="toc-attribution" class="nav-link" data-scroll-target="#attribution">Attribution</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab07-regression-modelling.pdf"><i class="bi bi-file-pdf"></i>Typst (sandstone)</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<section id="welcome-to-week-7" class="level1">
<h1>Welcome to week 7!</h1>
<p>This week’s lab will give you some practice fitting and interpreting Simple Linear Regression (SLR) and Multiple Linear Regression (MLR) models.</p>
<p>This will prepare you for next week’s content where we will seek to improve our models, and then in week 9 we will use improved models for prediction.</p>
<section id="learning-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcomes">Learning outcomes</h2>
<p>This module links to the following unit learning outcomes:</p>
<ul>
<li><p>LO3. demonstrate proficiency in the use or the statistical programming language R to apply an ANOVA and fit regression models to experimental data</p></li>
<li><p>LO5. interpret the output and understand conceptually how its derived of a regression, ANOVA and multivariate analysis that have been calculated by R</p></li>
<li><p>LO6. write statistical and modelling results as part of a scientific report</p></li>
</ul>
<p>In this lab, we will learn how to:</p>
<ol type="1">
<li>Fit and interpret simple linear regression (SLR) models</li>
<li>Fit and interpret multiple linear regression (MLR) models</li>
<li>Assess model assumptions and apply transformations when needed</li>
<li>Evaluate and compare model fit statistics</li>
</ol>
</section>
<section id="specific-goals" class="level2">
<h2 class="anchored" data-anchor-id="specific-goals">Specific goals</h2>
<p>By the end of this lab, you should be able to:</p>
<ul class="task-list">
<li><label><input type="checkbox">Fit a simple linear regression model</label></li>
<li><label><input type="checkbox">Assess model assumptions and apply transformations when needed</label></li>
<li><label><input type="checkbox">Interpret model parameters and fit statistics</label></li>
<li><label><input type="checkbox">Fit a multiple linear regression model</label></li>
<li><label><input type="checkbox">Assess model assumptions, including collinearity between predictor variables</label></li>
<li><label><input type="checkbox">Determine the most suitable fit statistics for a multiple linear regression model</label></li>
<li><label><input type="checkbox">Write a conclusion on your findings</label></li>
</ul>
</section>
<section id="preparation" class="level2">
<h2 class="anchored" data-anchor-id="preparation">Preparation</h2>
<p>Please work on these exercises by creating your own Quarto file. You are welcome to write your responses up in the style of a report.</p>
<section id="packages" class="level3">
<h3 class="anchored" data-anchor-id="packages">Packages</h3>
<p>This lab uses <code>tidyverse</code>, <code>readxl</code>, <code>moments</code>, <code>psych</code>, and <code>performance</code>. Install any you are missing by running the following <strong>in the console</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"readxl"</span>, <span class="st">"moments"</span>, <span class="st">"psych"</span>, <span class="st">"performance"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If a package is already installed, R will simply reinstall it — no harm done.</p>
</section>
<section id="comparing-diagnostic-plots" class="level3">
<h3 class="anchored" data-anchor-id="comparing-diagnostic-plots">Comparing diagnostic plots</h3>
<p>This package is really good for checking your models. For this lab, we will focus on the <code>check_model()</code> function from the <code>performance</code> package, which produces diagnostic plots that are easier to read than the base R <code>plot()</code> output. Compare the two approaches below to see why we recommend it:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href=""><code>plot()</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href=""><code>check_model()</code> from <code>performance</code></a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">plot</span>(iris_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb4-2"><a href="#cb4-2"></a><span class="fu">check_model</span>(iris_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="downloads" class="level3">
<h3 class="anchored" data-anchor-id="downloads">Downloads</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>File</th>
<th>Used in</th>
<th>Download</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Loyn_SLR.xlsx</code></td>
<td>Exercise 1</td>
<td><a href="data/Loyn_SLR.xlsx">Download</a></td>
</tr>
<tr class="even">
<td><code>california_streamflow.xlsx</code></td>
<td>Exercise 2</td>
<td><a href="data/california_streamflow.xlsx">Download</a></td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="simple-linear-regression-30-min" class="level1 page-columns page-full">
<h1>1. Simple linear regression (~30 min)</h1>
<p>Simple linear regression is a statistical method that allows us to investigate the relationship between two continuous variables. It is a powerful tool for understanding how one variable (the predictor) influences another variable (the response). Often a simple linear regression is the most appropriate model, so it is worth understanding.</p>
<p>Key points to follow:</p>
<ul>
<li>State the model and hypotheses</li>
<li>Conduct exploratory data analysis (EDA) to understand the data and relationships between variables. This includes correlation analysis and scatterplots.</li>
<li>Fit the model</li>
<li>Check the assumptions of the model and apply transformations if needed</li>
<li>Interpret the model parameters and fit statistics</li>
</ul>
<p>Good luck!</p>
<section id="analysis-for-bird-abundance-and-area-of-forest-patch" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="analysis-for-bird-abundance-and-area-of-forest-patch">Analysis for bird abundance and area of forest patch</h2>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="images/pen_ash-mph8XzVCVkw-unsplash.jpg" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Kookaburra sitting on a branch, from Unsplash, by pen_ash.</figcaption>
</figure>
</div>
<p>Habitat fragmentation resulting from agriculture and urbanisation has increased the rate of wildlife population decline in Australia. You are a consultant and have been asked to investigate the influence of forest fragment size upon bird abundance. You have been provided with a dataset containing measurements of bird abundance and patch area from 56 different forest patches in Southeastern Victoria, Australia, and you want to know if there is a relationship between these two variables.</p>
<p>The data is in the <strong>Loyn_SLR.xlsx</strong> file.</p>
<p>Variables are as follows:</p>
<ul>
<li>ABUND: Bird abundance within each forest patch (number of birds)</li>
<li>AREA: Area of each forest patch (ha)</li>
</ul>
<p>Original data source: Loyn, R. H. (1987). Effects of patch area and habitat on bird abundances, species numbers, and tree health in fragmented Victorian forests. In <em>Nature Conservation: the role of remnants of native vegetation</em> eds.&nbsp;D.S. Saunders, G.W. Arnold, A.A. Burbridge, &amp;A.J.M. Hopkins, pp.&nbsp;65-77. Surrey Beatty and Sons.</p>
</section>
<section id="section" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="section"></h2>
<section id="exercise-1" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-1">Exercise 1</h3>
<p><em>(i)</em> Write out the statistical model for a simple linear regression and define it in terms of influence of forest patch area upon bird abundance. You can write it out in words and/or in mathematical notation.</p>
<p><em>(ii)</em> State the hypotheses you will be testing for the relationship between bird abundance and patch area.</p>
<p>Remember: Null hypothesis = no change, no slope, therefore no relationship.</p>
<p><em>(iii)</em> Conduct some exploratory data analysis upon your two variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots.</p>
<p><em>(iv)</em> Investigate the relationship between bird abundance and patch area. Describe the relationship, supported by values (correlation coefficient) and plots.</p>
<p><em>(v)</em> Fit a simple linear regression model to the data, with bird abundance as the response variable and patch area as the predictor variable.</p>
<p><em>(vi)</em> Check the assumptions of your model. Do you need to transform any variables?</p>
<p>Hint 1: you can use the the <code>check_model()</code> function from the <code>performance</code> package to check the assumptions of your model.</p>
<p>Hint 2: If you do choose to transform a variable you will need to refit the model and check the assumptions again.</p>
<p><em>(vii)</em> Provide a plot of your model and interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between bird abundance and patch area?</p>
<p><em>(viii)</em> Write a concluding statement on your findings.</p>
<p>Hint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.</p>
</section>
<section id="solution" class="level4 ans page-columns page-full">
<h4 class="anchored" data-anchor-id="solution">Solution</h4>
<section id="i-write-out-the-statistical-model-for-a-simple-linear-regression-and-define-it-in-terms-of-influence-of-forest-fragment-size-upon-bird-abundance." class="level5">
<h5 class="anchored" data-anchor-id="i-write-out-the-statistical-model-for-a-simple-linear-regression-and-define-it-in-terms-of-influence-of-forest-fragment-size-upon-bird-abundance."><em>(i)</em> Write out the statistical model for a simple linear regression and define it in terms of influence of forest fragment size upon bird abundance.</h5>
<p>The statistical model for a simple linear regression is:</p>
<p><span class="math display">
y_{i} = \beta_0 + \beta_1x_i + \epsilon_{i}
</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">y_{i}</span> is the response variable (abundance) for the <span class="math inline">i</span>th observation when the predictor X = <span class="math inline">x_i</span> (area of the patch)</li>
<li><span class="math inline">\beta_0</span> is the intercept where the regression line crosses the y-axis (the expected abundance when patch area is 0)</li>
<li><span class="math inline">\beta_1</span> is the slope of the regression line, which represents the change in abundance for a one-unit increase in patch area</li>
<li><span class="math inline">\epsilon_{i}</span> is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance</li>
</ul>
<p>OR if written in terms of the variables in our dataset, the model would be:</p>
<p><span class="math display">
Abundance = \beta_0 + \beta_1Area + \epsilon_{i}
</span></p>
</section>
<section id="ii-state-the-hypotheses-you-will-be-testing-for-the-relationship-between-bird-abundance-and-patch-area." class="level5">
<h5 class="anchored" data-anchor-id="ii-state-the-hypotheses-you-will-be-testing-for-the-relationship-between-bird-abundance-and-patch-area."><em>(ii)</em> State the hypotheses you will be testing for the relationship between bird abundance and patch area.</h5>
<p>Remember: Null hypothesis = no change, no slope, therefore no relationship.</p>
<p>The hypotheses for the relationship between bird abundance and patch area are:</p>
<p><span class="math display">H_0 : \beta_1 = 0</span> <span class="math display">H_0 : \beta_1 \neq 0</span> Where <span class="math inline">\beta_1</span> is the slope of the regression line and represents the change in abundance for a one-unit increase in patch area.</p>
</section>
<section id="iii-read-in-the-dataset-and-conduct-some-exploratory-data-analysis-upon-your-two-variables.-describe-the-spread-and-central-tendency-of-each-supported-by-values-summary-statistics-and-plots." class="level5 page-columns page-full">
<h5 class="anchored" data-anchor-id="iii-read-in-the-dataset-and-conduct-some-exploratory-data-analysis-upon-your-two-variables.-describe-the-spread-and-central-tendency-of-each-supported-by-values-summary-statistics-and-plots."><em>(iii)</em> Read in the dataset and conduct some exploratory data analysis upon your two variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots.</h5>
<p>Read in the data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Load library if needed</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-3"><a href="#cb5-3"></a></span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="co"># Import the data</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>loyn <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/Loyn_SLR.xlsx"</span>, <span class="st">"Loyn_SLR"</span>)</span>
<span id="cb5-6"><a href="#cb5-6"></a></span>
<span id="cb5-7"><a href="#cb5-7"></a><span class="co"># check</span></span>
<span id="cb5-8"><a href="#cb5-8"></a><span class="fu">glimpse</span>(loyn) <span class="co"># could also use str() or head() to look at the data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 56
Columns: 2
$ ABUND &lt;dbl&gt; 5.3, 2.0, 1.5, 17.1, 13.8, 14.1, 3.8, 2.2, 3.3, 3.0, 27.6, 1.8, …
$ AREA  &lt;dbl&gt; 0.1, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0,…</code></pre>
</div>
</div>
<p>We can see there are two variables, with 56 observations each. and both are numeric (coded as ‘dbl’ here, which is a type of numeric/continuous variable).</p>
<p>Summary statistics</p>
<p>I have calculated each summary statistic separately here to produce the output as a table. If you are exploring the data for yourself, you are welcome to use <code>summary()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">library</span>(moments) <span class="co"># gives us the skewness() function</span></span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a>Abundance <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="at">mean =</span> <span class="fu">mean</span>(loyn<span class="sc">$</span>ABUND),</span>
<span id="cb7-5"><a href="#cb7-5"></a>  <span class="at">median =</span> <span class="fu">median</span>(loyn<span class="sc">$</span>ABUND),</span>
<span id="cb7-6"><a href="#cb7-6"></a>  <span class="at">min =</span> <span class="fu">min</span>(loyn<span class="sc">$</span>ABUND),</span>
<span id="cb7-7"><a href="#cb7-7"></a>  <span class="at">max =</span> <span class="fu">max</span>(loyn<span class="sc">$</span>ABUND),</span>
<span id="cb7-8"><a href="#cb7-8"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(loyn<span class="sc">$</span>ABUND),</span>
<span id="cb7-9"><a href="#cb7-9"></a>  <span class="at">skewness =</span> <span class="fu">skewness</span>(loyn<span class="sc">$</span>ABUND)</span>
<span id="cb7-10"><a href="#cb7-10"></a>)</span>
<span id="cb7-11"><a href="#cb7-11"></a></span>
<span id="cb7-12"><a href="#cb7-12"></a>Area <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb7-13"><a href="#cb7-13"></a>  <span class="at">mean =</span> <span class="fu">mean</span>(loyn<span class="sc">$</span>AREA),</span>
<span id="cb7-14"><a href="#cb7-14"></a>  <span class="at">median =</span> <span class="fu">median</span>(loyn<span class="sc">$</span>AREA),</span>
<span id="cb7-15"><a href="#cb7-15"></a>  <span class="at">min =</span> <span class="fu">min</span>(loyn<span class="sc">$</span>AREA),</span>
<span id="cb7-16"><a href="#cb7-16"></a>  <span class="at">max =</span> <span class="fu">max</span>(loyn<span class="sc">$</span>AREA),</span>
<span id="cb7-17"><a href="#cb7-17"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(loyn<span class="sc">$</span>AREA),</span>
<span id="cb7-18"><a href="#cb7-18"></a>  <span class="at">skewness =</span> <span class="fu">skewness</span>(loyn<span class="sc">$</span>AREA)</span>
<span id="cb7-19"><a href="#cb7-19"></a>)</span>
<span id="cb7-20"><a href="#cb7-20"></a></span>
<span id="cb7-21"><a href="#cb7-21"></a>summary_loyn <span class="ot">=</span> <span class="fu">rbind</span>(Abundance, Area) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">1</span>)</span>
<span id="cb7-22"><a href="#cb7-22"></a></span>
<span id="cb7-23"><a href="#cb7-23"></a><span class="fu">kable</span>(summary_loyn, <span class="at">caption =</span> <span class="st">"Table 1. Summary statistics for bird abundance and area of forest patches"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1. Summary statistics for bird abundance and area of forest patches</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">skewness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Abundance</td>
<td style="text-align: right;">19.5</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">39.6</td>
<td style="text-align: right;">10.7</td>
<td style="text-align: right;">-0.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Area</td>
<td style="text-align: right;">69.3</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">1771.0</td>
<td style="text-align: right;">266.1</td>
<td style="text-align: right;">5.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li>Bird Abundance (aka number of birds counted)</li>
</ol>
<p>The mean bird abundance in forest patches is 19.5 and the median is 21.0 (Table 1). These are quite similar, suggesting a normal distribution. This is further supported by the skewness coefficient of -0.28, which is close to 0, and the relatively symmetrical boxplot (Fig. 1), indicating a fairly symmetric distribution.</p>
<p>Bird abundance ranges from a minimum of 1.5 to 39.6 birds and the standard deviation is 10.73, which indicates that there is quite a bit of variability in bird abundance across the patches. This is also evident in the wider interquartile range visible in the boxplot (fig.&nbsp;1).</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">ggplot</span>(loyn) <span class="sc">+</span> </span>
<span id="cb8-2"><a href="#cb8-2"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> ABUND)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Abundance"</span>,</span>
<span id="cb8-4"><a href="#cb8-4"></a>       <span class="at">y =</span> <span class="st">"Bird abundance (number of birds)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 1. Boxplot of bird abundance</figcaption>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Area of forest patches (in hectares, ha)</li>
</ol>
<p>The mean area is 69.3 ha (Table 1), which is very different to the median of 7.5 ha, suggesting a highly skewed distribution. This is further supported by the skewness coefficient of 5.5.</p>
<p>We can also see this high amount of variability in the standard deviation of 266.1, and the area ranging from 0.1 ha to 1771 ha. The skewness and high amount of variation is most likely a result of two outliers present, visible in the boxplot (Fig. 2).</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">ggplot</span>(loyn) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> AREA)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Area"</span>,</span>
<span id="cb9-4"><a href="#cb9-4"></a>       <span class="at">y =</span> <span class="st">"Area of forest patch (ha)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 2. Boxplot of area of forest patches (ha)</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="iv-investigate-the-relationship-between-bird-abundance-and-patch-area.-describe-the-relationship-supported-by-values-correlation-coefficient-and-plots." class="level5 page-columns page-full">
<h5 class="anchored" data-anchor-id="iv-investigate-the-relationship-between-bird-abundance-and-patch-area.-describe-the-relationship-supported-by-values-correlation-coefficient-and-plots."><em>(iv)</em> Investigate the relationship between bird abundance and patch area. Describe the relationship, supported by values (correlation coefficient) and plots.</h5>
<p>Calculate the correlation coefficient</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">cor</span>(loyn<span class="sc">$</span>AREA, loyn<span class="sc">$</span>ABUND) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>) <span class="co"># calculate correlation |&gt; round to 2 decimal places</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.26</code></pre>
</div>
</div>
<p>Generate a scatter plot</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> loyn<span class="sc">$</span>AREA, <span class="at">y =</span> loyn<span class="sc">$</span>ABUND)) <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bird abundance vs area of forest patch"</span>,</span>
<span id="cb12-4"><a href="#cb12-4"></a>       <span class="at">x =</span> <span class="st">"Area of forest patch (ha)"</span>,</span>
<span id="cb12-5"><a href="#cb12-5"></a>       <span class="at">y =</span> <span class="st">"Bird abundance (number of birds)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 3. Scatterplot of Bird abundance vs area of forest patch (ha)</figcaption>
</figure>
</div>
</div>
</div>
<p>The correlation coefficient is 0.26, which indicates a weak positive relationship between patch area and bird abundance.</p>
<p>This is evident in the scatterplot (Fig. 3) where the relationship is not very clear, as most of the points clustered towards one side of the plot. This tells us that there is a high amount of variation in bird abundance for small patch areas, and mostly smaller areas of forest with two larger areas &gt;500 ha.</p>
</section>
<section id="v-fit-a-simple-linear-regression-model-to-the-data-with-bird-abundance-as-the-response-variable-and-patch-area-as-the-predictor-variable." class="level5">
<h5 class="anchored" data-anchor-id="v-fit-a-simple-linear-regression-model-to-the-data-with-bird-abundance-as-the-response-variable-and-patch-area-as-the-predictor-variable."><em>(v)</em> Fit a simple linear regression model to the data, with bird abundance as the response variable and patch area as the predictor variable.</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="co"># Fit the model</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>loyn_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> AREA, <span class="at">data =</span> loyn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="vi-check-the-assumptions-of-your-model.-do-you-need-to-transform-any-variables" class="level5">
<h5 class="anchored" data-anchor-id="vi-check-the-assumptions-of-your-model.-do-you-need-to-transform-any-variables"><em>(vi)</em> Check the assumptions of your model. Do you need to transform any variables?</h5>
<p>HINT: If you do choose to transform a variable you will need to refit the model and check the assumptions again.</p>
<p>Use the <code>check_model()</code> function to check the assumptions of the model. You can also use plot(loyn_lm) to check the assumptions, but <code>check_model()</code> gives you a prettier output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">check_model</span>(loyn_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Linearity: Line doesn’t follow the dashed line, indicating relationship may not be linear.<br>
</p></li>
<li><p>Independence: No clear pattern in the residuals vs fitted plot, suggesting that the residuals are independent.</p></li>
<li><p>Normality of residuals: Most points follow the line, but there are some deviations at the tails, suggesting that the residuals may not be perfectly normally distributed.</p></li>
<li><p>Equal variance: The reference line in the plot is not straight, and there is a funnel shape in the plot, suggesting that the variance of the residuals is not constant (heteroscedasticity).</p></li>
<li><p>Influential observations: Hard to see, but there is a point lying outside the dashed lines, which suggests that there may be an influential observation in the data.</p></li>
</ul>
<p>Decision: Usually we would transform the response variable first if the assumptions are not met, but we know the Area variable is highly skewed, so it is worth transforming the Area variable to see if this improves the model fit.</p>
<p><strong>Transform Area and refit</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co">#I have used log10 transformation here</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>loyn<span class="sc">$</span>log10_AREA <span class="ot">&lt;-</span> <span class="fu">log10</span>(loyn<span class="sc">$</span>AREA)</span>
<span id="cb15-3"><a href="#cb15-3"></a></span>
<span id="cb15-4"><a href="#cb15-4"></a><span class="co"># refit model with the transformed variable</span></span>
<span id="cb15-5"><a href="#cb15-5"></a>loyn_lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ABUND <span class="sc">~</span> log10_AREA, <span class="at">data =</span> loyn)</span>
<span id="cb15-6"><a href="#cb15-6"></a></span>
<span id="cb15-7"><a href="#cb15-7"></a><span class="co"># recheck assumptions</span></span>
<span id="cb15-8"><a href="#cb15-8"></a><span class="fu">check_model</span>(loyn_lm2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The assumptions of the model with the log10 transformed Area variable are much better. The relationship looks more linear, the residuals are more normally distributed, and there is less evidence of heteroscedasticity.</p>
</section>
<section id="vii-provide-a-plot-of-your-model-and-interpret-the-model-parameters-and-fit-statistics.-interpret-the-model-parameters-and-fit-statistics.-recall-the-key-information-we-draw-from-the-output-what-do-these-statistics-tell-you-about-the-relationship-between-bird-abundance-and-patch-area" class="level5 page-columns page-full">
<h5 class="anchored" data-anchor-id="vii-provide-a-plot-of-your-model-and-interpret-the-model-parameters-and-fit-statistics.-interpret-the-model-parameters-and-fit-statistics.-recall-the-key-information-we-draw-from-the-output-what-do-these-statistics-tell-you-about-the-relationship-between-bird-abundance-and-patch-area"><em>(vii)</em> Provide a plot of your model and interpret the model parameters and fit statistics. Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between bird abundance and patch area?</h5>
<p>Plot model to provide a visual of the relationship between bird abundance and patch area, with the fitted regression line.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">ggplot</span>(loyn) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> log10_AREA, <span class="at">y =</span> ABUND)) <span class="sc">+</span> </span>
<span id="cb16-3"><a href="#cb16-3"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">x =</span> log10_AREA, <span class="at">y =</span> ABUND), <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bird abundance vs log10 transformed area of forest patch"</span>,</span>
<span id="cb16-5"><a href="#cb16-5"></a>       <span class="at">x =</span> <span class="st">"log10 transformed area of forest patch (ha)"</span>,</span>
<span id="cb16-6"><a href="#cb16-6"></a>       <span class="at">y =</span> <span class="st">"Bird abundance (number of birds)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 4. Scatterplot and model of Bird abundance vs log10 transformed area of forest patch (ha) with fitted regression line</figcaption>
</figure>
</div>
</div>
</div>
<p>Get the model summary of your final model (with the transformed variable)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">summary</span>(loyn_lm2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ABUND ~ log10_AREA, data = loyn)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.380  -6.119   1.372   4.631  14.255 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   10.401      1.489   6.984 4.38e-09 ***
log10_AREA     9.778      1.209   8.086 7.18e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.286 on 54 degrees of freedom
Multiple R-squared:  0.5477,    Adjusted R-squared:  0.5393 
F-statistic: 65.38 on 1 and 54 DF,  p-value: 7.178e-11</code></pre>
</div>
</div>
<ol type="1">
<li>State the model equation</li>
</ol>
<p>Model equation is <span class="math inline">Abundance = 10.401 + 9.778 log10(Area)</span></p>
<ol start="2" type="1">
<li>Interpretation of regression coefficients</li>
</ol>
<p>For every 1 unit change in log10(Area), we expect a 9.778 increase in bird abundance.</p>
<ol start="3" type="1">
<li>P-value</li>
</ol>
<p>The P-value for the slope coefficient is &lt; 0.001, meaning we reject our null hypothesis that the slope is equal to zero (<span class="math inline">H0: \beta_1 \neq 0</span>) and conclude that log10(Area) is a significant predictor of bird abundance.</p>
<p>This is also supported by Figure 4, where the model is sloped, indicating there is a relationship between the two variables.</p>
<ol start="4" type="1">
<li>R-squared</li>
</ol>
<p>As we only have one predictor in the model, we can use the r<sup>2</sup> value rather than the adjusted r<sup>2</sup>.</p>
<p>The r<sup>2</sup> value is 0.55, which means that 55% of the variation in bird abundance can be explained by log10(Area). This is not really a strong r<sup>2</sup> value, so it suggests that there are other factors influencing bird abundance that are not included in the model.</p>
<p>We can see this in Figure 4 where the points do not follow the regression line too closely. If the r<sup>2</sup> were higher, then we would expect the points to sit closer to the line.</p>
</section>
<section id="viii-write-a-concluding-statement-on-your-findings." class="level5">
<h5 class="anchored" data-anchor-id="viii-write-a-concluding-statement-on-your-findings."><em>(viii)</em> Write a concluding statement on your findings.</h5>
<p>Hint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.</p>
<p>Recall that our original aim was to investigate the influence of forest fragment size upon bird abundance. Therefore we would say something like:</p>
<p>We fitted a linear model (estimated using OLS) to investigate the relationship between bird abundance and forest fragment size (area) upon bird abundance (equation: abundance = <span class="math inline">\beta_0 + \beta_1 \cdot area</span>).</p>
<p>The model explains a statistically significant and moderate proportion of variance (R<sup>2</sup> = 0.55, F(1, 54) = 65.38, p &lt; .001). Within this model, the effect of forest patch area is statistically significant and positive (<span class="math inline">\beta_1</span> = 9.778, t(54) = 8.086, p &lt; .001).</p>
</section>
</section>
<p>Before moving on to the next section, take a short break and stretch your legs.</p>
</section>
</section>
<section id="multiple-linear-regression-30-min" class="level1 page-columns page-full">
<h1>2. Multiple linear regression (~30 min)</h1>
<p>Multiple linear regression has a slightly different approach compared to simple linear regression. We are still fitting a linear model and you will notice the process is similar, but we are incorporating more than one predictor variable into the model, which brings some additional steps.</p>
<ul>
<li><p>More hypotheses: rather than a single null and alternate hypothesis, you will also need to consider the hypotheses for each predictor variable, as well as the overall model.</p></li>
<li><p>More EDA: Rather than exploring only two variables, you will need to explore the additional variables. You will also need to explore the relationships between the predictor variables (signs of collinearity).</p></li>
<li><p>More assumptions: in addition to the assumptions of linearity, independence, normality of residuals, and equal variance, we also need to consider the assumption of no collinearity between predictor variables as this can trick us into thinking our model is better than it actually is (we will explore this more in next week’s lecture).</p></li>
<li><p>More interpretation: rather than only interpreting one regression coefficient, you will now have to assess a number of <em>partial regression coefficients</em> and their significance. You will also need to consider the overall model fit, and whether the model is a good fit for the data.</p></li>
<li><p>You will need to use the <strong>adjusted</strong> r<sup>2</sup> value rather than the r<sup>2</sup> value to assess the fit of the model, as r<sup>2</sup> will always increase with the addition of more predictor variables, even if those variables do not actually improve the model fit. We will explain this more next week.</p></li>
</ul>
<section id="analysis-for-runoff-and-precipitation-in-bishop-california" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="analysis-for-runoff-and-precipitation-in-bishop-california">Analysis for runoff and precipitation in Bishop, California</h2>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="../../assets/images/AdobeStock_668401555.jpeg" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">Little Lakes Valley in the Eastern Sierra Nevada Mountains outside of Bishop, California. Source: Adobe Stock.</figcaption>
</figure>
</div>
<p>You are a hydrologist tasked with analysing legacy data to investigate the relationship between precipitation at three sites (Lake Sabrina, Pine Creek, and Rock Creek) and stream runoff volume at a site near Bishop, California. The dataset contains 43 years of annual precipitation measurements (in mm) taken at (originally) 6 sites in the Owens Valley in California. You will focus on only 3 variables.</p>
<p>The data is in the <strong>california_streamflow.xlsx</strong> file.</p>
<p>Variables are as follows:</p>
<ul>
<li><code>lake_sabrina</code>: Precipitation recorded at Lake Sabrina (mm)</li>
<li><code>pine_creek</code>: Precipitation recorded at Big Pine Creek (mm),</li>
<li><code>rock_creek</code>: Precipitation recorded at Rock Creek (mm)</li>
<li><code>runoff_volume</code>: Stream runoff volume measured at a site near Bishop, California (ML/year). This will be the response variable.</li>
</ul>
<p>Note the variables have already been log-transformed to increase normality of the residuals in the regressions.</p>
<p>Data source: Hollett, K.J., Danskin, F.M., McCaffrey, W.F., and Walti, S.L., 1991. Geology and water resources of Owens Valley, California. U.S. Geological Survey Water-Supply Paper 2370-H.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>This week we will focus on getting the model running and practice interpretation of the output. Next week we will focus on working out the most suitable model.</p>
</div>
</div>
</section>
<section id="section-1" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="section-1"></h2>
<section id="exercise-2" class="level3 question">
<h3 class="anchored" data-anchor-id="exercise-2">Exercise 2</h3>
<p><em>(i)</em> Write out the statistical model for a multiple linear regression and define it in terms of the data (precipitation at each site vs runoff volume at Bishop).</p>
<p>You can write it out in words and/or in mathematical notation.</p>
<p><em>(ii)</em> State the hypotheses you will be testing for the relationship between each site and runoff volume.</p>
<p><em>(iii)</em> Read in the data and conduct some exploratory data analysis upon your variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots.</p>
<p><em>(iv)</em> Investigate the relationship between each of your variables. Describe the relationship, supported by values (correlation coefficient) and plots.</p>
<p>Hint: we are not only looking at relationship between response and predictors here, but also the relationships between predictor variables (signs of collinearity).</p>
<p><em>(v)</em> Fit a multiple linear regression model to the data, with <code>runoff_volume</code> as the response variable and <code>lake_sabrina</code>, <code>pine_creek</code> and <code>rock_creek</code> as the predictor variables.</p>
<p><em>(vi)</em> Check the assumptions of your model. Do you need to transform any variables?</p>
<p>Hint 1: you can use the the <code>check_model()</code> function from the <code>performance</code> package to check the assumptions of your model.</p>
<p>Hint 2: You may notice some collinearity occurring between predictors. This week you only need to acknowledge it and then you can move onto interpretation. Next week we will look at how to deal with collinearity in models.</p>
<p><em>(vii)</em> Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between precipitation at each site and runoff volume at Bishop, California?</p>
<p><em>(viii)</em> Write a concluding statement on your findings.</p>
<p>Hint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.</p>
</section>
<section id="solution-1" class="level4 ans page-columns page-full">
<h4 class="anchored" data-anchor-id="solution-1">Solution</h4>
<section id="i-write-out-the-statistical-model-for-a-multiple-linear-regression-and-define-it-in-terms-of-the-data-precipitation-at-each-site-vs-runoff-volume-at-bishop." class="level5">
<h5 class="anchored" data-anchor-id="i-write-out-the-statistical-model-for-a-multiple-linear-regression-and-define-it-in-terms-of-the-data-precipitation-at-each-site-vs-runoff-volume-at-bishop."><em>(i)</em> Write out the statistical model for a multiple linear regression and define it in terms of the data (precipitation at each site vs runoff volume at Bishop).</h5>
<p>You can write it out in words and/or in mathematical notation.</p>
<p>The statistical model for a multiple linear regression with 3 predictors is:</p>
<p><span class="math display">
y_{i} = \beta_0 + \beta_1x_1 + \beta_2x_2 + \beta_3x_3 + \epsilon_{i}
</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">y_{i}</span> is the response variable (runoff volume) for the <span class="math inline">i</span>th observation when the predictor X = <span class="math inline">x_i</span> (precipitation at a site)</li>
<li><span class="math inline">\beta_0</span> is the intercept where the regression line crosses the y-axis</li>
<li><span class="math inline">\beta_1</span> is the slope of the regression line for the first predictor, which represents the change in runoff volume for a one-unit increase in precipitation at lake_sabrina</li>
<li><span class="math inline">\beta_2</span> is the slope of the regression line for the first predictor, which represents the change in runoff volume for a one-unit increase in precipitation at pine_creek</li>
<li><span class="math inline">\beta_3</span> is the slope of the regression line for the first predictor, which represents the change in runoff volume for a one-unit increase in precipitation at rock_creek</li>
<li><span class="math inline">\epsilon_{i}</span> is the random error term for the ith observation and is assumed to be normally distributed with mean 0 and constant variance</li>
</ul>
<p>OR if written in terms of the variables in our dataset, the model would be:</p>
<p><span class="math display">
\textrm{Runoff volume} = \beta_0 + \beta_1\cdot \textrm{lake_sabrina} + \beta_2\cdot \textrm{pine_creek} + \beta_3\cdot \textrm{rock_creek} +  \epsilon_{i}
</span></p>
</section>
<section id="ii-state-the-hypotheses-you-will-be-testing-for-the-relationship-between-each-site-and-runoff-volume." class="level5">
<h5 class="anchored" data-anchor-id="ii-state-the-hypotheses-you-will-be-testing-for-the-relationship-between-each-site-and-runoff-volume."><em>(ii)</em> State the hypotheses you will be testing for the relationship between each site and runoff volume.</h5>
<p>In multiple linear regression we are testing multiple hypotheses (one per predictor + one for the overall model).</p>
<p>Therefore:</p>
<ol type="1">
<li>Relationship between precipitation at lake_sabrina and runoff volume: <span class="math display">H_0 : \beta_1 = 0</span> <span class="math display">H_1 : \beta_1 \neq 0</span></li>
<li>Precipitation at pine_creek and runoff volume: <span class="math display">H_0 : \beta_2 = 0</span> <span class="math display">H_1 : \beta_2 \neq 0</span></li>
<li>Precipitation at rock_creek and runoff volume:</li>
</ol>
<p><span class="math display">H_0 : \beta_3 = 0</span> <span class="math display">H_1 : \beta_3 \neq 0</span> 4. Overal model:</p>
<p><span class="math display">H_0 : \beta_1 = \beta_2 = \beta_3 = 0</span> <span class="math display">H_1 : \textrm{at least one } \beta_i \neq 0</span></p>
</section>
<section id="iii-read-in-the-data-and-conduct-some-exploratory-data-analysis-upon-your-variables.-describe-the-spread-and-central-tendency-of-each-supported-by-values-summary-statistics-and-plots." class="level5 page-columns page-full">
<h5 class="anchored" data-anchor-id="iii-read-in-the-data-and-conduct-some-exploratory-data-analysis-upon-your-variables.-describe-the-spread-and-central-tendency-of-each-supported-by-values-summary-statistics-and-plots."><em>(iii)</em> Read in the data and conduct some exploratory data analysis upon your variables. Describe the spread and central tendency of each, supported by values (summary statistics) and plots.</h5>
<p>Read in the data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># read in the data</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>stream_data <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/california_streamflow.xlsx"</span>, <span class="st">"streamflow"</span>)</span>
<span id="cb20-3"><a href="#cb20-3"></a></span>
<span id="cb20-4"><a href="#cb20-4"></a><span class="fu">glimpse</span>(stream_data) <span class="co"># check the data</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 43
Columns: 4
$ lake_sabrina  &lt;dbl&gt; 1.958717, 2.087881, 1.981175, 2.054169, 2.102934, 2.1568…
$ pine_creek    &lt;dbl&gt; 2.017618, 2.282781, 2.383471, 2.451719, 2.618086, 2.3532…
$ rock_creek    &lt;dbl&gt; 2.275823, 2.450548, 2.491194, 2.585246, 2.706948, 2.3159…
$ runoff_volume &lt;dbl&gt; 4.825412, 4.920867, 4.911735, 4.924242, 5.120841, 4.9210…</code></pre>
</div>
</div>
<p>We can see there are four variables, with 43 observations each. All variables are numeric (coded as ‘dbl’ here, which is a type of numeric/continuous variable).</p>
<p>Summary statistics</p>
<p>I have calculated each summary statistic separately here to produce the output as a table. If you are exploring the data for yourself, you are welcome to use <code>summary()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">library</span>(moments) <span class="co"># gives us the skewness() function</span></span>
<span id="cb22-2"><a href="#cb22-2"></a></span>
<span id="cb22-3"><a href="#cb22-3"></a>runoff_volume <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb22-4"><a href="#cb22-4"></a>  <span class="at">mean =</span> <span class="fu">mean</span>(stream_data<span class="sc">$</span>runoff_volume),</span>
<span id="cb22-5"><a href="#cb22-5"></a>  <span class="at">median =</span> <span class="fu">median</span>(stream_data<span class="sc">$</span>runoff_volume),</span>
<span id="cb22-6"><a href="#cb22-6"></a>  <span class="at">min =</span> <span class="fu">min</span>(stream_data<span class="sc">$</span>runoff_volume),</span>
<span id="cb22-7"><a href="#cb22-7"></a>  <span class="at">max =</span> <span class="fu">max</span>(stream_data<span class="sc">$</span>runoff_volume),</span>
<span id="cb22-8"><a href="#cb22-8"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(stream_data<span class="sc">$</span>runoff_volume),</span>
<span id="cb22-9"><a href="#cb22-9"></a>  <span class="at">skewness =</span> <span class="fu">skewness</span>(stream_data<span class="sc">$</span>runoff_volume)</span>
<span id="cb22-10"><a href="#cb22-10"></a>)</span>
<span id="cb22-11"><a href="#cb22-11"></a></span>
<span id="cb22-12"><a href="#cb22-12"></a>lake_sabrina <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb22-13"><a href="#cb22-13"></a>  <span class="at">mean =</span> <span class="fu">mean</span>(stream_data<span class="sc">$</span>lake_sabrina),</span>
<span id="cb22-14"><a href="#cb22-14"></a>  <span class="at">median =</span> <span class="fu">median</span>(stream_data<span class="sc">$</span>lake_sabrina),</span>
<span id="cb22-15"><a href="#cb22-15"></a>  <span class="at">min =</span> <span class="fu">min</span>(stream_data<span class="sc">$</span>lake_sabrina),</span>
<span id="cb22-16"><a href="#cb22-16"></a>  <span class="at">max =</span> <span class="fu">max</span>(stream_data<span class="sc">$</span>lake_sabrina),</span>
<span id="cb22-17"><a href="#cb22-17"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(stream_data<span class="sc">$</span>lake_sabrina),</span>
<span id="cb22-18"><a href="#cb22-18"></a>  <span class="at">skewness =</span> <span class="fu">skewness</span>(stream_data<span class="sc">$</span>lake_sabrina)</span>
<span id="cb22-19"><a href="#cb22-19"></a>)</span>
<span id="cb22-20"><a href="#cb22-20"></a></span>
<span id="cb22-21"><a href="#cb22-21"></a>pine_creek <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb22-22"><a href="#cb22-22"></a>  <span class="at">mean =</span> <span class="fu">mean</span>(stream_data<span class="sc">$</span>pine_creek),</span>
<span id="cb22-23"><a href="#cb22-23"></a>  <span class="at">median =</span> <span class="fu">median</span>(stream_data<span class="sc">$</span>pine_creek),</span>
<span id="cb22-24"><a href="#cb22-24"></a>  <span class="at">min =</span> <span class="fu">min</span>(stream_data<span class="sc">$</span>pine_creek),</span>
<span id="cb22-25"><a href="#cb22-25"></a>  <span class="at">max =</span> <span class="fu">max</span>(stream_data<span class="sc">$</span>pine_creek),</span>
<span id="cb22-26"><a href="#cb22-26"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(stream_data<span class="sc">$</span>pine_creek),</span>
<span id="cb22-27"><a href="#cb22-27"></a>  <span class="at">skewness =</span> <span class="fu">skewness</span>(stream_data<span class="sc">$</span>pine_creek)</span>
<span id="cb22-28"><a href="#cb22-28"></a>)</span>
<span id="cb22-29"><a href="#cb22-29"></a></span>
<span id="cb22-30"><a href="#cb22-30"></a>rock_creek <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb22-31"><a href="#cb22-31"></a>  <span class="at">mean =</span> <span class="fu">mean</span>(stream_data<span class="sc">$</span>rock_creek),</span>
<span id="cb22-32"><a href="#cb22-32"></a>  <span class="at">median =</span> <span class="fu">median</span>(stream_data<span class="sc">$</span>rock_creek),</span>
<span id="cb22-33"><a href="#cb22-33"></a>  <span class="at">min =</span> <span class="fu">min</span>(stream_data<span class="sc">$</span>rock_creek),</span>
<span id="cb22-34"><a href="#cb22-34"></a>  <span class="at">max =</span> <span class="fu">max</span>(stream_data<span class="sc">$</span>rock_creek),</span>
<span id="cb22-35"><a href="#cb22-35"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(stream_data<span class="sc">$</span>rock_creek),</span>
<span id="cb22-36"><a href="#cb22-36"></a>  <span class="at">skewness =</span> <span class="fu">skewness</span>(stream_data<span class="sc">$</span>rock_creek)</span>
<span id="cb22-37"><a href="#cb22-37"></a>)</span>
<span id="cb22-38"><a href="#cb22-38"></a></span>
<span id="cb22-39"><a href="#cb22-39"></a>summary_creeks <span class="ot">=</span> <span class="fu">rbind</span>(runoff_volume, lake_sabrina, pine_creek, rock_creek) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb22-40"><a href="#cb22-40"></a></span>
<span id="cb22-41"><a href="#cb22-41"></a><span class="fu">kable</span>(summary_creeks, <span class="at">caption =</span> <span class="st">"Table 2. Summary statistics for runoff volume (ML/year) and precipitation at Lake Sabrina, Pine Creek, and Rock Creek (mm)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2. Summary statistics for runoff volume (ML/year) and precipitation at Lake Sabrina, Pine Creek, and Rock Creek (mm)</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">skewness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">runoff_volume</td>
<td style="text-align: right;">4.96</td>
<td style="text-align: right;">4.93</td>
<td style="text-align: right;">4.71</td>
<td style="text-align: right;">5.26</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">lake_sabrina</td>
<td style="text-align: right;">2.03</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">1.57</td>
<td style="text-align: right;">2.48</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">-0.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pine_creek</td>
<td style="text-align: right;">2.45</td>
<td style="text-align: right;">2.38</td>
<td style="text-align: right;">2.01</td>
<td style="text-align: right;">3.04</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">rock_creek</td>
<td style="text-align: right;">2.45</td>
<td style="text-align: right;">2.45</td>
<td style="text-align: right;">2.04</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">-0.03</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li>Runoff volume (ML/year)</li>
</ol>
<p>The mean runoff volume recorded at the site near Bishop, California is 4.96 ML/year and the median is 4.93 ML/year (Table 2). These are quite similar, suggesting a normal distribution. This is further supported by the skewness coefficient of 0.29, which is close to 0, and the relatively symmetrical boxplot (Fig. 5), indicating a fairly symmetric distribution. The median does seem to sit closer to the first quartile than the third quartile, suggesting a slight skew, but everything else seems to indicate a fairly normal distribution.</p>
<p>Runoff volume ranges from a minimum of 4.71 ML/year to 5.26 ML/year and the standard deviation is 0.14, which indicates that the spread of values is quite small.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">ggplot</span>(stream_data) <span class="sc">+</span> </span>
<span id="cb23-2"><a href="#cb23-2"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> runoff_volume)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Runoff volume (ML/year)"</span>,</span>
<span id="cb23-4"><a href="#cb23-4"></a>       <span class="at">y =</span> <span class="st">"Runoff volume (ML/year)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 5. Boxplot of Runoff volume (ML/year)</figcaption>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>Precipitation at Lake Sabrina (mm)</li>
</ol>
<p>The mean precipitation recorded at Lake Sabrina is 2.03 mm and the median is 2.05 mm (Table 2). These are quite similar, but given the narrow range of values the difference could be quite large. We can see this in the skewness coefficient of -0.44, which suggests the distribution is symmetrical, but there is a slight skew to the left. Upon visual inspection of the boxplot (Fig. 6) we can see there are a number of outliers which may be influencing this skew.</p>
<p>Precipitation at Lake Sabrina ranged from a minimum of 1.6 mm to 2.5 mm and the standard deviation is 0.20, indicating that there is some variability in precipitation at Lake Sabrina across the years.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">ggplot</span>(stream_data) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> lake_sabrina)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Precipitation at Lake Sabrina (mm)"</span>,</span>
<span id="cb24-4"><a href="#cb24-4"></a>       <span class="at">y =</span> <span class="st">"Precipitation (mm)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 6. Boxplot of precipitation at Lake Sabrina (mm)</figcaption>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>Precipitation at Pine Creek (mm)</li>
</ol>
<p>The mean precipitation at Pine Creek was 2.45 mm and the median was 2.38 mm. The mean and median are similar and the skewness coefficient of 0.19 suggests the distribution is symmetrical. Upon visual inspection of the boxplot (Fig. 7) we can see the median lies closer to the first quartile, but otherwise the boxplot looks fairly symmetrical.</p>
<p>Precipitation at Pine Creek ranged from a minimum of 2.01 mm to a maximum of 3.04 mm and the standard deviation is 0.24, indicating that there is some variability in precipitation at Pine Creek across the years.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="fu">ggplot</span>(stream_data) <span class="sc">+</span> </span>
<span id="cb25-2"><a href="#cb25-2"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> pine_creek)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Precipitation at Pine Creek (mm)"</span>,</span>
<span id="cb25-4"><a href="#cb25-4"></a>       <span class="at">y =</span> <span class="st">"Precipitation (mm)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 7. Boxplot of precipitation at Pine Creek (mm)</figcaption>
</figure>
</div>
</div>
</div>
<ol start="4" type="1">
<li>Precipitation at Rock Creek (mm)</li>
</ol>
<p>The mean precipitation at Rock Creek was the same as the median (2.45 mm), and the skewness coefficient of -0.03 suggests the distribution is very symmetrical. Upon visual inspection of the boxplot (Fig. 8) we can see the median lies exactly in the middle of the box, and there are no outliers, suggesting a very symmetrical distribution.</p>
<p>Precipitation ranged from 2.04 mm to 2.80 mm and the standard deviation is 0.18, indicating that there was a small amount of variability in precipitation at Rock Creek across the years.</p>
<div class="cell page-columns page-full">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">ggplot</span>(stream_data) <span class="sc">+</span> </span>
<span id="cb26-2"><a href="#cb26-2"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> rock_creek)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Precipitation at Rock Creek (mm)"</span>,</span>
<span id="cb26-4"><a href="#cb26-4"></a>       <span class="at">y =</span> <span class="st">"Precipitation (mm)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="margin-caption">Figure 8. Boxplot of precipitation at Rock Creek (mm)</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="iv-investigate-the-relationship-between-each-of-your-variables.-describe-the-relationship-supported-by-values-correlation-coefficient-and-plots." class="level5">
<h5 class="anchored" data-anchor-id="iv-investigate-the-relationship-between-each-of-your-variables.-describe-the-relationship-supported-by-values-correlation-coefficient-and-plots."><em>(iv)</em> Investigate the relationship between each of your variables. Describe the relationship, supported by values (correlation coefficient) and plots.</h5>
<p>Hint: we are not only looking at relationship between response and predictors here, but also the relationships between predictor variables (signs of collinearity).</p>
<p>It is good to have a numeric value (correlation coefficient) and a visual (scatterplot) to investigate the relationship between each of the variables.</p>
<p>You can do this separately using <code>cor()</code> and <code>pairs()</code>, or you can use the <code>pairs.panels()</code> function from the <code>psych</code> package to get both the correlation coefficients and the scatterplots in one go.</p>
<ol type="1">
<li>separately</li>
</ol>
<p>Correlation coefficient</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="fu">cor</span>(stream_data) <span class="co"># calculate correlation |&gt; round to 2 decimal places</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              lake_sabrina pine_creek rock_creek runoff_volume
lake_sabrina    1.00000000 0.07848517 0.09054996     0.1649284
pine_creek      0.07848517 1.00000000 0.88381452     0.8929251
rock_creek      0.09054996 0.88381452 1.00000000     0.9194688
runoff_volume   0.16492838 0.89292511 0.91946880     1.0000000</code></pre>
</div>
</div>
<p>Pairs plot</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">pairs</span>(stream_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="1">
<li>All in one</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>psych<span class="sc">::</span><span class="fu">pairs.panels</span>(stream_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interpretation</p>
<p>Stream runoff volume is highly correlated with rock_creek (r = 0.92) and with pine_creek (r = 0.88), but weakly correlated with lake_sabrina (r = 0.16). This is also evident in the scatterplots betweeen runoff_volume and rock_creek, and runoff_volume and pine_creek, which show a clear positive relationship, while the scatterplot between runoff_volume and lake_sabrina shows points scattered about the plot, indicating no clear relationship.</p>
<p>We can also see a strong correlation between pine_creek and rock_creek (r = 0.88), which may indicate collinearity between these two predictor variables. This is also evident in the scatterplot between pine_creek and rock_creek, which shows a clear positive relationship.</p>
<p>Lake Sabrina does not appear to be correlated with pine_creek or rock_creek (r = 0.08 and 0.09, respectively), which is also evident in the scatterplots which show points scattered about the plot rather than following a clear trend.</p>
</section>
<section id="v-fit-a-multiple-linear-regression-model-to-the-data-with-runoff_volume-as-the-response-variable-and-lake_sabrina-pine_creek-and-rock_creek-as-the-predictor-variables." class="level5">
<h5 class="anchored" data-anchor-id="v-fit-a-multiple-linear-regression-model-to-the-data-with-runoff_volume-as-the-response-variable-and-lake_sabrina-pine_creek-and-rock_creek-as-the-predictor-variables."><em>(v)</em> Fit a multiple linear regression model to the data, with <code>runoff_volume</code> as the response variable and <code>lake_sabrina</code>, <code>pine_creek</code> and <code>rock_creek</code> as the predictor variables.</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>runoff_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(runoff_volume <span class="sc">~</span> lake_sabrina <span class="sc">+</span> pine_creek <span class="sc">+</span> rock_creek, <span class="at">data =</span> stream_data)</span>
<span id="cb31-2"><a href="#cb31-2"></a></span>
<span id="cb31-3"><a href="#cb31-3"></a>runoff_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(runoff_volume <span class="sc">~</span> ., <span class="at">data =</span> stream_data) <span class="do">## you can also use the . to indicate use all variables</span></span>
<span id="cb31-4"><a href="#cb31-4"></a></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="fu">summary</span>(runoff_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = runoff_volume ~ ., data = stream_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.09885 -0.03331  0.01025  0.03359  0.09495 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.25716    0.12360  26.352  &lt; 2e-16 ***
lake_sabrina  0.05631    0.03756   1.499  0.14185    
pine_creek    0.21085    0.06756   3.121  0.00339 ** 
rock_creek    0.43838    0.08798   4.983 1.32e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04861 on 39 degrees of freedom
Multiple R-squared:  0.8817,    Adjusted R-squared:  0.8726 
F-statistic: 96.88 on 3 and 39 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="vi-check-the-assumptions-of-your-model.-do-you-need-to-transform-any-variables-1" class="level5">
<h5 class="anchored" data-anchor-id="vi-check-the-assumptions-of-your-model.-do-you-need-to-transform-any-variables-1"><em>(vi)</em> Check the assumptions of your model. Do you need to transform any variables?</h5>
<p>Hint 1: you can use the the <code>check_model()</code> function from the <code>performance</code> package to check the assumptions of your model.</p>
<p>Hint 2: You may notice some collinearity occurring between predictors. This week you only need to acknowledge it and then you can move onto interpretation. Next week we will look at how to deal with collinearity in models.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="fu">check_model</span>(runoff_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab07-regression-modelling_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Linearity: Line mostly follows the dashed line, so we can say the relationship is mostly linear. There are some deviations at the tails, suggesting that the relationship may not be perfectly linear (is there a better model for this relationship?).</p></li>
<li><p>Independence: No clear pattern in the residuals vs fitted plot, suggesting that the residuals are independent.</p></li>
<li><p>Normality of residuals: Most points follow the line, but there are some deviations at the tails, suggesting that the residuals may not be perfectly normally distributed.</p></li>
<li><p>Equal variance: The reference line in the plot relatively straight, suggesting that the variance of the residuals is constant.</p></li>
<li><p>Influential observations: No points lying outside the contour lines, which suggests that there are no influential observations in the data.</p></li>
<li><p>Collinearity: This is an additional assumption for Multiple Linear Regression. We can check for collinearity by looking at the correlation matrix (which we have already done) and by looking at the Variance Inflation Factor (VIF) values. VIF values greater than 5 or 10 indicate a potential problem with collinearity.</p></li>
</ul>
<p>Decision: No transformations needed BUT we are seeing an issue with collinearity.</p>
<p>We will explore collinearity and VIF more in next week’s lecture as it will help us fit a more appropriate model.</p>
<p>For now we can continue with this model and explore the output, keeping in mind that is is not perfect. We will explore how to deal with collinearity in next week’s lecture.</p>
</section>
<section id="vii-interpret-the-model-parameters-and-fit-statistics.-recall-the-key-information-we-draw-from-the-output-what-do-these-statistics-tell-you-about-the-relationship-between-precipitation-at-each-site-and-runoff-volume-at-bishop-california" class="level5">
<h5 class="anchored" data-anchor-id="vii-interpret-the-model-parameters-and-fit-statistics.-recall-the-key-information-we-draw-from-the-output-what-do-these-statistics-tell-you-about-the-relationship-between-precipitation-at-each-site-and-runoff-volume-at-bishop-california"><em>(vii)</em> Interpret the model parameters and fit statistics. Recall the key information we draw from the output; what do these statistics tell you about the relationship between precipitation at each site and runoff volume at Bishop, California?</h5>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">summary</span>(runoff_lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = runoff_volume ~ ., data = stream_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.09885 -0.03331  0.01025  0.03359  0.09495 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.25716    0.12360  26.352  &lt; 2e-16 ***
lake_sabrina  0.05631    0.03756   1.499  0.14185    
pine_creek    0.21085    0.06756   3.121  0.00339 ** 
rock_creek    0.43838    0.08798   4.983 1.32e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04861 on 39 degrees of freedom
Multiple R-squared:  0.8817,    Adjusted R-squared:  0.8726 
F-statistic: 96.88 on 3 and 39 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="1">
<li>State the model equation Model equation is:</li>
</ol>
<p>$ = 3.257 + 0.05631 + 0.210 + 0.438 $</p>
<ol start="2" type="1">
<li>Interpretation of regression coefficients</li>
</ol>
<p><em>Holding all other variables constant:</em> (very important to include this)</p>
<ul>
<li><p>For every 1 unit change in precipitation at lake_sabrina, we expect a 0.056 increase in runoff_volume;</p></li>
<li><p>For every 1 unit change in precipitation at pine_creek, we expect a 0.210 increase in runoff_volume;</p></li>
<li><p>For every 1 unit change in precipitation at rock_creek, we expect a 0.438 increase in runoff_volume.</p></li>
</ul>
<ol start="3" type="1">
<li>P-value</li>
</ol>
<p>When assessing the p-values, we must consider the p-value associated with each partial regression coefficient, as well as the overall model.</p>
<ol type="a">
<li>Relationship between precipitation at lake_sabrina and runoff volume:</li>
</ol>
<p>The P-value for the partial regression coefficient is &gt; 0.001, meaning we FAIL TO reject our null hypothesis that the slope is equal to zero (<span class="math inline">H0: \beta_1 = 0</span>) and conclude that precipitation at Lake Sabrina is NOT a significant predictor of runoff volume at the site near Bishop, California.</p>
<ol start="2" type="a">
<li>Precipitation at pine_creek and runoff volume:</li>
</ol>
<p>The P-value for the partial regression coefficient is &lt; 0.05, meaning we reject our null hypothesis that the slope is equal to zero (<span class="math inline">H0: \beta_2 = 0</span>) and conclude that precipitation at Pine Creek is a significant predictor of runoff volume at the site near Bishop, California.</p>
<ol start="3" type="a">
<li>Precipitation at rock_creek and runoff volume:</li>
</ol>
<p>The P-value for the partial regression coefficient is &lt; 0.05, meaning we reject our null hypothesis that the slope is equal to zero (<span class="math inline">H0: \beta_3 = 0</span>) and conclude that precipitation at Rock Creek is a significant predictor of runoff volume at the site near Bishop, California.</p>
<ol start="4" type="a">
<li>Overall model:</li>
</ol>
<p>The P-value for the model is &lt; 0.001, indicating that at least one slope is not equal to zero. This means we reject our null hypothesis that the all partial slopes are equal to zero (<span class="math display">H_0 : \beta_1 = \beta_2 = \beta_3 = 0</span>) and conclude that our model is significant.</p>
<ol start="4" type="1">
<li>R-squared As we more than one predictor in the model, we will need to use the adjusted r<sup>2</sup>. We will cover the reason for this in next week’s lecture.</li>
</ol>
<p>The r<sup>2</sup> value is 0.87, which means that 87% of the variation in stream runoff volume can be explained our model. This is quite a strong r<sup>2</sup> value, but we will need to acknowledge that more investigation is needed as the collinearity between predictors may be influencing our model.</p>
</section>
<section id="viii-write-a-concluding-statement-on-your-findings.-1" class="level5">
<h5 class="anchored" data-anchor-id="viii-write-a-concluding-statement-on-your-findings.-1"><em>(viii)</em> Write a concluding statement on your findings.</h5>
<p>Hint: Consider the initial aim and hypothesis of the study and write it in a way that is easily understood by your client.</p>
<p>We fitted a multiple linear regression model (estimated using OLS) to investigate the relationship between precipitation at three sites (Lake Sabrina, Pine Creek, and Rock Creek) and stream runoff volume at a site near Bishop, California (equation: <span class="math inline">\textrm{runoff_volume} = \beta_0 + \beta_1\cdot \textrm{lake_sabrina} + \beta_2\cdot \textrm{pine_creek} + \beta_3\cdot \textrm{rock_creek}</span>).</p>
<p>The model explains a statistically significant and strong proportion of variance (R<sup>2</sup> = 0.87, F(3, 39) = 96.88, p &lt; 0.05). Within this model, the effect of precipitation at Lake Sabrina was not statistically significant (<span class="math inline">\beta_1</span> = 0.056, t(39) = 1.499, p &gt; 0.05), while the effects of precipitation at Pine Creek and Rock Creek were statistically significant and positive (<span class="math inline">\beta_2</span> = 0.211, t(39) = 3.12, p &lt; 0.05; <span class="math inline">\beta_3</span> = 0.438, t(39) = 4.98, p &lt; 0.05).</p>
</section>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<section id="closing-thoughts" class="level2">
<h2 class="anchored" data-anchor-id="closing-thoughts">Closing thoughts</h2>
<p>You have done a great job fitting linear regression models and interpreting the output.</p>
<p>As you may have noticed in this lab, models are rarely perfect, so next week we will focus on working out the most suitable model for our data based on what we have.</p>
<p>Keep up the great work and see you in the week 8 lecture!</p>
<p>If you have any questions, please approach your tutors or you are welcome to post to the Ed Discussion board.</p>
<section id="attribution" class="level3">
<h3 class="anchored" data-anchor-id="attribution">Attribution</h3>
<p>This lab was developed using resources that are available under a <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International license</a>, made available on the <a href="https://github.com/usyd-soles-edu/">SOLES Open Educational Resources repository</a>.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>The University of Sydney</p>
</div>
  </div>
</footer>




</body></html>